### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1021]
http://stackoverflow.com/questions/14358817/best-practice-for-localization-and-globalization-of-strings-and-labels

http://www.localeplanet.com/support/howto-localize-js.html  - doesn't look too painful

**Comment by roshkins** [comment]
@erikdesjardins Can you post the items you need me to do to have the i18n script working? I lost it in IRC chat.

**Comment by erikdesjardins** [comment]
Sure (these are sort of in order):

- copy the code from https://astexplorer.net/#/QmOYtBMf4D into a file like `utils/i18nTransformer.js`
- install jscodeshift `npm i -D jscodeshift@0.3.30`
- replace the second last statement (starts with `basePath\n .find(j.Program)\n .get().node.body`) with some code that reads in en.json, adds the new strings, and writes `JSON.stringify(obj, null, '\t')` or similar to en.json
- add a `autoi18n` npm script to package.json, something like `jscodeshift --parser flow --transform utils/i18nTransformer.js`, which should end up usable with something like `npm run autoi18n -- path/to/module.js`
- import lodash `const _ = require('lodash')`
  - replace `optName` with `_.startCase(optName)` in one place (commented)
  - for the two other usages of `optName` that I marked with `_.camelCase`, manually capitalize the first letter (I thought lodash had `_.pascalCase` or `_.camelCase`, but it doesn't capitalize the first letter)

**Comment by mc10** [comment]
This exists now; see https://github.com/honestbleeps/Reddit-Enhancement-Suite/projects/1.
