### ISSUE TITLE
Move default macros into settings (not code)

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1044]
http://www.reddit.com/r/Enhancement/comments/25ggd1/re_macros_can_i_somehow_make_shortcuts_to_macros/#

It's probably not necessary to keep the throttling/warning for "you clicked this too often" at this point. That was added when those macros were directly on the toolbar, so it was easier to click - but now the macro is inside hte menu, so you have to enable the "don't close macro menu" option to make it easier to spam -- and it doesn't prevent copy-pasta.

**Comment by erikdesjardins** [comment]
#2270
