### ISSUE TITLE
Update RES logo in chrome store

### ISSUE THREAD

**Issue by thybag** [honestbleeps/Reddit-Enhancement-Suite#1071]
Hello,

Was just looking through the chrome store and noticed that the RES logo there could probably use an update (current one is tiny/pixely). 

See under extensions:
https://chrome.google.com/webstore/search/reddit

The new image sizes appears to be around 142*92px, not really urgent at all, but probably still worth updating whenever anyone gets a second.

**Comment by erikdesjardins** [comment]
@honestbleeps whenever you have a minute, [icon128.png](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/images/icon128.png) should do nicely.

**Comment by erikdesjardins** [comment]
The promo images are appearing now; the icon has been updated but it's still small:

![image](https://cloud.githubusercontent.com/assets/7673145/17121942/4b4ad55a-52a5-11e6-95f8-88586f810f6b.png)

But I think it looks that way for all extensions:

Extension:
![image](https://cloud.githubusercontent.com/assets/7673145/17121973/891b8140-52a5-11e6-9f5a-81595a443262.png)
App:
![image](https://cloud.githubusercontent.com/assets/7673145/17121987/a33cbd0a-52a5-11e6-93b2-167dd7c698c0.png)
