### ISSUE TITLE
500px image expando support

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1095]
http://www.reddit.com/r/Enhancement/comments/25tbzp/feature_request_expando_support_for_the_still/  
http://www.reddit.com/r/Enhancement/comments/l1ly5/request_add_support_for_images_from_500pxcom/  
http://www.reddit.com/r/Enhancement/comments/tk6og/feature_request_500px_inline_image_support/  
http://www.reddit.com/r/Enhancement/comments/1r0r1x/feature_request_500px_thumbnails/

**Comment by allthefoxes** [comment]
Close?

**Comment by andytuba** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/1479
