### ISSUE TITLE
Strange error with subreddit info

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1213]
Try this : 
Open your dev console (to see error), go on reddit homepage, and try to mouseover subreddit. Randomly pause/enable NER, or open/close the setting console while trying to mouseover subreddit. You may have an error : 

```
Uncaught TypeError: Cannot read property 'callback' of null hover.js:128
```

Or 

```
Uncaught TypeError: Cannot set property 'textContent' of undefined subredditInfo.js:239
```

In fact, it's seem not related to NER or the console, because I success to get the error one time without doing anything special (I just refresh the page and mouseover a subreddit and directly got the error).

But this bug seem random, maybe related to the fact to mouseout the mouse just after the popup started to appear.

**Comment by mc10** [comment]
Going to close this for now; if this is reproducible, feel free to reopen.
