### ISSUE TITLE
Add a way to disable res temporary (mostly for dev purpose)

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1234]
In troubleshooter -> Reload page an disable RES for this tab

=> Reload the page and set a flag in sessionStorage => init.js check this flag at loading

>00:48:05	andytuba  oh yeah okay here's an idea
00:48:12	andytuba  add an option to the RES menu
00:48:20	andytuba  "reload without RES"
00:48:28	andytuba  that dumps a flag in RESstorage or sesionstorage or something
00:48:33	matheod__  yea nice idea
00:48:34	andytuba  and when RES loads it can check for that flag
00:48:37	 matheod_ has quit: Ping timeout: 121 seconds.
00:49:06	andytuba  i think sessionstorage is better because you can just close the tab to go back to normal
00:49:10	matheod__  yea
00:49:11	andytuba  session stoarge is per tab, right?
00:49:13	matheod__  yes
00:49:39	matheod__  This option should be in troubleshooter I think
00:49:46	andytuba  that sounds good

**Comment by erikdesjardins** [comment]
Fixed by #1235
