### ISSUE TITLE
User Tagger editor - macro-style dropdown with text/color to autofill usertag

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1270]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1263#issuecomment-46223953

**Comment by erikdesjardins** [comment]
https://www.reddit.com/r/Enhancement/comments/2yum2c/is_there_a_way_to_have_res_tag_people_en_masse/cpdanpl

**Comment by andytuba** [comment]
https://www.reddit.com/r/Enhancement/comments/43l28n/feature_request_custom_labels_instead_of_colour/

**Comment by matheod** [comment]
I think tag should be updated with a table in option that allow to create tags : 
color / background color / Name / Default Text / Move / Delete

**Comment by andytuba** [comment]
https://www.reddit.com/r/Enhancement/comments/49hyq7/is_there_a_way_to_save_a_tag_to_tag_people_quickly/

**Comment by andytuba** [comment]
https://www.reddit.com/r/Enhancement/comments/4munzt/feature_request_fast_tagging/
