### ISSUE TITLE
keyboard shortcut for show / hide child comments

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1274]
http://www.reddit.com/r/RESissues/comments/28drjj/using_keyboard_shortcut_to_show_child_comments_of/

maybe shift-enter or alt-enter?

**Comment by erikdesjardins** [comment]
https://www.reddit.com/r/Enhancement/comments/36655o/keyboard_shortcut_to_show_child_comments_on_a/

**Comment by andytuba** [comment]
Alternatively, "hide child comments" could instead toggle all the child comments closed

**Comment by qwerty-space** [comment]
I'd love this as well!

**Comment by andytuba** [comment]
This got implemented as Shift-P a while back.

**Comment by decadent** [comment]
Shift-P does a different thing for me in 5.0.3 (in Chromium)—it shows a popup with the chain of parent comments. The description for shift-P in the help popup confirms this.

I don't see anything in the help popup for 'show/hide child comments.'

**Comment by andytuba** [comment]
Oh, I might've misread "child" as "parent" when I closed this.
