### ISSUE TITLE
HTML5 videos auto expand when "View Images" is clicked and a new page is loaded.

### ISSUE THREAD

**Issue by JonBons** [honestbleeps/Reddit-Enhancement-Suite#1287]
Steps to repro:
* Go to /r/HTML5_GIF/
* Click "View Images" (Note that nothing expands)
* Scroll down so "Never Ending Reddit" loads page 2
 * Note that HTML 5 videos have auto expanded.

**Comment by larsjohnsen** [comment]
Videos marked 'muted' are auto-expanded.

**Comment by erikdesjardins** [comment]
^ muted HTML5 videos are treated like .gifs, for all intents and purposes, and they're consistently expanded with/without NER.
