### ISSUE TITLE
"Turn off everything" option for the minimalist users

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1288]
http://www.reddit.com/r/Enhancement/comments/28l416/feature_request_turn_off_everything_option_for/#

**Comment by erikdesjardins** [comment]
Implemented in 9ad53d752c7b612c55eb3c00172c06354e8bbe8d

**Comment by mc10** [comment]
Going to close this as superseded by #2182.
