### ISSUE TITLE
OneDrive Support

### ISSUE THREAD

**Issue by sgtfrankieboy** [honestbleeps/Reddit-Enhancement-Suite#1329]
I've figured out a way to support OneDrive. But the method isn't using a publicly available API.

The method will use the query parameters of a OneDrive url and it will then initiate a `XMLHttpRequest` to an internal OneDrive API which returns a list of all files in that directory or a single file (this allows for some kind of inline image/video gallery).  Before I start on it I want to know if this is allowed and that it will not get RES in any trouble.

**Comment by mc10** [comment]
Fixed by #1333 and #2170.
