### ISSUE TITLE
RES Lite - one button to default everything to normal reddit

### ISSUE THREAD

**Issue by hermithome** [honestbleeps/Reddit-Enhancement-Suite#1340]
[This](http://www.reddit.com/r/TrollXChromosomes/comments/29cuby/mrw_i_saw_a_redditor_with_a_20_and_after_looking/cikiht7?context=3) comment got me thinking. It's not the first time I've heard this sentiment expressed. A lot of people install RES because they want a few features and find the full deal to be a heavy load or just overwhelming. Or they find it confusing and want to understand each item before turning it on.

So, what about a giant freaking button that resets all preferences. Not to default RES, but to default Reddit. So they can turn on each preference one by one.

We could even make this a choice on install:

"We recommend choosing the default RES setup, which means bladdy blah blah. But you can also choose the default Reddit setup which will change nothing. You'll have to turn each individual feature on in order to use it."

**Comment by andytuba** [comment]
Fixed by 9ad53d752c7b612c55eb3c00172c06354e8bbe8d

Suggestions for other presets?
