### ISSUE TITLE
Comment score color-coding doesn't work in never-ending reddit

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1409]
http://www.reddit.com/r/RESissues/comments/2a2fq3/bug_comment_score_colorcoding_doesnt_work_in/

**Comment by erikdesjardins** [comment]
Fixed by https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/df1ab717a9c5c942ef0278f288d1a651bda204a1
