### ISSUE TITLE
some images downloading on opening (/closing?) expando

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1450]
http://www.reddit.com/r/EDC/comments/2ad4he/32mmoron/

https://farm6.staticflickr.com/5571/14306877339_3e25050ea7_c_d.jpg

http://www.reddit.com/r/RESissues/comments/2aafnz/bug_autodownloading_pictures_when_next_page_loads/ciu35ae?context=6

In Safari, some images are being downloaded when you open the expando.

**Comment by Poonaka** [comment]
I'm seeing this with 4.5.4 and the latest El Capitan beta 15A226f.
