### ISSUE TITLE
[request] make 'navigate by' a dropdown like 'sort by'.

### ISSUE THREAD

**Issue by agentlame** [honestbleeps/Reddit-Enhancement-Suite#1457]
navigate by is getting rather long: submitter|moderator|friend|me|admin|highlighted|gilded|IAmA|images|videos|popular|new, it would be nice if it could be displayed as a dropdown like sort by, to clean up the uI a bit.  Potentially an optional setting?

**Comment by larsjohnsen** [comment]
Implemented.
