### ISSUE TITLE
Rewrite certain links from href="/..." to "reddit.com/..."

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1466]
specifically subreddit manager's links

maybe sidebar links (per @hermithome suggestion)

**Comment by erikdesjardins** [comment]
This [is done](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/5419768b491b4544b09a3aa349a6bae77889e736/lib/modules/noParticipation.js#L99); explicitly specified subdomains are excluded naturally because it only replaces path-relative links.
