### ISSUE TITLE
Albums sometimes randomly switch back to previous images

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#1494]
This bug is immensely annoying to track down (mainly because it doesn't show up all the time), but sometimes, in albums (I've only seen it in imgur albums as those are the most popular), if you browse through an album and stay at a image, the album randomly switches to another (previous) image in the gallery. The size of the placeholder element is not updated to account for the change in images until you click-and-drag to resize.

**Comment by aiman-alsari** [comment]
I also see this behaviour. I am running 4.5.4 under Chrome 39.0.2171.99.
The steps to replicate and associated symptoms are exactly as described by previous posters.

**Comment by erikdesjardins** [comment]
I can reproduce this consistently like the above posters have said, with RES v4.5.4 in both Chrome 41 and FF 35 in Win 8.1.

AFAIK all that is necessary is for conserveMemory to be enabled, then open an album and scroll down to a point that conserveMemory is enabled, and the album will return to its original position (where it was when you scrolled down) a short delay after scrolling. (as explained above)

Now to fix it...

**Comment by honestbleeps** [comment]
Wait, your'e seeing this in Chrome 41? I've never seen or heard of it in Chrome at all... wonder if Canary introduced something similar to whatever's causing this in FF?

**Comment by blark** [comment]
I have this bug in Chrome too, and I've had it across multiple OS installs.

**Comment by allthefoxes** [comment]
I believe this has already been fixed

**Comment by sdluze** [comment]
I still have this problem, OS X Yosemite, Chrome 40.0.2214.111 (latest)

Turning off 'Conserve Memory' for UI fixes the issue.

**Comment by andytuba** [comment]
sdluze, yes, it is fixed for the next release. the fix hasn't yet been released.
