### ISSUE TITLE
automate the paperwork portion of the release process

### ISSUE THREAD

**Issue by honestbleeps** [honestbleeps/Reddit-Enhancement-Suite#1495]
- [ ] create some mechanism for updating the RES version number displayed on the RES website (maybe I just add a script to the RES site that pulls it from wikidata on reddit?)
- [ ] create some sort of script that aggregates all commit messages after [release tag] for later hand-editing of changelog
- [ ] ideally, also create a way of auto-updating the /r/RESIssues and /r/Enhancement sidebar info and http://reddit.com/r/enhancement/wiki/support with latest version # per browser, maybe from same wikidata as point 1 above.
- [ ] the above should support updating each browser individually if/whenever possible due to the AMO and Opera lag time in approval (Opera ~2-5 days, AMO often several weeks)

**Comment by mc10** [comment]
This is pretty much done, so closing.
