### ISSUE TITLE
High-pass score filter for frontpage posts per subreddit

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1508]
http://www.reddit.com/r/Enhancement/comments/2divdx/feature_request_filter_posts_that_show_up_on/

Although it might result in a bad-ish user experience, it still seems like a reasonable enhancement.  people can take it upon themselves to create a bad experince.

**Comment by erikdesjardins** [comment]
Implemented in #2077
