### ISSUE TITLE
in subreddit with naut theme, resize reply box makes reply box skip down the page

### ISSUE THREAD

**Issue by andreacrain** [honestbleeps/Reddit-Enhancement-Suite#1512]
In a subreddit with the naut v.2.2 theme, while browsing in Chrome with RES enabled, if you resize the reply box, it skips down the page about 1000 pixels. Disabling RES in extensions stops this happening, and it does not happen in non-naut subreddits, so it is some interaction between naut and RES.

**Comment by mc10** [comment]
Going to close this as a works for me; if someone can demonstrate a case where it's broken, feel free to reopen.
