### ISSUE TITLE
showImages.js: Gallery generation cleanup required

### ISSUE THREAD

**Issue by sgtfrankieboy** [honestbleeps/Reddit-Enhancement-Suite#1524]
Currently the generation of galleries is in the `generateImageExpando` function, which isn't optimal because I'm currently working on support for a website that has webm support in their galleries.

I've made partial progress converting the gallery generation to it's own function but the gallery will reuse the media container (`img`, `video`, `audio`) so it will try to load the video inside an `img` tag or the other way around. Does anyone have a nice method of handling this?

Current Progress: https://github.com/sgtfrankieboy/Reddit-Enhancement-Suite/blob/vidble/lib/modules/showImages.js#L819

**Comment by larsjohnsen** [comment]
Fixed.

**Comment by erikdesjardins** [comment]
#2903
