### ISSUE TITLE
Night Mode will not remain off

### ISSUE THREAD

**Issue by landaire** [honestbleeps/Reddit-Enhancement-Suite#1533]
I recently had night mode set to automatic, but decided to turn it off. The auto night mode option sticks, but the night mode option itself stays on for whatever reason. Turning off night mode completely does not help either. For some reason the night mode stylesheet is still being used in some places.

Here's an example, /r/techsupport:
![screen shot 2014-08-22 at 09 08 06](https://cloud.githubusercontent.com/assets/1313522/4013476/96009580-2a16-11e4-8073-5c74244f89b7.png)

I've cleared my browser cache and restarted it for good measure but still no dice.

**Comment by atomic1fire** [comment]
I think I've encountered this bug.

I turn night mode off without completely turning the module off.

It's fine for a while, and then suddenly it's night mode again.

I made sure I was running chrome stable (Am now) and the bug still exists.

**Comment by mc10** [comment]
Going to close due to staleness; if this is still a bug, feel free to reopen or make a new issue.
