### ISSUE TITLE
Title disappears from thing after editing comment from userpage

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1541]
http://www.reddit.com/r/RESissues/comments/2efv73/bug_editing_a_comment_from_ones_user_page_causes/

This is handled by modules.betteReddit.editMyComments

probably fallout from bsimpson's change last week to comment HTML.. definitely RES's responsibility to fix it.

**Comment by erikdesjardins** [comment]
Reddit gets to fix this (it still happens) now that they provide the edit buttons.

I guess it should be closed?
