### ISSUE TITLE
top/controversial posts from: temporarily

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1542]
implement a "sort comments temporarily"-like thing for top/controversial linklistings.  should be the same sort of logic.

reddit.com/top
reddit.com/controversial
reddit.com/domain/site.com/top
reddit.com/me/m/multi/top
reddit.com/r/subreddit/top

**Comment by larsjohnsen** [comment]
Added by #4574
