### ISSUE TITLE
multiusers love this one crazy hack to let you reddit on several accounts simultaneously

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1548]
Take the account id, in example : 1252525

And use this url : http://01.25.25.25.reddit.com with a cookie limited to this domain.

(or maybe http://id.01.25.25.25.reddit.com, i don't know)

If the user click on a link to www.reddit.com, show a notification with a link to go back to 01.25.25.25.reddit.com.

[](#that’s an interesting hack that’s pretty fucking clever actually)

**Comment by mc10** [comment]
Going to close this as impractical, I think most of us would prefer that we don't copy around URLs with random numerical subdomains.
