### ISSUE TITLE
[Concept] User profile

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1549]
Hi,

So here a special idea ([chat log](https://gist.github.com/matheod/f6287c16650a31edf5af)).

I (and not only me) feel reddit lack of a way for user to present themself. Lots of time, you found user saying smart thing, but if you want to learn more about them, you have to search on their comment information about them.

So here the idea :
Allow people to write they profile description with this little hack : http://api.reddit.com/api/multi/user/matheod/m/profile/description

So what the point with RES ? This concept need to spread to be effective, and res could be a good way to create a sort of convention.

Res should, when going on a profile, fetch (with a cache system of course) `http://api.reddit.com/api/multi/user/USERNAME/m/profile/description` and if it exist, show the description in the profile sidebar. Also RES should provide easy way to create/edit our profile description.

The big advantage, is it also work for non RES user ! If this concept spread, people would just have to check if there is a "profile" multireddit, and open it to look at the description (http://www.reddit.com/me/m/profile)

@Andytuba also suggested to allow non-res user to easily set up/edit their profile description with a application redditenhancementsuite.com/editprofile

Of course, it's a little off topic with res, but it's all about launching a very usefull concept.

**Comment by mc10** [comment]
Obsolete now with [Reddit building profiles themselves](https://www.reddit.com/r/announcements/comments/60p3n1/tldr_today_were_testing_out_a_new_feature_that/).
