### ISSUE TITLE
RES trophy

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1553]
When we launch res for first time (maybe after 1H), show a notification to the user asking him if he want a RES trophy visible only by res people.

If yes, it create a public multi reddit RES_trophee.

And when on user page, res check if there is a RES_trophee multi reddit :)

**Comment by mc10** [comment]
Going to close this unless there's more interest, especially since it might be confused with Reddit's trophies.
