### ISSUE TITLE
Fix search syntax

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1554]
Convert ourself the syntax into cloudsearch syntax.

https://rawgit.com/DeeNewcum/reddit/master/cloudsearch/cloudsearch_reference.html

http://www.reddit.com/r/bugs/comments/2cwjz9/search_queries_get_mangled_to_the_point_where/

---

http://yoursandmyideas.wordpress.com/2012/04/07/infixtoprefix/

**Comment by matheod** [comment]
Todo : (something easier, not fixing search)

Allow to search for an url

- Detect search exactly in the form url:[an url] (will not work if anything else)

- Add a button somewhere to search for an url

**Comment by erikdesjardins** [comment]
Cloudsearch is no longer going to be used https://www.reddit.com/r/changelog/comments/6pi0kk/improving_search/dkpx8nu/?context=4
