### ISSUE TITLE
refactor keyboardNav.handleKeyPress and called actions

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1557]
those damn switch statements have got to go. 

i envision something like

    keyboardNav.options.upVote = {
        ...,
        actions: [
             { 
                pageType: [ 'linklisting', 'profile' ]
                action: function() { 
                     this.upVote(true);
                }
            }
             { 
                pageType: [ 'comments', 'inbox' ]
                action: function() { 
                     this.upVote();
                }
            }
         }
    }

    keyboardNav.options.upVote = {
        ...,
        actions: undefined
    }

handleKeyPress should iterate through keyboardNav.options where type=keycode, find all matching keycodes with either no actions or option.actions where pageType includes current page type, and execute keyboardNav[optionKey] if no actions else keyboardNav.options[optionKey].actions where pageType includes current page type.

**Comment by erikdesjardins** [comment]
Fixed by #2025
