### ISSUE TITLE
Allow to send an MP when we mention someone

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1565]
When mentionning a user (I.e. writing /u/matheod for example), show under the post some checkbox for each mentionned user.  If we check it and send the message, it's send* an mp to checked user.
(the mp contains the comment + link to the comment)

*not all at the same time, more than 1 mp each 30s ore something like that + maybe limit to max 5 users

**edit:** check if the user is gold or not and don't send if he his gold maybe ?

**Comment by erikdesjardins** [comment]
Probably redundant now that you don't need gold for this.
