### ISSUE TITLE
"give me your settings please" code idea...

### ISSUE THREAD

**Issue by honestbleeps** [honestbleeps/Reddit-Enhancement-Suite#1571]
For debugging people's issues, it would be great if we could do something like this...

reply to a comment with something like: [Please share your moduleName settings with us](#shareSettings/moduleName) -- when the user encounters this reply, they'd see a prompt asking permission (only in RESIssues and Enhancement, probably) to post their settings JSON as a comment. If they click yes, it will reply and paste that in.

Considerations:
- working from the inbox would be nice, but I wouldn't want non-RES devs to be able to 'trick' people into sharing?  maybe a whitelist of approved support users or something, pulled from wiki data?
- account switcher needs to be a hard coded exception, since passwords are stored in it

**Comment by andytuba** [comment]
New idea: dump non-default scalar options (except selected sensitive values eg username Hider replacement text) as a list of `[](#res:settings/moduleID/optionid "non default value")`

**Comment by allthefoxes** [comment]
This is a really cool idea, would be very helpful. I do think a modmail would be the best solutions, a full set of RES settings could be a digital fingerprint

**Comment by larsjohnsen** [comment]
Implemented by #4248.
