### ISSUE TITLE
e10s support

### ISSUE THREAD

**Issue by kevinji** [honestbleeps/Reddit-Enhancement-Suite#1574]
e10s for Firefox is probably still in the future, but if possible, we should support it as soon as we can. [Bug 1046044](https://bugzilla.mozilla.org/show_bug.cgi?id=1046044).

**Comment by yaomtc** [comment]
Using Firefox 48 on Linux and the beta of RES, and browser.tabs.remote.autostart set to true, multiprocess currently doesn't work. It only works if I disable RES (and many other add-ons for that matter)
