### ISSUE TITLE
Spotlight'd post don't get expandos

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1586]
http://www.reddit.com/r/RESissues/comments/2fwlk5/bug_image_expando_does_not_appear_in_spotlight_box/

**Comment by erikdesjardins** [comment]
https://www.reddit.com/r/Enhancement/comments/315uq9/feature_request_expando_on_spotlight

**Comment by tobiasvl** [comment]
:+1:

**Comment by andytuba** [comment]
This might actually be easy if the "get selectable items" class includes this in the selector.  Let's try and get it fixed for 4.6.3.

**Comment by andytuba** [comment]
Hidden requirement :stuck_out_tongue: -- open expando should be closed when clicking the [<] [>] prev/next buttons in the spotlight navigator.
