### ISSUE TITLE
Clyp.it Expandos do not pause when closing

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#1654]
See here: http://www.reddit.com/r/pics/comments/2hwdje/teen_who_wanted_his_cat_in_his_yearbook_is_joined/ckwmt3s

**Comment by jpatapoff** [comment]
Clyp co-founder/developer here. For anyone who's familiar with the issue, is this something I can fix on my end? I could listen for an event that fires when the widget element is no longer visible and then subsequently pause the audio file. This would fix this issue, but would cause other problems. For example, if the widget is embedded on someones blog, the user then clicks play and scrolls down the page to look at more content, the the audio file would pause when out of view. I think the result of this hypothetical change would be worse than the situation we're in right now. 

I'm thinking a better solution would be to totally remove the widget from the DOM when collapsing the expando.

Thoughts?

@honestbleeps this shouldn't be an issue anymore as we're now 100% HTTPS.

**Comment by Saturate** [comment]
@jpatapoff I agree, removing the DOM would be a good solution.

**Comment by larsjohnsen** [comment]
Fixed.

**Comment by erikdesjardins** [comment]
...in #2903
