### ISSUE TITLE
highlight "me"

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1666]
https://www.reddit.com/r/Enhancement/comments/2iqmf0/feature_request_highlighting_own_username/

**Comment by Double-A-92** [comment]
This is probably done in https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/userHighlight.js If somebody whats to try it.

**Comment by larsjohnsen** [comment]
@Double-A-92 `loggedInUser` returns the user id.
