### ISSUE TITLE
use imgur gifv instead of gfycat when convertGifsToGfycat enabled

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1669]
https://www.reddit.com/r/Enhancement/comments/2iwdzn/feature_request_use_imgurs_prehtml5ied_gifvs/cl655fz

**Comment by erikdesjardins** [comment]
Fixed in #2998: `convertGifsToGfycat` runs after siteModules do, so if imgur emits `type: 'VIDEO'` it won't be converted.
