### ISSUE TITLE
Add xkcd expando support

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#1709]
A JSONP API is available at https://dynamic.xkcd.com/api-0/jsonp/comic/123?callback=func (where 123 is the comic number and func is the callback function), so this should be doable without additional permissions.

[r/Enhancement post.](https://www.reddit.com/r/Enhancement/comments/2k5o5i/feature_request_expando_support_for_xkcd_links/)

**Comment by erikdesjardins** [comment]
#2815
