### ISSUE TITLE
RedditEnhancementSuite.com features page is very out of date

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#1727]
http://redditenhancementsuite.com/features.html

A few things need to be changed, it seems:

>Save Comments
>Allows you to save comments, since reddit doesn't!

Save Comments
Allows you to store comments locally without reddit gold

(or, alternatively if we want to avoid the without reddit gold thing)

Save comments
Allows you to store comments locally, to easily view them in the future!

---

>Spam Button
>Adds a Spam button to posts for easy reporting

Is that even a thing still? Maybe I have that off

---

>Uppers and Downers Enhanced
>Displays up/down vote counts on comments. Fully customizable!

RIP

---

And:

>Syncing
>RES Pro allows you to sync settings and data to a server.
>This feature is coming ~~soon!~~ never!

/s hurhurhur

**Comment by thybag** [comment]
Suspect this issue is closeable, as of the new site :)

**Comment by erikdesjardins** [comment]
Had to make a few changes
