### ISSUE TITLE
RES Icons blurry on high DPI displays

### ISSUE THREAD

**Issue by imjoshdean** [honestbleeps/Reddit-Enhancement-Suite#1770]
On high DPI displays, such as Macbook Pro with Retina, the RES icon spite map is blurry. These should be updated to work. The process is (in theory) simple:
1. Increase the original images to 2x size.
2. Keep the same positioning in the sprite image
3. Update the CSS to include background-size property set equal to the height and width of the original
4. ???
5. Profit!

**Comment by larsjohnsen** [comment]
Seems to have been fixed.
