### ISSUE TITLE
"null" in RESmodules.dashboard.USERNAME breaks dashboard

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#1777]
Hello,

I just received that : 

> https://www.reddit.com/r/RESissues/comments/28olsq/bug_dashboard_is_broken_old_and_unresolved_problem/cicxj2f
> 
> My issue was fixed by running that command and removing the "null" in the beginning of the array.
> 
> Thank you.

This may be usefull I don't know :)

**Comment by andytuba** [comment]
Let's make this a real todo item.

TODO: troubleshooter option to clear out nulls in dashboard data
