### ISSUE TITLE
fire a notification when clicking navigate by: new if disabled

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1793]
https://www.reddit.com/r/Enhancement/comments/2mnucw/feature_request_mark_navigate_by_new_as_a_gold/

**Comment by voidplayer** [comment]
after noticing navigation by new was not working during a very long long time, i decided today to report this bug... just to learn is a gold feature...

this is not clear by the interface at all and both fixes seem easy enough

on the bright side i discovered the "navigate by" bar... i always use the semi-transparent combo selector on the right

**Comment by larsjohnsen** [comment]
`new` is now not shown when there's no gold. #4507
