### ISSUE TITLE
PDFy embedding

### ISSUE THREAD

**Issue by joepie91** [honestbleeps/Reddit-Enhancement-Suite#1798]
I run a PDF hosting service at https://pdf.yt/, and given that more and more people seem to be starting to use it on Reddit, it'd be cool if RES could support it in its expand/embed feature, like it does with image URLs, YouTube videos, and so on. Is it possible to add support for this?

The embed code can be found on the site, but it really just comes down to appending `/embed` to the URL and iframing it, optionally with some parameters; eg. https://pdf.yt/d/kdIrOFZdTzelLwY9 -> https://pdf.yt/d/kdIrOFZdTzelLwY9/embed?sparse=1 (to hide the toolbar by default). The layout is responsive, so it should work within a very small `iframe` as well.

I don't think CORS support would be necessary as it's an embed in `iframe` form, but as I don't have any experience with browser extension development, please do correct me if I'm wrong.

**Comment by allthefoxes** [comment]
The way showImages.js is handled now would require a bit of shuffling around, just FYI

**Comment by mc10** [comment]
Closing, as the site appears to be down.
