### ISSUE TITLE
option to prefer gif over gifv

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1803]
there seem to be enough reasonable responses at this point to validate it

https://www.reddit.com/r/Enhancement/comments/2mvxlw/is_there_a_way_to_see_inline_gifs_from_imgur_as/

etc.

**Comment by andytuba** [comment]
https://www.reddit.com/r/RESissues/comments/39sqtq/bug_gif_loaded_with_res_looks_like_its_got/cs6inpc?context=3

**Comment by munumafia** [comment]
Anyone have a problem with me picking this up?

**Comment by andytuba** [comment]
Go for it!
