### ISSUE TITLE
Pin OP to top

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1821]
http://www.reddit.com/r/Enhancement/comments/2nov5j/is_there_a_scroll_in_middle_option/

This is the second or third request.

**Comment by erikdesjardins** [comment]
https://www.reddit.com/r/Enhancement/comments/2rl5m1/feature_request_on_a_post_page_view_the_link/

Linked user suggested that we could include OP in the parent hover pop-up, could be interesting (might not be enough room, though).

**Comment by andytuba** [comment]
brainstorms:

"scroll helper": button to scroll to top, which then toggles to "scroll back where you were". Could be a keyboard nav item too

**Comment by erikdesjardins** [comment]
Another request:
https://www.reddit.com/r/Enhancement/comments/2vaq1i/
