### ISSUE TITLE
Use gifv inside imgur albums

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1833]
https://www.reddit.com/r/RESissues/comments/2nytwl/bug_imgur_albums_with_gifs_between_20m_and_50m_do/

**Comment by fireattack** [comment]
Just found a more serious example about this issue: https://www.reddit.com/r/oddlysatisfying/comments/4b304b/incredibly_satisfying_power_washing_videos/

You can see here, for the second images of this album, the GIF link doesn't even work (not animated) at all.
