### ISSUE TITLE
When using convertGiftoGfycat with Opera the content is blocked

### ISSUE THREAD

**Issue by Lehmax** [honestbleeps/Reddit-Enhancement-Suite#1863]
This is a problem with RES and Opera, so I'll post this on both forums.
When I open a gif with the Inline Image Viewer it gets blocked by Opera because it's coming from insecure sources. Could that be caused by gfycat not using SSL or is this a bug with RES?
![ss 2014-12-14 at 09 07 00](https://cloud.githubusercontent.com/assets/8298953/5428863/3c8b378a-83d5-11e4-9819-a703657e149b.png)

**Comment by xur86x** [comment]
bump?

**Comment by andytuba** [comment]
Could you post this to /r/resissues/submit instead, please?  "I'm having an issue" or "I found a bug" button on the submit page.

**Comment by xur86x** [comment]
Will do. Thanks for the answer.

**Comment by andytuba** [comment]
thanks!  sorry you didn't get a reply sooner, it was busy coming up on the holidays.

**Comment by xur86x** [comment]
Part of it was my own fault. Should have posted that comment earlier to get some attention.
