### ISSUE TITLE
support fennic (android's firefox)

### ISSUE THREAD

**Issue by zbowling** [honestbleeps/Reddit-Enhancement-Suite#188]
The api is nearly the same but the extension needs to say it supports it. Should probably work out of the box. Unfortunately mobile chrome doesn't have extensions just yet.

**Comment by mc10** [comment]
I'm going to close this as too out-of-scope, as there's no real way we'll be able to support Android's Firefox on top of the other browsers, and the user experience seems quite suboptimal. Also, a plethora of Reddit apps already exists for Android that give a much better user experience.
