### ISSUE TITLE
Account switcher breaks username hider with no rows in account list

### ISSUE THREAD

**Issue by brettp** [honestbleeps/Reddit-Enhancement-Suite#1881]
Console log: 
![screen shot 2014-12-19 at 12 33 33 pm](https://cloud.githubusercontent.com/assets/43375/5508465/47bdb1f6-877b-11e4-8aa4-e2e3339b49f2.png)

**Comment by mc10** [comment]
Going to mark as "works for me" unless someone else can reproduce this.

**Comment by brettp** [comment]
FWIW, this is definitely still a problem for me with RES 4.5.4 and Chrome 42.0.2311.135 (64-bit) OS X:

![screen shot 2015-05-14 at 9 41 56 am](https://cloud.githubusercontent.com/assets/43375/7632694/8649e8b2-fa1d-11e4-9cb0-f52b42bb6721.png)

**Comment by andytuba** [comment]
Can you try going into your settings and adding an empty row to the Account Switcher's accounts list?

**Comment by brettp** [comment]
That fixed it. As you probably guessed, I had the account switcher enabled,
but none defined.
