### ISSUE TITLE
Extend defaultContext to userpage and mod pages

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1903]
https://www.reddit.com/r/RESissues/comments/2q5x5y/bug_defaultcontext_setting_does_nothing/

**Comment by andytuba** [comment]
This is fixed, right?

**Comment by 13steinj** [comment]
@andytuba for profile pages, yes. For mod pages, not that I know of (I don't see anything that does this in master nor release/4.6.1). I thought that there was a PR for it (or one that includes it); but I can't seem to find it atm
