### ISSUE TITLE
Show current user's gold status in user bar

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1915]
followup to #1914

**Comment by coreyja** [comment]
Where would be a good place to check the gold status and add the icon? A new module similar to the showKarma one that adds the comment karma?
I have a pull request for #1914 and was going to work on this one too, but didn't know where it should go.

**Comment by andytuba** [comment]
i'd just dump it into showKarma since it's related both conceptually and code-wise, and then maybe consider changing the name to showUserDetails.

**Comment by bruno207** [comment]
Hey there!

I've started looking into this issue and it seems fairly straightforward to implement. I was wondering if there were specific opinions about placement of the icon around the user span area. 

If you take a look here:
![plopped](https://cloud.githubusercontent.com/assets/10170354/18769198/23283680-80f9-11e6-9c0f-2c7603e11060.png)

I've gone ahead and dropped the 'gilded-icon' in between the user span and the selector '|'. Just curious about an opinion before I go ahead and play with showKarma to get it in there if the user has gold.
