### ISSUE TITLE
Review .forEach/.some changes

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1965]
I'd like to more deeply test @mc10's linting changes from last week, but want to avoid too much duplication of effort.

**Comment by andytuba** [comment]
@mc10, could you call out changes you've already double-checked?

**Comment by mc10** [comment]
Fixes made already:
* https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/2911a06ea46a5249dd95676457cb813e7076db86
* https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/1ad4522f846de8d4936d2e1059915e27398e2b5e
* https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/817740ac93bb91f7c2c1e1eda655c4118a2710a4
* https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/72aa079739042c5d562c79c622f539821f235f7c
* https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/6664aa0de9befc3a4fdc0720763bb6ec3bcf6a32
* https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/4e3e58c9eb8dd9258c97b6579fc431e529ddc3d8
* https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/acb38d7615a77f7cc1bdee3745adeff9355b9afb / https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/d5e5c432f960072c86480fe5da821d81ff2508c8 / https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/fca6db3937f07d0adbc93056e712bd53484328dd

**Comment by andytuba** [comment]
I made a few stylistic commits (e.g. swapping around each/every/some), plus some actual functional fix-ups to the console (don't dupe save changes buttons, hide the button in modules w/o options, show the "options saved!" a little bit longer)
