### ISSUE TITLE
NeverEndingReddit: Need to scroll past post list to load next page

### ISSUE THREAD

**Issue by buesing** [honestbleeps/Reddit-Enhancement-Suite#1966]
On subreddits with long sidebar text (e.g. /r/linux), the sidebar height exceeds the height of the post list. In order to load the next page, you need to scroll until the end of the page, which can result in a lot of wasted space and is a little confusing since you need to scroll up again to continue where you stopped reading. It would be better to load the next page when you reach the end of the post list, not the end of the page.

Google Chrome Version 39.0.2171.95 (64-bit), Debian.

**Comment by andytuba** [comment]
fixed by #1930

**Comment by andytuba** [comment]
will be included in v4.5.5 release
