### ISSUE TITLE
"Quick Message" popup truncated message at semicolon

### ISSUE THREAD

**Issue by martey** [honestbleeps/Reddit-Enhancement-Suite#1967]
Google Chrome 39.0.2171.95
RES 4.5.4

I used the new "quick message" popup dialog to write a message to the Reddit admins. The message sent successfully, but seems to have truncated my message (e.g. I wrote "Lorem ipsum; dolor sit amet", but the Sent Messages page only shows "Lorem ipsum").

**Comment by erikdesjardins** [comment]
#1950

**Comment by martey** [comment]
I did a search but somehow missed this. Thanks!
