### ISSUE TITLE
4.6 Changelog

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#1976]
## RES 4.6 Changelog

**Features**
- Added "Upload" module. Allows file uploading directly from the /submit page ^(thanks @SirCmpwn, @andytuba, @erikdesjardins, and @imgrush)  - Currently only supports imgrush.com - If you are interested in adding upload support for your site, please [check the RES GitHub wiki](https://github.com/honestbleeps/Reddit-Enhancement-Suite/wiki/Adding-new-media-hosts).

- Added custom filters to *filteReddit* module ^(big thanks @gamefreak)

- Added loading selected subreddit stylesheets anywhere ^(big thanks @andytuba)

- Added custom toggles to RES dropdown menu, particularly for turning custom-loaded subreddit stylesheets on/off 

- Added "Orangered" module, for managing and syncing unread notifications (locally). does not replace reddit message notifiers. ^(thanks @andytuba)

- Added global spoiler tag module. Currently only works on user profiles. Any markdown pointing to /spoiler or #spoiler (or other standard spoiler implementations) will be hidden. Hovering shows the text ^(thanks @SirCmpwn and @andytuba )

- Added some usability and gussying-up to the settings console ^(thanks @andytuba and @gamefreak)

- Added a back to top button ^(thanks @andytuba)

- Added new "presets" - One button press to apply different presets to RES settings. ^(thanks @andytuba )

- Added the ability to send messages as a subreddit with quickMessage ^(thanks @erikdesjardins )

- Added the option to automatically add the page link/comment link when opening quickMessage ^(thanks @erikdesjardins )

- quickMessage can now handle /message/compose links and can fill in relevant fields ^(thanks @erikdesjardins )

- Extended subreddit filter to everywhere by default, with an option to go back to /r/all and /domain ^(thanks @allewun and @andytuba)

- Added gold icon to accounts listed in *Account Switcher* dropdown menu ^(thanks @coreyja)

- Added repost warning on submit page ^(thanks @erikdesjardins and @andytuba) ^(The "Someone has already posted that link..." warning now warns you *on* the "submit a post" page, before you try to submit.)

- Subreddit Info now shows when hovering over trending subreddit listings ^(thanks @andytuba)
- Added the ability to customize keyboard shortcuts for comment tools (bold, italic, etc.) ^(thanks @erikdesjardins )

- Added a prompt before abandoning changes to settings options you haven't saved ^(thanks @andytuba)

- Added options to show full timestamps by default ^(thanks @erikdesjardins)

- Added a "New RES announcement" notification in RES dropdown menu ^(thanks @andytuba)

- Added a subreddit manager option for lowercase/mixed-case shortcuts in top bar ^(thanks @andytuba)

- Added a subreddit manager option to use different/same set of shortcuts for different accounts ^(thanks @andytuba)

- Added # to "show child comments" on top-level comments ^(thanks @erikdesjardins)

- Added steamusercontent.com expando support to *showImages* module ^(thanks @JonBons )

- Added futurism.co expando support to *showImages* module ^(thanks @mverderese )

- Added pastebin.com expando support to *showImages* module ^(thanks @erikdesjardins )

- Added gist.github.com expando support to *showImages* module ^(thanks @erikdesjardins )

- Added drscdn.500px.org support to *showImages* module ^(thanks @erikdesjardins, @andytuba)

- Added Microsoft OneDrive support to *showImages* module ^(thanks @sgtfrankieboy and @andytuba)

**Fixes**
- Vote weight (RES tracking upvotes/downvotes you give to each user) tracks again ^(thanks @matheod)

- rts and save-RES buttons and some other things should now work with newly loaded comments ^(Thanks @erikdesjardins )

- Username Hider hides username with correct displayText in header and taglines ^(thanks @erikdesjardins)

- Username Highlighter adds colored background to hidden usernames (e.g. OP, mod, admin, etc.) ^(thanks @erikdesjardins )

- New tabs will open in the foreground/background according to browser preference now. (Used to only open in background) ^(Thanks @mc10) 

- Fixed certain elements in nightmode (code blocks, quotes, etc..) to work with reddit's new markdown. ^(Thanks @gavin19)

- Fixed Modmail keyboard shortcut not being able to be customized ^(thanks @erikdesjardins)

- Fixed post title link changing to its expando's direct URL ^(thanks @erikdesjardins)

- Fixed quickMessage not respecting usernameHider ^(thanks @erikdesjardins )

- Fixed albums switching back to image 1 when scrolling  ^(thanks @erikdesjardins 

- Fixed tumblr photo captions not showing for single-image posts ^(thanks @andytuba)

- Fixed account switcher not closing properly sometimes ^(thanks @Shraymonks)

- Fixed multiple entries for the same subreddit appearing in "My subreddits" dropdown ^(thanks @andytuba)

- Fixed nightmode adding a black background when visiting sites with the reddit toolbar enabled ^(thanks @andytuba)

- Fixed nightmode styling on login popup ^(thanks @yangzihe)

- Fixed wrong account age near first of the month in user info hover popup ^(thanks @yangzihe)

**Other**

- Updated various icons and buttons to use a flat look ^(thanks @erikdesjardins )

- Made the new announcement notification on the RES Gear Icon stand out a bit more ^(thanks @erikdesjardins )

- Moved *uncheckSendReplies* from *betteReddit* to *submitHelper*

- Default macros now editable - LoD removed from default macro list

- Cleaned up *quickMessage* module ^(thanks @erikdesjardins )

- Cleaned up *accountSwitcher* menu and error code ^(thanks @andytuba)

- Console fixes ^(thanks @matheod )

- Remove autocomplete from console (It didn't work anyways) ^(thanks @gmcclure382) 

- Fewer ajax calls to check for moderated subreddits ^(thanks @JordanMilne, @andytuba)

- Update jQuery things ^(thanks @mc10 )

- Refactored *showImages.js* - All hosts now have their own file, allowing for easier fixing and creation of expando supporting hosts. ^(thanks @andytuba @erikdesjardins and more)

- Greatly refactored *KeyboardNav* ^(thanks @andytuba)

- RES added elements such as keyboardNav numbers and usertags will no longer get copied when you copy a text ^(thanks @arresteddevelopment)

- Refactored gulp a bit ^(thanks @andytuba)

- Update readme ^(thanks @allthefoxes and @mc10 )

- Linting and janitoring

- A [few](http://i.imgur.com/s4XgqRN.png) [typo](http://i.imgur.com/1oTVuEX.png) [commits](http://i.imgur.com/DC6svMP.png) [as](http://i.imgur.com/H5TJPnD.png) [always](http://i.imgur.com/yGrByoR.png) - [and](http://i.imgur.com/FkfNwcc.png) [these](http://i.imgur.com/PJSJCru.png) too.

**Comment by allthefoxes** [comment]
##RES 4.5.5

**Features**
-

**Fixes**
-rts and save-RES buttons and some other things should now work with newly loaded comments (Thanks @erikdesjardins )
- New tabs will open in the foreground/backround according to browser preference now. (Used to only open in backround) (Thanks @mc10)

**Other**
-Cleaned up quickMessage module (Thanks @erikdesjardins )
-Linting and janitoring
-Console fixes (Thanks @matheod )
-Remove autocomplete from console (Thanks @gmcclure382)

**Comment by allthefoxes** [comment]
@andytuba The vote weight thing is fixed right?

**Comment by erikdesjardins** [comment]
#1926 fixed in
https://github.com/matheod/Reddit-Enhancement-Suite/commit/59e0b024e2692b72ee75464d5f59e3554568b738

**Comment by andytuba** [comment]
noted, thanks.  i know i'm missing a bunch of fixes from the last month or so, so feel free to highlight anything (or @allthefoxes just edit into your comment)

**Comment by allthefoxes** [comment]
If my opinion means anything, I am about ready to ship this freaking update already. Tired of the daily "RES doesn't track my votes anymore!!!!?!?!" threads ;_;

**Comment by erikdesjardins** [comment]
#1972 is probably significant enough to include here

**Comment by allthefoxes** [comment]
@andytuba I've clened up the changelog a little bit, trying to make it a bit more spiffy and standardized.

**Comment by andytuba** [comment]
i hope i didn't ruin the spiffifying

**Comment by allthefoxes** [comment]
@andytuba One of the things I am trying to spiff up with spiffying is using a more fixed terminology - I.e. features where something was added should start with "Added.." and bug fixes should start with "Fixed..." -- all if possible.

**Comment by erikdesjardins** [comment]
Dupe:
>Added "you haven't saved your settings yet, are you sure you want to close the settings console yet?" prompt

---
>Added a prompt before abandoning changes to settings options you haven't saved

Also, for "Remove autocomplete from console" you might want to mention that it didn't actually work, so people don't think we've removed functionality.

Also "Cleaned up Inline Image Viewer file structure" is probably made redundant by "Refactored showImages.js - All hosts now have their own file".

Otherwise, I definitely like the spiffying - thanks for maintaining this!

**Comment by allthefoxes** [comment]
Fixed it up

**Comment by erikdesjardins** [comment]
>Fixed the RES gear icon not showing sometimes when SRStyle was off

Was only an issue with the dev build, so we probably don't need to mention it.

**Comment by allthefoxes** [comment]
Gotcha.

**Comment by allthefoxes** [comment]
By the way, I spaced it out just for the time being since editing it is a nightmare without the spaces.

**Comment by erikdesjardins** [comment]
Should probably thank SirCmpwn for the upload module - he wrote it and the mediacrush module that imgrush now uses.

**Comment by andytuba** [comment]
wow how did we miss putting upload on there.

fixed up

**Comment by SirCmpwn** [comment]
woo

**Comment by SirCmpwn** [comment]
Good luck imgrush, hope you're ready to have your servers smashed!

**Comment by andytuba** [comment]
backup:

## RES 4.6 Changelog

**Features**
- Added "Upload" module. Allows file uploading directly from the /submit page ^(thanks @SirCmpwn, @andytuba, @erikdesjardins, and @imgrush)  - Currently only supports imgrush.com - If you are interested in adding upload support for your site, please [check the RES GitHub wiki](https://github.com/honestbleeps/Reddit-Enhancement-Suite/wiki/Adding-new-media-hosts).

- Added custom filters to *filteReddit* module ^(big thanks @gamefreak)

- Added loading selected subreddit stylesheets anywhere ^(big thanks @andytuba)

- Added custom toggles to RES dropdown menu, particularly for turning custom-loaded subreddit stylesheets on/off 

- Added "Orangered" module, for managing and syncing unread notifications (locally). does not replace reddit message notifiers. ^(thanks @andytuba)

- Added some usability and gussying-up to the settings console ^(thanks @andytuba and @gamefreak)

- Extended subreddit filter to everywhere by default, with an option to go back to /r/all and /domain ^(thanks @allewun and @andytuba)

- Added gold icon to accounts listed in *Account Switcher* dropdown menu ^(thanks @coreyja)

- Added repost warning on submit page ^(thanks @erikdesjardins and @andytuba) ^(The "Someone has already posted that link..." warning now warns you *on* the "submit a post" page, before you try to submit.)

- Subreddit Info now shows when hovering over trending subreddit listings ^(thanks @andytuba)
- Added the ability to customize keyboard shortcuts for comment tools (bold, italic, etc.) ^(thanks @erikdesjardins )

- Added a prompt before abandoning changes to settings options you haven't saved ^(thanks @andytuba)

- Added options to show full timestamps by default ^(thanks @erikdesjardins)

- Added a "New RES announcement" notification in RES dropdown menu ^(thanks @andytuba)

- Added a subreddit manager option for lowercase/mixed-case shortcuts in top bar ^(thanks @andytuba)

- Added a subreddit manager option to use different/same set of shortcuts for different accounts ^(thanks @andytuba)

- Added # to "show child comments" on top-level comments ^(thanks @erikdesjardins)

- Added steamusercontent.com expando support to *showImages* module ^(thanks @JonBons )

- Added futurism.co expando support to *showImages* module ^(thanks @mverderese )

- Added pastebin.com expando support to *showImages* module ^(thanks @erikdesjardins )

- Added gist.github.com expando support to *showImages* module ^(thanks @erikdesjardins )

- Added drscdn.500px.org support to *showImages* module ^(thanks @erikdesjardins, @andytuba)

- Added Microsoft OneDrive support to *showImages* module ^(thanks @sgtfrankieboy and @andytuba)

**Fixes**
- Vote weight (RES tracking upvotes/downvotes you give to each user) tracks again ^(thanks @matheod)

- rts and save-RES buttons and some other things should now work with newly loaded comments ^(Thanks @erikdesjardins )

- Username Hider hides username with correct displayText in header and taglines ^(thanks @erikdesjardins)

- Username Highlighter adds colored background to hidden usernames (e.g. OP, mod, admin, etc.) ^(thanks @erikdesjardins )

- New tabs will open in the foreground/background according to browser preference now. (Used to only open in background) ^(Thanks @mc10) 

- Fixed certain elements in nightmode (code blocks, quotes, etc..) to work with reddit's new markdown. ^(Thanks @gavin19)

- Fixed Modmail keyboard shortcut not being able to be customized ^(thanks @erikdesjardins)

- Fixed post title link changing to its expando's direct URL ^(thanks @erikdesjardins)

- Fixed albums switching back to image 1 when scrolling  ^(thanks @erikdesjardins 

- Fixed tumblr photo captions not showing for single-image posts ^(thanks @andytuba)

- Fixed account switcher not closing properly sometimes ^(thanks @Shraymonks)

- Fixed multiple entries for the same subreddit appearing in "My subreddits" dropdown ^(thanks @andytuba)

- Fixed nightmode adding a black background when visiting sites with the reddit toolbar enabled ^(thanks @andytuba)

- Fixed nightmode styling on login popup ^(thanks @yangzihe)

- Fixed wrong account age near first of the month in user info hover popup ^(thanks @yangzihe)

**Other**

- Updated various icons and buttons to use a flat look ^(thanks @erikdesjardins )

- Moved *uncheckSendReplies* from *betteReddit* to *submitHelper*

- Default macros now editable - LoD removed from default macro list

- Cleaned up *quickMessage* module ^(thanks @erikdesjardins )

- Cleaned up *accountSwitcher* menu and error code ^(thanks @andytuba)

- Console fixes ^(thanks @matheod )

- Remove autocomplete from console (It didn't work anyways) ^(thanks @gmcclure382) 

- Fewer ajax calls to check for moderated subreddits ^(thanks @JordanMilne, @andytuba)

- Update jQuery things ^(thanks @mc10 )

- Refactored *showImages.js* - All hosts now have their own file, allowing for easier fixing and creation of expando supporting hosts. ^(thanks @andytuba @erikdesjardins and more)

- Greatly refactored *KeyboardNav* ^(thanks @andytuba)

- Refactored gulp a bit ^(thanks @andytuba)

- Update readme ^(thanks @allthefoxes and @mc10 )

- Linting and janitoring

- A [few](http://i.imgur.com/s4XgqRN.png) [typo](http://i.imgur.com/1oTVuEX.png) [commits](http://i.imgur.com/DC6svMP.png) [as](http://i.imgur.com/H5TJPnD.png) [always](http://i.imgur.com/yGrByoR.png)

**Comment by allthefoxes** [comment]
Did you add all the changes you made to this today?

**Comment by andytuba** [comment]
I think I did?

**Comment by danieljl** [comment]
When will this version be released?

**Comment by allthefoxes** [comment]
When its all ready. Still a few more things to finish.

**Comment by SirCmpwn** [comment]
https://youtu.be/fjsTZzP8nkI?t=6s
