### ISSUE TITLE
'Night mode' broke some img in the Wiki.

### ISSUE THREAD

**Issue by rafaelsc** [honestbleeps/Reddit-Enhancement-Suite#1979]
Steps: 
1. Enter in http://www.reddit.com/r/ludobots/wiki/core01
2. See the Formula Image in "Project Details"
3. Enable 'Night mode'
4. Return to http://www.reddit.com/r/ludobots/wiki/core01
5. The Formula Image is missing.

**Comment by gavin19** [comment]
Is the 'use subreddit style' checkbox in the sidebar checked?

**Comment by erikdesjardins** [comment]
This is intended behavior: night mode will disable a subreddit's style (thereby getting rid of the images) if it doesn't indicate that it is night mode compatible.

To see them, simply re-enable subreddit style as described above.
