### ISSUE TITLE
better "handle" icon for options tables (moving rows up up and down)

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1981]
the squiggly icon I picked is goofy. ![](http://puu.sh/eyAvn/d80e60ce9d.png).  (i was looking for "up and down arrow")

ideally something more like a handle, or the  original dots: ![](http://i.stack.imgur.com/JDjFg.png)

**Comment by erikdesjardins** [comment]
Fixed in #2001
