### ISSUE TITLE
Gfycat videos do not expand comment space

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#1986]
https://www.reddit.com/r/nfl/comments/2fi8nt/game_thread_green_bay_packers_00_at_seattle/ck9i0md is a good example: try expanding a video and scrolling.

**Comment by erikdesjardins** [comment]
Not RES, they limit the height of `.md`:
![image](https://cloud.githubusercontent.com/assets/7673145/5793854/41166212-9f22-11e4-8335-a2738fbc2215.png)
Works fine if you disable subreddit styles.

**Comment by honestbleeps** [comment]
seems we should close this then, thanks!
