### ISSUE TITLE
Navigate galleries with arrow keys

### ISSUE THREAD

**Issue by andrewrice** [honestbleeps/Reddit-Enhancement-Suite#1991]
![image](https://cloud.githubusercontent.com/assets/3012015/5849070/1f2d5ece-a1ae-11e4-887a-8941813f0344.png)

I should be able to flip through this gallery with the arrow keys, unless that option already exists and I'm just missing it.

**Comment by OneKorg** [comment]
right now the way to navigate through a gallery is using the " [ " character for left and " ] " for right, though it might be nice to also be able to move using arrow keys

**Comment by gamefreak** [comment]
Can't you bind `previousGalleryImage` and `nextGalleryImage` to those keys in in the keyboard navigation module?

**Comment by honestbleeps** [comment]
yes, this functionality already exists, just not with the keybindings OP prefers -- which can be adjusted in the RES settings console. Closing this issue.
