### ISSUE TITLE
Never Ending Reddit breaks reddits new unread count by messages

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#1993]
The old icon is shown when NER is active and in use

**Comment by andytuba** [comment]
Just to clarify, is NER using an old copy of the icon? Does it affect the user menu bar and/or the floating envelope?

**Comment by allthefoxes** [comment]
Have an unread message, then go to page 2 with NER, scroll back up and the unread icon will show as RES's version

**Comment by andytuba** [comment]
okay, thanks for clarification.  crufty ol' ner..

**Comment by andytuba** [comment]
not yet fixed, but orangered will be the place for it
