### ISSUE TITLE
Login panel not night-mode compatible

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1994]
![](https://i.imgur.com/WQ9NEaD.png)

https://www.reddit.com/r/RESissues/comments/2ti6gr/bug_redditcomlogin_is_not_night_mode_compatible/

**Comment by andytuba** [comment]
@gavin19 can you do that fancy thang you do?

also lemme know if you're ever getting tired of nightmode stuff, or want me to ping you for other more interesting stuff.

**Comment by githue** [comment]
Can't repro in same version of RES and Chrome 40:

![reddit-login-nm](https://cloud.githubusercontent.com/assets/7245595/6077821/7900ae32-ae3e-11e4-9591-2825a86bce22.png)

**Comment by andytuba** [comment]
i meant specifically the white background on the password fields
