### ISSUE TITLE
code blocks/runs not night-mode compatible with new markdown style

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#1996]
https://www.reddit.com/r/RESissues/comments/2tvbx3/announcement_postcomment_styling_changes_from/co2v9bi?context=3
![](https://i.imgur.com/d2BRwjF.png)

the reddit css in question:

    .md code, .md pre {
        border: 1px solid #eeeed2;
        background-color: #fcfcf7;
    }

**Comment by Fyren** [comment]
This doesn't appear to fix inline code blocks (at least, in Firefox, but I don't think that's relevant).  The dev tools tell me the CSS rule that's getting applied is for .link .md :not(pre) > code, not the one mentioned in the first comment.

**Comment by andytuba** [comment]
sure looks like it.

**Comment by allthefoxes** [comment]
Fixed in #2041
