### ISSUE TITLE
Imgur gifv links display "Image you are requesting does not exist or is no longer available"

### ISSUE THREAD

**Issue by jspenguin** [honestbleeps/Reddit-Enhancement-Suite#1998]
Whenever I attempt to expand a gifv link inline, I get an error saying "The image you are requesting does not exist or is no longer available". If I visit the link directly, the gifv plays normally

Example: https://www.reddit.com/r/gifs/comments/2u55c3/fuck_the_system/ links to http://i.imgur.com/hXkpWiu.gifv

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0
RES version: RES 4.5.4, commit 1699c7c65c0a80bb5a3f2e2e6ace566b5246f95c

Edit: Apparently: some gifv links do work: https://www.reddit.com/r/gifs/comments/2u457o/700_mph_car_crash_basically_vaporizes_the_car/ links to http://i.imgur.com/SBVmX7B.gifv. I also noticed that the links that don't work, when I view them directly, are using Flash instead of HTML5 video.

**Comment by honestbleeps** [comment]
you likely have a conflicting extension causing this problem by rewriting the URL somehow - what other extensions do you run?  your example of a broken gifv works fine for me.

**Comment by jspenguin** [comment]
On further investigation, opening the Network inspector, it appears that RES is rewriting the gifv extension to webm: https://i.imgur.com/hXkpWiu.webm; Imgur serves an mp4 encoded with H.264 instead of a webm; RES then tries to fall back to https://i.imgur.com/hXkpWiu.gif, which redirects to http://i.imgur.com/removed.png.

Is there any way to redirect these through Gfycat, which always uses webm (like the gif -> gfycat option)?

**Comment by honestbleeps** [comment]
assuming you're correct, it seems like instead we should alert imgur to the issue on their end, rather than start forcing gfycat to transcode stuff just because they don't have the bug.

so I take it Firefox in Linux lacks H264 support?

**Comment by jspenguin** [comment]
That's what I'm investigating now. I heard it could use gstreamer, which I have installed.

**Comment by jspenguin** [comment]
I finally figured out what went wrong. Essentially, Firefox uses gstreamer to support H264 on Linux. I verified that gstreamer was installed, and that it could play H264 files. According to https://bugzilla.mozilla.org/show_bug.cgi?id=806917, Firefox is supposed to use GStreamer 1.0 starting with version 30, but poking around in a debugger shows that it was still using version 0.10, which is deprecated and had ffmpeg support removed in Ubuntu 14.04. I managed to find a package to add support back, and it works now.

I still think the issue should be raised with Imgur, so they can support both h264 and webm, depending on what the browser supports.

**Comment by honestbleeps** [comment]
seems worth at least raising with them, but I'll close this since it's not RES.

challenge for imgur would be detecting what you support - not sure how simple that is, and it's kind of specific to linux users I would think, as I'm pretty sure FF supports h264 automatically on OSX / Windows due to OS level support (going from memory here, I could be wrong)...

in any case, glad you got things sorted out and thanks for doing some legwork on the details, appreciate it!
