### ISSUE TITLE
Medicru.sh no longer online - Submit Page uploader needs something to use

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2008]

**Comment by andytuba** [comment]
@SirCmpwn reports that imgrush is happy to take uploads from RES

**Comment by imgrush** [comment]
We have been working around the clock to get this fully set up. We are currently using OVH for the host.  You can update any uploaders to use imgrush.com

**Comment by allthefoxes** [comment]
Glad to hear, @imgrush - If you would like to play around with RES yourself and submit a pull request to enable this feature (and replace mediacrush), that would be great!

If not, I am sure @andytuba would be glad to work with you guys to get everything going

**Comment by andytuba** [comment]
I've got the code mostly done and stashed somewhere.  Basically:

1. copy lib/modules/hosts/mediacrush.js to lib/modules/hosts/imgrush.js
1. add imgrush.js to manifests  (`gulp add-module --file hosts/imgrush.js`)
1. remove the `modules['upload'].hosts['mediacrush']` object from mediacrush.js
1. update mediacrush -> imgrush in imgrush.js

**Comment by allthefoxes** [comment]
@andytuba I can probably do this myself later tonight.

**Comment by imgrush** [comment]
@andytuba @allthefoxes 
going through the code, I can see that we need a vendor file too correct? Just like [MediaCrush.js](https://raw.githubusercontent.com/honestbleeps/Reddit-Enhancement-Suite/master/lib/vendor/mediacrush.js)

**Comment by imgrush** [comment]
@andytuba @allthefoxes Can you take a look at the pull request i made for this:
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2030

Thanks

**Comment by andytuba** [comment]
i was thinking of changing vendor/mediacrush.js so that you can give it a domain, instead of copying the whole shebang.. seems safe so long as all the mediacrush clones that RES interacts with maintain the same API.

**Comment by andytuba** [comment]
thanks for PR!

**Comment by imgrush** [comment]
@andytuba @allthefoxes did you get a chance to look over the PR https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2030

**Comment by allthefoxes** [comment]
@imgrush Sorry about that, I'll play with it this afternoon!
