### ISSUE TITLE
blog.twitch.tv needs to be excluded from expando

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2013]
http://allthefoxes.me/img/I-02-04-153644.png

There is no stream, its an article

http://www.reddit.com/r/DotA2/comments/2us9i0/visual_mapping_of_twitch_viewership_across_games/

**Comment by erikdesjardins** [comment]
Uh, that's reddit's expando right? We don't have Twitch expandos (at least, [I hope we don't](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/1737)).
