### ISSUE TITLE
Some elements in wiki pages aren't styled by nightmode

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2018]
[Reddit post,](https://www.reddit.com/r/RESissues/comments/2uvs64/bug_text_in_bullet_point_and_tables_is/) [test case.](https://www.reddit.com/r/powersofmiddleearth/wiki/northernevendim)

Occurs with stuff like bullet points, tables, and probably more.

It seems that reddit's `.md` style is overriding our `.res-nightmode .content` style.

**Comment by andytuba** [comment]
Still/again? I thought we already ironed those out for next release.

**Comment by erikdesjardins** [comment]
Yep, apparently I didn't test this with a dev build...

**Comment by andytuba** [comment]
well, we do still have to resolve #1996
