### ISSUE TITLE
subredditHover does not work on full links

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2021]
the hover info for subreddits works on things like /r/subreddit, but not http://www.reddit.com/r/subreddit

Lets play, BUG. OR. FEATURE?

**Comment by andytuba** [comment]
let's call it a bug

**Comment by allthefoxes** [comment]
You can try reproducing here: http://www.reddit.com/r/Fox/comments/2vh2gy/bug_test/cohk8j4
