### ISSUE TITLE
siteModules.gfycat needs to hide reddit's expando / give the option to prefer it

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2032]
[This reddit post.](https://www.reddit.com/r/RESissues/comments/2vip7y/bug_gfycat_expander_shows_two_links_one_doesnt/)

Should be pretty straightforward, we already do this in other modules.

**Comment by andytuba** [comment]
I'm not seeing reddit/embedly-provided expandos for gfycat. Can anyone repro?

**Comment by erikdesjardins** [comment]
[Sorry for the volume bar](http://i.imgur.com/SeaMZTy.png)
(I actually had to install Firefox on my phone for this - Chrome insists on redirecting to https even when I'm logged out)

**Comment by allthefoxes** [comment]
I cant confirm on this post specifically but I see it happen. Will SS next time i see it

**Comment by erikdesjardins** [comment]
https://www.reddit.com/r/RESissues/comments/2x7m5x/bug_why_cant_i_close_this_gif/
