### ISSUE TITLE
showUnreadCountInFavicon is using 'beforeunload', destroying Firefox's bfcache optimization

### ISSUE THREAD

**Issue by Nephyrin** [honestbleeps/Reddit-Enhancement-Suite#2034]
Try this in Firefox:
- Enable showUnreadCountInFavicon in RES (the default)
- Load reddit homepage, wait for complete load
- Click any comments link (that is, navigate to another reddit page) and let it load.
- Press back and forward a few times.
- Disable showUnreadCountInFavicon pref in RES, hard reload reddit.com, try again.

With the pref on, the page reloads each time you back/forward. With it off, the load is nearly instant. The problem is that Firefox has a cache that keeps the previous page alive, allowing the 'back' button to essentially be a tab-switch. The effect is very pronounced: back-forward with the pref disabled or RES uninstalled is essentially a single frame, whereas with it enabled the page reloads somewhat laboriously (RES + Firefox is not super performant to begin with).

The culprit is the `beforeunload` handler. If any handlers for `beforeunload` exist, this caching mechanism doesn't work, as the page 'knows' it has been unloaded, and can't be switched back to as if nothing has happened. See: https://developer.mozilla.org/en-US/docs/Using_Firefox_1.5_caching

Given how common it is to navigate away from reddit and then press back, and the very noticable difference in load time without this option, it seems prudent to find another way to implement this option.

**Comment by honestbleeps** [comment]
so the reason that's done was the many incessant complaints about bookmarks getting the unread count in the favicon.

>  it seems prudent to find another way to implement this option.

I may be wrong, but I'm *pretty sure* there just isn't another way.

That said, we may just have to decide here: cache, or be concerned about favicon having unread count in bookmarks?

I feel like cache probably wins.

**Comment by andytuba** [comment]
I threw an option into the new orangered module to turn off the favicon behavior.

**Comment by larsjohnsen** [comment]
Reddit also adds a `beforeunload` listener now, so there's unfortunately nothing RES can do to preserve the optimization.
