### ISSUE TITLE
Comment Live Preview stripes should anchor to the top instead of moving

### ISSUE THREAD

**Issue by markbao** [honestbleeps/Reddit-Enhancement-Suite#2036]
The Comment Live Preview box has a striped background that seems to be anchored to the bottom of the box. What this means is that when you type more info in the comment text box, the entire box redraws itself, which is distracting while writing a comment. If there's a way to anchor the striped background to the top of the box, that would be more visually appealing.

![screenshot](https://cloud.githubusercontent.com/assets/27594/6199015/d7351d82-b3f5-11e4-8637-03c4791758a7.png)

**Comment by andytuba** [comment]
Here's the relevant CSS:

    .livePreview, .livePreview .md { 
        background: repeating-linear-gradient(-45deg, transparent, 
           transparent 40px, 
           rgba(166,166,166,.07) 40px, 
           rgba(166,166,166,.07) 80px); 
       }

It's not anchored per se, the browser just redraws the stripes every time the box's dimensions change (i.e. new line).

I'm open to some other styling to indicate "this is a read-only preview", like just candystriping around the border or semi-transparency or something less distracting..

**Comment by markbao** [comment]
@andytuba thanks for triaging this! Looks like the main reason it looks like it's "shifting" is due to the `-45deg` rotation. Can you try `-225deg` and see if that seems to "anchor" it to the top?

**Comment by andytuba** [comment]
-225deg still shifts around, but it doesn't seem as obvious.

Applying it to both `.livePreview` and `.livePreview md` is making for odd jaggies, though.
