### ISSUE TITLE
Dummy uppers and downers

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2049]
So many people ask "how do i turn on the uppers and downers i see in screen shots? I looked through settings and didn't see anything." 

How about a functionless module that has all the right words and screenshots to educate people that this functionality is no more?

 We could even throw in some options to add placebo values for the diehards. Or not, because that's dumb.

**Comment by allthefoxes** [comment]
Why? Why not just macro an expanation?

**Comment by andytuba** [comment]
because it keeps getting asked so goddamn often and it's hard to write a good AutoMod rule.

**Comment by andytuba** [comment]
this should probably be part of the Vote Enhancements description: 

* quick blurb
* embed https://mediacru.sh/f5GA0z8v7ZT9 and either move that to imgur or add it to the extension assets
* link to https://www.reddit.com/r/Enhancement/wiki/faq/uppers_downers_removed

**Comment by honestbleeps** [comment]
Go home, tuba. You're drunk!

**Comment by andytuba** [comment]
it's true, i got a 21st amendment at the station for the train ride home when i was githubbing.

**Comment by mc10** [comment]
It's probably been enough time for people to get used to this change, so I'm going to close this issue.
