### ISSUE TITLE
Search Time and Sort selections should be changed to match up with reddits new way of displaying dropdowns

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2051]
Basically, reddit no longer shows the option already selected when opening a dropdown

For example, if you sort by new, then click the Sort By... drop down, *new* won't be listed, since it is already selected

With RES installed and when searching, a box comes up where you can choose how to sort (hot, new, top, etc...) and the time selection (today, this week, etc...)

This functionality should be changed to line up with reddits, where the current option is not in the dropdown.

**Comment by andytuba** [comment]
Are you talking about the selects in the sidebar search box?  those are a different kind of control, a <select>, instead of reddit's dropdowns, which are a link menu.

**Comment by allthefoxes** [comment]
Yes, I understand that, but should we not try to match reddit functionality?

If "relevant" is already selected, there is no need to for it show in the dropdown

**Comment by andytuba** [comment]
they're two different controls, that are supposed to act in different ways.  they shouldn't match.

`<select>` behavior is determined by the browser designers. 

sanity check: are we talking about the same thing?  the sidebar search dropdown, and the /search page dropdowns?
![screen shot 2015-02-28 at 3 33 47 pm](https://cloud.githubusercontent.com/assets/455632/6428682/403dc256-bf5f-11e4-9c78-c817e2f6d2f1.png)
![screen shot 2015-02-28 at 3 33 57 pm](https://cloud.githubusercontent.com/assets/455632/6428683/405cf784-bf5f-11e4-8cae-9053d47fc6d2.png)

**Comment by allthefoxes** [comment]
Yes, we are talking about the same things.

But alright, I guess I'll close this.

Doesn't make much sense to me but what do I know :P
