### ISSUE TITLE
Night mode doesn't change the color of pre and code elements on Firefox Developer Edition

### ISSUE THREAD

**Issue by haySwim** [honestbleeps/Reddit-Enhancement-Suite#2054]

**Comment by allthefoxes** [comment]
I may be wrong here, but is this not a known and fixed issue already?

**Comment by gavin19** [comment]
I tested the dev edition and it works fine, though I noticed that I'd neglected `pre` blocks in the sidebar.

**Comment by allthefoxes** [comment]
Ah.

**Comment by larsjohnsen** [comment]
Appears to be fixed.
