### ISSUE TITLE
UserHover not calculating age correctly

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2058]
Have't confirmed yet, just copying from reddit - http://www.reddit.com/r/RESissues/comments/2xl0jw/bug_incorrect_calculation_of_account_age/

**Comment by allthefoxes** [comment]
Can confirm

Test here: http://www.reddit.com/user/meow--

**Comment by yangzihe** [comment]
I think I solved the bug. Just one question: is RESUtils.niceDateDiff supposed to include the current date in the calculation as well?
