### ISSUE TITLE
Use unicode triangle wedge up/down for comment navigator up/down buttons

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2083]
http://i.imgur.com/87CBWf9.png 

and make 'em real buttons.  with disabled states, and cursor:pointer/default and opacity:100/30.

**Comment by andytuba** [comment]
is that the only place RES uses those wedge images?

**Comment by honestbleeps** [comment]
pretty sure it is, yes.
