### ISSUE TITLE
quickMessage: open on links to reddit.com/message/compose

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2088]
\<foxes> [09:03:24] hey andytuba erikdesjardins - Do you think quickMessage could ever be expanded to handle reddit message links in-page?

\<foxes> [09:03:41] i.e. https://www.reddit.com/message/compose/?to=dotamatchbot&subject=approve&message= opening in quick message, on the page, with the feilds filled out

**Comment by allthefoxes** [comment]
#2087 lol
