### ISSUE TITLE
Refactor upload

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2089]
Related #2008 

Made a new issue since really upload needs some copy editing and fixups.

@imgrush is a host we can use, see #2008 and #2030

**Comment by andytuba** [comment]
refactor what? upload module should already be pretty well factored. what might need refactoring is nediacrush / imgrush.

**Comment by imgrush** [comment]
@allthefoxes  @andytuba any update here? initially, It seemed like changing the domain would be enough to make this work, we probably have to take another look at this. Let me how to proceed. Thanks

**Comment by allthefoxes** [comment]
@andytuba Whatever its built on, there is some cruft that is keeping it on using mediacrush. Refactor may have been the wrong word, but it needs some cleaning up to play nice with any host.

**Comment by andytuba** [comment]
@allthefoxes the issue should be limited to hosts/imgrush.js and vendor/Mediacrush. modules/upload is pretty limited.  I'm gonna close this in favor of just @imgrush's PR.
