### ISSUE TITLE
link to subreddit when listed as "xpost" in title

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2096]
https://www.reddit.com/r/Enhancement/comments/2ynzh1/feature_request_would_it_be_possible_to_have_res/ and a dozen other requests

potential implementations: 

* post info/actions hover pop-up when hovering the title, shown below the title
* wrap subreddit name in a span, onclick open subreddit (yuck, re implementing links in JavaScript) 
* split post title link into multiple links, but this sounds dangerous

**Comment by erikdesjardins** [comment]
Related: #1229

**Comment by andytuba** [comment]
> * wrap subreddit name in a span, onclick open subreddit (yuck, re implementing links in JavaScript)
> * split post title link into multiple links, but this sounds dangerous

compromise idea: 

1. wrap subreddit name in a span
1. onclick span change title link to that url
1. onclick link revert title link to original url

**Comment by erikdesjardins** [comment]
There's also #2425. It's a different approach, but I like it, I think it would be less surprising.

**Comment by andytuba** [comment]
Oh right! Yeah, I think I like that best.

**Comment by erikdesjardins** [comment]
#2425
