### ISSUE TITLE
Option for post title max-height

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2113]
specified in `em`?  maybe `4em` by default?  and `overflow: hidden; text-overflow: ellipsis`

https://www.reddit.com/r/Enhancement/comments/2z4d87/how_to_remove_all_titles_longer_than_one_line/

**Comment by jkcchan** [comment]
I am currently looking at a solution for this.
 - set all .title to have styles:
    `overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;`

**Comment by erikdesjardins** [comment]
#2646
