### ISSUE TITLE
Package images with RES

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2115]
I believe this is all of them:

- [Bacon](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/38ce5c3301ccace657c01e1e23d5e167039d8df2/lib/core/res.css#L1009) - [img](https://s3.amazonaws.com/f.thumbs.redditmedia.com/OvX59a7-5YkWrwLw.png), transparent background [version](https://i.imgur.com/tj2stKH.png)
- [Spritesheet](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/38ce5c3301ccace657c01e1e23d5e167039d8df2/lib/core/res.css#L1207) - [img](https://s3.amazonaws.com/b.thumbs.redditmedia.com/tBwwK20XXxtpgudWx1L7bDXla-iotv-JA0jgA0Y-FVs.png), [updated](https://i.imgur.com/oYDs89u.png) (depends on #2110)
- [Nightmode arrows](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/38ce5c3301ccace657c01e1e23d5e167039d8df2/lib/modules/nightmode.css#L335) (simplified in #2110) - [img](https://b.thumbs.redditmedia.com/WZDoQsDzUySVTErcweuA3k2HH1HU5-BZNnBXOR4FDwc.png)
- [Nightmode expandos](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/38ce5c3301ccace657c01e1e23d5e167039d8df2/lib/modules/nightmode.css#L522) - [img](https://s3.amazonaws.com/a.thumbs.redditmedia.com/PkckcN8_3ijRUVP-GUQ6E-c8Ash_jQ3kCrEAoqKjSC4.png)
- [Nightmode multi add subreddit buttons](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/38ce5c3301ccace657c01e1e23d5e167039d8df2/lib/modules/nightmode.css#L988) - [img](https://b.thumbs.redditmedia.com/TItqbtZ6QLVach67LqyHqj-cCnYMempXSwW17SDlTKM.png)
- [Nightmode snoo balloons](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/38ce5c3301ccace657c01e1e23d5e167039d8df2/lib/modules/nightmode.css#L1000) - [img](https://b.thumbs.redditmedia.com/oPSTBWXkQufBAIYbFWiN0eI2J06zBLDEmq1NMHQ-Ems.png)
- [Nightmode about page header](https://a.thumbs.redditmedia.com/xxM_X1OL6Lt4I4GC9F1SbNIcbeoZPXOmPIo6P1slaP4.png) - [img](https://a.thumbs.redditmedia.com/xxM_X1OL6Lt4I4GC9F1SbNIcbeoZPXOmPIo6P1slaP4.png)
- [Colorblind mail icon](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/38ce5c3301ccace657c01e1e23d5e167039d8df2/lib/modules/orangered.js#L255) - [img](http://i.imgur.com/JK3IiSu.png)

[Chrome / OperaBlink:](https://developer.chrome.com/extensions/i18n#overview-predefined) Just add `"images/*.png",` to `web_accessible_resources` in [manifest.json](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/Chrome/manifest.json#L148), then hardcode `chrome-extension://__MSG_@@extension_id__/images/img.png`.

[Firefox:](https://stackoverflow.com/questions/18055770/referencing-image-resources-in-addon-data-folder) ~~Assuming that [our id](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/XPI/package.json#L7) doesn't change (it doesn't seem to), we can probably hardcode `resource://jid1-xufzosoflzsoxg-at-jetpack/reddit_res/data/images/img.png`. Otherwise we'll have to figure out the URL at runtime.~~ Can use a relative path like Safari.

[Safari:](https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/AccessingResourcesWithinYourExtensionFolder/AccessingResourcesWithinYourExtensionFolder.html) Just hardcode `../images/img.png`.

[Opera 12](https://github.com/operasoftware/operaextensions.js/blob/master/docs/api/extensions-api-resourceloader.html#L24 "Ugh, why do we still support this -.-"): As far as I can tell, must be done at runtime.

**Comment by thybag** [comment]
An alternate option would potentially be to inline them as datauris (There are a couple of nice grunt/gulp libs that would help do this automatically as part of the builds). 

Would potentially save having to have separate implementations for each browser :)

**Comment by erikdesjardins** [comment]
Hmmm, data URis are the exact thing we're trying to avoid with this, but if it's part of the build process then we won't have to deal with them.

(Thoughts, @andytuba, @gamefreak? FYI I have already gotten this to work [except for Opera 12] without data URIs, but it would be straightforward to feed it through a gulp plugin instead)

**Comment by andytuba** [comment]
I think Opera12 will have to take the hit for this one.

**Comment by erikdesjardins** [comment]
There is one thing, though: I have a feeling AMO won't like hardcoding the image URLs (even if they're static), since I don't *think* you're supposed to. In that case, we'll have to use either data URIs or a function like RESGetResourceURL() at runtime.

**Comment by andytuba** [comment]
Hmm, we could ask in #addons - irc://irc.mozilla.org/addons

**Comment by erikdesjardins** [comment]
Never mind, Firefox allows relative paths - not sure why I didn't see that in any documentation (maybe it's too obvious).

**Comment by mc10** [comment]
This should be closed by #2916 right?

**Comment by erikdesjardins** [comment]
Yep
