### ISSUE TITLE
Force image links (even .jpg's!) to gfycat when it belongs to a subreddit with gif in it

### ISSUE THREAD

**Issue by vohof** [honestbleeps/Reddit-Enhancement-Suite#2121]
An example:
```
http://www.reddit.com/r/CatGifs/comments/2zfv0h/misplaced_revenge/
```

OP linked to a gif hiding in the wrong extension, so RES doesn't automatically convert them to gfycat. To help ease the burden, I think RES should make it be converted to gfycat even if it ends in jpg/png/jpeg when the link is submitted to a subreddit with `gif` in it.

**Comment by allthefoxes** [comment]
Following that link, it still plays as a gif. Did it not work for you?

**Comment by vohof** [comment]
Yes it plays, but it gets loaded very slow :frowning:

**Comment by allthefoxes** [comment]
The extension should make no difference in loading speed

**Comment by andytuba** [comment]
The problem is that RES should be loading this as a gifv,  not a gif. The solution is upgrading res's imgur integration, not redirecting to gfycat. It shouldn't ever be necessary anymore to fail over to gfycat for imgur links.

**Comment by andytuba** [comment]
also i think this issue is logged somewhere else. if not, let's reopen this issue.

**Comment by vohof** [comment]
@andytuba thanks!
