### ISSUE TITLE
New settings changed indicator perhaps a bit too small?

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2129]
I don't wanna be "that guy", but I am color blind and I cannot distinguish at all between the grey and the greenish whatever color in the little circle.

Can you?

http://allthefoxes.me/img/03-SJvp3iPL.png

http://allthefoxes.me/img/03-DlfhL3wN.png

**Comment by andytuba** [comment]
yeah, let's make that circle twice the size and a darker green.

**Comment by andytuba** [comment]
maybe swap it for a batch icon of a floppy disk which is gray/30% opaque --> white/opaque

**Comment by andytuba** [comment]
@allthefoxes how's that look to you?  plz to re-open if it deserves a different tweak.

**Comment by andytuba** [comment]
save now: ![screen shot 2015-04-26 at 11 43 33 am](https://cloud.githubusercontent.com/assets/455632/7338707/7c443cc2-ec09-11e4-9483-b4a8d99fe2d7.png)

nothing to save: ![screen shot 2015-04-26 at 11 43 36 am](https://cloud.githubusercontent.com/assets/455632/7338708/7c4fb0d4-ec09-11e4-9807-6ac0621cecbb.png)
