### ISSUE TITLE
Add support for translations

### ISSUE THREAD

**Issue by JordanMilne** [honestbleeps/Reddit-Enhancement-Suite#2135]
[Some Japanese folk are working on a translation for RES' UI](https://www.reddit.com/r/newsokur/comments/304tw7/%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%A7%E3%81%8A%EF%BD%8B_for_res%E3%82%92%E5%85%AC%E9%96%8B%E3%81%97%E3%81%BE%E3%81%99/), but it's a greasemonkey script using string search/replaces to patch up the interface at runtime. It'd be nice to integrate gettext or something similar so the user's locale could be detected, and the proper language used if available.

**Comment by allthefoxes** [comment]
This makes my little 12 gig partition for archiving RES builds very very sad.

But sacrifices must be made. **For the greater good**

---

Seriously though this is a neat idea and something I would like to see.

**Comment by andytuba** [comment]
related: #1021

**Comment by JordanMilne** [comment]
Derp, I searched for "i18n" and "translation", but not "localization"

**Comment by andytuba** [comment]
took me three tries to track it down, too :P

**Comment by andytuba** [comment]
@allthefoxes, it'll be alllll good, just a few extra kb for the l10n library and language packs.

**Comment by wojtekmaj** [comment]
Bumping it as it deserves some attention for sure :)
Maybe we could set up crowdsourcing translation service somewhere? I'd love to help.

**Comment by BenMcGarry** [comment]
i18n Implementation has started! See the below Project for tracking.

https://github.com/honestbleeps/Reddit-Enhancement-Suite/projects/1
