### ISSUE TITLE
options to hide each comment navigator type 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2147]
http://www.reddit.com/r/enhancement/comments/30pvbw/image_preview_visited_links_vote_enhanecment_and_comment_macro/cpunmv2

eg for iama, op, etc

**Comment by Dashed** [comment]
I think it'll be better to not show context navs if there aren't any to navigate.

**Comment by andytuba** [comment]
That'd be smart, eh..
