### ISSUE TITLE
Subreddit Tagger is shown in both Filters and Posts menu in settings console

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2163]
http://i.imgur.com/zIBNKee.png

**Comment by erikdesjardins** [comment]
[That's intended](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/618ea0e9ac5f090d6611fc1e6b4e9d10bfc45948/lib/modules/subredditTagger.js#L4) (unless you mean that it expanded both sections somehow)

**Comment by andytuba** [comment]
Yeah, I deliberately put some modules in multiple categories for discoverability.  It's a quirk of implementation that both sections expand. I kinda wanna leave it that way but it's probably more polished (and hopefully not too much more work) to only open the first category or leave the current category open if it's in the module's category list.

**Comment by allthefoxes** [comment]
Honestly it seems like bad design to me :( (Having one thing in two places)

But I understand the reasoning
