### ISSUE TITLE
Comment Navigator should warn user if no comments found and sortby=new

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2166]
Several times people have posted  "why can't I see comments from OP on this AmA" and inevitably it's because they had "sort by: new".  Comment Navigator should alert the user if it finds relatively few comments and the user has set "sort by" to "new".

https://www.reddit.com/r/Enhancement/comments/31o3pg/question_iama/

**Comment by larsjohnsen** [comment]
Number of matches are now surfaced.
