### ISSUE TITLE
Comma is not used in .userkarma when comment karma >= 1000

### ISSUE THREAD

**Issue by The6P4C** [honestbleeps/Reddit-Enhancement-Suite#2188]
A comment karma of greater than or equal to 1000 does not have commas in its display in the `.userkarma` element.

![(3,416 · 5777](https://cloud.githubusercontent.com/assets/7885480/7174566/7d144930-e44d-11e4-8bf5-a045f12c355e.PNG)

I should be trying to get on this now. If not, I'll update this if I abandon fixing it myself.

**Comment by The6P4C** [comment]
Probably because there's an option for it. Why though?

Closing this, if I can work out how.

**Comment by allthefoxes** [comment]
The comma in link karma was added by reddit. Already a PR open.

**Comment by andytuba** [comment]
#2168 specifically
