### ISSUE TITLE
New Settings Console - Username Hider makes "save options" disappear

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2196]
Here is a fancy webm: https://www.allthefoxes.me/res/bug.webm

**Comment by erikdesjardins** [comment]
It's not just Username Hider but any module that's disabled when you open it.

i.e. I can reproduce with Account Switcher or any module I turn off and then navigate to.

**Comment by allthefoxes** [comment]
Closing for #2197

**Comment by andytuba** [comment]
whoops, sorry i missed this
