### ISSUE TITLE
Gallery does not convert gif to gifv

### ISSUE THREAD

**Issue by fbm-static** [honestbleeps/Reddit-Enhancement-Suite#2199]
When an imgur gallery is linked, the contents are displayed as images. However, when one of them/all of them is/are gif(s) they don't get converted to gifv.

Thanks.

**Comment by andytuba** [comment]
duplicate of #1833. working on it this week too!

**Comment by fbm-static** [comment]
Aw, sorry I didn't notice man. Cheers!
