### ISSUE TITLE
Option for autohide filtered posts

### ISSUE THREAD

**Issue by Bfgeshka** [honestbleeps/Reddit-Enhancement-Suite#2201]
Now they're just not showing, but it would be better if posts will be marked as hidden.

**Comment by allthefoxes** [comment]
This would create so many api calls that it would hurt

**Comment by andytuba** [comment]
related discussion: https://www.reddit.com/r/Enhancement/comments/33x21m/why_doesnt_the_subreddit_filter_option_uses_the/

**Comment by Bfgeshka** [comment]
How about workaround? 

For example, now we have notification when filtered posts reach some percentage, is it possible to add "hide filtered" button in this notification popup?

**Comment by andytuba** [comment]
solves the "require human confirmation" problem but not the api ratelimiting one.. maybe we can hand it off to the background process.

**Comment by andytuba** [comment]
Update on this: reddit's "hide post" API now accepts multiple IDs, so RES can batch-hide filtered posts.
