### ISSUE TITLE
upload.js breaks /r/enhancement submit wizard / breaks everything

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2204]
http://i.imgur.com/QmGtKtY.png

Problem lies on upload.js:66

Also happens on /r/resissues

**Comment by allthefoxes** [comment]
@andytuba already fixed it

**Comment by andytuba** [comment]
39ad448a410d30ced484751a4ff0c216656d5ced
