### ISSUE TITLE
Konami code broken thanks to keyboardNav

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2210]
## This is an issue on master, not on release

I think @andytuba fixed up some cruft with the konami easter egg, however, pressing enter to finish the code entry will load the selected post (or reload the page if already in a post)

This results in the animation appearing for just a moment before going away

**Comment by andytuba** [comment]
fixed bbc82b0e5ee65e17b222c51caa4cf493d901e6c1
