### ISSUE TITLE
Add key bindings for searching contents

### ISSUE THREAD

**Issue by 3v1n0** [honestbleeps/Reddit-Enhancement-Suite#2211]
There should be a shortcut for quickly add focus to the search bar, so that it's possible to search content using keyboard.

Also, the RES Command console should include a command for searching in the whole reddit (or subreddit), and not only to search in RES settings.

**Comment by allthefoxes** [comment]
In the future, consider leaving feature requests on /r/enhancement. Thanks

**Comment by 3v1n0** [comment]
Oh, sorry... I didn't want to "spam" there as well, since the issues were actually tracked here, but I'll do this in future.

Thanks.

**Comment by honestbleeps** [comment]
this is a good idea for the keyboardNav module, @3v1n0 - I like it.

The main reason we direct them to /r/Enhancement is that a lot of the requests we get (most, frankly) are bad ones, and we'd rather not have them cluttering out github issues.

This one is a good idea :-)

**Comment by honestbleeps** [comment]
by the way, do you have a suggested binding?  I think / is a common one, but because of that I believe that Firefox may already have it bound to "find in page"

**Comment by 3v1n0** [comment]
> by the way, do you have a suggested binding?

Mhm... Yeah,`/` is already used by firefox... I'd have used we might use `Shift+f`, but it's already taken... So maybe `Alt+f`? :)

Probably it's possible to override firefox default, BTW. Not sure it's nice.

**Comment by allthefoxes** [comment]
`Alt-F` opens menu in chrome by the way

**Comment by 3v1n0** [comment]
Right... So it does in Firefox... Well, just `F` or 'Shift+F` are active only when in Go mode, so maybe they can still be used.

**Comment by andytuba** [comment]
goMode is optional, by the way.

**Comment by rhwang201** [comment]
Couldn't find an active thread on this on r/Enhancement, so bumping here. I vote for "/", like duckduckgo.

**Comment by Propheis** [comment]
Is there still interest for this feature? I could pick it up if people still want it.

**Comment by 3v1n0** [comment]
I would love to
