### ISSUE TITLE
Unread count should be syncronized between tabs

### ISSUE THREAD

**Issue by 3v1n0** [honestbleeps/Reddit-Enhancement-Suite#2212]
One things I find pretty annoying is that if I read an unread element from a tab, then the unread count on the all other windows is not updated correctly.

Ideally this value should be live-updated everywhere.
I see the 4.6 changelog mentions something related to this new Orangered module, but not sure whether this fixes this issue.

**Comment by allthefoxes** [comment]
It does. Please make feature requests on /r/enhancement, not here.

**Comment by andytuba** [comment]
Yes, this is one of the biggest wins of the orangered module.
