### ISSUE TITLE
Back to top button needs to be batched

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2217]
Getting the good old box of death []

**Comment by andytuba** [comment]
Bleh, your system really doesn't support [upwards black arrow unicode character](http://www.fileformat.info/info/unicode/char/2b06/index.htm)?

**Comment by allthefoxes** [comment]
nope https://www.allthefoxes.me/img/56-SMbwXeBK.png

**Comment by andytuba** [comment]
rabble rabble rabble.

Hmm, different arrow, CSS arrow, or batch icon?  Batch F018 seems like the best bet, but I don't really like it.  It might be time to start building our own font.
![screen shot 2015-05-04 at 1 05 41 pm](https://cloud.githubusercontent.com/assets/455632/7461335/5bdc1382-f25e-11e4-8b94-6d63fe52e9b3.png)

**Comment by andytuba** [comment]
6925c9595efdb0761f7f2bb6c175d6e9b8b1cecb 
![screen shot 2015-05-09 at 10 14 38 am](https://cloud.githubusercontent.com/assets/455632/7551184/39645d3a-f634-11e4-8980-98b381c3f885.png)
