### ISSUE TITLE
Enabling reddit beta causes strange styling

### ISSUE THREAD

**Issue by NathanJang** [honestbleeps/Reddit-Enhancement-Suite#2220]
[reddit has recently allowed people to opt into the beta programme](https://www.reddit.com/r/announcements/comments/3576g2/bringing_back_the_redditcom_beta_program/), but the icon next to the userbar is positioned strangely. It's also meant to be a link to /r/beta.

![screen shot 2015-05-08 at t11 43 51 0800](https://cloud.githubusercontent.com/assets/7534708/7530266/c9d2bd34-f577-11e4-8465-7461a805fcba.png)

**Comment by honestbleeps** [comment]
https://www.reddit.com/r/Enhancement/comments/3579th/known_issue_reddits_new_beta_icon_clips_with_the/
