### ISSUE TITLE
Opera27 not showing image gallery nav button batch icons

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2225]
![screen shot 2015-05-09 at 5 51 16 pm](https://cloud.githubusercontent.com/assets/455632/7552623/1ad232b2-f674-11e4-8da6-7642b8ae1754.png)

![screen shot 2015-05-09 at 5 53 00 pm](https://cloud.githubusercontent.com/assets/455632/7552625/457ca1d2-f674-11e4-837b-22eea864b5c2.png)

**Comment by erikdesjardins** [comment]
Interesting, I can't reproduce on Opera 29 (on Windows):
![image](https://cloud.githubusercontent.com/assets/7673145/7671153/ee09cf62-fc8e-11e4-9901-67c6b38d459b.png)

**Comment by erikdesjardins** [comment]
We only support Opera 42+ now; can't repro
