### ISSUE TITLE
YouTube video time not showing?

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2234]
I think YouTube changed their API last week and broke this.  

https://www.reddit.com/r/RESissues/comments/3608v8/time_length_of_videos_no_longer_show_on_rvideos/

**Comment by allthefoxes** [comment]
Can definitely confirm this.

**Comment by Vakz** [comment]
Youtube has officially retired the v2 API, which RES uses. v3 requires each request to supply an API key, meaning this is possibly unfixable?

**Comment by allthefoxes** [comment]
Nothing is unfixable

**Comment by mc10** [comment]
It's definitely possible for one of us to create an API key (probably @honestbleeps), but we'd likely need to keep that key publicly in the repo, making it easily for someone else to just steal our key and send requests using it. It may be possible to include a config file that isn't checked out to the repo, and make sure that the build process checks for this config file, but that seems a tad annoying.

**Comment by thybag** [comment]
Assumedly people could just steal the key out of the compiled plugin anyway (at least in chrome) so it wouldn't really help much having it as a build time thing.

**Comment by andytuba** [comment]
@mc10 we have that same problem with our other API keys anyway so... shrug.jpg

**Comment by swiftSwathSee** [comment]
@mc10 In the mean time, can you just have the user provide their own API key? It's better than just omitting this highly useful feature.
