### ISSUE TITLE
"Hide search options" incompatible with reddits beta search

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2246]
The new search in reddit's beta doesn't play nice with hide search options.

https://imgur.com/KttMUoP

And then you click it:

https://imgur.com/dOcGB1l

edit: The issue is that, after hiding search options, there is no way to get them back (without modifying the URL)

**Comment by mc10** [comment]
It's not just an issue with the beta search bar; it also breaks for the [normal site's search bar](https://www.reddit.com/search) if you have no search results. (Too lazy to get screenshots, but it breaks the exact same way as above.)
