### ISSUE TITLE
API docs are unreadable in night-view mode

### ISSUE THREAD

**Issue by brianfryer** [honestbleeps/Reddit-Enhancement-Suite#2249]
When night-view mode is enabled in RES [1], www.reddit.com/dev/api becomes unreadable [2].

[1]:
> ![image](https://cloud.githubusercontent.com/assets/1923767/7781516/ab749608-00b4-11e5-8901-b493b31b362c.png)

[2]:
> ![image](https://cloud.githubusercontent.com/assets/1923767/7781523/c481e9b6-00b4-11e5-9488-e264e4ca21fd.png)

**Comment by andytuba** [comment]
Fixed for next release

![](https://i.imgur.com/RVQd9J2.png)

**Comment by githue** [comment]
I think this should be reopened because the heading is black and code elements have a white background.
