### ISSUE TITLE
moveOption() migrators don't work with removed options

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2252]
The issue appears to lie [here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/a9bbe83ece42ad6d3f1f3c4209405cb328e02434/lib/core/options.js#L280-L291), in `getOptions()` - it only saves the values of options that are in the code, so the values of any options in storage but not in the code will be unaccessible.

Although it's been this way for a long time (since at least [v4.5.0.2](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/v4.5.0.2/lib/utils.js#L113-L125)), so either something else is contributing to the issue or `moveOption()` migrators haven't worked for a few releases (which seems unlikely).

![image](https://cloud.githubusercontent.com/assets/7673145/7786358/79b4c69c-0195-11e5-9459-f0ab3102dead.png)

**Comment by andytuba** [comment]
Do you remember how you caused these errors to fire? 

I think I've reproduced this in the past by manually removing RESStorage entries for options versions. However, I did a token test with loading the code for each version from 4.5.1, 4.5.2, 4.5.3, 4.5.4, and HEAD and didn't see any errors.

**Comment by erikdesjardins** [comment]
I can get these errors consistently by copying my localstorage from the 4.5.4 release.

I can fix it with [these changes](https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/60e0aa327112e9a3fd07b660bf9c8147fefc9871#diff-6336f73a63012a931c28c14c4ede2b6c), but it doesn't seem optimal.
The old options that are loaded cause errors with the settings console (no `default`, etc.) during that pageload (not to mention they shouldn't be there). So maybe it should refresh the page after migration. Or maybe load the options into a different `modules` object for migration, so we don't mess with the actual one. I dunno what the best way is.

Feel free to checkout [that branch](https://github.com/honestbleeps/Reddit-Enhancement-Suite/compare/master...erikdesjardins:more-migration) and finish it (it contains other fixes) if you have any ideas.
