### ISSUE TITLE
Request: Option to show either user's link karma, comment karma, or combined karma next to every post

### ISSUE THREAD

**Issue by BrentNewland** [honestbleeps/Reddit-Enhancement-Suite#2258]
Some people have more than 1,000,000 karma. Some people have no karma, or negative karma. The amount of karma other people have is important to me - an account with a very high amount of karma might be some sort of corporate or government account, and an account with very low karma might be a troll account.

It would be nice if, next to every user's name on every post and comment, I could have it show that user's comment karma, link karma, or combined karma.

**Comment by honestbleeps** [comment]
Sorry, this isn't really technically viable due to the fact that it'd require an API call for each user on each page. Especially on comments pages, but even on posts pages, this just can't be done within the API limitations that reddit has (1 per 2-3 seconds) - a default page of 25 posts would mean 50-75 seconds of waiting for all the queries to finish, etc...

**Comment by allthefoxes** [comment]
@BrentNewland It is generally better if you put feature requests in https://reddit.com/r/enhancement - Just so you know! :smile:

**Comment by BrentNewland** [comment]
I opened a request at https://github.com/reddit/reddit/issues/1326

If the API is altered, this will become technically feasible, at which point the topic could be revisited.

**Comment by allthefoxes** [comment]
Thats..not..how it works. 

1. Reddit isn't going to drastically change API policy for RES

2. Its not that the API can't do it, its that the API can only take one call per 2 seconds.

3. There is no good reason to be judging accounts based on karma. Everyone on reddit has an equal voice

**Comment by BrentNewland** [comment]
You can limit conversation to a single thread.

1. This is not asking Reddit to "drastically change API policy for RES"

2. I'm not asking Reddit to allow tons of API calls. I'm asking for an addendum to the API to allow it to return more information.

3. That's your personal choice.
