### ISSUE TITLE
Show "/me/f/all" link in subreddit manager

### ISSUE THREAD

**Issue by dashed** [honestbleeps/Reddit-Enhancement-Suite#2261]
This would be useful for gold users.

Show "me/f/all" link in subreddit manager setting for https://www.reddit.com/#!settings/subredditManager

**Comment by andytuba** [comment]
Proposal for option: enum of f/all (default), r/all, or hidden. If somebody really wants both f/all and r/all, they can add their own shortcuts.

**Comment by Dashed** [comment]
> If somebody really wants both f/all and r/all, they can add their own shortcuts.

This doesn't work for `me/f/all`. This links to https://www.reddit.com/r/me/f/all

**Comment by erikdesjardins** [comment]
You can use `../me/f/all`

**Comment by Dashed** [comment]
@erikdesjardins Clever :+1: . Following this suggestion, I think I'm going to close this issue.

**Comment by andytuba** [comment]
Oh, I still liked the idea.. seemed like a better default than hacking in a not-subreddit shortcut

**Comment by Dashed** [comment]
> Proposal for option: enum of f/all (default), r/all, or hidden.

IMO, `me/f/all` and `r/all` are actually distinct if a gold member actually use "native" filters. I occasionally like to visit `r/all` when I want to get out of my own filter bubble.

**Comment by denizdogan** [comment]
In the pull request I just made, I've put "FILTERED" right next to "ALL" in the order, just like any other special button. Ideally, I'd like to merge them without a separator, as in:

* If user wants only ALL, just use "ALL"
* If user wants only FILTERED, just use "FILTERED"
* If user wants both, see them as "ALL (FILTERED)", where both ALL and (FILTERED) are separate links

**Comment by erikdesjardins** [comment]
/me/f/all 302s to /r/all now that everyone has /r/all filters
