### ISSUE TITLE
Duplicate expandos for gfycat links 

### ISSUE THREAD

**Issue by pastudan** [honestbleeps/Reddit-Enhancement-Suite#2265]
![screen shot 2015-06-04 at 12 31 04 am](https://cloud.githubusercontent.com/assets/1296162/7979120/64e6d3ee-0a51-11e5-8ac5-84636cd08a9e.png)

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/d7911c50bfbd53388b683c2125847666acbffa3b/lib/modules/hosts/gfycat.js#L22 doesn't seem to be removing the existing expando, but I haven't figured out why yet. maybe some race condition?

**Comment by pastudan** [comment]
just wanted to note that this is a particularly annoying bug, because when you attempt to close the existing reddit expando, the video doesn't close.

**Comment by erikdesjardins** [comment]
That's because this repo is not identical to the last release - there have been >1000 commits since then.

So the indicated code *is* the fix for this issue. (well, actually all duplicates from any site should be removed now, so that code is redundant and will be removed)

**Comment by pastudan** [comment]
Haha, thanks for explaining. I probably should have built it from source and tried it before making an issue. Glad this is resolved.

**Comment by allthefoxes** [comment]
Search is also your friend :wink:
