### ISSUE TITLE
Multiple imgur gifs and album expandos

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2271]
https://www.reddit.com/r/RESissues/comments/392p89/bug_res_is_showing_gifs_and_imgur_albums_twice/

This is different from usual in that there's only one button, so our existing fix doesn't work.

**Comment by andytuba** [comment]
I've got a branch ready to test and PR which will prevent this in the future and allow reddit to remove their workaround for us.
