### ISSUE TITLE
Automatic night mode broken? 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2279]
There have been several reports of this. 

http://www.reddit.com/r/Enhancement/comments/39fccw/how_do_i_customise_night_mode/

**Comment by mc10** [comment]
Huh, has anything changed recently? It's odd that it'd break so randomly, but I'll take a look.

**Comment by andytuba** [comment]
I've seen the occasional report over the past few months.

**Comment by andytuba** [comment]
https://www.reddit.com/r/RESissues/comments/2gaact/bug_automatic_night_mode_has_never_worked_for_me/?ref=search_posts

**Comment by andytuba** [comment]
potential: https://www.reddit.com/r/RESissues/comments/347cgt/proper_way_of_toggling_night_mode_when_automatic/?
