### ISSUE TITLE
Duplicate elements of interface

### ISSUE THREAD

**Issue by DarkDimius** [honestbleeps/Reddit-Enhancement-Suite#2298]
Just installed  RES on Firefox 38, with default configuration I have duplicate parts of reddit interface:
duplicate interface of RES: https://yadi.sk/i/atpoSbFqhJgKj
duplicate message window: https://yadi.sk/i/ZPamg1q6hJfNP
duplicate item in right column: https://yadi.sk/i/k6sil2jyhJfZy

If I disable RES, problem goes away.

**Comment by andytuba** [comment]
Please post to /r/RESissues.
