### ISSUE TITLE
Support oddshot.tv expandos

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2321]
oddshot is a new popular service for uploading clips right from twitch.tv. I've been seeing it everywhere, and there was a request [here](https://www.reddit.com/r/Enhancement/comments/3bv6qw/feature_request_oddshot_support/)

**Comment by erikdesjardins** [comment]
They don't appear to have an API right now, but if they release one I could implement this.

**Comment by sgtfrankieboy** [comment]
@erikdesjardins No need for an API.

An oddshot link looks like this:
`http://oddshot.tv/shot/esl_csgo_1573_201507021602404103`
The video link looks like this:
`https://s3.eu-central-1.amazonaws.com/oddshot/capture/esl_csgo_1573_201507021602404103.shot.mp4`

So you can do `https?://oddshot.tv/shot/(.*)`

Video: `https://s3.eu-central-1.amazonaws.com/oddshot/capture/$1.shot.mp4`
Poster: `https://s3.eu-central-1.amazonaws.com/oddshot/thumbs/$1.shot.thumb.jpg`

Shouldn't take long to implement, trying to get a pull request done within the hour.

**Comment by erikdesjardins** [comment]
Ah, looks good. That's what I get for making assumptions.

**Comment by perry-mitchell** [comment]
Wow, you guys are definitely on top of this. We'll be adding proper API support for our shots very soon, and with that most likely a PR for the enhancement suite.

**Comment by perry-mitchell** [comment]
Wow, you guys are definitely on top of this. We'll be adding proper API support for our shots very soon, and with that most likely a PR for the enhancement suite.

**Comment by andytuba** [comment]
@perry-mitchell Thanks for providing the oddshots service! It looks like a great contribution to the video game community.

Do you have a small logo to show under the expandoed video?  

* Favicon (16x16)
* Image sized between 15x15 -- 150x30 pixels
* Fallback will be "oddshot.tv" with a little border, which seems to match the site's current aesthetic.

**Comment by andytuba** [comment]
@perry-mitchell If you want any help with a PR, feel free to ping someone on github, irc, /r/enhancement.. the showImages code can be a little obscure.
