### ISSUE TITLE
User Tag dialog overflows

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2339]
Whenever it's long enough that the preview wraps.
![image](https://cloud.githubusercontent.com/assets/7673145/8538089/505f0e3e-2435-11e5-959c-c7b35c86d827.png)

**Comment by andytuba** [comment]
Hmm, that dialog should have a min-height instead of a fixed height .. 

I've kinda been wanting to add a optional max-width (default of 3em) and overflow-hidden to tags, too.
