### ISSUE TITLE
Bug with image expandos causing page to scroll down

### ISSUE THREAD

**Issue by githue** [honestbleeps/Reddit-Enhancement-Suite#2341]
Tested on Chrome on Windows 7, latest dev build of RES. Doesn't happen in 4.5.4.

Steps to reproduce:

1. Go to any link listing with multiple image expandos, like http://www.reddit.com/r/funny
2. Expand the image of the second submission
3. Expand the image of the first submission
4. Scroll down until the expando of the second submission comes into view
5. Collapse the image of the second submission

Result: the page scrolls down to where the second image used to be.

Doesn't happen with videos.

Does happen on http://www.reddit.com/r/gifs

Also happens on new search page: http://www.reddit.com/r/funny/search?q=&restrict_sr=on&sort=top&t=week

**Comment by andytuba** [comment]
Fixed in release/4.6.1
