### ISSUE TITLE
Add dashboard to redditlogodestination option

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2362]
maybe an option for "custom user-defined URL"?

https://www.reddit.com/r/Enhancement/comments/3dj4xp/how_to_link_dashboard_to_reddit_logo_link/

**Comment by pll33** [comment]
This should be closed since PR #2366 was merged right? @erikdesjardins

Just looking for some other things to do :)

**Comment by erikdesjardins** [comment]
Yep, thanks!
