### ISSUE TITLE
Clarify Inline Image Viewer: preloadImages

### ISSUE THREAD

**Issue by RollingStar** [honestbleeps/Reddit-Enhancement-Suite#2364]
It looks like preloadimages loads every image on every Reddit page visited while enabled. Is this correct?

It also looks like expanding one image does not cause other images in the gallery to be loaded (when preloadimages is disabled). Is this correct?

Is there any option to preload every image in a gallery, but only after the gallery has been expanded?

**Comment by larsjohnsen** [comment]
Option replaced with 'preloadCount'.

**Comment by erikdesjardins** [comment]
>Is there any option to preload every image in a gallery, but only after the gallery has been expanded?

That's exactly how it works. In the next release you'll also be able to choose how many images ahead are loaded, instead of the entire album, as @larsjohnsen said.
