### ISSUE TITLE
An option to automaticall resume loading in Never Ending Reddit

### ISSUE THREAD

**Issue by helarqjsc** [honestbleeps/Reddit-Enhancement-Suite#2367]
Can such a feature be added? 
I mean, currently my "workflow" with RES is like this: 
1. Scroll down 7 pages (my value of `pauseAfterEvery` option in `Never Ending Reddit`);
2. Press "Open Next Page";
3. In the new page press "Resume", so the Never Ending Reddit works again;
4. Repeat.

If there was an option to automatically resume scrolling when a new page is opened, I wouldn't have to press "Resume" manually every time. What do you guys think?

**Comment by allthefoxes** [comment]
:+1:

**Comment by andytuba** [comment]
I think the "open next page" button should unpause NER when the page number is a pauseAfterEvery page, yes.

**Comment by andytuba** [comment]
fyi I am slapping on 'unconfirmed' because while i am pretty it works exactly as you described i want somebody to double-check.  @allthefoxes did you repro or are you just expressing approval?

**Comment by erikdesjardins** [comment]
#2385
