### ISSUE TITLE
beta button

### ISSUE THREAD

**Issue by sajadm** [honestbleeps/Reddit-Enhancement-Suite#2368]
users signed onto reddit /r/beta have a beta icon (lab flask icon) to the left of their username. the beta button intrudes on usernames (ultimately covering short usernames)

image:

https://i.imgur.com/QeSQnHS.png

this should work:

.beta-hint {
position: static;
display: inline-block;
height: auto;
vertical-align: top;
}

**Comment by githue** [comment]
That CSS causes the beta tooltip to point to the wrong place and the icon still covers up the toggle button. I'd love to rework the CSS for the toolbar, but I'm not sure if it's ok to make some changes that will require certain subreddits to update their CSS.

**Comment by githue** [comment]
I spoke too soon.

All it takes is changing this selector:

    #header-bottom-right #userbarToggle + *

To 

    #header-bottom-right > .user
