### ISSUE TITLE
Better module categorizing

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2374]
Module categories are a little arbitrary right now. Could they be improved?

Reminder: modules can belong to multiple categories.

**Comment by andytuba** [comment]
@githue

**Comment by githue** [comment]
Card sorting is a quick and easy exercise for finding ways to categorize items. When I tried it with RES this was my result: [cards screenshot](https://cloud.githubusercontent.com/assets/7245595/8886424/2b5df54c-32ad-11e5-8b6d-e45aa4b2c969.png). I started without any groups and just put similar cards in piles, then I started naming the piles based on their common trait. It took about 30 minutes. You can do your own and compare the results to make it better.

I then made a new RES branch and updated the categories: [menu screenshot](https://cloud.githubusercontent.com/assets/7245595/8886489/7de54aee-32ae-11e5-8fd7-24d0fb96c1de.png).

That's somewhat better I think, but the 'viewing content' category is far too ambiguous, where should modules like 'spam button' and 'table tools' go? Maybe my categories are all wrong, or maybe it just needs a few changes.
