### ISSUE TITLE
Youtube (non-link) expandos are easily fakable

### ISSUE THREAD

**Issue by puckipedia** [honestbleeps/Reddit-Enhancement-Suite#2379]
Due to the use of regexes in the handling of youtube expandos, it's easy to create youtube links that, when viewed using an expando show one thing, but when clicked on directly show another. I made a test post outlining how this works: https://www.reddit.com/r/puckipedia_tests/comments/3erl0x/res_youtube_breakage/

(note: this does not work on link expandos, because those use the oembed metadata in the pages)

**Comment by erikdesjardins** [comment]
>does not work on link expandos

Yeah reddit generates those.

I'll discipline the regex for being too greedy.
