### ISSUE TITLE
Ctrl+K messes with OS X keybindings in Chrome

### ISSUE THREAD

**Issue by mhavard999** [honestbleeps/Reddit-Enhancement-Suite#2388]
There's some weird alert or confirm box or something that pops up when you hit Ctrl+K, but on OS X, you can use Ctrl+K to kill a line (pipe operator is cursor):
```
|Here is a line that I want to cut and maybe paste somewhere else.
 Here is the next line.
```
(Ctrl+K)
```
|
 Here is the next line.
```
But then I have to hit esc to get rid of the pop up.

**Comment by andytuba** [comment]
That pop-up is "create a link using snudown (reddit markdown)". You can customize that keyboard shortcut in the upcoming release.

In the future, could you report bugs to /r/RESissues? Thanks!

**Comment by mhavard999** [comment]
GitHub markdown is 100000000x better than reddit markdown but whatevs

**Comment by mhavard999** [comment]
Reddit doesn't even do syntax highlighting

**Comment by mhavard999** [comment]
So how about no

**Comment by allthefoxes** [comment]
Okay, what does that have to do with anything?

**Comment by mhavard999** [comment]
How are you supposed to have discussions with code examples???

**Comment by andytuba** [comment]
@mhavard999 We prefer starting these discussions on /r/RESissues to take
advantage of the bug management tools built into RES, AutoMod, and
/r/RESissues. When there's a need for nice syntax highlighting or a new bug
has been identified, then it's appropriate to start a gist or GitHub issue.


For this discussion, reddit's markdown is sufficient.
​


---
andytuba@andytuba.com
