### ISSUE TITLE
Top bar: link karma count has a comma separator, comment karma does not.

### ISSUE THREAD

**Issue by alexskc** [honestbleeps/Reddit-Enhancement-Suite#2393]
![really](https://cloud.githubusercontent.com/assets/6933425/9039372/4b56a38a-39fb-11e5-9d5b-5d782cd346cb.png)

Inconsistent and mildly distracting.

**Comment by erikdesjardins** [comment]
https://www.reddit.com/r/RESissues/wiki/knownissues#wiki_comment_karma_commas

**Comment by mc10** [comment]
Already fixed by https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/81c1f05b83a73ec85311be7c62e91323a0c2ecdf.
