### ISSUE TITLE
incorrect character count on ban message

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2394]
https://www.reddit.com/r/toolbox/comments/3frjkb/suggestion_character_countwarning_in_the_ban/

**Comment by kAbhi** [comment]
this seems to be fixed. Confirmation provided: https://www.reddit.com/r/toolbox/comments/3frjkb/suggestion_character_countwarning_in_the_ban/ctrccf4

**Comment by erikdesjardins** [comment]
It's fixed in [Toolbox](https://github.com/creesch/reddit-moderator-toolbox/) (where it was reported), but the issue also occurs in RES (where it isn't fixed yet).

I'll fix it now though, it's simple.
