### ISSUE TITLE
Modmail is nearly invisible in night mode

### ISSUE THREAD

**Issue by RollingStar** [honestbleeps/Reddit-Enhancement-Suite#2421]
![image](https://cloud.githubusercontent.com/assets/4810902/9311928/9aa8dd58-44e7-11e5-8a6c-b51dd5ecba2f.png)

Clicking on each post makes it white, but clicking on the next post turns the text black or green again.

I'm on Windows 8.1. My Chrome x64 extensions are:

* 4chan X
* Enhanced Steam
* Google Docs
* Lastpass
* Lazarus
* Reddit Enhancement Suite
* uBlock Origin

**Comment by erikdesjardins** [comment]
This is already fixed for the next release, and it is listed in the known issues on /r/RESissues.

Thank you for the report, but please use /r/RESissues in the future.
