### ISSUE TITLE
Character count needs to be updated for new global 40k limit

### ISSUE THREAD

**Issue by Darkhand81** [honestbleeps/Reddit-Enhancement-Suite#2433]
As of June 10th, Reddit no longer differentiates character counts between different types of subreddits; it is now a global limit of 40,000 characters.

See commit:  https://github.com/reddit/reddit/commit/4245fde3e1836ea9f649b94643bbbef5b581c1ea

However RES still lists a character limit of 10,000 when posting.

**Comment by erikdesjardins** [comment]
As of June 12th, [we fixed it](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2283).

It just hasn't been released.
