### ISSUE TITLE
The friend button in user info doesn't always work

### ISSUE THREAD

**Issue by githue** [honestbleeps/Reddit-Enhancement-Suite#2447]
Two issues:

1. The toggle() function on [+friend] sends a href value, instead of just the username. So if the link is `<a href="/u/githue">`, then onclick will be `toggle('/u/githue')` instead of `toggle('githue')`.
2. The isFriend var is checking for the presence of the class 'friend', which means it only works for links inside `.tagline`. The check won't work for links in self posts and sidebars.

I don't know how the second issue should be solved.

**Comment by andytuba** [comment]
Re: 2. - `/user/:username/about.json` returns `data.is_friend = true|false`
