### ISSUE TITLE
observe clippy option for tooltip on video embeds

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2458]
https://www.reddit.com/r/RESissues/comments/3m7yc7/bug_clippy_is_not_disabling_tooltips_on_gifv_and/

**Comment by DrLeh** [comment]
It seems like clippy isn't working at all right now.

If I'm not mistaken, I believe the `&&` should really be an `||` on this line: https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/e6238bd47e9c4b656b3d563978a4fbb82657c7ee/lib/modules/showImages.js#L1781 

This would make it skip clippy text if either clippy is set to false or the title has already been applied.

**Comment by erikdesjardins** [comment]
#2713
