### ISSUE TITLE
Slight error in style when in beta mode

### ISSUE THREAD

**Issue by andrewnguyen42** [honestbleeps/Reddit-Enhancement-Suite#2467]
When someone has signed up for the beta, the default RES style lays the beta icon over the username

<img width="69" alt="screen shot 2015-10-01 at 11 01 37 pm" src="https://cloud.githubusercontent.com/assets/1887458/10239242/6ca58998-6890-11e5-8413-f750c698f6a0.png">

For reference, the non-RES beta-style looks like this

<img width="71" alt="screen shot 2015-10-01 at 11 04 34 pm" src="https://cloud.githubusercontent.com/assets/1887458/10239277/ddf2ffd6-6890-11e5-8ad0-6b00120dd9fc.png">

My proposal is to add a little bit of padding on the .beta-hint class and .userbarHide so it looks like this

<img width="92" alt="screen shot 2015-10-01 at 11 06 13 pm" src="https://cloud.githubusercontent.com/assets/1887458/10239311/4414b9d0-6891-11e5-8bfe-d97536ddb826.png">

**Comment by allthefoxes** [comment]
This is a very, very known issue.

**Comment by andytuba** [comment]
This is fixed in master already. (Release eta unknown.)
