### ISSUE TITLE
"Slashtags" snuOwnd support

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2469]
https://www.reddit.com/r/RESissues/comments/3nbhc6/reddit_no_longer_requires_a_slash_in_front_of_a/

u/user and r/subreddit are autolinked in snudown, but not snuOwnd.

**Comment by erikdesjardins** [comment]
Switching [to this](https://github.com/erikdesjardins/snudown-js) is an option - it's compiled straight from C, so updating for any future changes will be easy.

**Comment by andytuba** [comment]
Oh boy, it's that simple?

**Comment by erikdesjardins** [comment]
Yeah, [this file](https://github.com/erikdesjardins/snudown-js/blob/master/snudown.js) is all of the handwritten JS (~20 LOC).

It's also compiled to asm.js, so it should be blazing fast (not that that's important for our usage anyways).
