### ISSUE TITLE
Disappearing text in Chrome with expandos (test case)

### ISSUE THREAD

**Issue by githue** [honestbleeps/Reddit-Enhancement-Suite#2473]
I made a test case for [this issue](https://www.reddit.com/r/RESissues/comments/3ky4ad/bug_expandos_hide_link_after_the_expando_is/) and found a couple of possible fixes: http://jsbin.com/wodigu

I'll leave this here in case someone has another solution and also so we can check whether a browser update fixes it.

I think [this bug for Blink](https://chromium.googlesource.com/chromium/src/+/cebc72fa017b6979b0646a75eb7b1baf7ce54b67) was closely related but not quite the same.

**Comment by githue** [comment]
Fixed in new Chrome update.

**Comment by andytuba** [comment]
Thanks for investigating though!
