### ISSUE TITLE
convert forEachChunked to WorstThanHipster's implementation

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2488]
https://github.com/LiterallyWTH/reddit-moderator-toolbox/commit/80ad3810e1d8bae71218b58aafbce99753284b27

> to keep the framerate at a target framerate, that you can set but i default it to 30.
> No chunk size is needed.  You can set options but it's just array and callback.  It defaults to a chunk size of 10 but ramps up (or slows down) very quickly
> No dependencies, all vanilla, so you can paste it wherever to try it out.

**Comment by LiterallyWTH** [comment]
This entire branch is devoted to the dynamic chunking:

https://github.com/LiterallyWTH/reddit-moderator-toolbox/tree/dynamic-chunks

You can just monitor that to stay up to date as I test (and refactor?) it.  You can performance test it on arrays inside or out of RES or toolbox.  I'll be more than happy to put together a PR if you guys like it.

**Comment by andytuba** [comment]
It would be super great if you wrote a PR for RES.
