### ISSUE TITLE
imgur Gifs not visible on expansion

### ISSUE THREAD

**Issue by gofirst2220** [honestbleeps/Reddit-Enhancement-Suite#2495]
Browser: Firefox Nightly
Browser Version: 44
RES Version: 4.5.4.1-Signed
OS Version: Windows 10 Pro Insider Preview Build 10565

Sometimes on /r/funny, gifs aren't visible on expansion, I even cleared the cache. Is there a fix for this bug?

**Comment by allthefoxes** [comment]
I would wait for the issue to get out of nightly, first of all

**Comment by gofirst2220** [comment]
Before the gifs were working on yesterday's hotfix. I'm guessing something changed in today's hotfix update

**Comment by andytuba** [comment]
@gofirst2220 Working yet?
