### ISSUE TITLE
RES makes pages "crash"

### ISSUE THREAD

**Issue by shavitush** [honestbleeps/Reddit-Enhancement-Suite#2496]
I'm using Firefox 41.0.2
Example video: https://youtu.be/nYOHrNZ47sI  
Page that crashed for me: https://www.reddit.com/r/GlobalOffensive/comments/3qm9qh/csgo_update_for_28102015/

Only happens when I have Firefox's hardware acceleration enabled, doesn't happen if disabled.  
Also it started when I changed to an R9 380 GPU, worked flawlessly with a GTX 650.

**Comment by 13steinj** [comment]
May wanna post on /r/resissues

**Comment by andytuba** [comment]
Yes please, post to /r/resissues and make sure to leave all the data from the wizard.
