### ISSUE TITLE
nightmode: automatically toggle automatic nightmode when the time comes

### ISSUE THREAD

**Issue by tswaters** [honestbleeps/Reddit-Enhancement-Suite#2502]
I think it would be pretty neat if nightmode automatically toggled when the time comes.  Usually I'll be browsing down on page 30+ of RES and I'll click a comment only to see night mode has been enabled -- and it is likely past my bed time.  

I can't help but notice there's an event that never ending reddit will fire when it has finished loading a page - I think this is the perfect event to check for whether automatic nightmode should be enabled or not... I think for the most part, the only time I wish it would toggle automatically is when using never ending reddit.

It would be possible to figure out the time it should be enabled and set a timeout for that time -- but that would probably be more effort for what it's worth.  I'm creating a PR with the method I had in mind...

**Comment by tao-lu** [comment]
@tswaters Any interest in continuing this feature?

**Comment by tao-lu** [comment]
Re: automatically selecting a time, we could go with something like http://sunrise-sunset.org/api as an additional option (perhaps named: synchronize auto transition with local sunset/sunrise times).

**Comment by andytuba** [comment]
How about simply implementing it completely inside nightmode, something like `setInterval(checkForAutomaticNightMode, 5 * MINUTE`? And, of course, add in an option to disable it.

The sunrise-sunset sounds like a night idea, too! It could override the existing options for on/off times, but let's keep those for people on third shift. It would be very considerate to add a migration to turn off the synchronized time option if the user has changed the on/off times to a value >=2 different than the default.

**Comment by andytuba** [comment]
The sunrise-sunset sounds like a night idea, too! It could override the existing options for on/off times, but let's keep those for people on third shift. It would be very considerate to add a migration to turn off the synchronized time option if the user has changed the on/off times to a value >=2 different than the default.

**Comment by erikdesjardins** [comment]
http://api.sunrise-sunset.org/json appears to send CORS headers, so it's all good on that front.

Also:

> **Usage limits and attribution**

>The sunrise and sunset API can be used free of charge. You may not use this API in a manner that exceeds reasonable request volume, constitutes excessive or abusive usage. We require that you show attribution to us with a link to our site.

So we should be fine if the option is disabled by default and we link to the site in the option description.

**Comment by andytuba** [comment]
> excessive usage

Ping it once a week, maybe?

**Comment by andytuba** [comment]
https://www.reddit.com/r/Enhancement/comments/5dheyp/feature_request_night_mode_based_on_sunset_and/

**Comment by erikdesjardins** [comment]
Moving sunrise/sunset-based nightmode to #3657
