### ISSUE TITLE
quickMessage: Text after an ampersand symbol is left out

### ISSUE THREAD

**Issue by cubrr** [honestbleeps/Reddit-Enhancement-Suite#2515]
When using the quickMessage module to send a message, any text after an ampersand gets left out from the message. Considering the fact that [`encodeURIComponent` is used by the module](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/a368d4a360b8e07cfb0b4a27b169864a35ea7389/lib/modules/quickMessage.js#L332), could this be a problem with reddit's API?

##### Image 1: Message being written

> ![screenshot_8](https://cloud.githubusercontent.com/assets/6078228/11148080/2fb348ea-8a23-11e5-9051-373b5c5b12f9.png)

##### Image 2: Resulting message

> ![screenshot_7](https://cloud.githubusercontent.com/assets/6078228/11148065/1ca6eaf4-8a23-11e5-95af-8f3fc6e70745.png)

**Comment by allthefoxes** [comment]
I thought this was fixed already for 4.6? Unsure

**Comment by erikdesjardins** [comment]
This is already fixed, and is listed in the known issues on /r/RESissues.

Please do not open an issue in the repo without *at least* confirming that it actually happens in said repo.

**Comment by cubrr** [comment]
Sorry. I didn't know about /r/RESissues.

How can I get the "latest" version? The one available from the website is 4.5.4.1-signed.

**Comment by allthefoxes** [comment]
4.5.4 Is the most up to date public release of RES.

Stay tuned for 4.6!

**Comment by cubrr** [comment]
Okay, thank you.
