### ISSUE TITLE
Support for Derpibooru Media Host

### ISSUE THREAD

**Issue by Ajedi32** [honestbleeps/Reddit-Enhancement-Suite#2527]
[](/twibeam) I've started frequenting [/r/mylittlepony](https://www.reddit.com/r/mylittlepony) recently, and one of the more popular image hosts there (and on [all the other MLP subs](https://www.reddit.com/r/wehavetoomanymlpsubs)) is [Derpibooru](https://derpiboo.ru/).

[](/twisquint) I'd like to add support for that site to RES's image expand feature, but I want to make sure a PR for that would be welcome before I start working on it. Derpibooru [has an easy-to-use API](https://derpiboo.ru/pages/api), and I've already located [the place in RES where new media hosts are placed](https://github.com/honestbleeps/Reddit-Enhancement-Suite/tree/master/lib/modules/hosts), so I'm pretty confident this wouldn't be too difficult to implement, just give me the go ahead and I'll get to work. [](/ajhappy-in)

**Comment by erikdesjardins** [comment]
I don't see any reason it wouldn't be welcome.

There is one issue you'll run into: they don't seem to send [CORS headers](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), so you'll need to request optional permissions for Chrome. Right now, [the code to do this](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/hosts/twitter.js#L51-L82) is a bit horrifying (it should - and will, eventually - be 1 line), though you can pretty much copy most of that.

**Comment by Ajedi32** [comment]
@erikdesjardins They don't? I thought I checked...

Yeah, Chrome is showing `access-control-allow-origin:*` returned from https://derpiboo.ru/1025639.json

**Comment by erikdesjardins** [comment]
Huh, it seems like curl was lying to me...or I'm just blind at reading the headers.
In that case - yeah it'll be easy.

**Comment by andytuba** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/hosts/example.js

:+1:

**Comment by Ajedi32** [comment]
Quick question: I noticed that some of the existing media host modules like Photobucket seem to include code specifically for handling the case where the user links the image in question directly. (E.g. not just the page the image is on.) Given that RES already handles direct image links, is that sort of code strictly necessary?

Probably won't matter in my case since Derpibooru seems to host its images on a separate domain from the main site, but still I'm kind curious.

**Comment by Ajedi32** [comment]
Another question, is the `caption` still used by RES? The example file mentions it, but the strings I put in the caption property don't seem to be displayed anywhere.

**Comment by erikdesjardins** [comment]
Right, RES will handle images with normal image/video extensions on any domain.
So it does seem like that Photobucket code is unnecessary - though it could be for handling links that don't have a file extension but are still direct links to images, à la [Steam](http://images.akamai.steamusercontent.com/ugc/392173174169202234/DD4B78C2D95DF7B1C2481150434147D5A3E6F21A/).

**Comment by erikdesjardins** [comment]
I'm not sure if `caption` is used; the properties that are used are a bit ad-hoc (and undocumented) and they depend on the `type`, I think [deviantArt](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/hosts/deviantart.js) and [tumblr](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/hosts/tumblr.js) use all of the `type: photo` ones.

**Comment by Ajedi32** [comment]
So apparently you also need to set `imgCaptions` on the link element in order to show image captions? https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/showImages.js#L866-L871 Is that intended?

**Comment by Ajedi32** [comment]
Also, just noting this for myself for future reference: the Deviantart host currently silently swallows errors raised in its `handleInfo`.

**Comment by Ajedi32** [comment]
[](/twipride) Yay! Done. :tada:

That wasn't too hard...
