### ISSUE TITLE
How are image captions supposed to work?

### ISSUE THREAD

**Issue by Ajedi32** [honestbleeps/Reddit-Enhancement-Suite#2532]
The comments in `lib/modules/hosts/example.js` states the following:

```
Embedding infomation:
All embedding information (except 'site') is to be attached to the
html anchor in the handleInfo function.

optional caption:
	string to be displayed below the image
```

I recently tried playing around with this while working on #2531, and discovered that it doesn't seem to work. Though I'm not all that familiar with RES's codebase, I think [this code here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/showImages.js#L866-L871) might be responsible:

```javascript
if ('imgCaptions' in imageLink) {
	var captions = document.createElement('div');
	captions.className = 'imgCaptions';
	$(captions).safeHtml(imageLink.caption);
	imgDiv.appendChild(captions);
}
```

Is this a bug? Or is it intended?

**Comment by Ajedi32** [comment]
Also, the comment in example.js incorrectly states that the caption is displayed below the image. That wasn't the case for me when I test it.

**Comment by erikdesjardins** [comment]
This was intended [when it was changed](https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/b673055cb6f6a3e539a66585e1dc4ca7ffca0c1c), but nothing uses it right now, so I imagine it should be changed to `'caption' in imageLink`.

That comment in example.js is simply incorrect, it should be "below the title".
