### ISSUE TITLE
Minor: DeviantArt Media Host will silently swallow errors raised in its `handleInfo` method

### ISSUE THREAD

**Issue by Ajedi32** [honestbleeps/Reddit-Enhancement-Suite#2533]
Minor issue I discovered while working on #2531: if an error is thrown in DeviantArt's handleInfo method, the error will be silently caught and ignored thanks to https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/hosts/deviantart.js#L16-L21

**Comment by andytuba** [comment]
Thanks! Did you find some da urls that threw errors which should be handled better?

**Comment by Ajedi32** [comment]
I'm not aware of any specific user-facing problems caused by this issue, it seems like more of an internal thing so far.

I just used some of the code from the DeviantArt media host as the basis for the Derpibooru host I'm working on, and unintentionally created a similar problem there. It made debugging quite a bit harder until I discovered the problem. (Since problems in the handleInfo method were being silently ignored instead of printed to the console.)

Like I said, minor issue. Still probably worth fixing though. I'll send a PR which addresses it later.

**Comment by andytuba** [comment]
Ah, okay. Maybe reject with the error message?

**Comment by Ajedi32** [comment]
The solution I used for Derpibooru was to just not catch the exception. handleInfo shouldn't be throwing exceptions anyway AFAIK, so if there is one it's best to just let it bubble all the way out to the console so devs can easily see what went wrong and fix it.

**Comment by Ajedi32** [comment]
I think maybe the fix explains the problem a bit better. A minor thing, but still worth fixing IMO.
