### ISSUE TITLE
'You switched to /u/account' message comes up on reddit.com/url.json

### ISSUE THREAD

**Issue by MajorityReports** [honestbleeps/Reddit-Enhancement-Suite#2535]
If you switch accounts while on a .json page the alert message comes up making it hard to see and impossible to select, even though it's just a single click.  Nightmode even activates making it hard to see .json pages, and it even defeats the JSON Viewer plugin I have.  I think RES should do something useful with .json pages or ignore them.

**Comment by andytuba** [comment]
RES should ignore .json pages.
