### ISSUE TITLE
[request] When I get the "you are doing that too much. try again in X minutes" message, give me a button to have RES store that submission and submit it in the background after the designated time passes.

### ISSUE THREAD

**Issue by jdgalt** [honestbleeps/Reddit-Enhancement-Suite#2543]
This was posted in r/enhancement so long ago that it's archived.  And it needs to happen, so it ought to be here.

**Comment by erikdesjardins** [comment]
[RES will not make it easier to deal with anti-spam measures.](https://www.reddit.com/r/Enhancement/wiki/rejectedfeaturerequests#wiki_when_reddit_tells_me_.22wait_5_minutes.2C_you.27re_doing_that_too_much.22.2C_can_res_automatically_post_after_5_minutes.3F)
