### ISSUE TITLE
How to build xpi via jpm

### ISSUE THREAD

**Issue by darkred** [honestbleeps/Reddit-Enhancement-Suite#2544]
I want to build the latest xpi via jpm. (win10x64)

Is the following the correct procedure?
_I have already installed node.js v5.1.0 x64_

```
git clone https://github.com/mozilla/jpm
cd jpm
npm install 
npm link
cd ..
git clone https://github.com/honestbleeps/Reddit-Enhancement-Suite
cd XPI
-----> Do I also need:  npm install  ?  
jpm xpi
```

**Comment by andytuba** [comment]
Yes, you need to `npm install` and, every time you pull / edit, then `gulp build -b Firefox && cd dist/XPI && jpm xpi`

**Comment by darkred** [comment]
So, if I got this right,
I do this the 1st time:


```
git clone https://github.com/mozilla/jpm
cd jpm
npm install 
npm link
cd ..
git clone https://github.com/honestbleeps/Reddit-Enhancement-Suite
cd XPI
npm install
```
and after every time I do a `git pull` in the Reddit-Enhancement-Suite directory, 
I have to do (have gulp installed and then) :
```
gulp build -b Firefox 
cd dist/XPI 
jpm xpi
```

<br>
Ιs `gulp build -b Firefox ` really necessary in order to build the xpi (not run it in a new profile)? 
Isn't `jpm` sufficient?
And, what's the purpose of the above command? 
I only found In [here](http://gruntjs.com/using-the-cli) that: 
```
--base, -b
Specify an alternate base path. By default, all file paths are relative to the Gruntfile.
```

**Comment by mc10** [comment]
`gulp build -b Firefox` packages all of the files and moves them into the proper `dist` folder. The link you provided actually refers to Grunt, not gulp (confusing, especially since we still have both build systems). So yes, it is necessary to build the XPI.

**Comment by darkred** [comment]
Thanks for your reply.
But, after

```
git clone https://github.com/honestbleeps/Reddit-Enhancement-Suite
cd XPI
npm install
```
I get `npm WARN EPACKAGEJSON reddit_res@4.5.4 No repository field`


_(using npm 3.3.12  (node.js 5.1.0 x64) in win 10 x64)_

**Comment by andytuba** [comment]
Sorry, I missed a line earlier. 

You should run npm install from the RES root directory, not XPI.

**Comment by darkred** [comment]
Thanks.
`npm install` showed various WARN and ERR messages:
http://pastebin.com/raw.php?i=471JZVQ4

Do I need to install other packages too?
Or I may just continue with gulp?

**Comment by mc10** [comment]
Should be fine. You probably want to pull, delete your `node_modules`, and re-run `npm install`, as a good amount has changed on the dev branch. I'm going to close this for now unless any further issues appear.

**Comment by darkred** [comment]
Thank you for replying

So I tried it again doing: 
`git pull`, 
deleted the `Reddit-Enhancement-Suite/node_modules` directory, 
and then re-run `npm install` 

here is what I got: http://pastebin.com/raw.php?i=1XBtA1M7

Then, I did
```
git clone https://github.com/gulpjs/gulp
cd gulp
npm install -g gulp
npm link
````
and finally
```
cd ../Reddit-Enhancement-Suite/
gulp build -b Firefox 
cd dist/XPI 
jpm xpi
```
but here is what I got
```
[01:54:25] Requiring external module babel-core/register
[01:54:26] Using gulpfile ~\Desktop\New folder (2)\Reddit-Enhancement-Suite\gulpfile.babel.js
[01:54:26] Starting 'babel'...
[01:54:26] 'babel' errored after 9.44 ms
[01:54:26] TypeError: Cannot read property 'dests' of undefined
    at getBuildDir (gulpfile.babel.js:112:60)
    at gulpfile.babel.js:119:41
    at Array.reduce (native)
    at pipeToBrowsers (gulpfile.babel.js:118:18)
    at Gulp.<anonymous> (gulpfile.babel.js:144:2)
    at module.exports (C:\Users\Kostas\Desktop\New folder (2)\Reddit-Enhancement-Suite\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\Kostas\Desktop\New folder (2)\Reddit-Enhancement-Suite\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\Kostas\Desktop\New folder (2)\Reddit-Enhancement-Suite\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\Kostas\Desktop\New folder (2)\Reddit-Enhancement-Suite\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Kostas\Desktop\New folder (2)\gulp\bin\gulp.js:129:20
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```
and there wasn't any `dist` directory created,
and so I can't do:
```
cd dist/XPI 
jpm xpi
```

**Comment by darkred** [comment]
Could someone please help me with this? What's wrong in the procedure I followed?

**Comment by Ajedi32** [comment]
From the errors you're getting on `npm install` it sounds like `bufferutil` and `node-sass` require Python to be installed and on your PATH.
