### ISSUE TITLE
Reddit live and night mode don't work well

### ISSUE THREAD

**Issue by choikwa** [honestbleeps/Reddit-Enhancement-Suite#2546]
The text in reddit live and night mode is unreadable unless highlighted.

![daymode](https://cloud.githubusercontent.com/assets/5455710/11550988/ea48735a-9942-11e5-8013-696a01090433.png)
![nightmode](https://cloud.githubusercontent.com/assets/5455710/11550989/ea4d6252-9942-11e5-83fd-24eae468d846.png)
![highlighted_text](https://cloud.githubusercontent.com/assets/5455710/11550990/ea522882-9942-11e5-98ca-fd347afca4ab.png)

**Comment by githue** [comment]
Fixed in master: https://github.com/githue/Reddit-Enhancement-Suite/commit/1be2357acefe3a72d4c015206de688a7671e9ca4
