### ISSUE TITLE
Upload.js only has one host and it's been down for some time (imgrush)

### ISSUE THREAD

**Issue by githue** [honestbleeps/Reddit-Enhancement-Suite#2552]
Trying to upload an image:

> https://imgrush.com/api/upload/file Failed to load resource: the server responded with a status of 521 (OK)

Should probably 'hide' the module until another host is added.

**Comment by andytuba** [comment]
Oh goodie, imgrush is down? Yeah, let's hide that for sure and we should get an imgur anonymous uploader working at least.

**Comment by andytuba** [comment]
moved milestone to PR
