### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2587]
- [ ] [SauceLabs account](https://saucelabs.com/opensauce/)  @andytuba
- [ ] .travis.yml build valid .crx/.xpi
- [ ] [Script installing copy of extension](http://stackoverflow.com/questions/15005833/browser-plugin-testing-with-selenium)
- [ ] .travis.yml SauceConnect @andytuba
- [ ] .travis.yml run existing selenium tests using SauceLabs @andytuba
- [ ] .travis.yml run existing qunit tests
- [ ] Determine things to test
- [ ] Prioritize things to test
- [ ] Write tests

Note: 
- Selenium == UI tests (emulate user clicking/typing)
- qunit == testing code which doesn't need reddit UI

**Comment by erikdesjardins** [comment]
Running QUnit tests in Travis should be pretty straightforward; working on that now.

**Comment by Ajedi32** [comment]
@erikdesjardins Pretty sure @andytuba already implemented that: #2584

**Comment by andytuba** [comment]
I got qunit running in `release/4.6.0` but I'm having some trouble running them in `master` via `gulp-qunit`. If you get it running, that would make cherry-picking #2584 into `master` much easier.

**Comment by erikdesjardins** [comment]
Sorry, yeah I meant Gulp - it's a bit more complicated in `master` than #2584 (which only works in `release/4.6.0`) cause we need to run it through Babel first.

**Comment by mc10** [comment]
This has already been running for a while, so closing.
