### ISSUE TITLE
Restore keyboard focus to page after cancelling comment edit

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2589]
https://www.reddit.com/r/RESissues/comments/3z2q1r/bug_when_using_keyboard_navigation_movedownthread/cykmx16?context=3

**Comment by larsjohnsen** [comment]
Appears to be fixed (focus is always restored to `document.body`).

**Comment by erikdesjardins** [comment]
Appears to be fixed for me too
