### ISSUE TITLE
On some (big?) tables, table sort goes wonky

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2590]
https://www.reddit.com/r/RESissues/comments/3zadm2/bug_table_sort_sometimes_doesnt_work/

![tablesort](https://cloud.githubusercontent.com/assets/455632/12080493/bda8dc54-b210-11e5-9870-e503d0060937.gif)

**Comment by andytuba** [comment]
Looks like just the table header wedges go weird.

**Comment by githue** [comment]
The strong tags in the table headers are confusing the script, I believe.

**Comment by erikdesjardins** [comment]
#2592
