### ISSUE TITLE
Comment boxes should only be added on body.comments-page (dev)

### ISSUE THREAD

**Issue by githue** [honestbleeps/Reddit-Enhancement-Suite#2597]
Currently it's being applied everywhere, even on wiki i.e. `.res-commentBoxes body > .content { padding-right: 0; }`

**Comment by githue** [comment]
This can be resolved by moving commentBoxes into its own module. I'm thinking about adding a module called 'Comment Styling', which would include commentBoxes and any other relevant options.

**Comment by erikdesjardins** [comment]
Makes sense; if you do that, you might as well rename `_commentBoxes.scss` to `_commentStyling.scss` (or whatever you decide to call it), so all the names lines up.
