### ISSUE TITLE
Hosted imgur accounts are no longer inlining their images

### ISSUE THREAD

**Issue by vermiculus** [honestbleeps/Reddit-Enhancement-Suite#2599]
#2239 seems to be broken in at least 4.5.4 on Chrome 47.0.2526. [19] and [20] aren't showing inline on [this thread](https://redd.it/2zk1ae).

**Comment by erikdesjardins** [comment]
That simply has yet to be released.
![image](https://cloud.githubusercontent.com/assets/7673145/12189330/a8de2e00-b58a-11e5-8e39-8835d5724184.png)

**Comment by vermiculus** [comment]
Oh :frowning: my apologies
