### ISSUE TITLE
Don't try to expando dropbox links

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2604]
https://www.reddit.com/r/RESissues/comments/40fwcv/bug_dropbox_image_viewing/

showImages has a domain blacklist, right?

**Comment by Ajedi32** [comment]
Alternately, is there any way to get around those restrictions imposed by Dropbox? As a browser extension, I suspect RES has a lot more flexibility in this regard than a regular website does.

Or... maybe I should back up a step. _Should_ we try to get around these restrictions? Any idea why Dropbox is doing this in the first place?

**Comment by andytuba** [comment]
We could write an official JavaScript client that calls file_get from the Dropbox API instead of hotlinking directly.. but will Dropbox API give RES an official URL that's okay for hotlinking?

**Comment by Ajedi32** [comment]
I'm not actually sure whether there's a way to do this using the Dropbox API. My initial thought was to just rewrite the `referer` header in the request for the image to prevent Dropbox from detecting it as a hotlink. Not sure if there's a cross-browser way of doing that. I know you can do it with Chrome. https://developer.chrome.com/extensions/webRequest

I guess a feature like that might be more trouble than it's worth though. Just disabling expandos for those images is a reasonable solution, especially short-term.

**Comment by andytuba** [comment]
I'd rather not resort to those kinds of hijinks since it may result in Dropbox going to more drastic measures to enforce their policy. It'd be better to see if Dropbox as a method they condone for hotlinking to images, or forego it.

**Comment by Ajedi32** [comment]
Yeah, that's why I raised the concern in my previous comment of whether we _should_ try to get around such restrictions, and what Dropbox's motivation for putting them in place initially was.

I'd argue that what RES is doing isn't quite the same as hotlinking, since users have to click to expand the image anyway (which is essentially the same as them clicking on the link, only slightly more convenient).

That said, obviously using the official API is a much easier and better way of doing this if possible.

**Comment by honestbleeps** [comment]
the purpose of dropbox having bandwidth limits is pretty clear, so I don't think we should really try and circumvent it.

official API usage is, to me, the only viable option and even then I'm not sure it'd be possible because we'd probably need some sort of key/secret that ought not be shared in our open source javascript.

**Comment by Ajedi32** [comment]
Does dropbox require an application level API token? The way I'm interpreting [the docs](https://www.dropbox.com/developers/documentation/http/documentation), it sounds like the OAuth token is only needed for accessing a user's private files. We only need to access public data.

**Comment by thybag** [comment]
Aside from info on bandwidth limits (before the links get disabled) dropbox don't appear to make there position on hotlinking images particularity clear.

https://www.dropbox.com/help/4204  & https://www.dropbox.com/help/45 being the only relevant articles i could dig up.

**Comment by Ajedi32** [comment]
@thybag Interesting. From that, it looks like hotlinking (or any type of linking, really) is more of a concern for the Dropbox account holder than for Dropbox itself.

Also, it looks like there _is_ a rather easy fix for this: http://cantonbecker.com/etcetera/2014/how-to-directly-link-or-embed-dropbox-images/ We just need a dedicated mediaHost for Dropbox. Seems easy enough. I really should have just Googled this sooner.

**Comment by larsjohnsen** [comment]
@Ajedi32  https://github.com/honestbleeps/Reddit-Enhancement-Suite/compare/master...larsjohnsen:dropbox

**Comment by Ajedi32** [comment]
@larsjohnsen You wana send a PR for that?

Also, see #1852

**Comment by thybag** [comment]
Assuming everyone is happy with the account holder taking the risk (That ship has probably sailed by the time its been posted on reddit anyway, with or without RES expando support) then I'd vote to go with @larsjohnsen media host over a black list. A working expando is always gonna be the better user experience.

That said, I'm not sure any real conclusion was reached over in https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/1852 - so possibly one for @honestbleeps or @andytuba to weigh in on?

**Comment by erikdesjardins** [comment]
This makes sense to me:

> That ship has probably sailed by the time its been posted on reddit anyway

While RES makes it easier, the account holder is already taking the risk that too many people will click through to the hotlinked image (and I've seen dropbox images linked in popular threads have public access throttled/revoked, so it wouldn't be unprecedented).

Calling for @honestbleeps or @andytuba to make a final decision
