### ISSUE TITLE
Clicking image in album doesn't go to album

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2605]
https://www.reddit.com/r/Enhancement/comments/40hgpo/clicking_an_inline_image_thats_part_of_an_album/

**Comment by erikdesjardins** [comment]
[Probably me](https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/bd1970aaeb65ad419c77a188d43130390b7c76e1), what I should have done is `sourceImage.href || sourceImage.src`. Will investigate tonight.

Note to self: remove from promise-to-async

**Comment by gfairchild** [comment]
This has been a bug with Vidble albums for months. Does PR #2616 fix it for Vidble albums as well?
