### ISSUE TITLE
v4.6.0 maxes out CPU usage

### ISSUE THREAD

**Issue by zschmidt** [honestbleeps/Reddit-Enhancement-Suite#2613]
On OSX 10.11.1 using Chrome Version 47.0.2526.106 (64-bit), every tab puts my CPU at 99.x% (per tab)

Disabling the extension lowers the CPU usage to 0.0% per tab.

**Comment by 13steinj** [comment]
Question that I asked someone else on /r/Enhancement:

1. Have you tried restarting your computer? Yes, as stupid as that sounds.

2. Next time this happens, can you please right click the page, press inspect, navigate to the console, refresh the page, and see if any errors occur in the console?

**Comment by zschmidt** [comment]
It would seem that it gets more interesting! Restarting didn't fix it, but here's a new development:

The tab hovers at 99% CPU *until* it's viewed, then it drops. So the steps to reproduce are like this:

1.) Navigate to Reddit with RES v4.6.0
2.) CMD click on the "Comments" link of any post
3.) Note that Activity Monitor reports 99% CPU usage on "Google Chrome Helper" and Chrome's Task Manager identifies the tab that was just opened as the culprit
4.) Navigate to the newly opened tab
5.) Observe CPU usage drops to 0%

**Comment by erikdesjardins** [comment]
Hmmm...can you try turning off all extensions except RES, to make sure it's not due to a conflict?

Also: does it happen on all reddit pages? If it doesn't, what page types doesn't it happen on? (wikis, comments, post listings, user profiles, etc.)

**Comment by zschmidt** [comment]
I disabled my only other extension for the above test (the conflict thought occurred to me as well)

I can confirm it happens on the following pages (without viewing the tab, of course):
1.) Comment threads
2.) Subreddits
3.) The homepage (right click on favorites link), though this is probably the same as the subreddits
4.) User pages
5.) Wikis

Let me know if there are other cases that I can try.

**Comment by mc10** [comment]
r/RESissues posts: https://www.reddit.com/r/RESissues/comments/40i3i2/bug_100_cpu_usage_after_updating_to_460/, https://www.reddit.com/r/RESissues/comments/40gtoi/bug_100_cpu_usage_on_chrome_mac_os_yosemite/

**Comment by honestbleeps** [comment]
seems clear this is happening in the 1ms settimeout that's looking for document.body - we could make it 50ms as a quick fix, but I wonder if there's a way to detect "okay, there's no document.body AND this tab is inactive, so wait for a tab active event" -- I believe this is possible.

**Comment by mc10** [comment]
Can we just use [MutationObservers](http://stackoverflow.com/questions/5525071/how-to-wait-until-an-element-exists) and drop the `document` ready check?

**Comment by erikdesjardins** [comment]
Yeah, that's [what I plan to do](https://github.com/erikdesjardins/Reddit-Enhancement-Suite/blob/d979ad173b095b76aa14e232d5869dad004cd0e6/lib/core/init.js#L41) ([impl](https://github.com/erikdesjardins/Reddit-Enhancement-Suite/blob/d979ad173b095b76aa14e232d5869dad004cd0e6/lib/core/utils.js#L262)) for 4.7.

I could port that part of init over, but a 50ms timeout would probably be safer for 4.6.1.

**Comment by honestbleeps** [comment]
I'm not sure if that would work or not. The idea is to run as early as
possible. Worth a try!

**Comment by mc10** [comment]
I'm not sure if that's the only issue; we should definitely profile and see if anything else turns up.

**Comment by legate** [comment]
I also had this issue, but it doesn't seem to happen anymore after updating to the latest stable version of Chrome ([47.0.2526.111](http://googlechromereleases.blogspot.com/2016/01/stable-channel-update.html)). [This bug fix](https://chromium.googlesource.com/chromium/src/+/19e6a44082f36d5ac3a76bc61734b859abee4dee) seems relevant.

**Comment by dsedivec** [comment]
> I also had this issue, but it doesn't seem to happen anymore after updating to the latest stable version of Chrome (47.0.2526.111). This bug fix seems relevant.

Same here.  I have been having this issue all week and as recently as this afternoon.  I've since upgraded Chrome to 47.0.2526.111.  Just now I opened four Reddit tabs in the background and CPU usage stayed normal.

**Comment by honestbleeps** [comment]
that's great news, glad it's been fixed on Chrome's side... I wonder if we should still put a check of some sort in our code, in case this comes up again... While I'd argue it's a chrome bug, the possibility of getting stuck in an infinite loop is still icky in the case where something goes wrong with the browser.

**Comment by andytuba** [comment]
In between Chrome fix and f230a91804362c16af0bdeeca25ccb08203c8ff2, gonna close
