### ISSUE TITLE
Safari instructions need a minor update

### ISSUE THREAD

**Issue by ngyikp** [honestbleeps/Reddit-Enhancement-Suite#2614]
On README.md:

> 4 . It will likely say you cannot install it because no Safari development certificate exists. You will need to visit the [Safari Dev Center](https://developer.apple.com/devcenter/safari/index.action) and create an account (right hand side).
> 5 . You then need to visit the [Safari Developer Program](https://developer.apple.com/programs/safari/) site and sign up for a FREE account.

It's not required anymore on Safari 9, it can auto-generate a certificate if you don't enroll for their US$99 Apple Developer Program, but the extension will be gone when you close Safari.

**Comment by andytuba** [comment]
Could you submit a pull request?  For this kind of change, you could just click the pencil icon in the top right corner of a file and GitHub will automatically fork the repo and make a branch for you when editing the file.
