### ISSUE TITLE
Keyboard nav next sibling always uses "lock to top" scrolling

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2622]
https://www.reddit.com/r/RESissues/comments/40mftf/bug_keyboard_nav_uses_lock_to_top_when_it_should/

(can also confirm this)

For reference, [keyboardNav.js@4.5.4](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/e83e5e0e01ca21e694922e95e2d6413bf32f9257/lib/modules/keyboardNav.js)

**Comment by beck** [comment]
:star:
