### ISSUE TITLE
filtering subreddits shouldn't filter them from multireddits, just /r/all and all-like subs

### ISSUE THREAD

**Issue by honestbleeps** [honestbleeps/Reddit-Enhancement-Suite#2626]
https://www.reddit.com/r/RESissues/comments/40gbte/bug_filters_are_no_longer_working_on_res_460/cyuojps?context=3

**Comment by 13steinj** [comment]
May wanna check /r/mod and /r/contrib. They're "special" multireddits; but I doubt filtering from those would be intentional. (If it happens currently; didn't have the chance to check)

**Comment by andytuba** [comment]
I think this is fixed now by the default option for "filter from".
