### ISSUE TITLE
mediaBrowseMode is always "lock to top" despite selected scrollStyle

### ISSUE THREAD

**Issue by beck** [honestbleeps/Reddit-Enhancement-Suite#2628]
This is especially problematic when using keyboard navigation to hide posts. When you stop on a post, and the previous requests to hide are being executed, the post in view will pop out of frame when the hide requests finish.

Example:
- hide three posts & stop
- post pops out of view

Video: https://dl.dropboxusercontent.com/u/1728414/2015%20RES%20hiding.mov

Before the recent release this was not an issue because `mediaBrowseMode` seemed to abide `scrollStyle` (or at the very least, would not lock to top)

rel: https://www.reddit.com/r/RESissues/comments/40mftf/bug_keyboard_nav_uses_lock_to_top_when_it_should/

**Comment by Ajedi32** [comment]
Possibly related to #2622?

**Comment by andytuba** [comment]
thanks for report!

@Ajedi32 related but slightly different i think.  i messed a lot with scrolling in 4.6.0.

**Comment by erikdesjardins** [comment]
Are you certain that it used to act differently in 4.5.4? In a fresh install of 4.5.4, mediaBrowseMode acts the same way it does now - ignoring scrollStyle and always locking to top when you move down.

It is entirely possible that there's a third setting affecting this, though.

**Comment by beck** [comment]
Installed master, seems to be fixed.  Assuming it was corrected with https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2668

Thanks @erikdesjardins

**Comment by beck** [comment]
There has been some cleanup & refactoring, issue seems to have been re-introduced.

Removing the hardcoded scroll style fixes for me:
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2830

**Comment by larsjohnsen** [comment]
I don't believe this is an issue anymore: `scrollStyle` is only set to `top` if `scrollOnExpando` is enabled https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/218c1bdae2b2595793d209c5ce50933bc5644b53/lib/modules/keyboardNav.js#L806 (the `scrollOnExpando` description should be updated to reflect this).

**Comment by erikdesjardins** [comment]
And #3347 made onHideMoveDown not scroll

**Comment by beck** [comment]
This issue should be reopened as a regression.
Here is a pull to fix: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2628
