### ISSUE TITLE
Live threads unreadable when using Night Mode

### ISSUE THREAD

**Issue by BrettDuclos** [honestbleeps/Reddit-Enhancement-Suite#2631]
When night mode is activated, reddit live threads are unreadable. See the screenshot below.

![image](https://cloud.githubusercontent.com/assets/4016579/12283329/2904357a-b95a-11e5-9e79-da15c099d333.png)

**Comment by andytuba** [comment]
RES v4.6.0, yes?

**Comment by BrettDuclos** [comment]
Sorry about that.

- Night mode: true
- RES Version: 4.5.4
- Browser: Chrome
- Browser Version: 47
- Cookies Enabled: true
- Platform: Windows

**Comment by githue** [comment]
Any particular reason you're using 4.5.4? The recent 4.6 fixed nightmode for Reddit Live and many other often overlooked parts of Reddit.

**Comment by BrettDuclos** [comment]
My mistake guys, thank you for your time.
