### ISSUE TITLE
XKCD Expandos

### ISSUE THREAD

**Issue by Ajedi32** [honestbleeps/Reddit-Enhancement-Suite#2634]
It'd be great if links to XKCD comics were expanded by RES.

Note that I'm currently working on this feature myself.

**Comment by Ajedi32** [comment]
So here's the deal, [XKCD's API](https://xkcd.com/json.html) doesn't send any CORS headers. I'm currently looking at the code that gets around that for Twitter and OneDrive, but those are both the `GENERIC_EXPANDO` type. Any ideas on how to do this with the `IMAGE` expando type?

As I understand it, that whole method for working around a lack of CORS is actually just a big hack right now. Maybe it's time to refactor?

**Comment by erikdesjardins** [comment]
> time to refactor

Coming to a master branch near you...eventually:

![image](https://cloud.githubusercontent.com/assets/7673145/12285078/5959daf2-b984-11e5-982f-f338287aad43.png)

**Comment by Ajedi32** [comment]
:+1: Nice.

Oooh, and we get to use await too? Sweet! :wink:

**Comment by Ajedi32** [comment]
FYI: http://forums.xkcd.com/viewtopic.php?f=10&t=113315

**Comment by andytuba** [comment]
> await

Yep, master has transpilation now :)

**Comment by Ajedi32** [comment]
Are we also transitioning to native Promises instead of the jQuery-based ones I've seen scattered around the codebase? The example media host seems to suggest that we need to return a jQuery promise object from the `handleLink` and `handleInfo` methods, which AFAIK is impossible if we declare them as `async`. (They'll always return a native promise then.)

**Comment by erikdesjardins** [comment]
Yeah, I'm converting everything to native promises. I'm also getting rid of `handleInfo` since it adds pointless boilerplate when you can `await` as many things as you need in `handleLink`.

I'm done almost everything, just need to do a few more things (repenting for my sin of caching to permanent storage, etc.).

**Comment by honestbleeps** [comment]
FWIW, I believe converting to native promises may be the final nail in the coffin for Opera 12 support - and I'm 100% ok with that.  I understand its users are passionate, but there are not enough of them to justify the continued work/maintenance required. It has an IE6-ish level of odd quirks etc.

**Comment by erikdesjardins** [comment]
[He's dead, Jim](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2565)

**Comment by erikdesjardins** [comment]
#2815
