### ISSUE TITLE
Add an option to hide 'subscribe to thread' button

### ISSUE THREAD

**Issue by githue** [honestbleeps/Reddit-Enhancement-Suite#2637]
https://www.reddit.com/r/Enhancement/comments/40r3ku/feature_request_option_to_disable_ability_to/

**Comment by jkcchan** [comment]
I've added a new option showSubscribeButton, with the description: 'Show/hide the comment subscribe button.'

In handleButton(), I check for the option's value, and returns if false.

Let me know if this is not how imagined.
