### ISSUE TITLE
quickMessage "from" field should inherit reddit's native dropdown, doesn't, so it reduces functionality

### ISSUE THREAD

**Issue by honestbleeps** [honestbleeps/Reddit-Enhancement-Suite#2640]
Details here with screenshot:

https://www.reddit.com/r/RESissues/comments/40tnln/bug_res_quick_message_window_doesnt_allow_me_to/

**Comment by andytuba** [comment]
It does this already, there's just something broken with that user's fetching their mod list.

**Comment by honestbleeps** [comment]
ah, whoops. sorry!
