### ISSUE TITLE
"Save options" counterintuitive - Green shouldn't means "Unsaved change"

### ISSUE THREAD

**Issue by matheod** [honestbleeps/Reddit-Enhancement-Suite#2648]
Currently, if there is unsaved changes in options, the "Save options" icon go green.

I found it very counterintuitive, the color should be yellow or orange.

**Comment by andytuba** [comment]
I chose a bright contrasting color to make it colorblind friendly and contrast with the blue. Yellow or orange will probably work.

**Comment by andytuba** [comment]
using orange:

unsaved:
<img width="130" alt="screen shot 2016-01-24 at 11 26 52 am" src="https://cloud.githubusercontent.com/assets/455632/12538385/72733738-c28d-11e5-8a2b-41b28413e171.png">

saved:
<img width="127" alt="screen shot 2016-01-24 at 11 26 59 am" src="https://cloud.githubusercontent.com/assets/455632/12538386/728c2996-c28d-11e5-9d3f-4f437cf130dc.png">

**Comment by matheod** [comment]
Yellow is perfect !

**Comment by andytuba** [comment]
yellow also works pretty well:

<img width="403" alt="screen shot 2016-01-24 at 12 35 31 pm" src="https://cloud.githubusercontent.com/assets/455632/12538762/15e33860-c297-11e5-8481-7ef5080e7f86.png">

![screen shot 2016-01-24 at 11 26 52 amdeut](https://cloud.githubusercontent.com/assets/455632/12538768/1f08fdbc-c297-11e5-8cde-8f34e7d463d7.png)

**Comment by matheod** [comment]
Yellow is good too. As you want :)
