### ISSUE TITLE
Removed comments are not highlighted in pink for mods

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2667]
https://www.reddit.com/r/Enhancement/comments/4226et/noob_mod_and_new_to_res/#!settings/troubleshooter

**Comment by andytuba** [comment]
not a blocker -- can probably address via RESUpdates.css

**Comment by andytuba** [comment]
... this might be fixed?

**Comment by githue** [comment]
Nope, it's broken on child comments. It's an issue with commentBoxes and specificity. Kind of a pain to fix without using a hack like this:

```
.res-commentBoxes .comment.spam { background-image: linear-gradient(hsl(0,70%,80%), hsl(0,70%,80%)); }

.res-nightmode .res-commentBoxes .comment.spam { background-image: linear-gradient(hsl(0,30%,30%), hsl(0,30%,30%)); }
```

**Comment by andytuba** [comment]
Huh, I didn't think the specificity on this changed with 4.6.0.

**Comment by githue** [comment]
I think it's always been that way, could be wrong though.

**Comment by andytuba** [comment]
Should we experiment with removing the `!important` on the `.comment .comment` rules? I could add them back in via RESUpdates.css if a lot of complaints come in.

**Comment by githue** [comment]
```
<githue> removing !important would open a can of worms
<andytuba> like suddenly half of the styled subreddits wouldn't have the zebra striping?
<githue> probably
<githue> some would have background colors appear that they didn't know where there previously
<andytuba> hm yeah
<githue> I think the background-image hack wouldn't be too bad, because it's only on removed comments
<andytuba> yeah it seems like a pr good idea
```
