### ISSUE TITLE
Quick message doesn't decode the title and body

### ISSUE THREAD

**Issue by Farow** [honestbleeps/Reddit-Enhancement-Suite#2673]
A link such as `/message/compose?to=user&subject=a+space&message=in+the+middle` places `a+space` in the title instead of `a space`. Same thing for the body.

**Comment by erikdesjardins** [comment]
It does `decodeURIComponent`, so `%20` will work.

Looks like we'll have to explicitly `replace(/\+/g, ' ')`, since even `decodeURI` doesn't respect that query strings are encoded differently.
