### ISSUE TITLE
Video Expandos do not overlap site bar

### ISSUE THREAD

**Issue by vincchan** [honestbleeps/Reddit-Enhancement-Suite#2677]
When you open the expando of a video, it will not overlap the site bar when the browser window is smaller than usual. Images will overlap the sitebar though

| Video        | Image           | 
| ------------- |:-------------:| 
| <img width="657" alt="screen shot 2016-01-25 at 08 59 18" src="https://cloud.githubusercontent.com/assets/868272/12545439/890de76c-c342-11e5-91f4-98718e619f6a.png">      | <img width="662" alt="screen shot 2016-01-25 at 08 58 51" src="https://cloud.githubusercontent.com/assets/868272/12545440/8c0f3e52-c342-11e5-9e54-6b151ace8ba4.png">|

**Comment by larsjohnsen** [comment]
Fixed.
