### ISSUE TITLE
futurism expando showing first image, not nice summary

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2695]
attn: @dansutera, @mverderese  

https://www.reddit.com/r/RESissues/comments/43aqti/bug_links_to_articles_on_futurismcom_create_an/

Fix needed on RES or futurism.co, or working as expected?

**Comment by jetlej** [comment]
@andytuba - I've made it so the API endpoints returns false on blog post types. Should be fixed now!

Example: https://www.reddit.com/r/Cyberpunk/comments/43ail3/australian_scientists_will_soon_begin_trials_for/

**Comment by andytuba** [comment]
:+1: thanks for tidying that up!
