### ISSUE TITLE
Add link to reddit "preferred comment sort" on comment sort dropdown

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2697]
https://www.reddit.com/r/Enhancement/comments/43f342/feature_request_permanently_override_suggest_sort/czhqmsw?context=3

**Comment by gdtrombetti** [comment]
I will add this link

**Comment by johnnybigoode** [comment]
Heya, I think this is still open? I'd love to take this.

**Comment by andytuba** [comment]
@johnnybigoode  Go for it!

**Comment by johnnybigoode** [comment]
Thank you. I'm still working on it. It's been a crazy week but I'm sure I can do it.

**Comment by radhakri555** [comment]
Can i take up this issue?

**Comment by ofekp** [comment]
@radhakri555 are you on it?

**Comment by andytuba** [comment]
Thanks for adding that to the redesign, @ofekp! 

If anyone still wants to implement this on old.reddit.com, it would be neat for you to extend #4898 with also append the gear link to the legacy frontend's sort menu.
