### ISSUE TITLE
customFilter: if upvoted/downvoted

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2701]
https://www.reddit.com/r/Enhancement/comments/43py1n/is_there_a_way_to_hide_upvoteddownvoted_posts_but/

**Comment by OmgImAlexis** [comment]
I'd like to branch off this and suggest allowing an option to only hide voted posts on the homepage. This would help keep the homepage fresh but still allow the user to see all posts in a subreddit.

**Comment by erikdesjardins** [comment]
@OmgImAlexis since this will be a custom filter you'll be able to combine it with other arbitrarily filters, like "is browsing frontpage".

**Comment by Giljjj** [comment]
In the thing class:
```
thing.entry.classList.contains('unvoted'); // Not voted
thing.entry.classList.contains('likes'); // Upvoted
thing.entry.classList.contains('dislikes'); // Downvoted

```
