### ISSUE TITLE
When Editing Text Posts, the Dialog "Commenting As:" is Shown

### ISSUE THREAD

**Issue by powderblock** [honestbleeps/Reddit-Enhancement-Suite#2708]
When a user edits a text post, the "Commenting As:" Dialog is shown despite the user editing a text POST. Not a COMMENT.

Example:
![](http://i.imgur.com/bG82rXI.png)

![](http://i.imgur.com/w7l6NNs.png)

I believe this has to do with this code found in /lib/css/modules/_commentTools.scss on lines 122-138.

```
// "Commenting as"
.commentingAs {
	clear: left;
	margin-top: 10px;
	margin-bottom: 3px;

	a.userTagLink {
		cursor: default;
		display: inline;
	}
}

.res-commentTools-macroButtons {
	.commentingAs {
		float: left;
	}
}
```

One way to fix this might be by adding some condition to check whether the user is editing a comment or editing a post. Depending on this condition, a different dialogue would be triggered.

**Comment by andytuba** [comment]
Alternatively, just change the text to "Submitting as:"
