### ISSUE TITLE
presets.cleanSlate should show prompt("Reload?") instead of notification

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2711]

**Comment by mtblanton** [comment]
I'm working on this. I have the confim working, but I'm not getting anything from option.description to put into the prompt. This is making the "Applied Preset:" part of the prompt not show anything. Is this a known issue, or should I file a new one?

**Comment by andytuba** [comment]
How are you loading in the description? Maybe call `i18n("theDescriptionValue")`

**Comment by mtblanton** [comment]
I'm not loading it in at all, confirmPreset is getting called with what I think is a malformed option. I couldn't figure out where the callback was being called from. Do you know where it's being called from? I think if I knew that I may be able to track this down.

Here's my modified code along with the param values at the top.
![image](https://user-images.githubusercontent.com/2118649/31873047-4eedebf6-b786-11e7-8b6d-144555d7299f.png)

Also, I realized I didn't mention that it wasn't working with a clean repo as well. I tested with release and the master branch and was getting the same issue. Here it is on the release version:

![image](https://user-images.githubusercontent.com/2118649/31873321-1544d6ce-b788-11e7-9701-6a134ba4fdd0.png)
