### ISSUE TITLE
Inputting  code into a text comment on reddit not working?

### ISSUE THREAD

**Issue by ZongMan** [honestbleeps/Reddit-Enhancement-Suite#2715]
What is the syntax for Inputting  code into a text comment on reddit and for me its not working. When i type say this sentence and then go to input code on the end of it, i click on the code button but my whole sentence turns into a string of code now I'm not sure if it does that by default but its quite annoying also is it a problem or bug

**Comment by ZongMan** [comment]
i figured it out ima dummy lol can a mod delete this post , what it was is the tilde key is what starts the code line and hitting the tilde key again inputs and makes the code appear. `like this`

**Comment by andytuba** [comment]
FYI ` a is "backtick", ~ is a tilda.
