### ISSUE TITLE
Any interest in feature for filtering reddit saved page by subreddit?

### ISSUE THREAD

**Issue by chrisshroba** [honestbleeps/Reddit-Enhancement-Suite#2723]
I'm proposing a feature where a user can filter his/her `https://www.reddit.com/user/<username>/saved/` page by subreddit, to be able to see only posts saved from a particular subreddit, such as /r/gifrecipes or /r/funny.  If there's interest, I'll look into implementing!

**Comment by andytuba** [comment]
Since this is already a feature of reddit gold, it's inappropriate for RES.

However, it would be useful to add "when browsing saved page" or "when browsing saved page for /u/[optional]"  as a criteron to filteReddit customFilters.

**Comment by andytuba** [comment]
I think @larsjohnsen has handled this in filterline?
