### ISSUE TITLE
mediaBrowseMode breaks when Never Ending Reddit loads next page

### ISSUE THREAD

**Issue by esjay** [honestbleeps/Reddit-Enhancement-Suite#2724]
This may be related to #2302, but I don't tend to use the "View all" button. To reproduce this bug:

1. Ensure Keyboard Navigation > `mediaBrowseMode` and Never Ending Reddit > `autoLoad` are both enabled.
2. Load up any list of posts with [lots of images](https://www.reddit.com/r/images) (this happens with any expandable media)
3. Give focus to the top list item
4. Press X to expand the image/media attached
5. Press J once to verify that `mediaBrowseMode` expands the image for the next post
6. Hold down the J key until Never Ending Reddit loads the next page of posts

If the timing works out, the next page will load but the images will cease expanding on the next page.

This may be due to a race condition, because some scenarios carry the media expansion into the next page. I see this with normal usage (i.e. not when holding the J key down), which may come down to images that affect RES detecting a bottom edge for scrolling, loading that next page of posts, and immediately giving focus to the next list item before the attached media can be detected. By the time the media is detected, the focus was already granted to the list item so the `mediaBrowseMode` check has already occurred.

**Comment by esjay** [comment]
Relevant code seems to be here:
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/3e6b8ef8ca22f20625f59b785424881591688e8f/lib/modules/keyboardNav.js#L871-L902

**Comment by larsjohnsen** [comment]
Confirmed. Seems like it tries to open the expando before it is ready.
