### ISSUE TITLE
Match RESUtils.regexes against location.pathname instead of the full URL

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2726]
(Since it doesn't seem like any of them depend on the subdomain.)

This'll be cleaner and easier to run on a local reddit instance. ([via](https://www.reddit.com/r/Enhancement/comments/46j9zk/can_i_use_res_with_a_local_reddit_installation/))

**Comment by andytuba** [comment]
Oops.
