### ISSUE TITLE
gomode should leave noparticipation

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2731]

**Comment by bartnic1** [comment]
Hello, I'm new to making contributions and wanted to take this issue on as for my first pull request; with your permission I'd like to work on it. Is there anything I should know as a new contributor? I've read the contributing.md document and I have experience with github.

Thanks!

**Comment by andytuba** [comment]
Go for it!

Make sure to run linting and functional tests, or at least check for a red X / green checkmark on your PR a few minutes after submitting it.

**Comment by andytuba** [comment]
(it may help to run the automatic lint fix before pushing)
