### ISSUE TITLE
Make it more obvious that go-mode shortcuts require go-mode

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2733]
e.g. nextPage and prevPage

https://www.reddit.com/r/RESissues/comments/47fsdl/bug_using_n_or_p_doesnt_change_the_page/

**Comment by andytuba** [comment]
:+1:

**Comment by andytuba** [comment]
i've seen at least one other thread in the last 6mo where somebody didn't get goMode.

**Comment by erikdesjardins** [comment]
https://www.reddit.com/r/RESissues/comments/4opt9t/bug_f_key_not_working/
