### ISSUE TITLE
Spotify expandos

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2737]
https://www.reddit.com/r/Enhancement/comments/47w81c/feature_request_embed_spotify_tracks_and_playlists/

Matching urls:

https://open.spotify.com/track/4nMmJoCZoUHsON1yQzl92c
https://play.spotify.com/track/3xkTanhgzQT9tj7Quhkq8n
spotify:track:4nMmJoCZoUHsON1yQzl92c

(although the latter is not a valid link on reddit)

https://developer.spotify.com/technologies/widgets/spotify-play-button/

Should be doable with a fairly straightforward iframe expando, with

`src="https://embed.spotify.com/?uri=spotify:track:4th1RQAelzqgY7wL53UGQt" width="300" height="380"`

**Comment by anhallbe** [comment]
So a big problem with the embedded "Play Button" is that it doesn't have an embedded music player. It just controls an existing one (for instance a native client, or another browser tab).

There is no real API to control playback either. I still think it would be neat to have, even though it would lack some features.

**Comment by erikdesjardins** [comment]
Hmmm, that's unfortunate.

>I still think it would be neat to have

Yeah, it should work well enough :+1:

**Comment by erikdesjardins** [comment]
#2822
