### ISSUE TITLE
Chrome 49 broke RES configuration

### ISSUE THREAD

**Issue by wickles** [honestbleeps/Reddit-Enhancement-Suite#2749]
Just got updated to chrome 49 and my RES configuration broke. My settings were wiped and it kept showing me the "What's new" page, which mentioned I should try uninstalling RES, restarting Chrome, and reinstalling RES. That didn't work, so I had to just reconfigure RES on both my computers.

**Comment by mc10** [comment]
Yeah, RES settings randomly disappear at times during upgrades, so the best bet is always [backing up settings](https://www.reddit.com/r/Enhancement/wiki/backing_up_res_settings). I don't think this is reproducible, so I'll close for now, but feel free to reopen if you run into the issue consistently.

**Comment by wickles** [comment]
It keeps breaking on my mac system.
