### ISSUE TITLE
Issue with custom filters by score

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2751]
https://www.reddit.com/r/Enhancement/comments/48t6bx/activate_custom_filters/

    {"note":"+100","ver":1,"body":{"type":"group","op":"all","of":[{"type":"subreddit","patt":"talesfromtechsupport"},{"type":"score","op":">","val":"100"}]}}

Doesn't seem to work with any combination of "browsing subreddit" and "posted to subreddit".
I suspect that the problem lies in `RESUtils.thing::getScore`.

**Comment by erikdesjardins** [comment]
I think [this line](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/a9c8db88af4d5f76bbce632d69c6edee9a47c1bb/lib/core/utils.js#L537) should start with `this.thing` instead of `this.entry`.

I'll probably fix this tonight if nobody gets to it first.

**Comment by andytuba** [comment]
I think you're right.

I won't get to it until Saturday morning, so if you PR first :+1:
