### ISSUE TITLE
Firefox 47 will change the signature of nsICookieManager::remove()

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2779]
Which breaks account switcher (I haven't confirmed this): https://www.reddit.com/r/RESissues/comments/4acp34/bug_user_account_switcher_doesnt_work_in_firefox/

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager

Looks like they casually [added a new parameter](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager$compare?to=1028184&from=740059) to the middle of the list (!) last month.

**Comment by andytuba** [comment]
What the heck is it supposed to be. seems like passing in an extra false works.

**Comment by andytuba** [comment]
Closing, but 34a323b will need to be merged to master.

**Comment by erikdesjardins** [comment]
It will be done.
