### ISSUE TITLE
Support Imgur edited images

### ISSUE THREAD

**Issue by benwa** [honestbleeps/Reddit-Enhancement-Suite#2784]
In Imgur, you can edit an uploaded picture.  The new URL appends an integer parameter for what version of the image to serve.
For example, the original: http://i.imgur.com/vnQle7X.png and the edited: http://i.imgur.com/vnQle7X.png?1
RES will always expando the original version.

**Comment by erikdesjardins** [comment]
That param is just a cache buster, it doesn't do anything aside from making the URL look different. (i.e. both of the links you posted are the same image for me)

If you clear your cache, the expando will show the edited image.

**Comment by benwa** [comment]
Oh you're absolutely correct, my mistake!

**Comment by andytuba** [comment]
Looks like the imgur API doesn't provide `edited` metadata either.
