### ISSUE TITLE
flickr site module should support fli.ckr shortlinks 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2785]
https://www.reddit.com/r/RESissues/comments/4aprh3/bug_flickr_shortened_urls_do_not_trigger_the/

**Comment by Saturate** [comment]
This issue is linked with https://github.com/leedo/noembed/issues/60. It's possible to make a workaround, until it's supported.

**Comment by Saturate** [comment]
I'll do this later! :-) Should be a quick fix.
