### ISSUE TITLE
Nightmode filtered expando buttons.. some sort of compromise?

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2787]
https://www.reddit.com/r/RESissues/comments/4aqjio/bug_nightmode_expandos_are_white_instead_of/

4.6.2 is a proxy for "hotfix via updates.css"

@githue ideas?

**Comment by githue** [comment]
I have two ideas:

1. Expand the existing RES spritesheet by adding nightmode versions of the expandos. This will be necessary when Reddit updates their icons anyway. Will cause conflict with custom stylesheets.
2. Reduce the icon opacity further with something like `.res-nightmode .expando-button:not(:hover) { opacity: .5; }`. It's currently 0.8, which is better than 1.0. (The hover state is hard to read with reduced opacity.)

**Comment by erikdesjardins** [comment]
Related #2630

**Comment by andytuba** [comment]
This seems fixed for upcoming release.
