### ISSUE TITLE
Regression: unable to drag to resize the player size any more for Oddshot.tv expando after 4.6.1

### ISSUE THREAD

**Issue by fireattack** [honestbleeps/Reddit-Enhancement-Suite#2791]

**Comment by thybag** [comment]
Hello,

I believe the Oddshot emebed was [updated to use it's own player via an iframe](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2652). Unfortunately re-sizing can only be supported for videos & images that are embedded directly.

**Comment by fireattack** [comment]
Thanks. Is it possible to customize the size of said iframe? To be honest, the default size it way to small for video streams to be useful.

**Comment by erikdesjardins** [comment]
#3533
