### ISSUE TITLE
Never ending load event dispatch was renamed

### ISSUE THREAD

**Issue by ryan-nauman** [honestbleeps/Reddit-Enhancement-Suite#2792]
I don't think that this was on purpose. I'll change my script to listen for both event names...

https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/d4a9ea732ad40adc424467360f456a8e1403971e#diff-b5b236fa347169a5226fe818517af203

**Comment by erikdesjardins** [comment]
PR in question: #2690

Whoops, that was a code-review fail. Let's fix that up.
