### ISSUE TITLE
Cmd-Click on "x comments" links doesn't open link in new tab

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#2795]
Not sure if this is a regression in Reddit or RES, but Cmd-clicking on any of these "x comments" links for any post opens the comments page in the *current* tab instead of a *new* tab. I don't think I've run into this issue for any other link though. Tested on v4.6.1 for Firefox and Chrome.

**Comment by nothingrandom** [comment]
Running OS X El Captain, 10.11.3. Google Chrome 49.0.2623.87. RES 4.6.1

Cannot replicate.

**Comment by mc10** [comment]
Huh, odd, it started working again. Gonna close unless I can re-replicate.

**Comment by mc10** [comment]
For anybody who was interested in the cause: [r/bugs: Comments no longer opening in a new tab](https://www.reddit.com/r/bugs/comments/4auxjw/comments_no_longer_opening_in_a_new_tab/).
