### ISSUE TITLE
Add settings gear link to appropriate modules on /r/dashboard tabs

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2803]
maybe with an option to turn them off :P

**Comment by jkcchan** [comment]
I will take a look at this.

**Comment by andytuba** [comment]
Neato!  I was thinking of attaching them to the tabs, or somewhere in the title for the tab contents. What ideas do you have?

**Comment by dhensche** [comment]
@jkcchan have you done any work on this? If not, I can look into it. Is the request to add the settings gear/link to the tabs under the Dashboard link (My Dashboard, My User Tags, etc) if there are options for the tab/module?

**Comment by andytuba** [comment]
Sounds like you've got the gist of it, @dhensche .
