### ISSUE TITLE
Firefox 47 high CPU usage

### ISSUE THREAD

**Issue by Tajnymag** [honestbleeps/Reddit-Enhancement-Suite#2806]
I know that you can't support every nightly but I this problem persists for me for some time already. When I browse Reddit with images opened, the CPU maxes its load up to 100%. Sometimes this happens even with images collapsed. I've tried disabling every other addon but the problem seems to be tied only with RES.

I'm using:
- Firefox 47.0a2
- W10 x64
- 8 GB RAM
- i5 6200u

**Comment by mc10** [comment]
Closing for now, as this is pretty old; if this is still a problem, feel free to open a new issue.
