### ISSUE TITLE
The keyboard navigation help popover should respect night mode

### ISSUE THREAD

**Issue by baronfel** [honestbleeps/Reddit-Enhancement-Suite#2817]
Hi!  First off, thanks for this amazing utility.

I got a popup explaining that there was a helpful keyboard nav modal that I could launch, so I did and discovered that there didn't seem to be a night mode on it.  This was especially apparent because I pretty much only browse with night mode + no subreddit styles.

![image](https://cloud.githubusercontent.com/assets/573979/14031609/8da7a4ee-f1db-11e5-94ed-82ef7c4a26b7.png)

Would it be possible to hook this modal into whatever css toggle there is for the main view?

**Comment by honestbleeps** [comment]
how embarrassing, thanks for the report!

this is a result of us not adding night mode styles for the popup, totally our bad... we'll fix soon!
