### ISSUE TITLE
Vote counters don't work on inbox page

### ISSUE THREAD

**Issue by withmorten** [honestbleeps/Reddit-Enhancement-Suite#2838]
Pretty straightforward.

Ever since reddit broke the vote counters initially back then, vote counters didn't work at all. Fixed for the most part, but on inbox comments on [inbox](https://www.reddit.com/message/inbox/) links it still doesn't work.

Noticed this a lot, but never got around to reporting it. If this is a dupe, let me know. Wouldn't know how to search for it within all the general vote counters don't work reports.

Don't know how to debug this, sorry :)

**Comment by andytuba** [comment]
C'mon, withmorten, you should know to report which browser version and RES version you're using!

It should be fixed in RES v4.6.1.

**Comment by withmorten** [comment]
Wow, sorry for forgetting about this so long. I'm not sure how I missed your reply - and why I wasn't on 4.6.1. (I was on 4.6.0 it seems). It works on 4.6.1. The bug existed for so long (even in dev builds where vote counters worked again partially) I thought you guys missed it.

Next time I'll make sure to check my RES version number first!
