### ISSUE TITLE
Use the customFilters "engine" to run regular filters

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2839]
Having two different code paths to filter by subreddit, keywords, etc. is redundant.

**Comment by dhensche** [comment]
Is anyone working on this? If not, I have some time to look into it

**Comment by erikdesjardins** [comment]
#3042 _may_ do this (@larsjohnsen ?); either way we should probably wait for that to be merged cause it'll cause conflicts

**Comment by dhensche** [comment]
looks like that was merged in but I still see separate filtering logic for the "basic" filters. I've got a little something that transforms the basic filters into something the 'filter engine' can use
