### ISSUE TITLE
Firefox stops responding for a few seconds when opening new tab on reddit with RES

### ISSUE THREAD

**Issue by MySelfLuls** [honestbleeps/Reddit-Enhancement-Suite#2850]
Hello,

I've tried reinstalling firefox, updated RES and nothing works.
It only happens on reddit and it is the same error every time.

[Warning: Unresponsive Script](http://ss.myselfluls.xyz/hjxnckaUv.png)
[Debugging](http://ss.myselfluls.xyz/R8UsH57Uw.png)
[Troubleshooting information](http://ss.myselfluls.xyz/KOcM0CIWy.txt)

Please tell me if you require more information related to this issue.
Thank you in advance.

**Comment by erikdesjardins** [comment]
Caused by Dashlane: https://www.reddit.com/r/firefox/comments/3yzns6/temporary_hangs_on_scriptskwiftffjetpackminjs1/d0zhgv0

I'll add it to the [known extension conflicts](https://www.reddit.com/r/RESissues/wiki/knownissues#wiki_extension_conflicts).
