### ISSUE TITLE
Most self text expandos (tumblr, wikipedia) are very hard to differentiate from actual comment text

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2859]
In a post, a Wikipedia expando looks really good:

https://www.allthefoxes.me/img/04/s-04-94d9.png

In the comments, it looks much worse:

https://www.allthefoxes.me/img/04/s-04-3ae9.png

A border would be a really, really good idea.

**Comment by Ajedi32** [comment]
This was resolved by #2859, correct?

**Comment by erikdesjardins** [comment]
Yeah, #2871
