### ISSUE TITLE
showimages should Ignore redditmetrics 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2862]
https://www.reddit.com/r/RESissues/comments/4djadt/bug_image_expandos_are_triggered_by_url_that/

**Comment by larsjohnsen** [comment]
Fixed by https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3149/commits/cd37e0a9cbe8328cc45a0ea59eea30ebdfea32d1 since `hosts.default.detect` now tests `pathname` (which doesn't include anything after `?`) instead of `href`.
