### ISSUE TITLE
Account switcher dropdown broken - Edge

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#2863]
Accounts are listed but are not selectable and does not show karma.

Build 4.6.1 Affected

**Comment by andytuba** [comment]
https://www.reddit.com/r/RESissues/comments/4dj0a7/bug_account_switcher_drop_down_not_working_on_edge/

**Comment by andytuba** [comment]
Ben reports unchanged in Win10 14316

**Comment by BenMcGarry** [comment]
Line 337 of accountSwitcher.js. Caught in the block.

**Comment by BenMcGarry** [comment]
Appears to be a browser issue at this stage, problem talking to the API. Need further investigation.

**Comment by BenMcGarry** [comment]
Issue raised. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7477886/

**Comment by BenMcGarry** [comment]
Fixed, awaiting build.

**Comment by BenMcGarry** [comment]
Issue resolved in [14361](https://blogs.windows.com/windowsexperience/2016/06/08/announcing-windows-10-insider-preview-build-14361/). Closed.
