### ISSUE TITLE
Name of backup on download not working - Edge

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#2864]
Backup of RES settings unresponsive, restore working as intended.

Build 4.6.1 affected.

**Comment by andytuba** [comment]
Ben reports unchanged in Win10 14316

**Comment by BenMcGarry** [comment]
Line 30 backupAndRestore.js - Invalid Calling Object

**Comment by BenMcGarry** [comment]
`link.href = URL.createObjectURL(blob);` << Invalid calling Object

**Comment by BenMcGarry** [comment]
Appears to be a browser issue at this stage, problem with creating blobs. Issues existed in IE10+ with a similar MO to ours.

**Comment by BenMcGarry** [comment]
https://msdn.microsoft.com/en-us/library/hh779016(v=vs.85).aspx

**Comment by andytuba** [comment]
Abstracting "URL.createObjectURL / Blob" with different strategies for Edge vs Everyone Else could be a good reason to justify browsersupport-edge.js.

**Comment by erikdesjardins** [comment]
For sure, but we should probably figure out the root cause first -- `new Blob()` and `URL.createObjectURL()` work fine in [a codepen](http://codepen.io/anon/pen/XdZdwY) in Edge.
(for a certain definition of "fine" - it completely ignores the `download` attribute and gives the file a horrible opaque name)

**Comment by BenMcGarry** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/backupAndRestore.js#L36

Invalid Calling Object

**Comment by erikdesjardins** [comment]
To add on - the function linked above can be reduced to:
```js
function backup() {
	const blob = new Blob(['something something']);
	const link = document.createElement('a');
	link.href = URL.createObjectURL(blob);
	RESUtils.click(link);
}
```
and it errors in the same way.

**Comment by andytuba** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7187326/

**Comment by BenMcGarry** [comment]
Issue confirmed with Edge, fix in progress. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7187326/

**Comment by BenMcGarry** [comment]
In code review.

**Comment by BenMcGarry** [comment]
Issue marked as fix in Edge, will test when available in next build.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7187326/

**Comment by BenMcGarry** [comment]
In build 14342 backup is now functional, but it does not name the file correctly. It gives a name such as "B1BBD615-8FF5-498E-9217-3FB0AC44CB08". The downloaded file does have the settings contained. It is just the name.

**Comment by BenMcGarry** [comment]
Workaround:

1. Save the blob file.
2. Rename it in file explorer as well as the file extension to "RES.resbackup"

**Comment by BenMcGarry** [comment]
Issue resolved in 14971. Closed.
