### ISSUE TITLE
New Comment Count shows up repeatedly with bad data

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2867]
https://i.imgur.com/LiHZgp8.png

happens sporadically to my work laptop running v4.7.0 commit c2f6efcff4bbce1da703635949987bb07abad2f7

**Comment by allthefoxes** [comment]
To reproduce

1. Visit a comment thread
2. Leave and come back when there are new comments highlighted
3. Expand a "show more comments"
4. Profit
5. Repeat as desired until you reach infinity

---

Images:

https://www.allthefoxes.me/res/bugdir/infinite/step1.png - something with new comments
https://www.allthefoxes.me/res/bugdir/infinite/step2.png - Click a "load more comments"
https://www.allthefoxes.me/res/bugdir/infinite/step3.png - Results
https://www.allthefoxes.me/res/bugdir/infinite/step4.png - Repeated a few more times
https://www.allthefoxes.me/res/bugdir/infinite/infinite.png - Infinity

As the official bug namer, I declare this bug "4.7 Infinity"

**Comment by thybag** [comment]
Going to have a dig at this one
