### ISSUE TITLE
Under certain configuration, "enter" opens links twice on comment pages

### ISSUE THREAD

**Issue by stevenhoward** [honestbleeps/Reddit-Enhancement-Suite#2879]
Problem: 
---

Under specific configurations, pressing 'enter' from the comments page will open it both in the current tab and in a new tab.

Version:
---

RES 4.6.1
Firefox 45.0.2

Repro steps:
---

1. Open RES keyboard navigation settings.
2. Set "followLink" to "shift+enter".
3. Set "followLinkNewTab" to "enter".
4. Set "toggleChildren" to "enter". (this is the default)
5. Visit any non-self post comments page (e.g. [this one](https://www.reddit.com/r/CFB/comments/4ee14v/hamfisted_satellite_camp_ban_creates_unintended/))
6. With the link selected as the active keyboard navigation element, hit "enter".

**Expected result**: Link opens either in new tab (preferable) or same tab, but not both
**Actual result**: Link opens in both original tab and new tab

Cause
---

There are two places where the code special-cases links on the comments page.

In [followLinkNewTab](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/keyboardNav.js#L194):

	if (!RESUtils.isPageType('comments') || selected.thing.classList.contains('link')) {`

In [toggleChildren](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/keyboardNav.js#L1010)

	if (selected.thing.classList.contains('link')) {
		// Ahh, we're not in a comment, but in the main story... that key should follow the link.

The toggleChildren case appears to be the less correct of the two; in my opinion it should do nothing if the active thing is a link and defer to other key bindings that can respect user configuration.

**Comment by andytuba** [comment]
:+1: excellent bug report

**Comment by erikdesjardins** [comment]
10/10 would fix again. Thanks!
