### ISSUE TITLE
Attempting to change volume results in video resizing - Edge

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#2887]
Trying to change volume on a intergrated video results in the video being expanded in size instead of volume changing.

Exists in 4.7.0 14316

https://www.reddit.com/r/RESissues/comments/4emddq/bug_adjusting_volume_for_native_html5_video_in/

**Comment by andytuba** [comment]
I wonder if one of @larsjohnsen's PRs already addresses this.
