### ISSUE TITLE
Reports are unreadable in nightmode

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#2889]
https://www.reddit.com/r/RESissues/comments/4epnqk/expanded_reports_in_night_mode_are_unreadable/

Test post: https://www.reddit.com/r/restests/comments/4c2xt6/icons_and_badges/

@andytuba hotfix?

**Comment by andytuba** [comment]
hotfix++

**Comment by githue** [comment]
See hotfix-data.
