### ISSUE TITLE
NER Pause and to top button overlaps cog - Edge

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#2907]
https://i.imgur.com/5i5ZlLy.png

**Comment by andytuba** [comment]
blame either https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/c2dc7f1494e0a5d18bb4078bf9963857d51586f1/lib/modules/floater.js#L37 or https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/c2dc7f1494e0a5d18bb4078bf9963857d51586f1/lib/modules/floater.js#L43

**Comment by BenMcGarry** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/47fa261388c25d3132580143ee9ca139f345fb49/lib/core/templates.html#L445

Removing this line solves issue.

**Comment by BenMcGarry** [comment]
Fix tested in chrome and edge. Confirmed fix with no defects.

**Comment by andytuba** [comment]
Does it work on heavily styled subreddits eg /r/Naut?  I guess it'll be generally okay since that container element is at the end of the DOM and it's unlikely there will be a high z-index on any earlier sibling elements

**Comment by BenMcGarry** [comment]
Appears to be hidden behind images on Naut at the top due to the high z-index setting.

**Comment by andytuba** [comment]
This will forever be a whackamole game until we fix the root cause: determining why floater.js doesn't hide that element initially or onscroll.

**Comment by BenMcGarry** [comment]
z-index 101 makes it work on naut with no overlaps. Is there any reason why changing the z-index would solve it?

**Comment by gavin19** [comment]
When does this happen for you? On page load, or after scrolling down/back up?

If it's the former, it seems like it would suffice to set the default CSS to `display: none;` since `toggle(show)` will handle the show/hide anyway. No?

**Comment by BenMcGarry** [comment]
The cog overlapping? 100% of the time on edge with current 4.7 master.

**Comment by BenMcGarry** [comment]
Since webpack changes the pause button now doesn't show at all.

**Comment by BenMcGarry** [comment]
Issue resolved in eb34e08b4bdb76c35518a660443e57e67b380493. Closed.
