### ISSUE TITLE
Add class to post .thing for subreddit/author

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2960]
Use the same classnames as subreddit/userpage body class.  Of course, add an option to disable it.  Put it in the Stylesheets module

https://www.reddit.com/r/Enhancement/comments/4ihwzo/can_snippets_work_on_your_personal_front_page/d2zhgfp?context=5

**Comment by erikdesjardins** [comment]
Reddit already does this :P

![image](https://cloud.githubusercontent.com/assets/7673145/15154670/c29814e0-16ac-11e6-9d8c-e5a34964f613.png)

**Comment by andytuba** [comment]
oh lol i glazed right over that. thanks.
