### ISSUE TITLE
"open links in comments in new tabs" should ignore {currenturl}#!settings URLs

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#2968]

**Comment by Princesseuh** [comment]
If this is still relevant

Should it ignore every settings URLs (in which case maybe we can simply use [isSettingsUrl](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/ed8c3e497bf73f66634dc4cc528799033ffb88cf/lib/modules/settingsNavigation.js#L102-L104)) or just URL to the current page#!settings? 

For example would the url https://www.reddit.com/#!settings/search be opened in a new tab if it were posted in a comment? (AutoMod does this in /r/Enhancement)

**Comment by larsjohnsen** [comment]
I believe it is desirable to ignore all links which only changes the hash (either `Element.getAttribute('href').startsWith('#')` or `URL.pathname`, `URL.origin`, `URL.search` matches `location`).
