### ISSUE TITLE
Key navigation broken after opening comments by mouse click

### ISSUE THREAD

**Issue by larsjohnsen** [honestbleeps/Reddit-Enhancement-Suite#2976]
Browser: Chrome 50
Master branch

After clicking (open in new tab / middle click) on the comments link `a.bylink.comments.may-blank`, `document.activeElement` will point to that anchor. `handleKeyPresses` https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/keyboardNav.js#L783 only accepts keypresses when `document.activeElement` is `body`.

**Comment by erikdesjardins** [comment]
Can confirm this.
