### ISSUE TITLE
.RES-keyNav-* styles cannot be overriden

### ISSUE THREAD

**Issue by RomanHargrave** [honestbleeps/Reddit-Enhancement-Suite#2978]
I'm putting together a sub style that uses a dark theme. I was testing without nightmode and noticed that I cannot set a background color for the keyNav bits, which results in ugly white boxes around the active keyNav item.

**Comment by RomanHargrave** [comment]
This likely has something to do with the fact that RES places the inline styles for keyNav and whatnot _after_ the subreddit style.

**Comment by erikdesjardins** [comment]
They most certainly can be. You just need more [specificity](https://developer.mozilla.org/en/docs/Web/CSS/Specificity).

Simply appending `.res` to the selector (and using `!important`, of course) will do it. (see [/r/erikdesjardinstest](https://www.reddit.com/r/erikdesjardinstest/))
