### ISSUE TITLE
Request: sli.mg inline image support

### ISSUE THREAD

**Issue by alexchandel** [honestbleeps/Reddit-Enhancement-Suite#2979]
sli.mg seems to be an up-and-coming imgur replacement, and I see more and more posts every day that use it. While RES of course expands directly linked images, posts that link only to an image's page ([example of such a URL](https://sli.mg/e2bZC9)) aren't expanded. Can this support be added?

**Comment by mc10** [comment]
Closing, as sli.mg is down.
