### ISSUE TITLE
giphy host should use giphy api and support long url

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3005]
https://github.com/Giphy/GiphyAPI#get-gif-by-id-endpoint

because the direct urls are prone to change

http://giphy.com/gifs/screamqueens-emma-roberts-scream-queens-chanel-oberlin-3o85xCu8FfNyWoXYQg

**Comment by dhensche** [comment]
I don't have any experience with the giphy api, but am looking to get involved a little bit more with RES. It appears we'll need to get an api key to use their api, is there any standard practice around this? It also appears their api provides a multitude of sizes/options for the actual media URL, any preferences?

If I'm out of my element, just let me know haha

**Comment by dhensche** [comment]
I have a mock up using the demo key they provide, but not 100% sure how to test it for non-html5 links (those seem to be being handled by some other host mechanism?). The html5 links are working just fine 

```{javascript}
import { ajax } from '../../environment';

export default {
	moduleID: 'giphy',
	name: 'giphy',
	domains: ['giphy.com'],
	logo: '//giphy.com/static/img/favicon.png',
	detect: ({ pathname }) => (/^\/gifs\/(?:\w+-)*(.*?)(\/html5)?$/i).exec(pathname),
	async handleLink(href, [, id, isHtml5]) {
		const { data } = await ajax({
			url: `http://api.giphy.com/v1/gifs/${id}?api_key=dc6zaTOxFJmzC`,
			type: 'json',
		});

		if (isHtml5) {
			return {
				type: 'VIDEO',
				controls: false,
				fallback: data.images.original.url,
				loop: true,
				muted: true,
				sources: [{
					source: data.images.original.mp4,
					type: 'video/mp4',
				}],
			};
		} else {
			// gif
			return {
				type: 'IMAGE',
				src: data.images.original.url,
			};
		}
	},
};
```

**Comment by dhensche** [comment]
@andytuba should I move forward with getting a production giphy api key for RES? I have put one of their [required attribution logos](https://github.com/Giphy/GiphyAPI#request-a-production-key) up on imgur and updated the logo for the giphy host to point to it


![screen shot 2016-10-20 at 10 44 14 am](https://cloud.githubusercontent.com/assets/387763/19567133/5c2b1cda-96b2-11e6-9069-0c218f951e7c.png)

**Comment by andytuba** [comment]
It sounds like we won't need to switch to a production key. On the API key request form, I see a note:

> If your app is a form of a bot (ie. hubot), for internal purposes, open source, or for a class project, we highly recommend you institute the beta key for your app. Unless you're making thousands of requests per IP, you shouldn't have any issues.

**Comment by andytuba** [comment]
Let's store the "powered by giphy" image inside RES itself, instead of pulling from imgur.

**Comment by dhensche** [comment]
I read that part of the docs, but I guess I missed the part about open source projects. I'll put a copy of the image in the project itself (I was just unsure how to reference it in the host js file because all the other hosts seemed to link to external images)

**Comment by erikdesjardins** [comment]
You can put the image in `lib/vendor` (perhaps `lib/vendor/images`) and then import it with:

```js
import logo from 'url!../../vendor/whateverItsNameIs.png';
```

and use `logo` in place of the existing logo URL.

**Comment by dhensche** [comment]
hmm, for some reason it doesn't seem to be getting the correctly base64 encoded data to put in the img tag. I've manually encoded it using https://www.base64-image.de/ and end up with a different value than what is being imported, which results in the image not appearing. Any ideas?

**Comment by dhensche** [comment]
Okay, so I figured out (webpack stuff is pretty fresh for me) what that the `url!` was overriding the default configured loader. If I put the image in `lib/images/hosts` and don't override the loader, the url loader configured for that path loads the image just fine. If I put the image in `lib/vendor/images` the configured loader is the file loader, which does not create the data url.

**Comment by erikdesjardins** [comment]
Ah, right, sorry, what you actually need is `import logo from '!url!../../vendor/whateverItsNameIs.png';` (extra `!` before `url`).

We do want the loader specified in the import to override the loader configured in `webpack.config.js`, but (confusingly) that's not the default. So what you were getting was the JS file exporting the filename base64'd.

Putting it in `lib/images` is fine too though.

**Comment by timfrietas** [comment]
Hey All,

Tim From Giphy here.  Whether or not you need a production key or not depends on how RES works.  The beta key has a limit of 1000 requests a day per IP address.  If RES requests are being made by each individual client, then the beta key is fine.  Also, if you plan to have the API key visible in the source code for this project, the beta key is the best choice.

However, if RES requests to the Giphy API are centralized through a small fleet of servers then you'll probably want a production key and to keep the key out of the source code and store it server-side.

Hope this helps!

**Comment by erikdesjardins** [comment]
Yep, requests will be made by each client, so we'll stick with the beta key.

Thanks for the info!
