### ISSUE TITLE
findAllImages happens before initObservers

### ISSUE THREAD

**Issue by larsjohnsen** [honestbleeps/Reddit-Enhancement-Suite#3009]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/showImages.js#L352
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/utils/watchers.js#L30
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/core/init.js#L172

Seems that `go` (and within it `findAllImages`) in `showImages` is run before `initObservers`, so elements added in the meanwhile is not captured by the watchers.

A solution could be to run `findAllImages` very early on, at least on linklist pages, so that expandos quickly becomes available, and then later rerun it when the page is ready.

**Comment by erikdesjardins** [comment]
This might be intentional: the selftext watcher is only supposed to pick up native self post text expandos, not showImages text expandos, AFAIK.

**Comment by larsjohnsen** [comment]
To reproduce the issue, set links per page to 10 (or something small enough that NER triggers without scrolling). Depending on if the next page is loaded before `bodyReady` (I assume; this issue happens fairly seldom), the new links won't get picked up.
