### ISSUE TITLE
Mark Reddit expandos visited when expanded 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3014]
https://www.reddit.com/r/Enhancement/comments/4l6w59/feature_request_drag_to_resize_images_using/d3mvc9c?context=3

Also (optionally) in comment pages when auto expanded?

**Comment by larsjohnsen** [comment]
Fixed.

**Comment by andytuba** [comment]
Why do I get the feeling you fixed that a week ago and I to compile a change log.
