### ISSUE TITLE
x-post module has confusing wording

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#3017]
Currently, the x-post module uses this wording:

"submitted a minute ago by allthefoxes to /r/aww x-posted from /r/foxes"

**This is bad because** when browsing through a subreddit listing, it will definitely look like the post was originally in /r/foxes, rather than /r/aww

**Better wording:** "submitted a minute ago by allthefoxes x-posted from /r/foxes to /r/aww"

This makes sure that the original workflow is the same, and the subreddit name will be in the same place, no matter what. 

Image example: https://www.allthefoxes.me/img/05/s28-69a1.png - It's easy to see how I thought the top post was posted to /r/foxes

**Comment by andytuba** [comment]
while we're at it, only linkify /r/foxes -- not [xposted from r/foxes]
