### ISSUE TITLE
Add "how many multis are you in" to subreddit subscribe button

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3047]
https://www.reddit.com/r/Enhancement/comments/4mknme/feature_request_highlightalter_subscribe_button/

entails subreddit manager tracking your multis.  bonus: show them on the "my subredits" dropdown list

**Comment by dhensche** [comment]
Starting some work on this -- https://github.com/dhensche/Reddit-Enhancement-Suite/tree/multi-counts

**Comment by dhensche** [comment]
Are you envisioning something like this?
![screen shot 2016-11-03 at 2 59 45 pm](https://cloud.githubusercontent.com/assets/387763/19983019/4dc81998-a1d6-11e6-9e0f-00dce9b31b60.png)

Where the orange 2 indicates how many multis the SR is in?

**Comment by andytuba** [comment]
Neat!
