### ISSUE TITLE
The big editor doesn't properly display wiki TOC

### ISSUE THREAD

**Issue by Californ1a** [honestbleeps/Reddit-Enhancement-Suite#3070]
Similar to [this](https://github.com/reddit/reddit/issues/1083) (was was resolved, maybe their code helps you guys fix this one?), but it's with the preview pane of the big editor with RES. [Screenshot](http://i.imgur.com/rTv4zvv.png) - "Workshop" is H2, while "Camera" and "Menu" are H3, but the TOC in the top right doesn't properly display "Workshop" in the correct hierarchy. Makes it kind of difficult to work on wiki pages. I did notice [#2345](https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2345), but that is about the live preview pane in comments. I'm specifically noting the big editor preview, especially for editing wiki pages since they don't include a live preview.

**Comment by erikdesjardins** [comment]
Fixed in #2970; will be released in 4.7
