### ISSUE TITLE
Middle clicking on the upvote/downvote button messes with the votes for the specific user that posted

### ISSUE THREAD

**Issue by miniyuuzhan** [honestbleeps/Reddit-Enhancement-Suite#3105]
Hi,

So there are 6 behaviors, I don't think they're all intended :

- First Case : no upvote on the post/comment.
-- Middle clicking on upvote gives OP 1 positive vote for his post/comment and doesn't put color on the arrow
-- Middle clicking on downvote gives OP 1 negative vote, doen't put color on arrow.

- Second case : post/comment was already upvoted.
-- Middle clicking on upvote gives OP 1 Negative vote
-- Middle clicking on downvote gives OP 2 Negative votes

- Third case : post/comment was already downvoted.
-- Middle clicking on upvote gives OP 2 Positive votes
-- Middle clicking on downvote gives OP 1 Positive vote

It's not really breaking anything, and this vote counter is only seen by the user logged in, so not critical, but strange behaviors.

Happens on chrome Version 51.0.2704.84 (64-bit)

**Comment by andytuba** [comment]
Why are you middle clicking the vote button?

**Comment by andytuba** [comment]
Why are you middle clicking the vote button?

**Comment by miniyuuzhan** [comment]
I scroll down using the middle click, I didn't intend to use this click on the vote buttons, but it happened that I scrolled right after upvoting, made me notice this.

It may not be kept as an issue, I just raised these behaviors.
