### ISSUE TITLE
Support for i.redd.it images in expando.

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3116]
Appears images on i.redd.it arent expanding within RES show images. See: https://www.reddit.com/domain/i.redd.it/

Post titles appear to be self-post but are infact images, this is for images uploaded via Reddit's image uploader. e.g https://www.reddit.com/r/funny/comments/4pvo05/cant_place_the_building_here/

**Comment by andytuba** [comment]
erik notes that this only applies to anonymous users

**Comment by andytuba** [comment]
underlying cause: the post links to the reddit comments page in some circumstances, instead of to the direct image link.

**Comment by andytuba** [comment]
proposal: when selecting the media host, if the link points to reddit.com, use the post's thing::getDomain instead
