### ISSUE TITLE
Link in NP notice cannot be clicked

### ISSUE THREAD

**Issue by nyuszika7h** [honestbleeps/Reddit-Enhancement-Suite#3117]
When following a `np.` link there is a notice explaining not to vote or comment. It's impossible to click the links in that box as unhovering the text I hovered to make that text appear makes it disappear.

**Edit:** Clicking the "Hover here" text makes the text stay so the links are clickable but the behavior is still unintuitive.

**Comment by BenMcGarry** [comment]
Can we get some more information such as RES version and browser? I currently can not reproduce this on my end.

**Comment by erikdesjardins** [comment]
I can reproduce this; should be a simple fix, thanks.
