### ISSUE TITLE
userbar hider should use bodyclass option

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3128]
instead of `$.fn.toggle`

https://www.reddit.com/r/RESissues/comments/4qnfyr/bug_empty_messagecount_not_hidden_when_userbar_is/

**Comment by prayashm** [comment]
Hi, I want to solve this issue.
Just to confirm, when the unread count is 0, the counter should be hidden right?

**Comment by andytuba** [comment]
Right, for the counter in the user bar. (there's another one supplied by the orangered module, it floats in the top right corner.)  I wouldn't think you'd need to worry about that level of logic as part of this issue, since I expect this feature  to simply hide everything in the user menu except the reveal / expand button itself. 

Thanks for looking into this!
