### ISSUE TITLE
Use Synced Storage for Chrome

### ISSUE THREAD

**Issue by raidancampbell** [honestbleeps/Reddit-Enhancement-Suite#3134]
Chrome offers a [chrome.storage.sync](https://developer.chrome.com/extensions/storage#property-sync) API.  Usage is extremely similar, and is likely a drop-in replacement: `chrome.storage.local` -> `chrome.storage.sync`.  The rest of the API calls abstract out `local` vs `sync` into what they call `StorageArea`

Users with multiple computers would get everything synced between their computers: instead of per-computer storage, everything stored by RES gets shared and synced across the user's chrome installations automatically.

While I'm very new to frontend development, The code seems to have abstracted Chrome's storage API for easy replacement.  There should be a change [here for the background.entry.js](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/chrome/background.entry.js#L115) file, and four line changes in [environment.js](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/chrome/environment.js#L36).

**Comment by erikdesjardins** [comment]
Unfortunately it's not a drop-in replacement. The quotas (8k per item / 100k total) are too restrictive for our use. Especially the per-item limit; 8k is trivial to exceed.

**Comment by raidancampbell** [comment]
ah, good catch, storage quantity has never been an issue for my uses.  Thanks for the quick response
