### ISSUE TITLE
goMode navigation menu shows no destinations

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3136]
![](https://i.imgur.com/tbLapFb.png)

@larsjohnsen ideas?

**Comment by larsjohnsen** [comment]
That panel can probably be removed since is it obsolete. https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3089/commits/23bd642fe76667e776f5edf8297c79f0ba12d8be
