### ISSUE TITLE
Option on Inline Image Viewer to not change post URL

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#316]
Inline Image Viewer changes a post's link to the expando image.  While this is ostensibly a good idea, some people actually want to visit the original post.

Hopefully the image expando isn't too tied up in the URL -- but hey, what else is the data attribute for.

**Comment by erikdesjardins** [comment]
Fixed in #2684 (possibly earlier)

**Comment by andytuba** [comment]
this made it into 4.6.0 or 4.6.1.. of course, now people are asking for an option for the legacy  behavior.
