### ISSUE TITLE
Image/Gif unloading causes page scrolling issues.

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3163]
If you browse a subreddit with show images set to expand all, as you scroll down the page will start to jump around preventing you from looking at images, most likely due to them being unloaded.

This is it in action, as you can see it jumps: https://gfycat.com/AccomplishedPitifulArchaeopteryx

This was done on latest master.

**Comment by erikdesjardins** [comment]
I bet it's #3159 updating the size of the placeholder to the size of the 1px transparent gif. Thanks, Firefox

**Comment by larsjohnsen** [comment]
Sorry for not catching this —

I cannot test this now, but I think it will suffice to add the conditional `element.state !== mediaStates.UNLOADED` to `element.emitResizeEvent` https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/3e99d382b0ced43e89f9f231d7f72980758b29a7/lib/modules/showImages.js#L1055
