### ISSUE TITLE
4.7 Changelog notes

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3183]
- [x] Write 'em: https://docs.google.com/document/d/1VK8YNyBmtH3RkUnPRPRBSKZYGkD0gllnnSvuxL3TkDk/edit
- [x] Copy 'em to changelog.md
- [x] Copy 'em to redditenhancementsuite.com/whatsnew.html

**Comment by erikdesjardins** [comment]
#3188
