### ISSUE TITLE
Drag resize on "i.redd.it" images

### ISSUE THREAD

**Issue by bluetidepro** [honestbleeps/Reddit-Enhancement-Suite#3186]
The inline image drag on images that come from the Reddit upload domain `i.redd.it` do not resize. Is this something that could possible be fixed?

**Comment by andytuba** [comment]
This is already fixed in development and will be released in a few weeks.

**Comment by andytuba** [comment]
P.S. /r/RESissues is a better place to report bugs.

**Comment by bluetidepro** [comment]
@andytuba Good to know. Sorry, first time posting both of those issues! Thanks for the quick response! :)
