### ISSUE TITLE
r/RESAnnouncements post 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3189]
https://docs.google.com/document/d/1JBdNGfc2aQUxz7aKm5EbaSSgVoK7Lx_Iyz62sAW9fUE/edit#heading=h.1q5cbaxxzvc0

**Comment by BenMcGarry** [comment]
https://www.reddit.com/r/RESAnnouncements/comments/4u4pxu/announcement_upcoming_471_beta_releases_of_res/
