### ISSUE TITLE
filteReddit: allowNSFW is broken

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3193]
i.e. all NSFW posts are filtered regardless of what subreddits you have in allowNSFW

**Comment by larsjohnsen** [comment]
I believe I fixed it (or is there an use case I'm missing?) https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3144/commits/2b7c405ed82071fac8de1facf30dded23f30814f

**Comment by erikdesjardins** [comment]
@larsjohnsen I thought I remembered you fixing that, I may have fooled myself into thinking it was broken.

Tagging unconfirmed until I test it more thoroughly
