### ISSUE TITLE
indexedDB works with `jpm run` but not `jpm xpi`

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3194]
I have no words.

![image](https://cloud.githubusercontent.com/assets/7673145/17079793/86fa9478-50e8-11e6-86ca-3c2adec872d8.png)

**Comment by erikdesjardins** [comment]
This was happening because my main Firefox profile was somehow corrupted, see [bug 994918](https://bugzilla.mozilla.org/show_bug.cgi?id=944918).

`jpm run` was unaffected because it always uses a fresh profile. Deleting and recreating my main profile fixed it for `jpm xpi`.

I really hope this isn't a common thing, because there's nothing we can do besides telling users to delete their Firefox profiles...

**Comment by andytuba** [comment]
We could.. Um..  Put in an option to go back to simple storage :sob:
