### ISSUE TITLE
Hide child comments on non-top comments

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3207]
https://www.reddit.com/r/Enhancement/comments/4urp6k/is_it_possible_to_collapse_a_comments_children/

thought this was already a GH issue..

**Comment by pltarun** [comment]
I'm working on this. Not ready to make a pull request yet.
<img width="785" alt="screen shot 2016-08-10 at 21 16 18" src="https://cloud.githubusercontent.com/assets/5273804/17569390/e5f3d61e-5f3f-11e6-8cb2-27331a629d1c.png">
<img width="817" alt="screen shot 2016-08-10 at 21 17 09" src="https://cloud.githubusercontent.com/assets/5273804/17569391/e60faefc-5f3f-11e6-8e67-3ac157a3466f.png">
