### ISSUE TITLE
question: image browser

### ISSUE THREAD

**Issue by jabbalaci** [honestbleeps/Reddit-Enhancement-Suite#3213]
I have a question about the image browser feature. If an imgur image / album is posted to reddit, then RES shows an icon that allows us to browse the image(s) in place, without leaving the current page.
How is it done? Is RES prepared for imgur, or does the imgur page (say, an album page) contains some metadata that is extracted by RES and that's how it populates the image browser?
I have a website, where a page contains a big image. When this page is posted to reddit, I'd like RES to show the image browser icon.

**Comment by andytuba** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/examples/host.js

**Comment by jabbalaci** [comment]
Thanks! I think we can close this issue.
