### ISSUE TITLE
Bug: After updating to Firefox 48.0, account switcher does not function properly

### ISSUE THREAD

**Issue by kuhnerdm** [honestbleeps/Reddit-Enhancement-Suite#3223]
After clicking snoo and opening the drop list of usernames, when you click on a name:

Expected: Log in as that user

Actual: Nothing happens; no load, no error message, drop list stays. Usernames are virtually unclickable. "Add account" button still functions.

Running FF 48.0 (not dev, nightly, or anything like that). Only other addon is uBlock Origin.

**Comment by erikdesjardins** [comment]
Was fixed in #3222; please search before opening issues.

This is fixed [in the beta](https://www.reddit.com/r/RESAnnouncements/comments/4vt35o/announcement_chrome_and_firefox_beta_releases/), if you're feeling adventurous.
