### ISSUE TITLE
Disable subreddit styles does not work in Edge

### ISSUE THREAD

**Issue by sschneider1207** [honestbleeps/Reddit-Enhancement-Suite#3265]
Title.  It does not work in either night or daylight mode.

Versions:
* Edge: `38.14393.0.0`
* RES: `4.7.3`

**Comment by BenMcGarry** [comment]
Are you referring to the button in the URL or on page options?

**Comment by sschneider1207** [comment]
I had the page options set to whitelist no subreddits with night mode but it wasn't doing anything.  I just tried the button in the URL and it worked one time, then stopped working on subsequent page.  Now when I toggle the URL button nothing happens and styles stay on.

**Comment by BenMcGarry** [comment]
I am unable to replicate this on 4.7.3. Are you able to do a screen recording or make a [gif ](https://screentogif.codeplex.com/)to show it in action? I might be missing something.

**Comment by sschneider1207** [comment]
Huh, I'm not sure what changed but I cant seem to do it anymore either.  I don't think I had restarted edge after installing, so maybe that was the cause?
