### ISSUE TITLE
`await` all long-running async tasks kicked off in `go()`

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3296]
...especially `forEachChunked`, for more accurate profiling.

We don't want to do this for `beforeLoad`, because that stage should complete as soon as possible (so `go` can run), but we don't care if `afterLoad` is arbitrarily delayed (it's unimportant).

re #3295

**Comment by andytuba** [comment]
For example, https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3297 ?

**Comment by erikdesjardins** [comment]
Sort of; #3297 is specifically intended to improve performance, but most changes for this issue won't change performance, they'll just make it easier to profile.

For example, something like [this](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6a5b2870f395c7daa55e83a236161d2a398e8d7f/lib/modules/xPostLinks.js#L65) is not `await`ed, a profile shows xPostLinks doing very little work. If it (and every function up the chain to `go`) were `awaited`, the performance would be the same, but we'd be able to see it.

**Comment by andytuba** [comment]
OIC - measuring the full "lifetime" of `go` including its asynchronous tasks.

**Comment by erikdesjardins** [comment]
This is no longer how I want to structure init, so it no longer makes sense.
