### ISSUE TITLE
NER failing to hide/fade dupes on search.

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3308]
https://www.reddit.com/r/ideasfortheadmins/search?q=gold+server&restrict_sr=on&sort=relevance&t=all

With NER enabled, after page 2 RES states it cant load anything else, but fails to hide/fade the dupes. It just shows them as normal listings but they are repeats.

![](https://i.imgur.com/Dqlf35S.png)

**Comment by BenMcGarry** [comment]
#3112 fixes this.

**Comment by allthefoxes** [comment]
Oops, I mentioned this in Slack but forgot to report it here. Thanks. 

Possibly related: https://www.reddit.com/r/RESissues/comments/4zehre/bug_never_ending_reddit_will_load_the_last_page/ - Fixed by #3112 as well?
