### ISSUE TITLE
Reddit changed markup, breaking `.sitetable > .thing` selectors, perhaps more

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3314]
**Edit:** no longer a problem but some of these selectors should be made less specific so they aren't as fragile

Breaking "hide child comments" and "save-RES" links, etc.

https://www.reddit.com/r/RESissues/comments/4z2trh/bug_hide_all_child_comments_not_working/
https://www.reddit.com/r/RESissues/comments/4z2txo/bug_hide_all_child_comments_are_no_longer_working/

`.sitetable > .thing` is now `.sitetable > #listings > .thing` on comments pages

Potentially affected selectors:
- [ ] https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6ea2e540bedf3fcfbafac0d858de485693d83a29/lib/modules/hideChildComments.js#L45
- [ ] https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6ea2e540bedf3fcfbafac0d858de485693d83a29/lib/modules/hideChildComments.js#L80
- [ ] https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6ea2e540bedf3fcfbafac0d858de485693d83a29/lib/modules/pageNavigator.js#L55
- [ ] https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6ea2e540bedf3fcfbafac0d858de485693d83a29/lib/modules/saveComments.js#L85
- [ ] https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6ea2e540bedf3fcfbafac0d858de485693d83a29/lib/modules/userHighlight.js#L220
- [ ] https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6ea2e540bedf3fcfbafac0d858de485693d83a29/lib/utils/watchers.js#L138

**Comment by andytuba** [comment]
These selectors should be made more robust, but certainly lower priority since reddit pushed a fix.
