### ISSUE TITLE
YouTube video times don't work in Edge

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3315]
This appears to be an incompatibility between the Google API and Edge; specifically the API refuses to send CORS headers for the `ms-browser-extension:` protocol.

For example, Chrome origin:

``` bash
curl -isS \
-H 'Origin: chrome-extension://flhpapomijliefifkkeepedibpmibbpo' \
-H "Access-Control-Request-Method: POST" \
-H "Access-Control-Request-Headers: X-Requested-With" \
'https://www.googleapis.com/youtube/v3/videos?id=e_zLS2PjwCI&part=id%2CcontentDetails%2Csnippet&key=API_KEY' \
| grep -i '^access-'
```

prints:

```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: chrome-extension://flhpapomijliefifkkeepedibpmibbpo
Access-Control-Expose-Headers: Cache-Control,Content-Length,Content-Type,Date,ETag,Expires,Server,Vary,X-Google-GFE-Backend-Request-Cost
```

and Edge origin:

``` bash
curl -isS \
-H 'Origin: ms-browser-extension://RedditEnhancementSuite_gvs2z264nkw9j' \
-H "Access-Control-Request-Method: POST" \
-H "Access-Control-Request-Headers: X-Requested-With" \
'https://www.googleapis.com/youtube/v3/videos?id=e_zLS2PjwCI&part=id%2CcontentDetails%2Csnippet&key=API_KEY' \
| grep -i '^access-'
```

prints nothing (no `Access-` headers).

**Comment by fireattack** [comment]
Is it actually working in other browsers? I can't see any video length https://www.reddit.com/r/videos/, even though I am on Chrome.

**Comment by andytuba** [comment]
Towards the end of the day it might break because RES runs out of quota.  You can verify by examining the response from YouTube after requesting the video metadata.

**Comment by BenMcGarry** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9161008/
