### ISSUE TITLE
Target announcements to specific browsers

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3320]
@BenMcGarry has an idea: if a post to /r/RESAnnouncements mentions any browser names in the title, eg `[Safari]`, then only show the bell if that browser is in the title. Implement using build targets.

**Comment by michaelskiles** [comment]
I gave this a whirl:

https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3442

Note that this only applies to browsers that are currently supported by RES>
