### ISSUE TITLE
Loading cdn.redditenhancementsuite.com/updates.css makes page load noticeably slower

### ISSUE THREAD

**Issue by TheLQ** [honestbleeps/Reddit-Enhancement-Suite#3323]
Browser: Firefox on Linux
Reproducible at multiple locations (work and home)

Recently reddit has been loading slower and the common theme is "Transferring data from http://cdn.redditenhancementsuite.com/updates.css" at the bottom of the Firefox window. If you look at the network dev panel it shows it takes anywhere from 90-300ms, which is slow when most of the times around it are 50-100ms.

Now obviously this is going to vary with traffic at the moment, time of day, and location. This happens sporadically during the day: sometimes it's normal speed sometimes it's slow. This has also been reported before by someone else: https://www.reddit.com/r/RESissues/comments/4b7ywd/bug_opening_comments_hangs_a_bit_on_read/

I've disabled the Stylesheet Loader and page loading does seem noticeably faster and reliable. However this probably isn't the best fix and not ideal.

**Comment by honestbleeps** [comment]
hmm, that's especially weird because after one load, it ought to be cached by the browser and not consistently cause slowdowns... maybe I need to adjust a header or something.

I don't have time to dive into the network requests at the moment, so I'm throwing that out as a comment in the hopes someone can peek at it?

**Comment by BenMcGarry** [comment]
Investigating this now.

**Comment by TheLQ** [comment]
Yes it does, the expiration date is one hour and reloads show it hitting the cache. But to me it seems to happen more often than that.

**Comment by Idiomatick** [comment]
Having the same issue on FF 48 // Windows 10. Maybe FF broke caching.

**Comment by steiney001** [comment]
Same issue. cdn.redditenhancementsuite.com takes ~2 seconds to load. 

FF 48.0.2 OS X 10.9.5
