### ISSUE TITLE
Openseadragon support

### ISSUE THREAD

**Issue by harrisongill** [honestbleeps/Reddit-Enhancement-Suite#3326]
/u/openseadragonizer shows nothing when using RES on Safari. Only the link works offsite and RES assumes something should be loading as an image, but nothing happens. I assume this is unsupported but am not sure if it is a bug.

https://github.com/openseadragon/reddit-bot/issues/3

<img width="879" alt="screen shot 2016-08-27 at 7 05 00 pm" src="https://cloud.githubusercontent.com/assets/4271517/18031204/46f14c7e-6c8a-11e6-89fc-1be3c29b9cdd.png">

**Comment by avandecreme** [comment]
OpenSeadragonizer dev here (thanks @harrisongill for opening an issue here as well).

/u/openseadragonizer is creating a link to a url like this:
https://openseadragon.github.io/openseadragonizer/?img=https://i.redditmedia.com/3HRNAw4oQ2NaGXbV2ZCJn1wDTFww3uTkyF0OqP0HG_o.jpg?s=59f48e391b2473b93adb36e83a2b2989
RES seems to (wrongfully) interpret that as an image. Hopefully, we can work out something making RES and /u/openseadragonizer work better together. What do you think?

**Comment by BenMcGarry** [comment]
This appears to happen due to OpenSeadragonizer being a unsupported media host for RES. So the expando isn't quite sure what to do. If you would like RES to be able to expand these you will need to submit a mediahost, please see the URL below for an example.

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/examples/host.js

**Comment by avandecreme** [comment]
Having the expando working would be great, however is there a way to just disable it with OpenSeadragonizer as a first step?
I currently don't have time to dive into implementing a media host for RES.

Furthermore, it seems that RES might behave poorly with any URL containing .jpg/.png when they are not images.

**Comment by larsjohnsen** [comment]
This is fixed in the beta. The generic media host now only tests whether the path (i.e. `/openseadragonizer/`) matches.

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/hosts/default.js

**Comment by avandecreme** [comment]
Excellent! Thanks.
