### ISSUE TITLE
Images from redditbooru / cdn.awwni.me don't load inline

### ISSUE THREAD

**Issue by Lycerion** [honestbleeps/Reddit-Enhancement-Suite#3335]
These used to work, but broke a couple months back... was hoping it would be fixed along with next update but it's sadly still broken, only displaying the "Loading of image [...] Failed" thing.

Example: http://i.imgur.com/4c3ysWr.png

**Comment by BenMcGarry** [comment]
Can you please provide a list of extensions you are using? As well as browser and versions.

**Comment by andytuba** [comment]
Are you using RES v5.0.0 yet? https://www.reddit.com/domain/cdn.awwni.me shows lots of working images for me.

**Comment by Lycerion** [comment]
Alright I think this is actually an issue with privacy badger; I had disabled my other extensions to make sure it wasn't them, but after re-enabling it and manually allowing those domains, it's working again. Seems like there might be some persistent settings.
