### ISSUE TITLE
(index):27 Uncaught (in promise) Error: Error in "storage" interceptor: Generator is already running

### ISSUE THREAD

**Issue by MrCraftCod** [honestbleeps/Reddit-Enhancement-Suite#3339]
I get this error running in the console since today: 
![ss 2016-09-02 at 10 28 49](https://cloud.githubusercontent.com/assets/1688389/18197588/426cf0dc-70f8-11e6-834c-d64514564e8b.png)

I sometimes have the dark theme setting up in some subreddits, but not all. And menus like in the top right corner or the new "my subreddits" dropdown are not here.

Any help on that problem?

Thank you.

**Comment by BenMcGarry** [comment]
What version of Chrome are you running?

**Comment by MrCraftCod** [comment]
i'm running 54.0.2840.8 dev-m (64-bit).
On 02/09/2016 10:45:00, Ben McGarry <notifications@github.com> wrote:
What version of Chrome are you running?

**Comment by BenMcGarry** [comment]
Can you confirm the version of RES you are running? We have seen many reports of this and people have said updated to 5.0.0.1 has fixed it.

**Comment by MrCraftCod** [comment]
Yeah I do have this one. I even forced the updates in case. Then went to see on the chrome page and saw it was updated yesterday. So I maybe thought I was because of that.
![ss 2016-09-02 at 10 50 49](https://cloud.githubusercontent.com/assets/1688389/18198131/3d7aa774-70fb-11e6-9074-4ea39d7a6328.png)

**Comment by BenMcGarry** [comment]
Ok, from the outset it looks like it could be a Chrome bug, it appears to be resolved on the canary builds but for general usage i wouldnt reccomend those builds. I don't really work on Chrome so i'm not really able to start digging into this issue, when the American guys wake up they should be able to figure out whats gone wrong pretty quick. I'll leave this open as a note to them and monitor it today and try to see if theres anything i can do. Chrome 53 was released the day before we committed for stable and we didnt really have any reports of this in beta, so this has hit us as a bit of a shock.

**Comment by MrCraftCod** [comment]
Ok, I checked with the canary version and yeah, the extension seem to work fine. I'll close the issue as it is Chrome's fault and will wait that the update from canary passes into the other channels.

Thank you for your help and sorry to have disturbed you for that.
Have a great day.
