### ISSUE TITLE
NER is not functioning correctly 

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3341]
There have been a few reports that NER isn't working correctly on subreddits. The automated next page thing and next page buttons don't show.

https://www.reddit.com/r/RESAnnouncements/comments/50qer8/announcement_res_v500_release/d767tle

**Comment by hastings-recursive** [comment]
chrome v 49, cant update because i wont update osx after 10.8 since they messed with samba.  please fix

**Comment by erikdesjardins** [comment]
This is caused by Chrome 49 being out of date (`NodeList` is not iterable).

We don't support old versions of Chrome.

**Comment by tekmosis** [comment]
It stopped working on Linux, Chrome Version 50.0.2661.86 (64-bit)

**Comment by Ajedi32** [comment]
@tekmosis The latest stable version of Chrome is 53, try updating to that and see if that fixes the problem.

**Comment by tekmosis** [comment]
apt-get says google-chrome-stable is already on the latest version. I'm on Debian;
Linux navi 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

**Comment by honestbleeps** [comment]
I know this isn't going to go over well, but:

We can't indefinitely support old chrome versions.  If a user's OS of choice doesn't support newer Chrome versions, unfortunately that's going to sometimes just end up being a rough / upsetting situation.

There may (I'm really not sure yet and can't promise anything) be some sort of backward compatible fix This One Time(tm) - but the changes we have to make to support old browsers are often not trivial, and it will hinder the advancement of RES as a whole if we keep doing it.

**Comment by Ajedi32** [comment]
@tekmosis Try downloading the deb package from Chrome's site again and installing from there; it should be the latest version.

**Comment by hammerschaedel** [comment]
using Chrome 53 with win10 , NER doesn´t work

**Comment by Ajedi32** [comment]
@hammerschaedel Can you press F12 to open the dev tools and post a screenshot of what the console shows after you refresh the page and scroll down (so NER attempt to load the next page)? I haven't heard of this issue cropping up on Chrome 53 before...

**Comment by hammerschaedel** [comment]
http://i.imgur.com/r1G9TuE.png

**Comment by Ajedi32** [comment]
Interesting, doesn't look like anything too out of the ordinary...

I wonder if maybe another extension is interfering with RES. Try it on a separate Chrome profile with _only_ RES installed. That way we can at least narrow down the problem...

**Comment by hammerschaedel** [comment]
ok, checked it out. Seems that the Problem is "Shine for Reddit". After disabling it, scrolling works. thx for your help^^

**Comment by Ajedi32** [comment]
Ah, looks like that's a known issue with Shine: https://www.reddit.com/r/shine/comments/50sntp/reddit_enhancement_suite_updated_and_changed_a/
