### ISSUE TITLE
Doesn't work in Chrome 52

### ISSUE THREAD

**Issue by slikts** [honestbleeps/Reddit-Enhancement-Suite#3344]
OS: Windows 10
Chrome 52

Nothing works.

The errors I get in the console:

```
(index):27Uncaught (in promise) Error: Error in "storage" interceptor: Generator is already running(…)(anonymous function) @ (index):27step @ asyncToGenerator.js:1
(index):27Uncaught (in promise) Error: Error in "storage" interceptor: Generator is already running(…)(anonymous function) @ (index):27step @ asyncToGenerator.js:1```

**Comment by BenMcGarry** [comment]
`chrome://flags/#enable-javascript-harmony`

Is that flag enabled for you? If so turn it off.

**Comment by slikts** [comment]
That fixes it, thanks. I'd prefer to keep the flag on, though.

**Comment by vramana** [comment]
I don't have that flag. But I am on Chrome 55 (Dev Channel). I am seeing the same error.

**Comment by Ajedi32** [comment]
Dup of #3339
