### ISSUE TITLE
Imgur images do not expand on Wiki pages

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3345]
https://www.reddit.com/r/RESissues/comments/50st8v/bug_wiki_images_no_longer_able_to_expand/d76mrpg?context=3

**Comment by erikdesjardins** [comment]
Should be an easy fix, just adding `'wiki'` to `module.includes`, assuming that's the issue

**Comment by larsjohnsen** [comment]
@erikdesjardins `showImages` doesn't have `module.includes` specified, so it is running. `checkElementForMedia`  does however require that elements is within in a `Thing`. I'll fix it.
