### ISSUE TITLE
Make permissions explanation for expandos less confusing

### ISSUE THREAD

**Issue by Ajedi32** [honestbleeps/Reddit-Enhancement-Suite#3346]
I noticed some users [expressing confusion](https://www.reddit.com/r/Enhancement/comments/50qnyj/announcement_res_v500_release/d767tpt) at the new dialog for RES expando permissions:

![screenshot-www reddit com 2016-09-02 10-03-39](https://cloud.githubusercontent.com/assets/1876931/18208310/98b9930e-70f4-11e6-8610-3e2786d89e9b.png)

Upon further reflection, this is definitely very confusing wording. "Expando" seems to be a word RES just kinda made up. I've honestly never heard that term outside of the context of RES, and even [Googling for it](https://www.google.com/#q=expando&rct=j) turns up no results which might indicate this feature has anything to do with inline image expansion.

This text should be reworded, especially since it seems the whole point of this dialog is to explain to users why these permissions are needed.

**Comment by andytuba** [comment]
"expando" came from reddit, actually.  Unsure the original history.

**Comment by honestbleeps** [comment]
how about we show a picture of the button, and it's roughly like "in order to add the ability to expand content from this site, with a button like {this one} ..." ?

**Comment by andytuba** [comment]
maybe even "closed button  -> openbutton+image"
