### ISSUE TITLE
YouTube channel links recognised as YouTube videos

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3353]
https://www.reddit.com/r/RESissues/comments/50sbzt/bug_res_incorrectly_parses_url_to_a_youtube/

Test post: https://www.reddit.com/r/sweden/comments/50quuf/evanescence_pannkaka_av_tales_scales_p%C3%A5_youtube/d768ght

**Comment by slcc2c** [comment]
Should be as easy as detecting the /channel/ substring, will try and make time to fix.

**Comment by thesbros** [comment]
@slcc2c I don't think so, there is lots of different channel URLs. (e.g. /username, /c/username, /channel/username)

A better solution would be to see if it has /watch, otherwise handle it as a normal URL.

**Comment by slcc2c** [comment]
Damn you're right, I'm not a big YouTube user so I limited my consideration to the example.

**Comment by Ajedi32** [comment]
Not just `/watch` either, the short URLs use just a string of random (base 64?) characters. E.g. https://youtu.be/dQw4w9WgXcQ

**Comment by mckennajones** [comment]
Going to try tackling this within the next few days

**Comment by erikdesjardins** [comment]
@mckennajones FYI looks like @thesbros took care of it
