### ISSUE TITLE
Option for shorter user info cache time

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3354]
https://www.reddit.com/r/RESAnnouncements/comments/50qer8/announcement_res_v500_release/d7737g1?context=3

>  I tend to like to have it fairly instantly since being able to respond/react to a thread is important. Say the wrong thing by accident and notice you just lost a bunch of points is an indicator that you need to relook at it which then shows that you made a big mistake with w/e which you fix and your downward spiral has ended.

related: request to show "recent karma trend"

**Comment by andytuba** [comment]
several other people have also reported stale user info

**Comment by erikdesjardins** [comment]
I think the cache time is incorrectly "time since last access" instead of "time since last fetch".

Let's not make an option, and instead fix that and make it refresh every 10 minutes
