### ISSUE TITLE
[Regression] Zoom/resize level doesn't get kept across gallery expando

### ISSUE THREAD

**Issue by fireattack** [honestbleeps/Reddit-Enhancement-Suite#3360]
Example: https://www.reddit.com/r/interestingasfuck/comments/50sych/1910_when_paris_flooded/

When you resized the first image, and went to the next, the zoom level reset.

Before it will continue to use the same/similar zoom level for next images.

**Comment by larsjohnsen** [comment]
I see that the previous implementation set the same width for all pieces after resizing. I am not sure that is desirable behavior, as the images/videos in the album often has varying resolutions and aspect ratios.

**Comment by fireattack** [comment]
Only fixing the width should work fine with various resolution and aspect ratio though.
