### ISSUE TITLE
/r/subreddit/comments has page type 'comments'

### ISSUE THREAD

**Issue by larsjohnsen** [honestbleeps/Reddit-Enhancement-Suite#3366]
E.g. https://www.reddit.com/r/Art/comments has page type `comments`, while https://www.reddit.com/r/Art+Media/comments has page type `linklist`. 

It appears that the modules expect that these pages has page type `linklist`.

**Comment by erikdesjardins** [comment]
Fix for this should modify these tests: https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/utils/__tests__/location.js
