### ISSUE TITLE
[Feature Request] Force direct links to i.redd.it images instead of linking to comments page

### ISSUE THREAD

**Issue by mleyen** [honestbleeps/Reddit-Enhancement-Suite#3369]
Would it be possible to add an option to force i.redd.it submission titles to link directly to the image rather than linking to the comments page as currently done?

**Comment by erikdesjardins** [comment]
Use this option (`expandoCommentRedirects`): https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/9c6b5936e925440c73229ac6ab96e436dc9f2b38/lib/modules/showImages.js#L275

Sorry, the name is a little obscure.

**Comment by mleyen** [comment]
Thank you!
