### ISSUE TITLE
5.0.0 broke compatibility with Thumbnail Zoom Plus on i.redd.it (Firefox)

### ISSUE THREAD

**Issue by mleyen** [honestbleeps/Reddit-Enhancement-Suite#3370]
Not sure if this is a problem with TZP or RES, but I'll submit this here.
RES 5.0.0 has a new handler for i.redd.it which conflicts with Thumbnail Zoom Plus.

I think this is due to RES removing the `<div class="expando">` on each entry and replacing it with its own expando which does not contain the  actual image URL until expanded.

The workaround is to disable Inline Image Viewer entirely. A simple fix would be not to remove Reddit's expando element. See also #3369 my other request about i.redd.it.

**Comment by andytuba** [comment]
A simpler fix might be adding whatever that extension used to get the url. 

Could you link to the urls installer page for convenience?

**Comment by mleyen** [comment]
Do you mean the source? I think it comes from this part: https://github.com/dadler/thumbnail-zoom/blob/master/src/resources/pages.js#L1761

The installer would be https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/ .

**Comment by mc10** [comment]
Going to close for now, as Thumbnail Zoom Plus has no WebExtension version; if it gets updated and the issue still exists, feel free to reopen.
