### ISSUE TITLE
v5.0.0 When having NeverEndingReddit paused a popup telling me so shows up on every page load, sometimes twice.

### ISSUE THREAD

**Issue by creesch** [honestbleeps/Reddit-Enhancement-Suite#3371]
Basically what it says in the title, the following popup shows up: 

![image](https://cloud.githubusercontent.com/assets/2502190/18226796/bac86772-7211-11e6-9dcd-62aa995c580d.png)

And sometimes again when I click the close button. This is different from when it would show on previous version. 
When checking my RES settings I also see multiple mentions of NeverEndingReddit

![image](https://cloud.githubusercontent.com/assets/2502190/18226811/246360e2-7212-11e6-9302-7bdad81afeb5.png)

**Comment by creesch** [comment]
I should mention that I disabled the NER popups before making the screenshot. All four of them were enabled. 

Also this is on Chrome version 53.0.2785.89 m

**Comment by erikdesjardins** [comment]
If you uncheck "always show this type of notification" does it stop?

I think that checkbox just disables the notification in the table (so probably not), but it's worth a try.

**Comment by erikdesjardins** [comment]
Actually it seems that unchecking "always show this type of notification" fixes it for me, can you confirm?

**Comment by larsjohnsen** [comment]
Not resolved by #3379. 

For some reason is `notificationID` wrong (not `pause` as it should be) or ignored.
![image](https://cloud.githubusercontent.com/assets/1748521/18255593/4b52416a-73ab-11e6-9571-0f138b45d3a4.png)
