### ISSUE TITLE
autoSelectOnScroll should ignore posts in "recently viewed"  sidebar widget

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3377]
https://www.reddit.com/r/RESAnnouncements/comments/50qer8/announcement_res_v500_release/d78ex9j?context=3

This might be solved inside the "all things" utility function.

**Comment by erikdesjardins** [comment]
I can't seem to reproduce this, and it doesn't seem like it should happen: "recently viewed links" don't match any of [these](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/ed8f5c57ce7ebc4472b48e501bde6274e0eb45cc/lib/utils/Thing.js#L7) selectors, AFAICT (used [here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/ed8f5c57ce7ebc4472b48e501bde6274e0eb45cc/lib/utils/Thing.js#L28), used [here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/ed8f5c57ce7ebc4472b48e501bde6274e0eb45cc/lib/modules/selectedEntry.js#L234)).

**Comment by erikdesjardins** [comment]
Closing as I can't reproduce and we've had no other reports.
