### ISSUE TITLE
xkcd parsing issues on certain posts

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3384]
https://www.reddit.com/r/RESissues/comments/514vxm/bug_xkcd_expando_cuts_off_title_text_of_859/

**Comment by larsjohnsen** [comment]
Appears to be an issue with the library Noembed uses. https://github.com/leedo/noembed/blob/master/lib/Noembed/Provider/XKCD.pm

**Comment by erikdesjardins** [comment]
Reported https://github.com/leedo/noembed/issues/75

**Comment by Ajedi32** [comment]
For the record, I find it absolutely hilarious that [XKCD 859](https://xkcd.com/859/) ended up being the comic to trigger this issue.

**Comment by lucaswerkmeister** [comment]
It’s a pre-existing test case for any xkcd scraper/parser/viewer, isn’t it? :)

**Comment by AjaxGb** [comment]
I have to ask, why use Noembed when xkcd has a perfectly good JSON API?
https://xkcd.com/json.html

**Comment by erikdesjardins** [comment]
@AjaxGb it doesn't send CORS headers.

**Comment by AjaxGb** [comment]
@erikdesjardins Ah, that's disappointing. And apparently the JSONP API has encoding issues.
