### ISSUE TITLE
returnToPrevPage not working since 4.7.4

### ISSUE THREAD

**Issue by donlbooth** [honestbleeps/Reddit-Enhancement-Suite#3402]
Win 7 x64
Firefox 48.0.2
Waterfox 48.0.1

The page numbers no longer appear in the address bar. When going back a page it starts over at page 1
still persists on clean profile and new user account, reverting to 4.7.4 fixes the issue, 4.7.5 and higher all have the same problem.

**Comment by larsjohnsen** [comment]
When return to a page and not having the previous page restored, what does entering `performance.navigation.type` in the browser console result in?

**Comment by donlbooth** [comment]
It gives me a result of 2

**Comment by erikdesjardins** [comment]
@donlbooth is this fixed for you in 5.0.2?

**Comment by donlbooth** [comment]
It's still occurring on my work computer, I'll check my personal one after I get home from work
Res 5.0.2
Firefox 49.0.1

**Comment by donlbooth** [comment]
This is now kinda working in 5.0.3, but the pages are not auto increment as I scroll, I have to click something on each page to get it to trigger
