### ISSUE TITLE
Don't automatically save data in private mode 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3405]
https://www.reddit.com/r/Enhancement/comments/51b28e/res_breaching_private_browsing_mode/d7bk9xh

**Comment by andytuba** [comment]
@erikdesjardins Assuming they're referring to cached data, could this ticket be resolved by the cache layer not saving to storage in incognito, and maybe keeping cache in the background page's memory instead?  Do you think there's other data besides the cache that needs special treatment?

**Comment by erikdesjardins** [comment]
The cache is all in-memory now, so I have no idea what they mean by "users who have logged in", nothing like that should be stored. They were probably on an old version of RES.

"subreddits visited" is probably the subreddit manager last visited time.

**Comment by andytuba** [comment]
> "subreddits visited" is probably the subreddit manager last visited time.

Agreed, after experimenting I found keys like "RESmodules.subredditManager.subredditsLastViewed.{username}" and "RESmodules.subredditManager.subredditsLastViewed.null".

**Comment by andytuba** [comment]
newCommentCount.counts also leaks.
