### ISSUE TITLE
i.redd.it imageZoom not working

### ISSUE THREAD

**Issue by Ruddiger** [honestbleeps/Reddit-Enhancement-Suite#3413]
Image zoom doesn't work with images on i.redd.it

Running v5.0.1
Chrome: 52.0.2743.116 m

**Comment by andytuba** [comment]
I disabled some i.redd.it image zoom in 5.0.1 because it was hitting the reddit API too hard. If you look in your [reddit preferences](https://www.reddit.com/prefs) and select "Media Previews > Don't auto-expand media previews on comments pages", I believe that'll do the trick.

**Comment by Ruddiger** [comment]
That does the trick, thanks!
