### ISSUE TITLE
Redesign RES expandos for uniformity with reddit's new design

### ISSUE THREAD

**Issue by githue** [honestbleeps/Reddit-Enhancement-Suite#3415]
Reddit just changed their expando icons, including their appearance and CSS. I haven't looked into the CSS changes yet.

https://www.reddit.com/r/cssnews/comments/51u4sh/css_change_changes_to_default_thumbnails_expando/

![expando-mismatch](https://cloud.githubusercontent.com/assets/7245595/18369994/ad4a4f7a-766c-11e6-84ee-94a5a6d30d28.png)

Alpha map I made for the current RES icons:

![expando-alphas](https://cloud.githubusercontent.com/assets/7245595/18370061/602435e8-766d-11e6-941c-19ca39fbf48a.png)

Related: #2738

**Comment by andytuba** [comment]
I heard from someone else who is interested in contributing updated icons, but unsure if they can get it in by Tuesday for 5.0.2. I'll check in with them, but I think it'll be okay if @githue or somebody renders new RES icons in the new reddit style.

**Comment by andytuba** [comment]
It would be nice to add a "legacy icon" option, too, for the people who really hate change -- and add a disclaimer that they probably won't get updated if broken.

**Comment by githue** [comment]
That all sounds fine by me.

**Comment by groovenectar** [comment]
I came to the repo to mention the new icons as well, but specifically regarding night mode. The new icons make it a bit of an eyesore in night mode now. The exapando icons now seem to attract a bit more attention than the titles...

Here is a screenshot:

![](https://cloud.githubusercontent.com/assets/595446/18376264/85b1ec52-762b-11e6-9294-ff0324c11cea.png)
