### ISSUE TITLE
e10s support

### ISSUE THREAD

**Issue by mirh** [honestbleeps/Reddit-Enhancement-Suite#3416]
Follows #1574 that hasn't got any more love. 
I just checked RES with Add-on Compatibility Reporter and it's marked as incompatible.

**Comment by erikdesjardins** [comment]
FYI, the Compatibility Reporter's results have literally no bearing on whether the addon actually works in e10s, it's only whether or not the `multiprocess` flag is set in the manifest (there's nothing stopping you from setting the flag when your extension doesn't work at all).

I'll take care of it now, though.

**Comment by erikdesjardins** [comment]
And, like magic, we are "Compatible with multiprocess." 😜 

![image](https://cloud.githubusercontent.com/assets/7673145/18414157/b35545ce-778d-11e6-8b25-823551884179.png)

**Comment by IsSuEat** [comment]
Enabling e10s via about:config with only RES installed doesn't work. 
Although the Addon Compatibility addon says RES is multiprocessor capable, e10s is disabled in about:support.
