### ISSUE TITLE
Build fails [Win7/node6.5.0]

### ISSUE THREAD

**Issue by martixy** [honestbleeps/Reddit-Enhancement-Suite#3417]
I'm trying to build the app and it fails with the following error:

```
ERROR in ./chrome/background.entry.js
Module build failed: Error: Final loader didn't return a Buffer or String
    at DependenciesBlock.onModuleBuild (D:\WebDev\!GitHub\RES\node_modules\webpack-core\lib\NormalModuleMixin.js:299:42)
    [...]
    at D:\WebDev\!GitHub\RES\node_modules\async\lib\async.js:52:16
    at done (D:\WebDev\!GitHub\RES\node_modules\async\lib\async.js:241:17)
 @ ./~/extricate-loader/lib/extractLoader.js!./~/interpolate-loader!./chrome/manifest.json
```
And a bunch of similar traces after. Entire trace here: http://pastebin.com/FZVnSnvs

**Comment by erikdesjardins** [comment]
This error:

```
ERROR in Entry module not found: Error: Cannot resolve module 'GitHub\RES\node_modules\babel-loa
der\index.js' in D:\WebDev\!GitHub\RES\chrome
```

is suspect, since `babel-loader` is definitely in [package.json](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/4cd1ac0976f6f1fa818095d1f4c8a68cbfe9aebc/package.json#L74).

Make sure `npm` is up to date (`npm -v` should be  3.10.7 or similar), then try deleting the entire `node_modules` directory and running `npm i` again.

If that doesn't work, run `npm ls` and pastebin the result.

**Comment by martixy** [comment]
Was 3.10.3. Updated to 3.10.8.

Removed `node_modules` and even did you one further with `git clean -xdf`.

Still errorrs out.

`npm ls`
http://pastebin.com/1WvG20Gk

**Comment by erikdesjardins** [comment]
Ah, I think see what it is now: try moving it to a path that doesn't include `!`.
(Webpack uses `!` to delimit paths from loaders...this may be a Webpack bug, paths should probably be escaped)

**Comment by martixy** [comment]
That is indeed the culprit.

I use `!` as a sorting thing for folders or files, I want to appear in the beginning. The thing is, I've previously successfully built RES in that path, so this is a new thing.

Build output reports webpack 1.13.2 which is the latest non-beta version.

**Comment by erikdesjardins** [comment]
Yes, Webpack (/taking advantage of ES6 modules) is a somewhat new addition to RES.

See also https://github.com/webpack/webpack/issues/684

Closing as there's no feasible way to solve this within RES.
