### ISSUE TITLE
Public imgur albums removed from gallery result in 404/reddit embed

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3419]
https://www.reddit.com/r/Enhancement/comments/5223rl/question_about_imgur_galleries/

If imgur gallery 404s, try again as album. maybe don't try if reddit post is from before 2016.

**Comment by erikdesjardins** [comment]
This should be as simple as adding the equivalent of ```.catch(() => api(`a/${id}`))``` wherever the gallery request is made.

I don't think we should bother checking post age; links to deleted imgur galleries in old reddit posts are rare [read: a tiny fraction of pageloads], so an extra erroring request or id conflict (if that's even possible here?) isn't worth worrying about IMO.
