### ISSUE TITLE
Link to github diff with previous release in Firefox release review notes

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3444]
A diff was requested by the last reviewer to ease the review process, since the webpacked version shipped to AMO is difficult to review.

**Comment by BenMcGarry** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/compare/v5.0.1...v5.0.2

**Comment by andytuba** [comment]
Reopening targeting 5.1.0 with the hope we can automate it.
