### ISSUE TITLE
Option to only apply comment depth if # comments > threshold

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3456]
threshold default of .. 50?
customizable per subreddit
option (enabled) to always apply depth if # comments not immediately available

**Comment by dhensche** [comment]
Is there work being done on this? I think I could put something together

**Comment by andytuba** [comment]
Go for it!

There should be a `Thing::getCommentCount` method, I think, which filteReddit customFilters uses. It might need to be added or improved for inbox. It should look at the number of comments listed in a post's "comments" button or on an inbox message's "full comments" button.

You could look at the context module for an example.
