### ISSUE TITLE
Handles Leak for RES on EDGE

### ISSUE THREAD

**Issue by RemiGC** [honestbleeps/Reddit-Enhancement-Suite#3457]
- My browser Edge: Microsoft Edge 38.14393.0.0 - Microsoft EdgeHTML 14.14393
- My RES version: 5.0.2
- Am I in reddit beta (yes/no): no

_What's the problem?_
RES leak handle when you run on Edge. 
Old screen shot http://i.imgur.com/DOk9cnH.png from 4.7.3
New screenshot from 5.0.2 http://i.imgur.com/eY5iEKA.png

_Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?_
Yes. I posted it 9 days ago here. https://www.reddit.com/r/RESissues/comments/51gnnt/bug_possible_handle_leaks_on_res_for_edge/

_What other browser extensions are installed?_
AdBlock plus. Tested with and without it and it still leaks.

**Comment by BenMcGarry** [comment]
I have been monitoring this over the past few weeks and it appears to be a non-issue on Insider Builds. Marking as closed but will continue to monitor up until stable.
