### ISSUE TITLE
"Unhandled promise rejection" breaking RES v5.0.2 on Firefox

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#3478]
As title states. Firefox was working fine until the automatic update triggered. 😢

**Comment by BenMcGarry** [comment]
Is this the one with the disable res, enable res and restart the browser fix @erikdesjardins?

**Comment by erikdesjardins** [comment]
Unhandled promise rejection could be anything, probably the majority of errors log that.

@mc10 see if this works https://www.reddit.com/r/RESissues/comments/53tdjr/res_doesnt_work_for_me_on_firefox/

Or maybe try to see if anything else gets logged first...Firefox probably strips everything off of the error though

**Comment by mc10** [comment]
Hmm seems like a new "update" triggered and fixed the issue, so closing for now. The error messages in the browser console were very undescriptive when I checked them out earlier, so hopefully this doesn't reproduce?
