### ISSUE TITLE
Automate adding safari/Icon.png to 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3480]
1. Add safari/Icon.png
1. Make sure `gulp zip` or something copies that file into `dist/safari/Icon.png

Context:
> https://developer.apple.com/library/content/documentation/Tools/Conceptual/SafariExtensionGuide/ExtensionsOverview/ExtensionsOverview.html#//apple_ref/doc/uid/TP40009977-CH15-SW1
> ## The extensions part list
> **Icon**—The icon for your extension. Name the image file `Icon.png`. Every extension must have a custom icon, which should be at least 64 x 64 pixels in size; the icon image will be scaled up or down as needed. You can also supply additional images optimized for display at particular sizes.

**Comment by erikdesjardins** [comment]
We can put a comment in the .plist and have the existing build take care of it:

```
<!-- {{./Logo.png}} -->
```
