### ISSUE TITLE
make more friendly names for the settings

### ISSUE THREAD

**Issue by Haroenv** [honestbleeps/Reddit-Enhancement-Suite#3483]
Each of the settings is now a camel cased string, but it's probably quite trivial to change that to a regularly readable with something like [sugarjs](https://github.com/andrewplummer/Sugar/blob/2.0.0/lib/string.js#L1002) or underscore.

**Comment by andytuba** [comment]
http://stackoverflow.com/questions/7225407/convert-camelcasetext-to-camel-case-text

maybe also a `displayName` option

Should be used in:

* "Edit option" view in settings console
* "Search for options" view in settings console
* "Share to comment" from settings search in settings console

**Comment by erikdesjardins** [comment]
Also https://lodash.com/docs/4.16.2#lowerCase or https://lodash.com/docs/4.16.2#startCase (we already use lodash)

**Comment by Haroenv** [comment]
If lodash is already used that seems like a logical choice

**Comment by lcrossan** [comment]
Hey, I'd like to take this on if nobody else has it. Is this up for grabs?

**Comment by andytuba** [comment]
Go for it, @lcrossan ! 👍

**Comment by lcrossan** [comment]
@andytuba would you be able to point me at the code that handles this? thanks!

**Comment by andytuba** [comment]
@lacrossan https://github.com/honestbleeps/Reddit-Enhancement-Suite/find/master?q=Settings

Lemme find more specific pointers..

**Comment by ssonal** [comment]
@lcrossan I'm ready to pick this up if you haven't started yet.

**Comment by andytuba** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/settingsConsole.js#L539  here's where the option label text is set

**Comment by andytuba** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/settingsNavigation.js#L40

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/settingsNavigation.js#L55

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/settingsNavigation.js#L86

**Comment by andytuba** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/search.js#L171

**Comment by lcrossan** [comment]
Hey, I have it working for me. I'm having trouble pushing though -- mind giving me commit rights? Thanks!

**Comment by Haroenv** [comment]
Why no pull request @lcrossan?

**Comment by andytuba** [comment]
@lcrossan 

1. Fork the res repo on github (create your own copy on github) 
1. Push to your own fork. (you'll need to add your copy as a github remote) 
1. In github visit the repo home page and a little banner should appear prompting you to open a pull request.

**Comment by andytuba** [comment]
http://hisham.hm/2016/01/01/how-to-make-a-pull-request-on-github-a-quick-tutorial/ @lcrossan this might be useful although it presumes you forked first. You can either clone your fork locally and copy your changes, or add your fork as a remote to your existing local clone and push to it (imo cleaner but you have to learn a little more about using remotes).  Would you like more guidance on this?

**Comment by Haroenv** [comment]
Awesome!
