### ISSUE TITLE
Suddenly RES don't want to start in Firefox 49.0.1

### ISSUE THREAD

**Issue by mikhoul** [honestbleeps/Reddit-Enhancement-Suite#3491]
I report here cause I've seen lot of post about it in /r/RESissues and NO real answer at all

Here's one of those post:
https://www.reddit.com/r/RESissues/comments/5400u3/an_error_occurred_while_creating_the_indexeddb/

So I have the same issue since I upgraded to Firefox 48.02 or 49.01 from FF47 I'm not sure since about which update caused the bug since I 've updated from V48 to V49  on the same day.

Basically there is a real problem since I've seen many other RES users having this problem after upgrading to Firefox 49 when I was googling for a solution.

Here's a screenshot of my console with the errors highlighted ----> http://i.imgur.com/T3aHftx.png

Each time I reload a page RES try to write in the DB but fail so it does not "start" and the  message error happen... :cry:  

Since it happened for many user after FF49 update it's not related to the Mozilla bug IMO also I don't see any other program having problems with Firefox 49 and indexedDB.

Regards :octocat:

**Comment by erikdesjardins** [comment]
I answered [_that very post_](https://www.reddit.com/r/RESissues/comments/5400u3/an_error_occurred_while_creating_the_indexeddb/d7y332m?context=1) and my solution worked for OP. ಠ_ಠ

But let me tell you right now: I see no way that this can be fixed within RES. That message only shows up if `indexedDB.open` errors. And then there's nothing you can do. You can keep calling it, and it'll keep throwing errors. Firefox has no other stable storage APIs (`simple-prefs` is stable but far too limited).

**Comment by mikhoul** [comment]
@erikdesjardins  I understand what you are saying but Why only RES loss his DATA (or corrupt it ?) as often ?  :flushed:

I have lot of other addons that save data and they never become corrupt, the only addon that lose his setting so often is RES. 

I've use a very simple UserScript that use cookies to save his data https://github.com/spmbt/googleSearchExtraButtons

I never see before this technique maybe you should consider it since it would allow all browsers to use the same mechanism to save their data. :smiley_cat:  And moreover it's very reliable !

Regards ! :octocat:

**Comment by andytuba** [comment]
@mikhoul Thanks for the creative suggestion, but cookies are inappropriate for RES: as a large, complex extension, RES can store several megabytes of data and lots of private data. Cookies are max 4 kb and are sent to reddit on every request.

**Comment by mc10** [comment]
Closing for now; if the above solution doesn't work or if this is a recurring issue, feel free to reopen or create a new issue.
