### ISSUE TITLE
Can we get linked images/videos/etc. inside Twitter expandos to also expand?

### ISSUE THREAD

**Issue by Atario** [honestbleeps/Reddit-Enhancement-Suite#3492]
Most of the time in these cases all I care about is that image or what-have-you…

**Comment by andytuba** [comment]
If you're using Firefox, Mozilla requested disabling that feature because of security restrictions.

In the future, could you post these kinds of questions in [/r/Enhancement](https://www.reddit.com/r/Enhancement)? For bug reports, post to [/r/RESissues](https://www.reddit.com/r/RESissues).

**Comment by Atario** [comment]
Should I repost it there?

**Comment by andytuba** [comment]
Nah, but you could search for "twitter image" and get results like  https://www.reddit.com/r/Enhancement/comments/47cra1/i_wrote_a_greasemonkey_script_to_enable_twitter/
