### ISSUE TITLE
Add "saved" shortcut to subreddit manager

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3498]
https://www.reddit.com/r/Enhancement/comments/4glxm2/is_it_possible_to_create_a_link_to_my_saved/d8a1quh?context=3

- [ ] Optional, default enabled
- [ ] Only show when logged in

**Comment by bartw** [comment]
I created a pull request for this issue: https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3519
