### ISSUE TITLE
Hide multireddit nav menu if unused

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3499]
If users clicks a multireddit link from the left sidebar several times (5?) before clicking that nav menu, disable the nav menu module.

**Comment by dhensche** [comment]
I'd like to contribute on this, but I'm not 100% sure what the requested change is. Are you saying if a user clicks on a specific multi link from the left sidebar several times (5?) we should no longer show the nav menu that usually appears when they hover over the link?

**Comment by andytuba** [comment]
@dhensche Thanks for offering - check out the work I've done on #3587 and see if you have any suggestions?  I also changed the specifications to "show that menu less quickly/less often, and only disable if the user approves it."

**Comment by dhensche** [comment]
I really like the solution you are working on there. Adding the capability for feature enable/disable to be a bit smarter.
