### ISSUE TITLE
Unhandled promise rejection ReferenceError: 'URLSearchParams' is undefined

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3504]
Putting this in for reference in case it gets posted and for tracking.

Edge does not have support for the URL API ([it is currently in development](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/urlapi/)). 

Thus this error will be thrown whenever a youtube video is expanded.

**Comment by BenMcGarry** [comment]
Reference #3315

**Comment by erikdesjardins** [comment]
We can likely fix this on our side without unreasonable effort
