### ISSUE TITLE
HTML escaping on expandos

### ISSUE THREAD

**Issue by hillai** [honestbleeps/Reddit-Enhancement-Suite#3505]
- My browser: Chrome 53 on Windows 10
- My RES version: 5.0.2
- Am I in reddit beta (yes/no): nope

Hey there,
With all the new expandos that v5 brought, I think you should consider sanitizing the input from all these websites. Right now it seems like you just insert the text from the website straight into the HTML, no escaping - which can raise a security issue regarding XSS.
Case in point - [this xkcd description](http://i.imgur.com/wB0JpkE.png). Top is the RES expando, bottom is the xkcd transcriber bot.
Really appreciate you hard work so I wanted to bring this to your attention.
Best regards,

**Comment by Ajedi32** [comment]
Pretty sure this isn't an XSS issue, as RES [sanitizes HTML content in captions](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/showImages.js#L931).

More likely RES is mistakenly removing `<noun>` as a non-whitelisted tag (instead of just escaping it), or it might be an upstream issue with noembed related to #3384.

**Comment by andytuba** [comment]
@hillai Thanks for your concern! In the spirit of responsible disclosure, could you privately message /r/Enhancement with specific instances of XSS?

Let's keep this ticket open to investigate `<noun>`.

**Comment by thybag** [comment]
Probably best to but sure, but I suspect @Ajedi32 is correct in that the <noun> tag is just being stripped by the `safeHtml` sanitizer.

For info, raw output from noembed is https://noembed.com/embed?url=http://xkcd.com/524/
Example of expando: https://www.reddit.com/r/funny/comments/11wsnz/xkcd_party/

**Comment by erikdesjardins** [comment]
Yep, `<noun>` is not a whitelisted element so it's stripped by the sanitizer: https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/41f4e2f757e9d6d2bd1b5863b88d92847130806c/lib/vendor/HTMLPasteurizer.js#L30-L34

You can see this in the markup; there's no `<noun>` element, just whitespace:
![image](https://cloud.githubusercontent.com/assets/7673145/19163986/2e9c2854-8bcc-11e6-85af-7fa3a36d6840.png)

XKCD captions should probably be escaped so it stays plaintext.

**Comment by hillai** [comment]
@andytuba You're right, that'd definitely be more responsible. Noted.

Thanks for your responses, everyone, I'm glad this will be addressed :)
