### ISSUE TITLE
Don't auto-expand NSFW images in nsfw self-posts by default

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3508]
https://www.reddit.com/r/Enhancement/comments/561gw0/feature_request_dont_autoexpand_hotlinked_images/

**Comment by larsjohnsen** [comment]
An option could be added alongside with `autoExpandFirstVisibleNonMuted` (https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3306/files#diff-81e82c385dc9912064f4bc5e91b47e58R283) for `autoExpandNSFW`
