### ISSUE TITLE
Migrate Firefox data to WebExtensions with an embedded WebExtension

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3510]
Not viable for release until Firefox 51 is stable.

Looks like this is going to be the only way to migrate data: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions

Don't forget to add hasEmbeddedWebextension to package.json https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json

_keywords: web extension_

**Comment by BenMcGarry** [comment]
FF51 released - https://www.mozilla.org/en-US/firefox/51.0/releasenotes/

**Comment by dralley** [comment]
Developer guide to embedded WebExtensions:  

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions

**Comment by erikdesjardins** [comment]
That link is right on the second line of the original issue, but thanks...?

**Comment by dralley** [comment]
I somehow didn't notice that that was already posted.... time to get sleep...

**Comment by mc10** [comment]
Firefox 51 is now stable. We should begin this process, though we'll [technically have until Firefox 57](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/) until we are required to use WebExtensions.

**Comment by erikdesjardins** [comment]
Yep, I have a WIP branch locally, should have a PR next week
