### ISSUE TITLE
Use subreddit style by default should be off by default 

### ISSUE THREAD

**Issue by hdiwan** [honestbleeps/Reddit-Enhancement-Suite#3512]
The attached patch disables subreddit-specific styles by default.
[res.txt](https://github.com/honestbleeps/Reddit-Enhancement-Suite/files/518186/res.txt)

**Comment by andytuba** [comment]
Hi, thanks for the contribution, but could you make a real pull request?

**Comment by andytuba** [comment]
Hi, thanks for contributing, but this needs to be in the form of a real pull request and it should text whether the user has disabled subreddit styles globally first.
