### ISSUE TITLE
Download links don't work in Firefox

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3527]
https://www.reddit.com/r/Enhancement/comments/57p9o8/feature_request_can_the_download_button_actually/

~~This can't be fixed in general, but for imgur at least we can link to `i.imgur.com/download/<hash>` which sends `Content-Disposition: attachment`.~~ Perhaps it _can_, in fact, be fixed using extension APIs.

**Comment by Tarun80** [comment]
Firefox has supported `<a download>` since Firefox 20. W3Schools has more details about it. It also has a Try it Yourself where the functionality works just fine.

**Comment by erikdesjardins** [comment]
No, it's only same-origin. See https://bugzilla.mozilla.org/show_bug.cgi?id=874009.

So it doesn't work "just fine" if you replace the w3schools image with something you'd see on reddit, like https://i.imgur.com/vuV7oVb.jpg

**Comment by thesbros** [comment]
I think this could be fixed by using `chrome.downloads` (WebExtensions) or `Downloads.createDownload` (old API), depending on what RES uses.

**Comment by erikdesjardins** [comment]
@thesbros ooooh yes, it does look like that would work. RES doesn't use WebExtensions (yet) because there's no way to migrate settings (yet), see #3510.

**Comment by erikdesjardins** [comment]
I'd prefer not to use `Downloads.createDownload` because it requires importing another low-level `chrome` module, which may not play nice with e10s and will mean extra AMO security review, so this won't get fixed yet.

It will be revisited once we migrate to WebExtensions.

**Comment by thesbros** [comment]
Another solution could be to draw the image to a canvas, and then convert that into an image and download it. However it might just be better to wait for WE.
