### ISSUE TITLE
Fix Imagus incompatibility

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3530]
https://www.reddit.com/r/imagus/comments/54za6b/res_breaking_imagus_try_this_setting/

Because the sieve tries to get the image from the expando button's `cachedhtml`, we could fix this by copying all of reddit's expando button's `data` attributes into the markup for the RES expando button.

**Comment by dhensche** [comment]
I'd like to help with this, but I can't seem to replicate the issue. I left a comment on the reddit thread, but does anyone here know how I can test this issue?

**Comment by dhensche** [comment]
hmmm, I've logged out and hovering over i.redd.it links still pops open the Imagus expanded view. Here is a screenshot of behavior
<img width="1440" alt="screen shot 2016-10-22 at 11 38 55 am" src="https://cloud.githubusercontent.com/assets/387763/19620907/350d6202-984c-11e6-8d08-108a1e566287.png">

**Comment by dhensche** [comment]
The Imagus sieve configuration doesn't really have any documentation so I can't quite figure out how it is still working

**Comment by dhensche** [comment]
ahh, I think I see what the complaint is now. In that screen shot I was hovering over the reddit provided expando link (the lower link). I'm guessing the issue is that hovering over the main link does not pop up the image

**Comment by dhensche** [comment]
If you go to the reddit thread mentioned above, you can see the Imagus maintainer fixed the issue on the Imagus side in the latest release - https://www.reddit.com/r/imagus/comments/54za6b/res_breaking_imagus_try_this_setting/d942knd/

**Comment by erikdesjardins** [comment]
Confirmed here as well
