### ISSUE TITLE
Comment tools on live threads

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3532]
commentTools seems to be failing on locating the comment textarea

**Comment by tao-lu** [comment]
Would adding `[name=body]` to [findTextareaForElement](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/8ae5172088acce2f84ab1f554ac6e6486ea738e7/lib/modules/commentTools.js)'s filter solve the problem without introducing too many false positives? I'm not familiar with the codebase, sorry.

**Comment by andytuba** [comment]
Probably! Might also need to check the `.closest(...)` call right above the filter too.

**Comment by erikdesjardins** [comment]
@tao-lu yeah, that sounds like it would work. You'd also need to add a case to [this switch](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/8ae5172088acce2f84ab1f554ac6e6486ea738e7/lib/modules/commentTools.js#L344) with the character limit for live threads, if you haven't already.
