### ISSUE TITLE
RES stops working when auto update happens and user has not restarted browser/ has reddit open

### ISSUE THREAD

**Issue by mount2010** [honestbleeps/Reddit-Enhancement-Suite#3544]
- My browser (copy from https://www.whatismybrowser.com): Firefox 49
- My RES version: 5.0.3
- Am I in reddit beta (yes/no): No

_What's the problem?_
RES stops working when auto-update happens and user has not restarted the browser, or has Reddit still open. In some cases, the auto-update requires the user to restart the computer.

_Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?_
https://www.reddit.com/r/RESissues/comments/57qpmz/bug_res_stops_working_when_autoupdate_happens/

_What other browser extensions are installed?_
Not related to browser extensions.

**Comment by erikdesjardins** [comment]
Now that RES has switched completely to WebExtensions, it should no longer require a browser or computer restart on update.
