### ISSUE TITLE
Don't add post expando title if it matches the post

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3561]
https://www.reddit.com/r/AnimalsBeingJerks/comments/59d02v/got_the_family_together_for_a_christmas_photo/

![screen shot 2016-10-25 at 5 35 05 pm](https://cloud.githubusercontent.com/assets/455632/19709161/651bd566-9ad9-11e6-9cd7-6b3b15b21f2e.png)

**Comment by erikdesjardins** [comment]
Even in that example, the imgur album has a period that the title lacks...not sure how often this would work

**Comment by andytuba** [comment]
We could do a levenstein distance sort of thing. 95% match, don't show.

**Comment by erikdesjardins** [comment]
Levenshtein distance would be super useful for filters (and [fast-levenshtein](https://www.npmjs.com/package/fast-levenshtein) is tiny and has zero dependencies), but I'm still not convinced of this use-case.

The small possibility of confusion ("why do some imgur albums not display titles?"), and the marginal possibility that it hides titles (especially short titles) that aren't actually the same doesn't seem worth the (also marginal) benefit of not seeing the same title twice.

**Comment by vishva007** [comment]
Hi, 
Came here from hacktoberfest site. Can I look into this issue ?
Thanks
