### ISSUE TITLE
Set filteReddit NSFWFilter option display title to "NSFWFilter"

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3562]
https://i.imgur.com/HMCzaDB.png

**Comment by erikdesjardins** [comment]
It'll work if we change it to `NSFWFilter` (capital `F`) instead of `NSFWfilter`

**Comment by andytuba** [comment]
Yeah, but that's more work: updating references and adding a migration.

**Comment by deecewan** [comment]
![image](https://cloud.githubusercontent.com/assets/4755785/19716916/7c1c68b6-9ba1-11e6-88f8-5a3b22a1d84f.png)

can't reproduce this.  there's also no instance of `NSF Wfilter` in the codebase.

**Comment by erikdesjardins** [comment]
That's likely because you're not running a dev build (or haven't pulled recently)
