### ISSUE TITLE
Run integration tests on Edge

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3575]
It appears that we need Microsoft WebDriver to support extensions first: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9303555/

https://github.com/scottlow/Ignite2016#loading-extensions-in-webdriver

https://github.com/scottlow/Ignite2016/blob/master/Ignite%202016%20WebDriver%20Demo/IgniteWebDriverDemo/Program.cs

**https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages#automated-testing-with-webdriver**

**https://wiki.saucelabs.com/display/DOCS/Setting+Up+Pre-Run+Executables**

**Comment by erikdesjardins** [comment]
We need Edge 15 on Sauce Labs for this, which probably won't happen until a few weeks after it goes stable, so deferring to v5.7.x

**Comment by BenMcGarry** [comment]
Saucelabs now supports Edge 15, deferring to v5.10.x as we finalise current rel.

**Comment by BenMcGarry** [comment]
The ability to sideload extensions now exists in Edge webdriver under "ms:extensionPaths".

https://docs.microsoft.com/en-us/microsoft-edge/webdriver

**Comment by BenMcGarry** [comment]
https://github.com/SeleniumHQ/selenium/commit/8c1acbdd843eaab83802642d0fd6e460b9597cb2
