### ISSUE TITLE
Comment tools can't find textarea on ban page

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3581]
https://www.reddit.com/r/RESissues/comments/5axorn/bug_are_macros_supposed_to_work_on_ban_message/
https://www.reddit.com/r/RESissues/about/banned/

**Comment by dhensche** [comment]
looks like the `.ban-details` class is no longer finding a parent form/div for the textarea. Looks like the form could be selected with `#banned` or `.friend-add`. Any preference?
