### ISSUE TITLE
When video expando falls back to image the resize listener appears to be lost

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3603]
Test post: https://www.reddit.com/r/gifs/comments/5c7a1m/dream_of_every_pc_gamer/

Can repro in both Chrome and Firefox, appears to be browser-independent

![](https://cloud.githubusercontent.com/assets/7673145/20191976/e759d766-a755-11e6-9321-176a8e6ebdc8.png)

**Comment by larsjohnsen** [comment]
Fix hidden in https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3412/commits/48f4ce90a428b9dd5579689e23f44c18b2ad9d78
