### ISSUE TITLE
Notify if subscribed post is edited

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3622]
If a user has subscribed to new comment notifications on a post, and the post has been edited since the last visit to that page, then a notification should show. This should be optional and probably off by default. Is it worth making this optional by post?

https://www.reddit.com/r/Enhancement/comments/5dc290/does_res_notify_you_if_you_are_subscribed_to_a/

**Comment by Propheis** [comment]
Is this issue closed?

**Comment by erikdesjardins** [comment]
Yep, thanks
