### ISSUE TITLE
Post style buttons do not appear after second edit.

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3625]
https://www.reddit.com/r/RESissues/comments/5dltjl/bugedge_trying_to_edit_again_after_saving_first/

Confirmed repro'd on Edge.

**Comment by dhensche** [comment]
could be wrong, but it looks like maybe on the ajax post reddit is replacing the form/textarea so the edit bar and/or preview area are not attached to the new textarea. need to rebind after post?
