### ISSUE TITLE
Indicate that posts were filtered

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#363]
If a post listing has many/all posts filtered (> 70%?), then RES should add an indicator listing that the posts were filtered, maybe even reveal which filters in particular (nsfw, subreddit, domain, etc.; or an entry inside those options).  This message should include link/instructions to #!settings/filteReddit and nsfw filter toggle.

**Comment by erikdesjardins** [comment]
Fixed in #1826
