### ISSUE TITLE
Handle ajax errors more gracefully

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#365]
When reddit returns a 403 or other error for an ajax json request, RES should quit more gracefully.

This code is probably a good place to do it:

  GM_xmlhttpRequest({
                method: "GET",
                url:    location.protocol + "//"+ location.hostname+ "/user/" + RESUtils.loggedInUser() + "/about.json?app=res",
                onload: function(response) {
                    var thisResponse = JSON.parse(response.responseText);
                    var userInfoCache = {
                        lastCheck: now.getTime(),
                        userInfo: thisResponse
                    };
                    RESStorage.setItem('RESUtils.userInfoCache.' + RESUtils.loggedInUser(),JSON.stringify(userInfoCache));
                    while (RESUtils.loggedInUserInfoCallbacks.length) {
                        var thisCallback = RESUtils.loggedInUserInfoCallbacks.pop();
                        thisCallback(userInfoCache.userInfo);
                    }
                    RESUtils.loggedInUserInfoRunning = false;
                }
            });

relevant discussion: http://www.reddit.com/r/Enhancement/comments/1cf7yw/comment_karma/c9gdrc8

**Comment by erikdesjardins** [comment]
Ajax error handling significantly improved in #2684
