### ISSUE TITLE
Don't use jQuery.fn.data to read data-attributes

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#3662]
...because it behaves "cleverly" for `'true'`, `'123'`, etc.

Causing issues related to (but not as reported): https://www.reddit.com/r/Enhancement/comments/5eju98/why_does_filtering_r195_make_reddit_not_load_at/
Namely: you can't filter /r/195 from the subreddit info hover

**Comment by andytuba** [comment]
Yeah, subreddit info should maybe attach the data blob, or a lookup id, to the subreddit info popup.

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/subredditInfo.js#L188
