### ISSUE TITLE
Hide list of filtered subreddits on /r/all

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3697]
https://www.reddit.com/r/Enhancement/comments/5frpng/how_do_i_get_rid_of_the_new_filtered_text_on_rall/

Possibly implement a way to have the css snippet applied with a toggle?

**Comment by alexvanolst** [comment]
Reddit has hidden this by default on their end. Can probably close this.

**Comment by erikdesjardins** [comment]
Yep, thanks @andytuba 😉
