### ISSUE TITLE
Filter by flair or keyword broken

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3716]
https://www.reddit.com/r/Enhancement/comments/5go3at/announcement_res_v520_release/datt2xs/?context=3

**Comment by andytuba** [comment]
I think I confirmed flair not working, haven't tested keyword.

**Comment by larsjohnsen** [comment]
Appears to be an issue with case sensitivity (subreddit DnD is tested as if `dnd`, which doesn't match)
