### ISSUE TITLE
Reddit Enhancement Suite does nothing

### ISSUE THREAD

**Issue by inunah** [honestbleeps/Reddit-Enhancement-Suite#3728]
- My browser (copy from https://www.whatismybrowser.com): Chrome 55 on Windows 8.1
- My RES version: 5.2.0
- Am I in reddit beta (yes/no): No

*What's the problem?*
When RES is enabled, nothing changes. No expandos, night mode is gone, and all of my extra features aren't there. This was not happening prior to the release of 5.2.0.

I have disabled all of my extensions except for RES. I have reinstalled the extension. I have restarted my browser. I have restarted my computer. I have disabled then enabled RES. None of these things resulted in any change or resolution.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
Yes. https://www.reddit.com/r/RESissues/comments/5gq5c2/res_is_not_loading_up/

*What other browser extensions are installed?*
C.H.I.P. Flasher (flashes C.H.I.P and PocketC.H.I.P. devices to a new firmware)
Easy SteamGifts (enables one-click entering for giveaways on steamgifts.com)
Magic Actions for YouTube (enhances YouTube with a customizeable theater experience)
New XKit (enhances all of Tumblr's features)
Reddit Enhancement Suite (you know this one)
Smile Always (redirects all Amazon URLs to their smile.amazon.com equivalents)
Steam Database (adds database info to every Steam store page)
Stylish (allows you to customize any website's CSS - has not been used for Reddit)
uBlock Origin (adblocker)

**Comment by Ajedi32** [comment]
Could you open the JavaScript console (Ctrl + Shift + J), refresh the page, and take a screenshot?

Once user in the linked Reddit thread provided the following screenshot: ![Uncaught (in promise) TypeError: Object.values is not a function](https://i.imgur.com/1FAkehB.png) It'd be interesting to see if you're getting a similar error.

**Comment by inunah** [comment]
Got an identical error.

![image](https://cloud.githubusercontent.com/assets/14948772/20952959/bfb8c898-bbf5-11e6-8c33-c19e4bd4814b.png)

I did not have #enable-javascript-harmony enabled, so I enabled it. No change.
I did not have #disable-javascript-harmony-shipping enabled, so I enabled it. No change.
I enabled both of them together. No change. I re-disabled them.

I had  #enable-experimental-canvas-features enabled, so I disabled it. No change.
I had #disable-accelerated-2d-canvas enabled, so I disabled it. No change.
I had #enable-fast-unload enabled, so I disabled it. No change, so I re-enabled it.
I had #disable-hyperlink-auditing enabled, so I disabled it. No change, so I re-enabled it.

Suddenly, the issue was fixed.

At this point I realized I had to restart for each change, so I restarted Chrome. One or both of those two canvas features was the problem, I'm guessing.

**Comment by Ajedi32** [comment]
Yeah, these flags have broken stuff for people in the past. When Chrome says "Careful, these experiments may bite" they really do mean it. Perhaps we should add "go to `chrome://flags/`, click `Reset all to default` then restart your computer" to our list of standard troubleshooting steps.

**Comment by mc10** [comment]
Closing, as issue was fixed.
