### ISSUE TITLE
Empty custom toggles interfere with other toggles. 

### ISSUE THREAD

**Issue by creesch** [honestbleeps/Reddit-Enhancement-Suite#3732]
- My browser: Chrome
- My RES version: 5.2.0
- Am I in reddit beta (yes/no):  yes

*What's the problem?*
https://usercontent.irccloud-cdn.com/file/HXfWLJm0/2016-12-06_11-19-49.mp4

Having an empty custom toggle in your settings makes it so other toggles don't seem to work properly anymore. 

![image](https://cloud.githubusercontent.com/assets/2502190/20921929/97aba2f2-bba6-11e6-998f-47bb03a51cf9.png)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Not as far as I can tell.

*What other browser extensions are installed?*

Tested with only RES enabled.

**Comment by andytuba** [comment]
This is useful QA, thanks!

... But why leave in an empty row? 😂

**Comment by creesch** [comment]
I dunno, it was in there for some reason.
