### ISSUE TITLE
Cannot turn off multireddit badge.

### ISSUE THREAD

**Issue by creesch** [honestbleeps/Reddit-Enhancement-Suite#3733]
5.2.0 a feature was added that adds a badge displaying the number of multireddits a subreddit is in next to the subscribe button. Specifically this commit I believe https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/4dea07c1388bf5068bd1f71bc47170e35d0981be

Which is fine but I have absolutely no need for it and would like to turn it off (as I can with any other option in RES). This one doesn't have that option.

Even more so because it does seem to do api requests https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/subredditManager.js#L1352 on each page load you might want to consider not turning it on by default.

**Comment by creesch** [comment]
Seems like that is already covered by #3721

**Comment by erikdesjardins** [comment]
yep
