### ISSUE TITLE
Filterline F vs "go to frontpage" F

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3753]
1. If goMode is enabled and active, F shouldn't show filterline command line
2. If goMode is disabled, ... does filterline or frontpage win?

http://redd.it/5h2mt7

@larsjohnsen

**Comment by erikdesjardins** [comment]
Oh hey, #3909 fixed part of this. Now situation 1 works as expected.

Not sure what we can really do for situation 2. Migrate the filterline shortcut to something else for everyone that has useGoMode disabled?

**Comment by larsjohnsen** [comment]
This would remove (blank) the shortcut for the options that wasn't chosen. Thoughts?
 
![image](https://cloud.githubusercontent.com/assets/1748521/22178565/41d2f73c-e03a-11e6-88ab-97232247d774.png)

**Comment by andytuba** [comment]
How about a more conversational tone?  

> RES isn't sure what to do when you press the keyboard shortcut `F`. What should pressing `F` do?
> [button] 
> [button]
> (You can change this later from the \[keyboard navigation settings](#res:settings/keyboardNav).)
