### ISSUE TITLE
Update the Safari extension on Apple's site.

### ISSUE THREAD

**Issue by bumblebritches57** [honestbleeps/Reddit-Enhancement-Suite#3758]

**Comment by andytuba** [comment]
Are you looking for notifications when RES 5.2 gets pushed to Apple gallery, or just signal-boosting that it still needs updating?

**Comment by bumblebritches57** [comment]
I downloaded the zip and installed it myself, I posted to remind you guys. the one on Apple's extension page is 5.0.2.

**Comment by BenMcGarry** [comment]
https://www.reddit.com/r/RESAnnouncements/comments/5go2xd/announcement_res_v520_release/

**Comment by andytuba** [comment]
This duplicates the existing release todo issue: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/3677
