### ISSUE TITLE
"New Releases" tab opening every single time I visit a new page on Reddit

### ISSUE THREAD

**Issue by twchapman** [honestbleeps/Reddit-Enhancement-Suite#3767]
- My browser (copy from https://www.whatismybrowser.com): Chrome 54 on Windows 10
- My RES version: v5.2.1
- Am I in reddit beta (yes/no): no

*What's the problem?*
The "New Releases" tab opening every single time I visit a new page on Reddit, even after I've closed it, so I just end up with a whole bunch of them when I try to navigate somewhere new.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
Not that I could see.

*What other browser extensions are installed?*
Just ublock.

**Comment by erikdesjardins** [comment]
Run https://reddit.com/#res:settings/troubleshooter/testEnvironment and paste the results here.

**Comment by twchapman** [comment]
```
Private browsing: false

Sending multicast: 0.21988190836163568

Storage.set(): 0.7216450787621831
Storage.get(): null
Storage.has(): false
Storage.delete()
Storage.get(): null
Storage.has(): false

Session.set(): 0.7254436118702177
Session.get(): 0.7254436118702177
Session.has(): true
Session.delete()
Session.get(): undefined
Session.has(): false

wrapped.set(): 0.21791468885474874
wrapped.get(): default
wrapped.has(): false
wrapped.delete()
wrapped.get(): default
wrapped.has(): false

domain.set(): 0.79862600284539
domain.get(): default
domain.has(): false
domain.delete()
domain.get(): default
domain.has(): false
```

**Comment by erikdesjardins** [comment]
Hmm yes we've seen a few cases of this, where `chrome.storage` fails to store anything but doesn't set `chrome.runtime.lastError`.

Try [backing up your settings](https://reddit.com/#res:settings/backupAndRestore), [resetting to factory](#res:settings/troubleshooter/resetToFactory), then restoring your settings.

**Comment by twchapman** [comment]
That didn't seem to do it  :(

**Comment by andytuba** [comment]
Dang. Try uninstalling RES entirely, then reinstalling and restoring your settings?

**Comment by twchapman** [comment]
It seems to have stopped now - I wonder if I just didn't refresh the page after resetting to factory, but it's not popping up anymore. Thanks folks, appreciate the fast responses!

**Comment by andytuba** [comment]
> didn't refresh the page after resetting to factory

Sounds likely, I should've remembered to advise restarting Firefox after.

Glad you got it sorted!
