### ISSUE TITLE
loggedInUser should pull from username link, not text content

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3789]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/3d23be61b4f10b85993bb6866dfa2a2069b79c27/lib/utils/user.js#L10

Don't pull the text Content, that can get manipulated by other extensions.  Instead, extract the username from the link href

**Comment by gardnm4** [comment]
@andytuba I think this is closed now since Issue #3792 fixed it.

**Comment by andytuba** [comment]
@gardnm4 This issue can be closed as soon as that PR is merged.
