### ISSUE TITLE
Optionally double-click tagline to toggle content collapsed/visible

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3798]
https://en.reddit.com/r/Enhancement/comments/5in329/feature_request_double_click_comment_header_to/db9xwg8/?context=3

**Comment by jakewilson** [comment]
I think I can handle this. Which comment module would this go in? 'Editing tools' or 'Hide All Child Comments'? Or perhaps create a new one?

**Comment by andytuba** [comment]
A new module sounds appropriate. Maybe combine it into a module with @KetillG, who indicated interest (via modmail) in integrating [full-height comment toggle](https://github.com/KetillG/RedditMin)?

**Comment by KetillG** [comment]
Yeah, that sounds great. Would love to join and learn how this all works!
