### ISSUE TITLE
Expando for YouTube live stream URLs

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3810]
https://www.reddit.com/r/Enhancement/comments/5jh9fn/request_support_youtube_live_stream_expandos/

**Comment by gardnm4** [comment]
While looking into this I came across an issue. Live streams can happen in three types of URL: two of them RES can handle (`https://youtube.com/watch?v=IDCODE` and `https://youtu.be/IDCODE`) but the third is `https://www.youtube.com/c/CHANNELNAME/live` which it cannot handle. The first two types (`https://youtube.com/watch?v=IDCODE` and `https://youtu.be/IDCODE`) are for the standard uploaded and not-live videos.

When a live video ends and it was linked to reddit using either of these two supported urls, it will still have that url and the link will still work. However, with the third type, `https://www.youtube.com/c/CHANNELNAME/live`, it is directing to the current live stream of the channel. So if the live stream ends, it will default to the channel.

**Comment by gardnm4** [comment]
Did a bit more looking and it looks like you can use Google's Youtube Data API to get the IDCODE from a channel if you know the channelID for the live video posted. However you need to know the channelID, not the Channelname.

If you know the ChannelID and request a snippet, you get a JSON in this format:

{
  "kind": "youtube#searchResult",
  "etag": etag,
  "id": {
    "kind": string,
    "videoId": string,
    "channelId": string,
    "playlistId": string
  },
  "snippet": {
    "publishedAt": datetime,
    "channelId": string,
    "title": string,
    "description": string,
    "thumbnails": {
      (key): {
        "url": string,
        "width": unsigned integer,
        "height": unsigned integer
      }
    },
    "channelTitle": string,
    "liveBroadcastContent": string
  }
}

The key part in this is the item "liveBroadcastContent" which has 3 values, which includes the value "live", and the item "videoId" which has the value needed for embedding the video.

The only problem is that we need an API_key for this...

**Comment by WilliamChiu** [comment]
Given `https://www.youtube.com/channel/CHANNELID/live` , `https://www.youtube.com/embed/live_stream?channel=CHANNELID` seems to work: http://stackoverflow.com/questions/39275889/how-to-embed-new-youtubes-live-video-permanent-url.
