### ISSUE TITLE
[Regression] Vote Enhancements -> user defined comment karma coloring doesn't properly style negative values

### ISSUE THREAD

**Issue by SirNeon618** [honestbleeps/Reddit-Enhancement-Suite#3811]
- Firefox 53.0a1
- RES 5.2.2
- Not in Reddit Beta.

I had yellows, oranges, and reds assigned to -10/-100/-1000 for comment karma coloring and blue for 0. After a recent update the yellows/oranges/reds stopped being applied to the scores and the blue of 0 gets applied instead. I suspect [this](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/3714) might have broken it, but I'm not 100% sure. The colors for positive values get applied as expected.

**Comment by andytuba** [comment]
This was a reddit bug which has been fixed: https://www.reddit.com/r/RESissues/comments/5hczwd/bug_color_comment_score_no_longer_works_on_user/db7p2bt/
