### ISSUE TITLE
It is impossible to open gear menu under Microsoft Edge on touch devices

### ISSUE THREAD

**Issue by wojtekmaj** [honestbleeps/Reddit-Enhancement-Suite#3833]
- My browser (copy from https://www.whatismybrowser.com):
- My RES version:
- Am I in reddit beta (yes/no): 

*What's the problem?*

The gear menu opens on hover. Edge (and IE), when using touch device, unlike other browsers, assumes that hovering event ends as soon as you lift your finger from the element.
You can theoretically open the menu by clicking on it, however, before you "click" it with your finger, hover event fires up, so clicking hides the menu split second later. That makes it impossible to use gear menu.

I suggest simply removing hover action. It uses a slight delay before opening, so I always try to click the menu, and I end up closing it because it opens while my brain is processing ;)

I think it could be done as a part of #3553 

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

*What other browser extensions are installed?*

**Comment by andytuba** [comment]
I'd agree with disabling the hover trigger by default.

**Comment by BenMcGarry** [comment]
Even though #4233 helps resolve the issue, it is still hard to open the cog menu on Edge with touch.
