### ISSUE TITLE
Remove external RES stylesheet

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3852]
https://cdn.redditenhancementsuite.com/updates.css

With the rate we can release patches now is it really still needed?

**Comment by andytuba** [comment]
Yep, let's migrate it away.

**Comment by BenMcGarry** [comment]
Once this has been removed is cloudflare still required for the website?

**Comment by honestbleeps** [comment]
yes, I believe so, to shield github pages from being overwhelmed with bandwidth usage.

**Comment by BenMcGarry** [comment]
I believe we still need to merge some changes that are on the css file.

https://github.com/Reddit-Enhancement-Suite/hotfix-data/blob/master/css/RESUpdates.css

**Comment by mc10** [comment]
Once this is done, #3323 can be closed.

**Comment by BenMcGarry** [comment]
Resolved in #3858
