### ISSUE TITLE
Night mode causes line numbers in a code block to disappear.

### ISSUE THREAD

**Issue by tance77** [honestbleeps/Reddit-Enhancement-Suite#3893]
Night mode causes line numbers in a code block to disappear.

Edit: sub that uses code blocks 

https://www.reddit.com/r/learnprogramming/comments/5oc8v3/pythonflask_oauth2_missing_access_token/

**Comment by gavin19** [comment]
Can you point to a sub that uses that CSS?

**Comment by tance77** [comment]
@gavin19 here is an example sub 
https://www.reddit.com/r/learnprogramming/comments/5oc8v3/pythonflask_oauth2_missing_access_token/

**Comment by WilliamChiu** [comment]
To show the line numbers, you could click "Use subreddit style".
