### ISSUE TITLE
"Post is spoiler" custom filter

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3894]
https://www.reddit.com/r/cssnews/comments/5ojv90/upcoming_css_change_spoiler_tags/

**Comment by preethamrn** [comment]
Would this be a filter like the NSFW filter in filteReddit?

**Comment by andytuba** [comment]
I was primarily thinking of adding it to [postCases like `isNSFW`](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/daf566f36884e76a37bf224e3164d0d248955c99/lib/modules/filteReddit/postCases.js#L349). It may be worth adding it as a menu toggle-activated filter, like the nsfw filter.
