### ISSUE TITLE
Edge bugs with arrow function destructuring

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3919]
Revisit at Creators to see if issue has been resolved to reverse commit ~~#3918~~ #4102

External Reference: https://github.com/Microsoft/ChakraCore/issues/2401 and https://github.com/Microsoft/ChakraCore/issues/2606

**Comment by BenMcGarry** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/93fec936a1da5cca5403586b1f0229c1cf17ec60/lib/utils/alert.js#L43 Use before Dec

**Comment by BenMcGarry** [comment]
@erikdesjardins Looks like this has been resolved on 16237

**Comment by erikdesjardins** [comment]
Alright, I'll add it to a milestone and we'll keep pushing it back until Edge 16 is stable

**Comment by BenMcGarry** [comment]
Edge 16 has October 17th release.

**Comment by BenMcGarry** [comment]
#4102 can now be reversed.
