### ISSUE TITLE
Some expandos are not working

### ISSUE THREAD

**Issue by WilliamChiu** [honestbleeps/Reddit-Enhancement-Suite#3935]
- My browser (copy from https://www.whatismybrowser.com): Chrome 55 on El Capitan
- My RES version: 5.3.6
- Am I in reddit beta (yes/no): yes

*What's the problem?*
Permissions prompt doesn't show up for xkcd, theres some ajax issue with gfycat, and something about imgur gifv-s is 😖 

https://www.reddit.com/r/test/comments/5q71lc/test/

**Comment by erikdesjardins** [comment]
Any relevant console logs? All of those work for me 😕 (5.3.6, Chrome 55.0.2883.87 and 58.0.2991.0).

**Comment by WilliamChiu** [comment]
```
showImages: could not create expando for http://i.imgur.com/OhmTjA7.gifv
(anonymous) @ showImages.js:183
showImages.js:184TypeError: Cannot read property 'status' of undefined
    at ajax.js:85
    at Generator.next (<anonymous>)
    at step (ajax.js:114)
    at ajax.js:114
(anonymous) @ showImages.js:184
https://events.redditmedia.com/v1?key=RedditFrontend1&mac=ce9b9a42cc2356c35af0d154f88f9a2f58aab3134935cb2bc53084a48945c71e Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
showImages.js:183showImages: could not create expando for https://gfycat.com/BlueLimpBabirusa
(anonymous) @ showImages.js:183
showImages.js:184TypeError: Cannot read property 'status' of undefined
    at ajax.js:85
    at Generator.next (<anonymous>)
    at step (ajax.js:114)
    at ajax.js:114
(anonymous) @ showImages.js:184
https://events.redditmedia.com/v1?key=RedditFrontend1&mac=72954f7a77889c70c709c4179ace8ee8cee1c2c0d693d215e4143892f1b2ac59 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
chrome-extension://llplcemmngjfdjhhbmgnmkmodckilnpi/main.entry.js:175469 showImages: could not create expando for https://xkcd.com/1421/
(anonymous) @ chrome-extension://llplcemmngjfdjhhbmgnmkmodckilnpi/main.entry.js:175469
chrome-extension://llplcemmngjfdjhhbmgnmkmodckilnpi/main.entry.js:175470 Error: Permission not granted for: https://xkcd.com/*/info.0.json
    at Object.<anonymous> (chrome-extension://llplcemmngjfdjhhbmgnmkmodckilnpi/main.entry.js:156123)
    at Generator.next (<anonymous>)
    at step (chrome-extension://llplcemmngjfdjhhbmgnmkmodckilnpi/main.entry.js:156087)
    at chrome-extension://llplcemmngjfdjhhbmgnmkmodckilnpi/main.entry.js:156087
```

**Comment by erikdesjardins** [comment]
`Cannot read property 'status' of undefined` (from `response.status`)

There is no possible code path where `response` can be undefined, which suggests to me that something is going wrong with generator resume values (a Chrome bug we've seen before...). That would also neatly explain the XKCD permissions: you _have_ granted them, but the `true` becomes undefined, so it thinks you haven't.

On `chrome://flags/`, what are `#disable-javascript-harmony-shipping`, `#enable-javascript-harmony`, `#enable-ignition`, and `#v8-cache-options` set to?

**Comment by erikdesjardins** [comment]
Also, it seems as though Chrome 56 was just released, can you try that?

**Comment by WilliamChiu** [comment]
Running 'npm install' solved the issue 😰
