### ISSUE TITLE
Don't show "jump to add comment" button if "add comment" form is missing

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3943]
e.g. on a comment permalink page or if banned from a subreddit

**Comment by preethamrn** [comment]
I just tried testing this and it seems to work already. Should this be closed?

**Comment by andytuba** [comment]
Try it on a comment permalink: https://www.reddit.com/r/pics/comments/5qh8q0/wife_asked_me_to_check_if_the_chickens_laid_any/dcz95db/

**Comment by erikdesjardins** [comment]
reddit still renders the textarea and just hides it with `display: none` 😠 

Simplest way to check if it's visible is probably `commentArea.offsetParent`
