### ISSUE TITLE
res.css hanging on Safari 10.0.3 OSX 10.11.6

### ISSUE THREAD

**Issue by chicagobob** [honestbleeps/Reddit-Enhancement-Suite#3970]
- My browser: https://www.whatismybrowser.com/w/S48WD4G
- My RES version: 5.2.2 (direct)
- Am I in reddit beta (yes/no): no

*What's the problem?*

Recently reddit started to hang when attempting to load when RES is enabled.

According to dev tools rss.css is failing to load, see attached screen shot.
![screen shot 2017-02-02 at 10 05 50 pm](https://cloud.githubusercontent.com/assets/873698/22579297/96b65ee8-e994-11e6-8bc4-08cc251f4c98.png)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

NO

*What other browser extensions are installed?*
TwitterSSL, ClickToFlash, AdBlock, 1Password, Ghostery, Pinbar, CustomReader,

**Comment by andytuba** [comment]
You should just delete that row from **[loadStylesheets](#res:settings/stylesheet/loadStylesheets)** -- [](#gear) [RES settings console](#res:settings) > Appearance > [Stylesheet Loader](#res:settings/stylesheet "stylesheet") > [loadStylesheets](#res:settings/stylesheet/loadStylesheets)

It's getting removed in the next release.

**Comment by chicagobob** [comment]
I just looked, that row doesn't exist there.  Is there another place res.css might be getting picked up from? I quit and restart Safari.  Delete RES and reinstall and for a while it work, but then it eventually gets hung on loading that resource.   Thanks for any other suggestions.

**Comment by andytuba** [comment]
Oh, sorry, I misread your screenshot as pointing at https://cdn.redditenhancementsuite.com/updates.css.  I don't have an immediate answer for you. Maybe try disabling Adblock?

**Comment by chicagobob** [comment]
OK will try it.  I rebooted and everything is working for the moment, but usually after a few hours it starts hanging again.
