### ISSUE TITLE
5.4.0 Endgame

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3977]
5.4.0 target Wed 8th Feb, 5.3.8 final beta.

- [x] Resolve remaining issues https://github.com/honestbleeps/Reddit-Enhancement-Suite/milestone/27
- [x] ~~Announcement Post?~~
- [x] Changelog #3982
- [x] Chrome Submit - Automated
- [x] Edge Submit - @BenMcGarry
- [x] Firefox Submit - Automated
- [x] Opera Submit @honestbleeps (delayed, travelling)

**Comment by erikdesjardins** [comment]
I'm not sure if we need an announcement post this time, there haven't been any major changes (unless I've forgotten)
