### ISSUE TITLE
Check for new notifications/messages at regular intervals

### ISSUE THREAD

**Issue by aarzee** [honestbleeps/Reddit-Enhancement-Suite#398]

**Comment by erikdesjardins** [comment]
Closing as RES checks for new messages on new pageloads and NER pages, and (semi) realtime messages can be had with [native reddit notifications](https://www.reddit.com/prefs/#live_orangereds) or [companion](https://chrome.google.com/webstore/detail/companion-for-reddit/hjndgefhmfcgpoocjcgoemphhdkbhipm)
