### ISSUE TITLE
After clicking 'show child comments,' Enter stops working as 'collapse comments.'

### ISSUE THREAD

**Issue by decadent** [honestbleeps/Reddit-Enhancement-Suite#3992]
- My browser (copy from https://www.whatismybrowser.com): Chrome 55 on Mac OS X (El Capitan)
- My RES version: 5.4.1
- Am I in reddit beta (yes/no): no

*What's the problem?*
Have 'hide all child comments' enabled by default. Click a 'show child comments' link (cough [because no shortcut](/honestbleeps/Reddit-Enhancement-Suite/issues/1274) cough). Navigate comments with j/k, then press Enter—it hides back the comments expanded with that link, presumably because RES doesn't move keyboard focus from the link. Meanwhile the configuration has Enter as 'collapse comments,' as in collapse currently highlighted tree.

If you remap 'collapse comments' to another key instead of Enter, the behavior becomes more obvious: collapsing works, while Enter still presses the clicked link.

(If you click some other link instead of 'show child comments,' including links in child comments, the focus also won't move with j/k, and you'll have that linked clicked with Enter.)

Notably, before the update to 5.4.0, the behavior was similar in that after clicking on 'show child comments,' Enter pressed the same link again *until* you moved the selection with j/k—i.e. the keyboard focus was moved from the link. (Which also means that you couldn't collapse comments with Enter after clicking on a link without pressing j/k or clicking somewhere; a link here includes 'permalink' by the way—for example after clicking it with ctrl/cmd to open a comment in another tab.)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
Nope.

*What other browser extensions are installed?*
Checked with other extensions disabled—same thing.

**Comment by decadent** [comment]
Update: RES isn't moving keyboard focus with j/k on list pages too. Which means than if I clicked on a link to open it in another tab or right-clicked to copy the address, then shift-enter subsequently opens the same link in another window instead of opening the currently selected link. I have to click on empty space in a link entry to unfocus the link.

**Comment by erikdesjardins** [comment]
FWIW

>after clicking on 'show child comments,' [or any link] Enter pressed the same link again until you moved the selection

is not feasible to "fix" without breaking a11y, because it's not feasible to determine the intent of focusing--perhaps you want enter to follow the link because you tabbed to it, etc.
