### ISSUE TITLE
Add "popular" to sr manager if showing in vanilla bar

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#3997]
https://www.reddit.com/r/modnews/comments/5sghb1/introducing_popular/

> Logged in users will be able to access this list by clicking on “popular” in the top gray nav bar. We’re working on better integrating into the front page but we also want to get users access to the list asap! We are planning on launching this change early next week.

I'll get more details on what that'll look like.

**Comment by erikdesjardins** [comment]
#4024
