### ISSUE TITLE
Expando button inside spoiler selfpost text incorrectly adds candystripe

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#4016]
The selector targeting "post's expando button" just needs to be a little stricter.

**Comment by erikdesjardins** [comment]
The same thing happens for NSFW, I thought it was intended https://www.reddit.com/r/restests/comments/2yb8or/expandos/

Though I suppose if you've already expanded the parent then you probably know what to expect
