### ISSUE TITLE
[Safari] Is there a hotkey to get permalink of currently highlighted comment and put it in my clipboard?

### ISSUE THREAD

**Issue by nikitavoloboev** [honestbleeps/Reddit-Enhancement-Suite#4042]
- My browser : whatismybrowser.com/w/4DAKL5K
- My RES version: 5.0.2
- Am I in reddit beta (yes/no): I don't think so

*What's the problem?*

For example I have a comment selected like so : 

![2017-02-19 at 23 44](https://cloud.githubusercontent.com/assets/6391776/23107427/811138ee-f6fd-11e6-9088-eec7e8daceac.png)

Is it possible to press some hotkey and the permalink of that comment will be put in my clipboard?

I am using Safari. Thank you for any help.

**Comment by andytuba** [comment]
There isn't a hotkey for that, sorry. 

Additionally, we prefer you to post these kinds of questions in /r/Enhancement, and to use GitHub for confirmed issues or feature requests.
