### ISSUE TITLE
Add "selected" border to currently selected module in settings console

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#4048]
https://docs.microsoft.com/en-gb/windows/uwp/controls-and-patterns/nav-pane#tailoring

https://docs.microsoft.com/en-gb/windows/uwp/controls-and-patterns/images/nav_item_states.png

https://www.reddit.com/r/Enhancement/comments/5v7thx/hard_to_see_selected_on_left_in_res_settings/

**Comment by erikdesjardins** [comment]
(and make sure that it doesn't shift the title over)
