### ISSUE TITLE
Revert #4095 when Edge has native DOM 4 support

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#4096]
#4095

http://caniuse.com/#feat=dom-manip-convenience
http://caniuse.com/#feat=passive-event-listener
http://caniuse.com/#feat=matchesselector

**Comment by BenMcGarry** [comment]
Passive event listener support @ [16215](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/16215/)
