### ISSUE TITLE
New reddit "recommendations" don't play nice with nightmode

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#4120]
<img width="761" alt="s-l166-2615" src="https://cloud.githubusercontent.com/assets/5659793/24011140/4c098410-0a50-11e7-876d-aa231dc71529.png">

See: https://www.reddit.com/r/changelog/comments/5zrtnr/testing_community_recommendations/

**Comment by erikdesjardins** [comment]
Possibly fixed by reddit, but I can't get it to appear to test it https://www.reddit.com/r/changelog/comments/5zrtnr/testing_community_recommendations/df0mbbu/

**Comment by allthefoxes** [comment]
I'm in this A/B so I'll try and reproduce

**Comment by allthefoxes** [comment]
Courtesy of /u/tizorres, its mostly fixed https://i.gyazo.com/727131b941f810ae5c0d0bd841acd4b2.png

**Comment by erikdesjardins** [comment]
That seems good enough considering it's only a test at this point
