### ISSUE TITLE
Cordova app?

### ISSUE THREAD

**Issue by gunderson** [honestbleeps/Reddit-Enhancement-Suite#4137]
Have there been any attempts to wrap RES into a [Cordova](https://cordova.apache.org/) style webview app? Searching these [issues](https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues?utf8=%E2%9C%93&q=is%3Aissue%20cordova), [google](https://www.google.com/search?q=reddit+enhancement+suite+cordova&oq=reddit+enhancement+suite+cordova&aqs=chrome..69i57j69i64.8223j0j4&sourceid=chrome&ie=UTF-8) and [/r/enhancement](https://www.reddit.com/r/Enhancement/search?q=cordova&restrict_sr=on&sort=relevance&t=all) doesn't appear to.

In theory, it shouldn't be hard to shim the relevant parts of the [Chrome Extension API](https://developer.chrome.com/extensions/api_index) and inject RES into it's own webview as a sandbox. Then another webview opens Reddit that communicates back to the RES webview on load and message events, and for each exterior links you get a new webview (like most apps). Other than that, some styling would likely need to be updated. Anything else?

Am I missing some piece of the puzzle that's kept a solution like this from happening so far?

**Comment by honestbleeps** [comment]
Sorry, Cordova isn't a thing that will happen for a few reasons:

- it's drastically more difficult than just making a shim

- performance would likely be terrible, web-wrapped apps just don't perform that well especially when loading websites that aren't optimized for mobile performance

- the screen real-estate on a phone or even a tablet are drastically different from that of a desktop browser, which would require a massive amount of rethinking/redesigning - this is why reddit has a mobile version of the site that looks vastly different from desktop

- touch functionality would also be something we'd need to think long and hard about, even if the above weren't all huge problems (e.g. drag to resize images - not as simple on mobile)...

while the idea of RES on mobile sounds good as a quick thought, it just wouldn't work well. Especially as compared to a well crafted mobile app (for example: I like Reddit Sync, personally, on Android).
