### ISSUE TITLE
Drag resize for clips.twitch.tv disappears

### ISSUE THREAD

**Issue by fireattack** [honestbleeps/Reddit-Enhancement-Suite#4140]
- My browser (copy from https://www.whatismybrowser.com): Chrome 58 & Firefox 53 on Windows 7
- My RES version: 5.4.3
- Am I in reddit beta (yes/no): No

*What's the problem?*

The drag resize control on the bottom right corner for video iframe doesn't show up for Twitch clips any more. For example: https://www.reddit.com/r/DotA2/comments/61r7tp/newbees_4_man_vortex_burrowstrike/

![image](https://cloud.githubusercontent.com/assets/4130991/24373849/60177c22-12f8-11e7-82ac-51ba76e7e66d.png)

I'm pretty sure it worked before.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

No

*What other browser extensions are installed?*

I can reproduce this on a clean profile with no other extensions.

**Comment by erikdesjardins** [comment]
Twitch changed their URL format, so those are Reddit's embeds (#4086, fixed in #4087)
