### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by noplanman** [honestbleeps/Reddit-Enhancement-Suite#4177]
I have the situation where I have moved from Firefox Nightly to an earlier version, giving me the `IndexDB` error. Ok, that I understand and am fine with it.

Now, I have an export (RES->Backup) that I would like to import to the downgraded profile.
So I tried to completely remove RES and start from an empty install, then import from the backup.

My problem: How do I completely uninstall RES?!
I've removed the add-on, deleted the permanent storage files and reinstalled the plugin (restart of browser between each step).
Yet I still get an error regarding the `IndexDB`: `An error occurred while creating the IndexDB database.`

So clearly there is still something around that prevents RES from working.

If I start from a completely new profile, it works, but I would like to keep my existing profile for obvious reasons.

Thanks

**Comment by allthefoxes** [comment]
In the future, please post to /r/RESIssues

**Comment by erikdesjardins** [comment]
In theory, deleting that permanent storage folder should fix it; it has for me in the past, though it's possible that reverting from nightly corrupts a profile even more than it used to. The only thing I can say is to make sure that there are no firefox-related processes running when you delete it, not just that all windows are closed.

Unfortunately RES is completely at the whim of the browser to maintain/create/delete its database, so there's basically nothing we can do; this is more of a question/problem for Mozilla.
