### ISSUE TITLE
Post number not showing fully after 99

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#4200]
Numbers are there but cut off by content.

![](https://i.imgur.com/hpiLF8O.png)

**Comment by mc10** [comment]
Is this on a specific subreddit? The 100s look okay to me on the front page.

**Comment by BenMcGarry** [comment]
@mc10 I'm getting it on /r/all. Repro on Edge/Chrome

**Comment by mc10** [comment]
Hmm that's odd, I can't reproduce with either Firefox or Chrome. My guess is that the script that dynamically changes the CSS isn't running for some reason; should be [these lines in neverEndingReddit](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/4476ca06b578a97c79898be47bb486028d87c68b/lib/modules/neverEndingReddit.js#L426-L430). Do you have any non-default NER options on? Are there any errors in the browser console?

**Comment by BenMcGarry** [comment]
NER is at default and no errors. I can also repro on Firefox.

**Comment by BenMcGarry** [comment]
`width: 2.2ex;` is being applied on `body >.content .link .rank, .rank-spacer`. Disabling this solves it but content is mid-lined, is this ours?

**Comment by larsjohnsen** [comment]
@mc10 I can also repro. Since the rank width is correct without styling CSS, that block might be removed.

**Comment by mc10** [comment]
Hmm for me that style is present but is overridden by 
```
body.res > .content .link .rank {
  width: 3.3ex;
}
```
so the three-digits look okay. Is that inline style not appearing?

**Comment by BenMcGarry** [comment]
On mine i'm not seeing body.res

**Comment by BenMcGarry** [comment]
@mc10 what version of RES are you running?

**Comment by mc10** [comment]
Latest release v5.4.3.

**Comment by BenMcGarry** [comment]
Looks like this doesn't affect 5.4.3, but affects v5.5.x
