### ISSUE TITLE
Chrome: Unrecognized manifest key 'minimum_opera_version'.

### ISSUE THREAD

**Issue by dashed** [honestbleeps/Reddit-Enhancement-Suite#4209]
- My browser (copy from https://www.whatismybrowser.com): Chrome 59 on Mac OS X (El Capitan)

- My RES version: Using commit: d13a31e17b493e47614b7d5cd7b153133829a3d4 (master branch)
- Am I in reddit beta (yes/no): yes

*What's the problem?*

<img width="758" alt="screen shot 2017-05-06 at 2 17 44 am" src="https://cloud.githubusercontent.com/assets/139499/25770440/6e53f5ac-3203-11e7-9357-14ab1ceb8d5d.png">

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Not that I know of https://github.com/honestbleeps/Reddit-Enhancement-Suite/search?utf8=%E2%9C%93&q=minimum_opera_version&type=

*What other browser extensions are installed?*

Not related.

**Comment by BenMcGarry** [comment]
This is intended, as opera shares the came codebase as chrome, it allows us to set min versions. It does not affect the usage of RES.

**Comment by dashed** [comment]
I see. Thanks for the clarification 👍
