### ISSUE TITLE
showImages: mediaControls not visible on images

### ISSUE THREAD

**Issue by larsjohnsen** [honestbleeps/Reddit-Enhancement-Suite#4222]
Images get the `res-media-load-error` class added. Likely due to an `error` event erroneously being emitted. Appears to originate from https://github.com/honestbleeps/Reddit-Enhancement-Suite/compare/v5.5.4...v5.5.5

https://www.reddit.com/r/Enhancement/comments/69psii/expando_commands_to_rotatesavesearch_jpgs_have/

**Comment by rmansolino** [comment]
Media Controls is missing on static images (multiple sites); 

works for animated images, (multiple sites/formats)

**Comment by erikdesjardins** [comment]
I finished the bisection to #4056 (which isn't surprising).

Firefox doesn't like something about [the `template` element](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/8f03530/lib/utils/string.js#L54); changing it to a `div` fixes it (but then it may break in some circumstances).

Removing the `adoptNode()` call, `.remove()`ing the element (or `.parentNode.removeChild()`) before adopting it, replacing it with `cloneNode()` (or `cloneNode(true)`) don't help.

The event isn't enlightening:
![image](https://cloud.githubusercontent.com/assets/7673145/25789143/580a0442-337c-11e7-8ad9-9e3d3f3e90f9.png)
