### ISSUE TITLE
RES not working with Firefox 53.0.2 - XML Parsing Error: no root element found

### ISSUE THREAD

**Issue by asampal** [honestbleeps/Reddit-Enhancement-Suite#4239]
- Firefox 53.0.2, Windows 10 64 bit, Creators Update
- My RES version: 5.6.1
- Am I in reddit beta (yes/no): no

*What's the problem?*
On Reddit, there is no sign that that RES is installed even though Firefox says it is. It used to work until about a week ago. I've tried uninstalling, restarting Firefox, and reinstalling, but that didn't help. I get the following output in the console when a Reddit subreddit loads:

`XML Parsing Error: no root element found
Location: https://e.reddit.com/v1?key=RedditFrontend1&mac=73eca1540e516dd93b50dcf43a6c405f6e69b821473351b3f56f285adac6b31f
Line Number 1, Column 1:        v1:1:1`

When I click the v1:1:1, I get the following response:

```
<html>
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
  The resource could not be found.<br/><br/>
/v1


 </body>
</html>
```

**Comment by larsjohnsen** [comment]
The error you see is not related to RES (you'll see it without RES enabled too).

Could you see whether this solves your problem: https://www.reddit.com/r/RESissues/comments/6a8oy6/res_suddenly_stopped_working/dhco25m/?context=3

**Comment by asampal** [comment]
I get the following:

```
"[["RES.i18nCachedMessages",99871],["ads.adserverDownvotePixel",54792],["ads.adserverUpvotePixel",3119],["ads.recent",37],["RES.i18nCachedMessagesToken",17],["plugin.RES.state",8],["ui.collapse.wikiactions",5],["search.restrict_sr.checked",5],["ui.shown.welcome",4],["newsletterbar.seen",4],["RES.i18nCachedLang",2],["rules_modal_on_comment_Vive",1],["rules_modal_on_submit_The_Donald",1]]"
```
I deleted the top two entries and RES is still not working. So you're saying my profile is toast?

**Comment by larsjohnsen** [comment]
It might only be your RES storage which is broken. You could try removing `./browser-extension-data/jid1-xUfzOsOFlzSOXg@jetpack/storage.js` in your Firefox profile directory.

**Comment by asampal** [comment]
I did that and nothing changed. Was the file supposed to be re-created? It doesn't seem to be.

**Comment by mc10** [comment]
Going to close due to inactivity; if this is still an issue; please feel free to recreate or reopen the issue.
