### ISSUE TITLE
keyboardNav can't scroll to bottom with directional scroll style

### ISSUE THREAD

**Issue by jrmrjnck** [honestbleeps/Reddit-Enhancement-Suite#4246]
- My browser: Chrome 58.0.3029.110 (64-bit) on Linux
- My RES version: 5.6.2
- Am I in reddit beta (yes/no): no

Problem: I use "directional" scrolling without "never ending reddit" or other features that auto load posts. Prior to [this change](https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/02155d5ccbc3b845053d41c3abf572e62157342c) I could move to the bottom of a link page by holding "j" until it stopped. Now, it's impossible to get to the bottom of the page without being very careful, since it automatically goes to the next page. I tried using the move bottom shortcut, but that seems to force a scroll style that puts the last link at the top of the window and leaves a huge blank area below. There is no longer an easy way to put the bottom link at the bottom of the window.

I would prefer that the moveDown action does not load the next page, since there is already a shortcut for that. Alternatively, the moveBottom action should follow the configured scroll style.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?* no

*What other browser extensions are installed?*

**Comment by larsjohnsen** [comment]
Can you tell a little about your use case which requires the last link to be placed at the bottom of the window?

**Comment by jrmrjnck** [comment]
A page of 25 links does not fit in one screen so some scrolling is needed. First I browse through the top half (e.g. 1-17) and then I browse the second half (e.g. 8-25) by using moveDown until the last link is brought into view. The moveBottom action will skip past 18-24. It's obviously much easier to spam moveDown until scrolling stops than to go one-by-one and carefully watch for #25, which is what I have to do now. Unless there is another keyboard action I've missed which will let me easily browse just 1 page of links?

**Comment by larsjohnsen** [comment]
I see. Using page down might work for you after completing the top half, so that the next part comes into view and you can continue downwards without having the viewport moving.

**Comment by jrmrjnck** [comment]
The generic browser Page Down is suboptimal for me:
1. It only shows 16-25 + blank space, rather than 8-25.
2. Requires moving my hand from the home row.

I don't understand the rational for having moveDown to go the next page, especially since moveUp does not have complementary behavior. There is already a shortcut to go to the next page, and people can also use never ending reddit to get more links.

**Comment by larsjohnsen** [comment]
I agree with you that navigating to the next URL when NER is disabled is a step too many. I'll see if I can change that soon.
