### ISSUE TITLE
RES buttons cannot be highlighted

### ISSUE THREAD

**Issue by Sir-Cumference** [honestbleeps/Reddit-Enhancement-Suite#4255]
- Chrome 58 on Mac OS X 10
- My RES version: v5.6.2
- Am I in reddit beta (yes/no): yes

*What's the problem?*
Small bug, but RES buttons cannot be highlighted/selected when holding your cursor and dragging over them, whereas reddit buttons can:

<img width="600" alt="screen shot 2017-05-20 at 10 46 58 pm" src="https://cloud.githubusercontent.com/assets/5375326/26280758/7de72096-3dae-11e7-8c7c-95de11d40e80.png">

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
None that I can find

*What other browser extensions are installed?*
None

**Comment by erikdesjardins** [comment]
This is intentional, so if e.g. you're ctrl-f'ing for "source" you actually get useful results.

Why do you want to select them?

**Comment by Sir-Cumference** [comment]
@erikdesjardins I don't particularly want to select them. I just thought I'd report a small inconsistency.

**Comment by erikdesjardins** [comment]
If you want consistency you can enable `doNoCtrlF` (which makes reddit's buttons also unselectable).
