### ISSUE TITLE
RES's Stylesheet Loader not working if "allow subreddits to show me custom themes" is disabled

### ISSUE THREAD

**Issue by EmbersArc** [honestbleeps/Reddit-Enhancement-Suite#4292]
- My browser (copy from https://www.whatismybrowser.com):
Vivaldi 1.9 on Windows 10
- My RES version:
v5.6.4
- Am I in reddit beta (yes/no): 
no

*What's the problem?*
The Stylesheed Loader doesn't work and defaults to the standard reddit theme if "allow subreddits to show me custom themes" in the Reddit options is disabled.
The night mode can still be activated.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
As discussed on the subreddit /r/RESissues:
https://www.reddit.com/r/RESissues/comments/6fmv2k/is_it_just_me_or_is_ress_custom_theme_setting_not/
and
https://www.reddit.com/r/RESissues/comments/6fgfkz/stylesheet_loader_not_working/

**Comment by erikdesjardins** [comment]
#4306
