### ISSUE TITLE
Duplicate user tags on child comments after saving comment edit

### ISSUE THREAD

**Issue by corylulu** [honestbleeps/Reddit-Enhancement-Suite#4310]
I don't think this is related to the changes I made (since it also occurs in 5.6.4) and I haven't tracked it down yet... but I just noticed a bug in the user tags that caused a duplicate tag / tag icon to be set on all child comments after saving a comment, but only happens once. 

**Screen capture:**  https://gfycat.com/HomelyUnrulyBluefintuna
**Versions tested:** Dev and 5.6.4

My guess is it's a bug in the watcher.js, but could probably be fixed by performing a check to see if a tag already exists before adding one, but fixing the root of the problem is probably better to avoid unnecessary DOM checks. 

Any idea what causes this? I'll step through it myself when I get a chance and try to get a fix.

**Comment by larsjohnsen** [comment]
Note that the old tag stops responding to clicks. Reddit apparently clones the elements when saving the change, so it is correct to re-add the tag. It would be nice to do a cleanup of the old elements when that occurs, but with d2x this issue will likely self-correct.
