### ISSUE TITLE
Subreddit info popup always shows wrong subscription status (unsubscribed)

### ISSUE THREAD

**Issue by reallyuniquename** [honestbleeps/Reddit-Enhancement-Suite#4311]
When I hover mouse over subreddit's name I'm subscribed to, popup shows `[subscribe]` button instead of `[unsubscribe]`. Clicking that button basically does nothing. Although it changes to `[unsubscribe]` on click, it resets after popup is closed.

If I visit subreddit page directly it says `subscribed`.

I've never experienced this issue. Two things happened lately, I updated:
Firefox 52.1.0 -> 52.1.2
RES 5.6.0/5.4.3 (don't remember the exact version) -> 5.6.4

Any ideas how to fix this?

**Comment by erikdesjardins** [comment]
Do you have third-party cookies disabled for `https://reddit.com`?

(In the past that setting didn't apply to extensions like RES, but now it does. RES has always used/required third-party cookies because it is a third party.)

**Comment by reallyuniquename** [comment]
Yeah, just figured out it's basically effects of #4219 .

> In the past that setting didn't apply to extensions like RES, but now it does

Could you please clarify what's the latest version of RES that ignores browser cookies settings?

**Comment by reallyuniquename** [comment]
All right, the last version that doesn't require adding `www.reddit.com` to cookies exceptions is `5.4.3`.
This version is available for download at [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite/versions/?page=1#version-5.4.3). It works fine. Don't forget to disable this addon's autoupdate setting in Firefox.

**Comment by honestbleeps** [comment]
We strongly advise against running old versions of RES and disabling auto
update.

Adding the ability for the extension to send the same cookies you're
already sending in non-extension http requests is not any sort of
legitimate security or privacy risk. Running outdated versions of the
extension will mean bugs, no new features, and guaranteed eventual
breakage. Not to mention should there be any security updates you will not
receive them.

**Comment by reallyuniquename** [comment]
>Adding the ability for the extension to send the same cookies you're already sending in non-extension http requests

...and allow third-party cookies on reddit domain for all http requests. Yeah, no. You can't apply that setting only to addons.

> Running outdated versions of the extension will mean bugs, no new features, and guaranteed eventual breakage.

Kinda true. But generally new versions introduce breaking changes (like this one) that overweight all the new features they provide. 

Anyway you drop Firefox ESR support too fast. I've spent _years_ on 4.5.4 and the only issue I had was broken imgur album inline expander.

By the way some users on /r/RESissues chose to completely drop RES instead of allowing 3rd party cookies even for 1 domain.

**Comment by erikdesjardins** [comment]
FWIW when reddit switches the site over to the redesign all old versions will stop working.

Uninstalling does not harm us. (Though people seem to think it's a threat.)

Before the end of the year (Firefox 57) we'd be forced to make this change if we hadn't already. The maintenance and performance benefits from WebExtensions make it better to do sooner rather than later (for us, and the 99% of users with default cookie settings).

**Comment by erikdesjardins** [comment]
Nothing else productive can come of this thread.
