### ISSUE TITLE
Cannot scroll past the first page

### ISSUE THREAD

**Issue by kmyid** [honestbleeps/Reddit-Enhancement-Suite#4328]
- My browser (copy from https://www.whatismybrowser.com):
Firefox 54 on Linux
- My RES version:
v5.6.5
- Am I in reddit beta (yes/no): 
no

- Operating System
Debian Sid

*What's the problem?*

After recent update to firefox 54, I can no longer scroll pass the first page with the keyboard scroll. Never ending reddit loads the second page, but I need to use the mouse to scroll afterwards. I have confirmed that this does not happen with chrome stable, so probably something to do with firefox.

Edit: I also tried refreshing firefox which did not help.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

I tried googleing but nothing much popped up, rather than people saying that they just have issues with firefox54 and res 5.6.5

*What other browser extensions are installed?*

httpseverywhere, vimfx, ublock origin

**Comment by Baggykiin** [comment]
Can confirm this one. Keyboard navigation does not work at all past the first page. Pressing J once at the bottom of the page will not do anything, simply keeping the last post of the first page selected.
Additionally, the click-to-select feature does not work on posts past the first page.

I use Firefox on several different PCs and they are all affected by this bug.

**Comment by ElvisDumbledore** [comment]
I've been having this same issue for a while now.

My browser (copy from https://www.whatismybrowser.com):
    Firefox 55.0.3 on 64bit

    My RES version:
    v5.8.4

    Am I in reddit beta (yes/no):
    no

    Operating System
    Windows 10 64bit Version 1703 build 15063.540

Deleted all other addons. Pausing Never Ending Reddit and manually clicking at the bottom of the page does not fix the problem. Disabling Never Ending Reddit allows manually opening pages by using the next button.

Somewhat related: About the same time this error began I noticed that some websites will not load additional pages at all. Nexusmods is one. Specifically the forums section. I can view the first page of results but the next page just show a letter E. Like the original poster said, this is likely something to do with Firefox itself.

**Comment by matthew-piziak** [comment]
Can repro:
```
My browser
Firefox 57 on Linux

My RES Version:
v5.8.6

Am I in reddit beta (yes/no):
no

Operating System:
Linux 4.12.3-1-ARCH
```
Happens when everything in the first page is filtered, and I cannot reproduce on Chromium.

**Comment by hellosputnik** [comment]
I am experiencing the same issue on Firefox 57.0b6 using RES v5.8.6. I experience the issue on Windows 10 and macOS High Sierra so it's very likely something to do with Firefox.

Does anyone have a workaround?

**Comment by hellosputnik** [comment]
This bug essentially renders RES obsolete on Firefox. Unfortunately, it looks like we'll have to use Chrome until Firefox or an RES contributor resolves this issue :'(

**Comment by larsjohnsen** [comment]
Disabling [returnToPrevPage](https://www.reddit.com/r/all/#res:settings/neverEndingReddit/returnToPrevPage) should prevent this issue. 

`returnToPrevPage` saves the currently loaded page in `history.state` so that it can quickly be restored. Unfortunately, in some cases it exceeds the amount of data Firefox allows to be stored there, and Firefox silently stops further code execution.

**Comment by hellosputnik** [comment]
Thank you so much, @larsjohnsen!

**Comment by erikdesjardins** [comment]
Ah, so _that's_ why it's dependant on page size. Another workaround is to reduce the number of links displayed at once in your [reddit prefs](https://www.reddit.com/prefs).

**Comment by erikdesjardins** [comment]
We should just [catch and log the error](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/ab384adc7cb3129af53e2b909fbc65cdd0a87ba7/lib/modules/neverEndingReddit.js#L238) then, I guess

**Comment by Baggykiin** [comment]
Nice find, @larsjohnsen! I decided to take a look inside Firefox's about:config page to see if it defined the maximum size of `history.state` anywhere, and it turns out it does.

So for those who want a temporary fix but don't want to disable `returnToPrevPage`, try increasing the value of `browser.history.maxStateObjectSize` in `about:config`. Adding a zero seems to do the trick.

**Comment by erikdesjardins** [comment]
Actually #4458 effectively does that, isolating the error to that single listener

**Comment by Sorgrum** [comment]
Neither of the proposed solutions are working for me on Firefox Dev Edition. I've set `browser.history.maxStateObjectSize` to `65536000` and I have never ending reddit disabled so return to previous page shouldn't be enabled anyway.
