### ISSUE TITLE
Cannot load the extension compiled from GitHub into Edge

### ISSUE THREAD

**Issue by JMccormick264** [honestbleeps/Reddit-Enhancement-Suite#4336]
Is RES broken?       Visit https://www.reddit.com/r/RESissues
No

- My browser (copy from https://www.whatismybrowser.com): Microsoft Edge
- My RES version: 5.7.5
- Am I in reddit beta (yes/no): Yes

*What's the problem?*
Whenever I try to load the latest build compiled from GitHub in Microsoft Edge, I get this ``
[Image Here](https://puu.sh/wEfJz/a8e1cd4d45.png)
I am not sure how to fix this issue. Is this an Edge problem or is it a RES problem>

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
None

*What other browser extensions are installed?*
LastPass, Moderator Tools For Reddit, Ad Block and Enhancer Tools for YouTube

**Comment by BenMcGarry** [comment]
Click the X and try again

**Comment by JMccormick264** [comment]
I have done that. Multiple times. I am not sure if it's an Edge bug or RES. I was able to load it custom before.

**Comment by BenMcGarry** [comment]
There is nothing on RES's side causing this, looks to be an Edge bug. Closed.
