### ISSUE TITLE
Migrate text options values saved as number to string

### ISSUE THREAD

**Issue by larsjohnsen** [honestbleeps/Reddit-Enhancement-Suite#4346]
As shown [here](https://www.reddit.com/r/RESissues/comments/6ni1cg/bug_still_not_fixed_navigating_with_keyboard/dk9lppz/), many values are saved as number instead of as string. That can [cause issues when strings are expected](https://www.reddit.com/r/RESissues/comments/6ni9kb/expandos_not_working_in_chrome/).

**Comment by erikdesjardins** [comment]
Ugh I knew I should have killed it earlier. https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/df679ec0a144d9a97429068604e7ccf65656649e#diff-76e5b0daa9643512b72cc4a4d30b79bbL80
