### ISSUE TITLE
Quick access to /user/ME/overview, .../submitted, .../liked, etc.; and for message/inbox, etc.

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#435]
I think it would be nifty to have a menu that appears when you hover over your username in the userbar with quick links to the various tabs on the user page; and an analogous dropdown from the envelope icon.

**Comment by erikdesjardins** [comment]
Related: #1887

**Comment by andytuba** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2928
