### ISSUE TITLE
Restore from Google Drive has wrong encoding

### ISSUE THREAD

**Issue by larsjohnsen** [honestbleeps/Reddit-Enhancement-Suite#4353]
Issue seen [here](https://www.reddit.com/r/RESissues/comments/6ns7uk/bug_weird_characters_in_karma_display_after).

The issue is fixed by removing [this line](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/35fd8aaf83c9a6cff419f312ff8b94d60e9ace69/lib/modules/backupAndRestore/providers/GoogleDrive.js#L67), but that causes a `network request failed` error in Edge.

**Comment by larsjohnsen** [comment]
Using [this library (js-base64)](https://www.npmjs.com/package/js-base64) instead of `atob` also avoids the issue.

**Comment by erikdesjardins** [comment]
Let's use that lib, I guess.
