### ISSUE TITLE
subreddit autocomplete doesn't update

### ISSUE THREAD

**Issue by mweggen** [honestbleeps/Reddit-Enhancement-Suite#4356]
When using subreddit autocompletion (typing /r/\<start of subreddit\>), the first autocomplete list gets stuck. After that, any attempt to use subreddit autocomplete will keep displaying the first list. Tried disabling and re-enabling. Also tried removing RES, restarting chrome (killed all processes) and re-adding RES, but no change.

this is 5.8.1 in chrome 59.0.3071.115 (64-bit)

other enabled extensions: 
https everywhere
image search options
imagus
lastpass
tampermonkey
true unexpected jihad
ublock origin
ultrawide video

**Comment by erikdesjardins** [comment]
35fd8aaf83c9a6cff419f312ff8b94d60e9ace69
