### ISSUE TITLE
Unable to load extension on Microsoft Edge on Windows 10 16251

### ISSUE THREAD

**Issue by wojtekmaj** [honestbleeps/Reddit-Enhancement-Suite#4372]
- My browser (copy from https://www.whatismybrowser.com):
Microsoft Edge  41.16251.0.0
- My RES version:
5.8.4
- Am I in reddit beta (yes/no): 

*What's the problem?*

I downloaded the extension from Windows Store, but although it is listed in Microsoft Edge on Extensions panel, with proper icon and everything, it doesn't seem to launch at all.

I decided to investigate and cloned the repo, build the extension on my own and tried to sideload it as instructed. Sideloading failed, got an error: "Unspecified error: The system cannot find the file specified" or something similar (I'm using non-English build).

I'm not sure if these issues are connected to each other, but maybe that will make debugging easier.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Haven't found one :(

*What other browser extensions are installed?*

uBlock Origin
Microsoft Translator

**Comment by BenMcGarry** [comment]
Ref #4336, this appears to be a Edge issue. Just tested this myself and can repro however on retrying it completed fine. I have checked and we have nothing wrong with our manifest file (it recently passed all tests to be on the store). Please file feedback in the feedback hub.
