### ISSUE TITLE
Vote Weight count incorrect

### ISSUE THREAD

**Issue by blindman** [honestbleeps/Reddit-Enhancement-Suite#4384]
- My browser: **Chrome 60 on Mac OS X (El Capitan)**
- My RES version: **5.8.4**
- Am I in reddit beta (yes/no): **no**

*What's the problem?*

Vote Weight shows incorrect number of upvotes when upvoting the same user in the same thread.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

I couldn't find any, searched both subreddits and the github issue tracker.

*What other browser extensions are installed?*

A bunch, but none are causing conflicts or throwing errors. (I can update if this really is a concern)

*Steps to reproduce.*

1. Open a thread where the same user has commented at least twice
2. Upvote one of the users comments
3. Upvote a second comment made by the same user
4. Look at both of the vote weights next to the user's name in both comments you upvoted

*Image (I promise those are the same user)*

<img width="1361" alt="res_error" src="https://user-images.githubusercontent.com/850522/29671767-f78781f6-88af-11e7-83bc-a4598e68d12f.png">

**Comment by larsjohnsen** [comment]
Should be fixed by #4382

**Comment by ingochris** [comment]
Do you mean the cumulative vote amount?

**Comment by larsjohnsen** [comment]
Yes.
