### ISSUE TITLE
New x-post support

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#4385]
As per modmail we have a few incompatibilities, listed here for tracking.

- [x] ~~RES selector colour extends into body of x-post.~~ Appears to be intended, background is set to transparent on `.link .crosspost-preview-content .usertext-body .md`

https://i.imgur.com/fzShNDQ.png
- [x] Admin colour not present on x-posts

https://i.imgur.com/rkFUDJo.png

- [ ] Image x-posts do not show as intended, overwritten by RES expando.

Expected: 
![](https://i.imgur.com/HZxHKBU.png)

Actual:
![](https://i.imgur.com/LyIKZTp.png)

- [x] X-post requires nightmode support

https://i.imgur.com/ciKBBKp.png

This is what i could find from a brief look.

**Comment by andytuba** [comment]
Hmm, is the timeago a RES bug?

> Image x-posts do not show as intended, overwritten by RES expando.

We could address this by by adding an extra "title" from `thing.querySelector('.expando').getAttribute('[data-cachedhtml]')` -> parse as html -> `parsed.querySelector('.crosspost-preview-header')` -> clone into expando title

**Comment by andytuba** [comment]
`(last edited <timeago>)` is confirmed Reddit bug.

**Comment by andytuba** [comment]
`.crosspost-preview-header` will probably be bugged in nightmode

**Comment by erikdesjardins** [comment]
I think the last part can be pushed back to 5.9.x, we need to get something out for 5.8.5

**Comment by BenMcGarry** [comment]
https://www.reddit.com/r/modnews/comments/7a5ubn/crossposting_coming_soon_to_your_subreddit/

General release on the 8th Nov
