### ISSUE TITLE
Lots of expando features not available when not logging in

### ISSUE THREAD

**Issue by fireattack** [honestbleeps/Reddit-Enhancement-Suite#4398]
- My browser (copy from https://www.whatismybrowser.com): Both Firefox or Chrome, various versions (on Win 7)
- My RES version: 5.8.4 
- Am I in reddit beta (yes/no): no

*What's the problem?*

1. Log off the reddit account
2. Open https://www.reddit.com/r/aww/comments/6wdg3z/here_come_the_ears/

The expando has no hover toolbar, and you cannot drag-to-resize.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

No

*What other browser extensions are installed?*

Nothing, tested in new profile

**Comment by larsjohnsen** [comment]
This is expected, as RES won't replace an already opened expando. https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/690b3fcfbbd865a85ff9f42c5af71e4b924b2d7c/lib/modules/showImages.js#L929
