### ISSUE TITLE
RES randomly enables nightmode when opening post in new tab

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#4422]
Repro on Chrome 61.0.3163.79 (Official Build) (64-bit).
RES 5.8.4 Stable

https://www.reddit.com/r/Enhancement/comments/6zwmul/res_keeps_randomly_turning_nightmode_on/

https://www.reddit.com/r/RESissues/comments/72jq04/night_mode_turns_on_automatically_every_time_i/

I am able to repro it with the nightmode module disabled.

It only triggers nightmode on the opening of the second tab, nightmode = true is added to local storage.

Appears to be exclusive to chrome, and clearing browser cache fixes it.

**Comment by BenMcGarry** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=765524

Appears to have been a Chromium bug, fixed in M62. Awaiting confirmation it does fix the issue.

**Comment by erikdesjardins** [comment]
Looks like this was indeed fixed in Chrome 62; and if not it should be fixed by #4342/#4570
