### ISSUE TITLE
Clicking the [l+c] button or key shortcut l on a reddit hosted image opens the same thread in two tabs

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#4423]
RES 5.8.4 stable.
Can repro on all browsers.

Steps:

1. Find a i.redd.it post.
2. Click [l+c]

Expected: Post opens image in one tab, comments in second.
Actual: Post opens comments in both tabs

**Comment by tersers** [comment]
I'd like to take a shot at this!

**Comment by BenMcGarry** [comment]
Go for it @tersers :)

**Comment by tersers** [comment]
It appears that certain posts linking to a ```i.redd.it``` URL don't link to the image itself but rather to the comments. See below:

`<div class="entry likes RES-keyNav-activeElement">
    <div class="top-matter">
        <p class="title">
            <a class="title may-blank loggedin " data-event-action="title" href="/r/pics/comments/78oxmo/my_little_guy_fought_off_3_coyotes_and_lived_to/" tabindex="1" data-href-url="/r/pics/comments/78oxmo/my_little_guy_fought_off_3_coyotes_and_lived_to/" data-inbound-url="/r/pics/comments/78oxmo/my_little_guy_fought_off_3_coyotes_and_lived_to/?utm_content=title&amp;utm_medium=hot&amp;utm_source=reddit&amp;utm_name=pics" rel="">My little guy fought off 3 coyotes and lived to tell the tale</a>
            <span class="domain">(<a href="/domain/i.redd.it/">i.redd.it</a>)</span></p>
        <a class="expando-button toggleImage image collapsed collapsedExpando" title="" data-host="default"></a><span></span>
        <p class="tagline ">submitted
            <time title="Wed Oct 25 16:45:39 2017 UTC" datetime="2017-10-25T16:45:39+00:00" class="live-timestamp">10 hours ago</time> by <a href="https://www.reddit.com/user/skatesofla" class="author may-blank id-t2_edq3b">skatesofla</a><span class="RESUserTag">
				<a class="userTagLink RESUserTagImage" title="set a tag" href="javascript:void 0"></a>
			</span><span class="userattrs"></span></p>
        <ul class="flat-list buttons">
            <li class="first"><a href="https://www.reddit.com/r/pics/comments/78oxmo/my_little_guy_fought_off_3_coyotes_and_lived_to/" data-inbound-url="/r/pics/comments/78oxmo/my_little_guy_fought_off_3_coyotes_and_lived_to/?utm_content=comments&amp;utm_medium=hot&amp;utm_source=reddit&amp;utm_name=pics" data-href-url="/r/pics/comments/78oxmo/my_little_guy_fought_off_3_coyotes_and_lived_to/" data-event-action="comments" class="bylink comments may-blank" rel="nofollow">4080 comments<span class="newComments">&nbsp;(11 new)</span></a></li>
            <li class="share"><a class="post-sharing-button" href="javascript: void 0;">share</a></li>
            <li class="link-save-button save-button"><a href="#">save</a></li>
            <li>
                <form action="/post/hide" method="post" class="state-button hide-button">
                    <input type="hidden" name="executed" value="hidden"><span><a action="hide" href="#">hide</a></span></form>
            </li>
            <li class="report-button login-required"><a href="javascript:void(0)" class="reportbtn access-required" data-event-action="report">report</a></li>
            <li class="crosspost-button"><a class="post-crosspost-button" href="javascript: void 0;" data-crosspost-fullname="t3_78oxmo">crosspost</a></li>
            <li><span class="redditSingleClick"></span></li>
        </ul>
        <div class="reportform report-t3_78oxmo"></div>
    </div><span></span>
    <div hidden="" class="res-expando-box" style="min-height: 20px">
        <div class="res-expando-box-inner"></div>
    </div>
</div>`

In the `title` element, where you would normally find your imgur link, only the comments URL is found.

 I'm not quite sure if this can be fixed RES-side, or if it's an issue with how reddit populates their entries.
