### ISSUE TITLE
improve documentation to build

### ISSUE THREAD

**Issue by nhjiejan** [honestbleeps/Reddit-Enhancement-Suite#4438]
- My browser (copy from https://www.whatismybrowser.com):
- My RES version:
- Am I in reddit beta (yes/no): 

*What's the problem?*

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

*What other browser extensions are installed?*

**Comment by erikdesjardins** [comment]
This isn't actionable unless you actually explain what you mean.

The readme links to a file with 94 lines of (build-related) documentation. It is not clear how it could be improved.
