### ISSUE TITLE
Request to Implement: Automatically switch account if OP of post matches an added account

### ISSUE THREAD

**Issue by isiah-lloyd** [honestbleeps/Reddit-Enhancement-Suite#4442]
I'm planning to add this to the account switcher module. I may also expand the scope to look if any of the accounts in the account switcher have posted a comment on a post and switch to the account.

**Comment by andytuba** [comment]
Sounds great!  There's probably a few duplicate/related tickets that could be closed when you implement this.

**Comment by erikdesjardins** [comment]
#1686

**Comment by erikdesjardins** [comment]
Let's close this in favour of that
