### ISSUE TITLE
Custom ESLint rule to forbid spaces in module option names

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#4461]
i.e. an object assigned to the options property of anything or which is the options property of an object literal must have keys consisting only of word characters.

bad:
```js
module.options = {
  'some option': {}
}

export default new Host('foo', {
  options: {
    'some option': {}
  }
})
```

good:
```js
module.options = {
  someOption: {}
}

export default new Host('foo', {
  options: {
    someOption: {}
  }
})
```

**Comment by kraigh** [comment]
@erikdesjardins should the ESLint rule also check for other invalid names that would need quotes, like with a "-" or a reserved name? Or is just checking for spaces sufficient?
