### ISSUE TITLE
Opening comments in new tabs in clunky (should be easy fix)

### ISSUE THREAD

**Issue by bomjacob** [honestbleeps/Reddit-Enhancement-Suite#4514]
- My browser: Firefox 57 on Windows 10 `(Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0)`
- My RES version: v5.8.6 (though I'm looking at master code)
- Am I in reddit beta (yes/no): no

*What's the problem?*
When RES opens a new tab it does it using the code at [firefox/background.entry.js#L31](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/firefox/background.entry.js#L31), this means that if a user subsequently closes the tab, Firefox doesn't know which tab to go to. The intuitive behaviour would be to go back to the tab that opened the child tab.

As of version 57 of firefox (which will be released as stable in november), chrome.tabs.create supports openTabId ([mdn](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create#Browser_compatibility)) which means that fixing this should be fairly simple.
I can submit a PR, but I'd like to know if my suspicion of correct first?

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
Not that I can find

*What other browser extensions are installed?*
Not relavant

**Comment by erikdesjardins** [comment]
Sure, though we can't merge it until 57 is stable.

This also allows us to remove the `index` parts, which will fix #4230 as well.

**Comment by bomjacob** [comment]
Would you like me to remove the `index` parts from [chrome/background.entry.js#L31](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/chrome/background.entry.js) as well, or should they stay?
Where is the index (and stuff like the cookieStoreId) coming from in the first place?

**Comment by erikdesjardins** [comment]
Those are coming from the tab that sends the message to the background page:

passed in from the native message handler here https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/58e0cfa8da61484fd3b30fe2cd479d434f6551fb/browser/background.js#L29

and `sender.tab` is this https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab

**Comment by bomjacob** [comment]
Ah I see, thank you for that explanation :)
