### ISSUE TITLE
React UI

### ISSUE THREAD

**Issue by wojtekmaj** [honestbleeps/Reddit-Enhancement-Suite#4556]
Hey,
as crazy as it may sound, I believe that RES could benefit a lot from being rewritten to React.

RES, being 6 years old (first commit 15.11.2011 - happy birthday! 🍰 ) has an architecture that offers far less than what modern libraries like React could give us.

Here's how I think RES could benefit:

* Much more structured architecture will help in project maintainability
* Increased code reusability. Having a clear component-based structure would make it easier to reuse code.
* Less bugs
    * Can you easily follow how a simple toggleButton works? It's hard - jQuery-based event handling, heavily reliant on things like document.querySelector, decentralized code.
    * Switching to component-based architecture can help writing good - and fast - unit tests.
* Performance - the amount of stuff that's going on currently in DOM is crazy. We render HTML oftenly using innerHTML, then we replace some containers with other innerHTMLs, then we find these very elements we've just rendered using querySelector, pushing them to global variable and applying events. To me, it sounds like we're doing twice as many DOM operations as we should. On Modern browsers, direct DOM operations are faster than innerHTML, too, but writing own API to do that does not make a lot of sense.
* In the process, we could naturally get rid of jQuery, which I find unnecessary in current state of JavaScript.

So I started experimenting with rewriting RES to React just to ensure that it is possible without freezing down the entire development process. And I think it's doable!

A repo is worth 1000 words though, so let me give you a sneak peek on what I'm into recently. It's on its very early stage, but worth a look.

https://github.com/wojtekmaj/Reddit-Enhancement-Suite/tree/react

### What works
* Displaying navigation
* Routing
* Displaying module
* Displaying most module options
* Toggling modules on/off
* Changing option values

### Components
* reusable
    * Input - for rendering any given input type - button, enum, text, etc.
    * Toggle
    * Table - for rendering tables with ability to add and remove rows
    * Button
    * Html - for rendering pure HTML into React elements
    * Markdown - for parsing markdown text
* ConsoleWrapper - to connect Console to Router and Store
    * ConsoleContainer
        * Search - for rendering search field
        * ModuleSelector - for displaying menu
        * ConfigPanelOptions - for displaying main content (currently selected module)
            * OptionContainer - for rendering option container with title, description and control
                * Option - for rendering specific option control (button, text, enum, ...)

### Technologies
* React-Router (hash-based)
* Redux store (monkey patched to get data from Modules.all())
    * Storing modules for display purposes
    * Enable/disable/toggle modules + inform Module store
    * Change option values + inform Module store

What do you think?

**Comment by BenMcGarry** [comment]
Ref: https://github.com/honestbleeps/Reddit-Enhancement-Suite/projects/3

**Comment by wojtekmaj** [comment]
Huhuhuhuuu! I'm in!

**Comment by BenMcGarry** [comment]
There will be a lot more discussion on this over the next few weeks. Thank you for doing the initial look into this, Im sure the others will comment in due course.

I've added this into the project.

**Comment by mc10** [comment]
This is super cool! One thing I would vote for is to use Redux as well, if we're planning on doing a rewrite anyways, as it's easier to start with it than to port something over to using Redux.

**Comment by wojtekmaj** [comment]
Absolutely! I'm on it at the moment, although connecting it all together even by monkey patching is a huge task, hence I'm not committing. Definitely on it though ;)

![obraz](https://user-images.githubusercontent.com/5426427/32995736-250daffc-cd79-11e7-9ae0-866535326eef.png)

**Comment by wojtekmaj** [comment]
Hey all,
quick update since I got some time over the weekend.

Now, in React option pane:
* Module store talks better with Redux store.
    * Changing options value works properly
    * Highlighting of save button is now handled by Redux
* Tables are rendered, with ability to add/remove row.
* Applying presets now works

**Comment by erikdesjardins** [comment]
While we do plan to rewrite the settings console in React (while moving it to a separate page), I'm fairly strongly opposed to including it in the bundle that gets injected on reddit. React has a substantial startup cost (and memory cost, per gaearon himself), we are pretty much solely dependent on startup perf (since we have to race against reddit to avoid FOUC - something a normal SPA isn't concerned about), and I'm not going to regress that further.

Other things I can immediately think of that would benefit from the React + dedicated page treatment: the dashboard, the list of user tags...probably something else.

(jQuery->vanilla replacement is still planned.)

**Comment by erikdesjardins** [comment]
See #4259 for moving the settings console to the options page (so old it still has React 15, heh)

**Comment by wojtekmaj** [comment]
Since Reddit goes React, maybe we could cooperate with them and actually use Reddit's already loaded React library? This of course would be much further into the future, but maaaybe?

**Comment by erikdesjardins** [comment]
Extensions are sandboxed, so we couldn't use reddit's React instance without doing something horrifying like injecting our code verbatim in a `<script>` tag (which I'm sure Mozilla reviewers wouldn't be happy with).
