### ISSUE TITLE
Accidentally a word in commentToolsMacroPlaceholdersDesc

### ISSUE THREAD

**Issue by wojtekmaj** [honestbleeps/Reddit-Enhancement-Suite#4578]
Not sure if I can edit i18n files manually so I'm reporting rather than fixing it. In commentToolsMacroPlaceholdersDesc, you accidentally a word.

Is:
`On a post's comments page, this the person who made the post;`

Should be:
`On a post's comments page, this is the person who made the post;`

**Comment by erikdesjardins** [comment]
FWIW en.json can be edited, the other files can't
