### ISSUE TITLE
My Subreddits list does not populate

### ISSUE THREAD

**Issue by LtPatterson** [honestbleeps/Reddit-Enhancement-Suite#4597]
- My browser (copy from https://www.whatismybrowser.com): FF 57.0.2
- My RES version: 5.8.6
- Am I in reddit beta (yes/no): No

*What's the problem?*
See below posts. My Subreddits link in upper left corner which is supposed to display a dropdown of all subscribed subreddits does not function. I tried removing RES, removing Ghostery, nothing changes. I believe this is a FireFox specific issue since the update to 57.0.1 and 57.0.2.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
https://www.reddit.com/r/RESissues/comments/7jm6ym/my_subreddits_list_does_not_populate/
https://www.reddit.com/r/RESissues/comments/7ilw7j/res_not_showing_subreddits_and_new_pages_show/
https://www.reddit.com/r/RESissues/comments/7i6xkd/the_my_subreddits_dropdown_no_longer_shows_my/

*What other browser extensions are installed?*
Several. However, no combination of addons changes the end result.
Ghostery, AdNauseam, Tampermonkey (for RES Twitter Expando)

**Comment by LtPatterson** [comment]
Any updates? This feature is still not working.

**Comment by erikdesjardins** [comment]
This is almost certainly https://bugzilla.mozilla.org/show_bug.cgi?id=1322113 or _yet another_ Firefox bug.

Does it work in [a new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) with nothing else installed and no settings changed?

**Comment by LtPatterson** [comment]
Doesn't work even on a fresh install. Sometimes it does work, but rarely. It worked for a few days with the new FF update and broke again out of nowhere. I keep seeing threads about this being posted in /Enhancement so I figured I would make a report here on the github.

I am still experiencing the issue since moving to FF Quantum. Before Quantum, it worked, so I think it might be an RES w/ FF Quantum issue specifically.

**Comment by LtPatterson** [comment]
I'd really like to see if anyone else has this issue as it drives me nuts!

**Comment by honestbleeps** [comment]
did you ever add www.reddit.com to your list of approved 3rd party cookies? That has been the solution for (almost) everyone we've seen so far...  I know only of one person besides you who claims they added the exception and it still doesn't work - but we've not been able to duplicate the problem.

it's very important that www.reddit.com be added to exception list due to the bug linked above - there's simply no other way to make it work.  

One last person who couldn't get it working even adding the exception said they then disabled Ghostery and it worked -- so you might have to look at doing both of those things.

**Comment by LtPatterson** [comment]
Cleared cookies from reddit, whitelisted the site (https://reddit,com) - only worked when I used that exact URL, and the issue is finally resolved (for now). I hope it stays fixed! I had the wrong URL listed in there, you must have the exact URL as it appears in the browser tab or it will not work after restarting the browser.

Closed.

**Comment by LtPatterson** [comment]
Continuing issues again. I can't put my finger on what is causing this anymore. I got it to work for one FF session and since then it doesn't work. Additionally the "never ending subreddit" feature is not working either. A few issues posted recently in r/RESissues point to that error as well.
