### ISSUE TITLE
Comment selection triggers a ~100ms restyle

### ISSUE THREAD

**Issue by erikdesjardins** [honestbleeps/Reddit-Enhancement-Suite#4609]
Not a forced reflow anymore, but noticeably slow.

5.9.4:
![image](https://user-images.githubusercontent.com/7673145/34644055-5f4a6f1c-f2fd-11e7-8ef2-89cdba1c67d4.png)

5.9.6:
![image](https://user-images.githubusercontent.com/7673145/34644065-9702d098-f2fd-11e7-9f7d-97df90981d6d.png)

**Comment by larsjohnsen** [comment]
[These lines](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/7d338e49e019f9f48a690a6fe595749a843e2563/lib/css/modules/_filteReddit.scss#L19-L21) appears to be causing the subtree for both the unselected and select thing to be recalculated. I'm looking for a more performant way of achieving the "display whole comment when selected if filtered"-effect.
