### ISSUE TITLE
RES Version Compatibility Check Does Not Account for Firefox ESR

### ISSUE THREAD

**Issue by megasquid** [honestbleeps/Reddit-Enhancement-Suite#4615]
- My browser (copy from https://www.whatismybrowser.com): "Firefox 52 on Windows 10" which is wrong.  Running 52.5 ESR.
- My RES version: 5.8.6
- Am I in reddit beta (yes/no): no

*What's the problem?*

Firefox states that RES 5.8.6 isn't compatible with "old" versions of Firefox.  See screenshots at imgur gallery below:
[https://imgur.com/a/SnWww](https://imgur.com/a/SnWww)

Running Firefox Extended Service Release (ESR) 52.5 released Nov 2017, equivalent to Firefox 57.  See here:
[https://www.mozilla.org/en-US/firefox/organizations/](https://www.mozilla.org/en-US/firefox/organizations/)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Yes, with no resolution/fix noted.
[https://www.reddit.com/r/RESissues/comments/7obzx6/upgraded_to_firefox_esr_and_res_doesnt_work/](https://www.reddit.com/r/RESissues/comments/7obzx6/upgraded_to_firefox_esr_and_res_doesnt_work/)

*What other browser extensions are installed?*
Silverlight

**Comment by erikdesjardins** [comment]
ESR 52.5 contains only security fixes from Firefox 57, not features.

**Comment by erikdesjardins** [comment]
From the page you linked (emphasis mine):

> Maintenance of each ESR, through point releases, is limited to high-risk/high-impact security vulnerabilities and in rare cases may also include off-schedule releases that address live security vulnerabilities. **Backports of any functional enhancements and/or stability fixes are not in scope.**

**Comment by Ajedi32** [comment]
Perhaps Firefox ESR _should_ be supported? Even though it doesn't match the latest stable version of Firefox in terms of features, 52.5 ESR _is_ still actively supported by Mozilla, so it's not really an "old" version in that sense.

Though I guess 52.5 doesn't support WebExtensions, does it? I assume that makes supporting it impractical.

**Comment by erikdesjardins** [comment]
Indeed, and we're not gonna go back to a platform that can't provide basic persistence for its storage APIs... I'd rather not have to link to either [of](https://www.reddit.com/r/Enhancement/wiki/faq/update_lost_data) these [pages](https://www.reddit.com/r/Enhancement/wiki/faq/indexeddb_failure) ever again.

**Comment by honestbleeps** [comment]
for what it's worth, I think that looking into the feasibility of supporting future ESRs (when there's not such a major architectural change like webextensions) might not be entirely off the table -- but it may have to be addressed on a case by case basis...  Supporting an ESR may essentially be like supporting n+1 browsers depending on how much has changed, and it can be a ton of extra work to do all of the necessary testing (and keep in extra shim code, etc)...

I like the *idea* of supporting ESRs, but amount of work to practice that, weighed against what a small percentage of our users use ESR, sometimes may make it impractical.  I think it's something we might "strive for, but not promise"...
