### ISSUE TITLE
Sync my settings and tags across my browsers and through reinstalls.

### ISSUE THREAD

**Issue by Fieel** [honestbleeps/Reddit-Enhancement-Suite#4641]
Hello,

i already asked this questions in the subreddit but people kept suggesting using dropbox and other third-party features which is not what i'd love to have implemented.

Basically i want to be able to retrieve my data even if i'm on different computers or i have to format the OS, some kind of cloud database for users.

Is such a thing even possible with RES? I already lost all of my RES data multiple times now.

**Comment by BenMcGarry** [comment]
RES has options to automatically backup and restore RES settings to Dropbox, Google Drive and Onedrive. See https://www.reddit.com/r/Enhancement/wiki/backing_up_res_settings
