### ISSUE TITLE
Versions later than v5.9.2 don't work with latest Edge browser

### ISSUE THREAD

**Issue by farid-fari** [honestbleeps/Reddit-Enhancement-Suite#4647]
- My browser: https://whatismybrowser.com/w/KKP3D88
- My RES version: 5.10.2
- Am I in reddit beta (yes/no): no

I am using the latest version of Edge (`Microsoft Edge 41.16299.15.0` and `Microsoft EdgeHTML 16.16299`) on the latest build of Windows (`1709.16299.192`).

RES does not load at all, on the frontpage or any other subreddit when the bug occurs. I am unable to view the 'background page' debug option at all, and there are no signs of a crash or anything. This happens with the self-built option and the Store version (or at least the latest one). I originally thought this was a problem on my side, but after testing different version built with `npm run build edge`, I can confirm that:

- versions 5.9.2, 5.9.5, 5.9.8, 5.9.9, 5.10.0, 5.10.2 do **not work** on the latest version of Edge
- versions 5.7.0, 5.8.0, 5.9.0, 5.9.1 **work** with the latest version of Edge

I am technically illiterate and therefore unable to provide any extra information (unless guided of course).

**Comment by BenMcGarry** [comment]
I am not able to reproduce this with the versions mentioned as well as the browser version. All versions mentioned work on Edge inc Store and sideloaded versions. 

![](https://i.imgur.com/UPHiXDr.png)

I would suggest doing a Repair/Reset on Microsoft Edge, these options are on Settings > Apps > Microsoft Edge > Advanced Options.

**Comment by farid-fari** [comment]
Sadly I have way too many pinned tabs to do that....
I'll close the issue since it seems to be only me.

**Comment by farid-fari** [comment]
Can confirm a reset does work.
