### ISSUE TITLE
Auto-update broken on legacy versions of Firefox because minimum required version on AMO needlessly set to 57

### ISSUE THREAD

**Issue by blackwind** [honestbleeps/Reddit-Enhancement-Suite#4654]
- My browser (copy from https://www.whatismybrowser.com): Waterfox 56.0.3
- My RES version: 5.10.3beta
- Am I in reddit beta (yes/no): No

*What's the problem?*

Can you guys change RES's minimum required version on AMO to the *actual* minimum required version based on the APIs used, whatever that may be? Many of us are still on Firefox 56, Firefox 52 ESR, and Waterfox [for obvious reasons](https://www.ghacks.net/2017/04/27/if-firefox-57-would-be-released-today-2274-add-ons-would-be-compatible/), and although the add-on works just fine when manually downloaded and installed -- latest RES betas included, at least on 56 -- it can't be installed directly from AMO and therefore isn't automatically updated. Users who had previously installed the add-on from AMO when it *was* compatible according to the AMO listing are also affected.

I accept it may not be feasible to extend support all the way back to Firefox 52 ESR due to missing/incomplete APIs, but support for Firefox 56, at least until you begin using APIs only present in Firefox 57 and above, is as simple as changing the "57" in the AMO listing to a "56".

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

https://www.reddit.com/r/RESissues/comments/7rn9gq/cant_install_res_in_waterfox_5603_64bit_from/

*What other browser extensions are installed?*

Not relevant, as this isn't an extension conflict.

**Comment by BenMcGarry** [comment]
Firefox 57 is set as the minimum required version as we use an API that is only available in Firefox 57+.

`openerTabId `on https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create.

https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4518

**Comment by blackwind** [comment]
Well, it's good to see the version restriction was chosen conscientiously, though I do wonder if it's worth breaking compatibility for a surely-not-insignificant portion of your users over a triviality precious few would've ever noticed. Given that it's only a couple lines, would you consider restoring the old code behind a conditional (if Firefox < 57, do it the old way; else, do it the new way)?

**Comment by Mutantoe** [comment]
You can go [here](https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite/versions/) to download an older version. That's what I've done, and it seems to work fine.

**Comment by honestbleeps** [comment]
For security and compatibility reasons we do not endorse downloading old versions and/or disabling auto update...

**Comment by blackwind** [comment]
You might not endorse it, but that's exactly what's happening with the RES team's silence on this issue, potentially putting users at risk. It'd be great to see accommodations made for at *least* Firefox 56, which many of us will be unable to move on from for the foreseeable future.

**Comment by erikdesjardins** [comment]
Yeah, we can't really say that when there _isn't_ a newer version.

Still, no, since we've never supported Firefox forks, [mainline Firefox 56 is insecure](https://www.mozilla.org/en-US/security/advisories/), and [few people](https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite/statistics/usage/applications/?last=90) stayed behind when Firefox 57 was released.

If you accept that things will be broken, you can disable the compatibility check and manually install newer versions.

(Also, while that tab change is the _first_ thing that required Firefox 57, it probably isn't the only one. There are >100 commits after it, and I don't remember if there was anything else.)
