### ISSUE TITLE
URLSearchParams for Edge

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#4659]
Implemented as of [17063](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/urlsearchparams/)

Related: #3504, #3593.

**Comment by erikdesjardins** [comment]
This can also be simplified https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/e16add10b2ada0a7834a6ae21f17ecaacf54f74f/lib/environment/foreground/ajax.js#L122
