### ISSUE TITLE
Submit RTS posts in the background

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#468]
http://www.reddit.com/r/Enhancement/comments/1iezvh/feature_request_can_the_rts_button_be_made_to

Is there a good reason against making "submit to /r/reportthespammers" a one-click?

**Comment by mc10** [comment]
Going to close this, as the RTS subreddit is closed.

**Comment by allthefoxes** [comment]
/r/spam is a mirror
