### ISSUE TITLE
Remove usage of Travis's JWT addon

### ISSUE THREAD

**Issue by kevinji** [honestbleeps/Reddit-Enhancement-Suite#4683]
Travis's [JWT addon](https://docs.travis-ci.com/user/jwt) is [being deprecated on April 17](https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated), so we'll have to figure out another way to authenticate to Sauce Labs.

**Comment by erikdesjardins** [comment]
Yeah, it doesn't seem like there's another way to get secrets on pull requests. Which I guess makes sense cause it wouldn't be secure.

We'll still be able to run integration tests on master, which would be fine I guess, just a longer feedback loop. To test PRs we could use the "try" features of something like [Homu](https://github.com/servo/homu) or [Bors](https://github.com/bors-ng/bors-ng), i.e. where a committer comments `@bors try` on a PR and it gets pushed to a try branch in this repo.

**Comment by kevinji** [comment]
Gonna close this as Travis has been broken for a while anyways.
