### ISSUE TITLE
Media save button opens image in new tab instead of downloading

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#4701]
https://www.reddit.com/r/RESissues/comments/82rbr6/the_save_media_button_no_longer_saves_it_opens/

https://www.reddit.com/r/Enhancement/comments/8391mu/tfw_chrome_doesnt_let_you_autodownload/

Repros on Chrome Version 65.0.3325.146, RES 5.11.4

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/environment/foreground/download.js

**Comment by flymason** [comment]
Based on the code in download.js, it looks like Firefox already prohibits cross-origin download actions. Perhaps we need to switch chrome over to send a download message like Firefox here.
