### ISSUE TITLE
Reddit Redesign 

### ISSUE THREAD

**Issue by thekodester** [honestbleeps/Reddit-Enhancement-Suite#4762]
So reddit is doing a massive redesign. Current RES doesn't function on the redesign. What is going to be the future of RES with this change.

Learn more of redesign here: https://www.reddit.com/r/announcements/comments/891stx/starting_today_more_people_will_have_access_to/

Example:
<img width="1792" alt="screen shot 2018-05-06 at 10 53 58 am" src="https://user-images.githubusercontent.com/23484460/39674570-d597c06c-511b-11e8-90e3-50decbfbbf88.png">

My browser:
-Chrome 66 on Mac OS X 10
-Firefox 59 on Mac OS X 10

My RES version:
-v5.12.2

Am I in reddit beta (yes/no): No

**Comment by BenMcGarry** [comment]
We are building in support for the redesign per our [recent release and announcement](https://old.reddit.com/r/RESAnnouncements/comments/8gl04r/res_v5120_now_with_more_redesign/). We have been working on compatibility for many months and will continue to do so.

**Comment by thekodester** [comment]
Cool, thanks for the information, didn't see that post.
