### ISSUE TITLE
Night mode broken after redesign

### ISSUE THREAD

**Issue by MatthewRalston** [honestbleeps/Reddit-Enhancement-Suite#4770]
- My browser (copy from https://www.whatismybrowser.com): Chrome 64.0.3282.167 (RHEL7) and 66.0.3359.139 (Windows)
- My RES version: v5.12.2
- Am I in reddit beta (yes/no): no

Night mode seems to be broken on Chrome with the redesign.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
I did not find any issues in Github about nightmode, let alone about specific breaking with the redesign (mid May 2018).

*What other browser extensions are installed?*
goo.gl url shortener, giphy, extension manager. Switching all off results in the same behavior, so it's not related to polarization from other extensions.

**Comment by BenMcGarry** [comment]
RES will not be implementing Night Mode for the redesign due to it becoming a first party feature in the very near future.

**Comment by BenMcGarry** [comment]
RES will be supporting both .old and .new. When it becomes a first party feature we will be modifying the toggle to allow change on both sites.
