### ISSUE TITLE
Why you need my browsing history ?

### ISSUE THREAD

**Issue by RUSshy** [honestbleeps/Reddit-Enhancement-Suite#4809]
Hi,

Why do you need my browsing history with the chrome extension ?

Stop stealing my privacy, this shouldn't be allowed

I'll report your extension if that is not removed in next update

**Comment by honestbleeps** [comment]
You can read about that here: https://www.reddit.com/r/Enhancement/wiki/permissions

If you don't care to trust it, you can look at the source of the extension, well, right where you're at here on github.

If you don't care to read the source, and don't care to trust us, then I would recommend uninstalling the extension.
