### ISSUE TITLE
Endless Scrolling on Mac

### ISSUE THREAD

**Issue by ASBaumgarten** [honestbleeps/Reddit-Enhancement-Suite#4810]
- My browser (copy from https://www.whatismybrowser.com): whatismybrowser.com/w/YZZAM9B
- My RES version: 5.12.5
- Am I in reddit beta (yes/no): Can't remember

*What's the problem?*
Endless scrolling will not load on my Mac. This issue has been going on for well over a month now, and it is an issue exclusive to MacOS from what I've seen. I do not have the same issue on my Windows 10 desktop.
<img width="1539" alt="screen shot 10" src="https://user-images.githubusercontent.com/7777147/42585794-9246235e-8504-11e8-8f92-4962bea0323a.png">

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

*What other browser extensions are installed?*
<img width="1680" alt="screen shot 13" src="https://user-images.githubusercontent.com/7777147/42585795-9259447a-8504-11e8-9b16-d28bd3fdafd3.png">

**Comment by honestbleeps** [comment]
Please see here for info and a solution!

https://www.reddit.com/r/Enhancement/wiki/faq/never_ending_reddit

**Comment by ASBaumgarten** [comment]
That did the trick, thank you very much.
