### ISSUE TITLE
Ctrl-e keyboard shortcut to open big editor is not possibly to disable or change

### ISSUE THREAD

**Issue by fletom** [honestbleeps/Reddit-Enhancement-Suite#4811]
when typing a comment, pressing Ctrl-e opens up the big editor (side by side edit and preview). this is not mentioned in either of the RES settings pages related to keyboard shortcuts and seems impossible to change.

this keyboard shortcut also conflicts with the system-wide text navigation shortcuts that are built into Linux and macOS, specifically the shortcut to jump to the end of a line of text.

**Comment by IvanFon** [comment]
Looks like you can change it in the settings under `openBigEditor`:

![](https://u.teknik.io/f7YxO.png)

**Comment by fletom** [comment]
@IvanFon thanks! that works great.

I did look through the options for a setting for this, so I don't know if it's a recent addition or if I just stupidly missed it. I think I probably didn't think it would be under the "Live Preview" section instead of under the "Editing Tools" section.

anyways, I'll close this issue now. an alternative issue to possibly raise would be to not have this as a default keyboard shortcut because of its conflicts on Linux and macOS, but that doesn't seem too important. and hopefully anyone who runs into it will now be able to find this page.

**Comment by IvanFon** [comment]
It is pretty well hidden in the settings.

Just wondering, what Linux keyboard shortcut conflicts with this? The only place I can find where Ctrl + E does something is in the terminal (move to end of current line), and I'm not sure if that counts as a conflict since it's in two different programs.

**Comment by fletom** [comment]
on macOS at least those text-navigation shortcuts that are commonly used in the terminal are actually system-wide, so they work in the browser, mail clients, and so on. I may be mistaken about the same shortcuts working on desktop Linux distros as well since I only use server distros.
