### ISSUE TITLE
[Feature Request] add the subreddit name as a class to the title element for r/all and multireddit

### ISSUE THREAD

**Issue by jeop10** [honestbleeps/Reddit-Enhancement-Suite#4812]
May I suggest  that you guys add the subrredit name to the title element?, example below

```
<div class="thing">
   ...
   <div class="entry">
       <div class="top-matter">
            <div class="title subreddit-name-here">
                 ...
            </div>
       </div>
    </div>
</div>
```

That whay the users can add css to get a different color per subreddit, or in gold themes like serene be able to modify the `:before` and get a nice feedback of where the post is coming from.

If this is already a functionality, can you please point me to it? (I am new using RES).

Thanks in advance.

**Comment by andytuba** [comment]
The subreddit ID is already included in the `<div class="thing" data-subreddit-fullname="t5_12345">`.
