### ISSUE TITLE
Twitter permissions prompt is now required to be in user gesture

### ISSUE THREAD

**Issue by paulcbetts** [honestbleeps/Reddit-Enhancement-Suite#4821]
- My browser (copy from https://www.whatismybrowser.com):
70.0.3521.2 (Official Build) dev (64-bit) (cohort: Dev)
- My RES version: v5.12.5
- Am I in reddit beta (yes/no): yes

*What's the problem?*

https://www.reddit.com/r/RESissues/comments/7s8989/twitter_permission_system_is_broken_on_chrome/

Just logging this on GitHub since it doesn't appear to be here yet, Twitter permission grants are broken at the moment because Chrome now requires these requests to be initiated via a user action (i.e. an `onClick` has to be on the call stack).

**Comment by larsjohnsen** [comment]
Closing since this was probably just a browser issue.
