### ISSUE TITLE
Wrong image being embedded by inline image viewer

### ISSUE THREAD

**Issue by Unihedro** [honestbleeps/Reddit-Enhancement-Suite#4851]
*To start off: I've read the RESissues wiki front page, checked to make sure there isn't a duplicate ticket, made sure it's the newest version, turned my computer off and on again...*

- My browser (copy from https://www.whatismybrowser.com):Chromium 65 on Ubuntu Linux
- My RES version:5.12.5 latest as of authoring
- Am I in reddit beta (yes/no): yes

*What's the problem?*
When clicking button to load image through image viewer, it gets forcefully rewritten to the unedited version of the image - more specifically, my markdown text was `[Board](https://i.imgur.com/cuzMrt4.png?1)`. RES loads this image instead: `https://i.imgur.com/cuzMrt4.png` As imgur allows editing images, which will indeed show up properly when the page is visited, the direct link is not the same and will lead to the initial version - The image viewer is expected to show the image being linked, so it should not have rewritten the link to remove the `?1`.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
no

*What other browser extensions are installed?*
disabled when testing

**Comment by larsjohnsen** [comment]
This might have been a caching issue. Can you check whether the the link loads the updated image now?

**Comment by andytuba** [comment]
What @larsjohnsen  said.

The `?1` is a cachebuster provided by Imgur to mitigate browser caching. The direct link leads to the same file, but your browser is loading the cached pre-edited version. Other users will see the latest version.

**Comment by Unihedro** [comment]
Yes
