### ISSUE TITLE
Show Images button missing on me/f/mod/about/unmoderated/ and me/f/mod/about/modqueue/

### ISSUE THREAD

**Issue by LilSpazJoekp** [honestbleeps/Reddit-Enhancement-Suite#4864]
- My browser (copy from https://www.whatismybrowser.com):
https://www.whatismybrowser.com/w/L72NCB4
- My RES version:
v5.12.6
- Am I in reddit beta (yes/no): 
yes
*What's the problem?*

On https://www.reddit.com/me/f/mod/about/unmoderated/ and https://www.reddit.com/me/f/mod/about/modqueue/
the 'Show images' button is not visible.
*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
None that I could find.

*What other browser extensions are installed?*
Moderator Toolbox and µblock Origin

**Comment by Brcrwilliams** [comment]
Thanks for helping to improve RES! Turns out that RES was not categorizing the filtered /r/mod as a modqueue page.
