### ISSUE TITLE
Changelog toast won't go away by any means

### ISSUE THREAD

**Issue by dylanh724** [honestbleeps/Reddit-Enhancement-Suite#4869]
- My browser (copy from https://www.whatismybrowser.com):
**Chrome 69 on Windows 10**

- My RES version:
**5.12.6**

- Am I in reddit beta (yes/no): 
**yes**

*What's the problem?*
**https://i.imgur.com/NZHoD3n.png
The changelog toast will NOT go away. I've tried everything.**

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
**I posted on the /r/ a while back regarding this issue, but never got any comments in return. It's now bumped away to oblivion. Link is somewhere, but can't find it.**

*What other browser extensions are installed?*
**uBlock origin is probably the only significant one, but using some pretty standard rules that most people reading this probably also has. Disabling it still keeps this issue active.**

**Comment by larsjohnsen** [comment]
Doesn't seem to be caused by RES. Check chrome:extensions for other extensions with version "4.0.16".

**Comment by andytuba** [comment]
Looks like r/toolbox. Can you post over there asking for help?
