### ISSUE TITLE
Firefox can't reach the download. Suggest a manual install button somewhere that isn't HSTS.

### ISSUE THREAD

**Issue by CthulhuHalo** [honestbleeps/Reddit-Enhancement-Suite#4917]
- My browser (copy from https://www.whatismybrowser.com): https://whatismybrowser.com/w/49LKQDP
- My RES version: N/A
- Am I in reddit beta (yes/no): No

*What's the problem?*

I can't even get to the addon download page on firefox. It keeps complaining that the HSTS certificate is unknown (Possibly a problem with my antivirus but nothing else does that aside from the RES page for some reason. I use Kaspersky). Is there a download link that isn't HSTS and doesn't go to the firefox addons site?

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Not that I know of

*What other browser extensions are installed?*
Irrelevant for now

**Comment by Brcrwilliams** [comment]
Could you please supply the exact link that you are trying to use? It is not clear from your post which site you are trying to reach.

**Comment by CthulhuHalo** [comment]
The link that goes to the firefox addons page for RES. I can't access it.

**Comment by Brcrwilliams** [comment]
This one? https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite/

I don't think there is a good way to distribute Firefox extensions besides Mozilla's Add-On's site.

That aside, it is concerning that you are getting an HSTS error. HSTS is a security feature which Mozilla is using to prevent Man-In-The-Middle attacks. It prevents you from accepting invalid TLS (HTTPS) certificates (An attacker can create a fake one and use it to intercept your connections if you accept the invalid certificate). The fact that you are receiving this error suggests that someone is doing something nefarious on your network.

**Comment by mc10** [comment]
Closing; there isn't a better way of distributing addons except via the official site.
