### ISSUE TITLE
Submission Helper - uncheck send replies - redesign compatibility

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#4956]
Look for aria-labelledby="send-replies" and figure out how to untick it

**Comment by zachary822** [comment]
```javascript
let ele = document.querySelector('div[aria-labelledby="send-replies"]');

ele.getAttribute('aria-checked')  // returns "true" or "false" based on current status
ele.click() // changes the checked state
```

Not sure if this is what is needed.

**Comment by andytuba** [comment]
@prakhar1912 Does this look interesting?

**Comment by prakhar1912** [comment]
> @prakhar1912 Does this look interesting?

Sure, I will work on this too.

**Comment by andytuba** [comment]
<img width="1432" alt="Screen Shot 2019-03-14 at 11 37 27 AM" src="https://user-images.githubusercontent.com/455632/54382626-9eabdc00-464d-11e9-833f-10f3b885fceb.png">

https://new.reddit.com/submit#res:settings/submitHelper/uncheckSendRepliesToInbox
