### ISSUE TITLE
Table tools - redesign compatibility

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#4973]
Scan for tables inside post / comment usertext and apply to them.

May need refreshing occasionally if react thrashes them

**Comment by fhernandezn** [comment]
Hello @andytuba are you accepting help with this one?

**Comment by andytuba** [comment]
@fhernandezn Go for it!

**Comment by CAVillalobos** [comment]
Hello, @andytuba and sorry for the delay. I'm working with @fhernandezn with this issue and I want to let you know we found a solution for this issue. May I post the PR for you to review or do you need something else?

**Comment by andytuba** [comment]
@CAVillalobos Great! Yes, go ahead with posting the PR :smile:
