### ISSUE TITLE
JavaScript buttons broken on page 2 of never-ending reddit

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#5008]
Several RES users have reported that several JS-only buttons fail when using Never-Ending Reddit.

On page 2 or higher of modqueue, clicking [spam] / [remove] / [approve] buttons throw a "*whateverfunction* is not defined". This is weird, because they're Reddit's own inline onclick handlers, and clicking those buttons on page 1 works.

Context doesn't work on any page!

Paired with this report from one user, I also saw exceptions thrown from multicast "MessageHandlerError: could not connect to extension". IIRC this persisted after restarting the browser.

The users also typically install toolbox and snoonotes side by side.

Current workaround: disable NER.

**Comment by larsjohnsen** [comment]
Works in Firefox. Confirmed not working in Chrome. It seems that since RES' "owns" the succeeding pages, the `onclick` Javascript is executed in RES' environment.

**Comment by larsjohnsen** [comment]
This is likely due to a change in Chrome or an old bug (the issue is also present in v5.0.3). I'm not aware of any good way to fix this.

**Comment by larsjohnsen** [comment]
Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=912069#c39

Seems likely it will be backported to M71.

**Comment by andytuba** [comment]
Great detective work!
