### ISSUE TITLE
Redirecting reddit.com to old.reddit.com

### ISSUE THREAD

**Issue by aaomidi** [honestbleeps/Reddit-Enhancement-Suite#5027]
So I understand that the official response from RES is that there is a user setting to change this. However, reddit seems to be ignoring that user setting every 20-30 requests. I propose that RES adds this as an option to anyone who wants to use it.

I've had to create another chrome extension https://github.com/aaomidi/reddit-fixer (extension: https://chrome.google.com/webstore/detail/boahhdcjflkiibelindjjjfpnffcjdag).

If there is any interest I can contribute this to RES as well.

**Comment by BenMcGarry** [comment]
There is currently a known issue related to the redirect to old that the admins are aware of.

https://www.reddit.com/r/redesign/comments/adxv7b/update_on_the_bug_where_youre_randomly_reverted/

Right now we have no intentions to ship this feature as we do not want RES to be used solely as a redirect tool while the officially supported feature is being fixed.

**Comment by aaomidi** [comment]
That seems like a weird decision but I respect it.
