### ISSUE TITLE
Settings console is now in a chrome-extension:// iframe?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [honestbleeps/Reddit-Enhancement-Suite#5038]
Makes it impossible to affect the CSS with any user style, and breaks all the existing ones. WTH was the point of this?

**Comment by narcolepticinsomniac** [comment]
Tried to export a backup, side-load the previous stable version and import the backup, which doesn't seem to work at all. Only filters I have are for visited links, but after importing the backup, RES removes every post without exception. This sucks. I just want it back the way it was 2 days ago.

**Comment by larsjohnsen** [comment]
The settings console has been embedded to make it more responsive, and to avoid having having custom stylesheets inadvertently break it. If you don't mind me asking, what custom styles did you apply to it?

> RES removes every post without exception

The migration process is currently a little slow, so the filters are erroneously applied before the migration is ready. This is something which is currently being fixed.

**Comment by larsjohnsen** [comment]
> How is an iframe more responsive?

Reflows in the embedded window don't have to take Reddit's styles into account. Other extensions, such as LastPass and uBlock, don't slow it down. Previously all the settings console code and styles had to be loaded on every single page. This change will also allow utilizing frameworks such as React there in the future, as they will not become an extra burden on every other page load.

> iframe broke the style I've been using for years.

Do you mean that styles on pages other than the settings console are broken? If so, that's something I would like to debug.

**Comment by larsjohnsen** [comment]
I'll see if I can make the styles be applied also on the embedded page. Note that classes might have changed a bit (and likely will change more).

**Comment by narcolepticinsomniac** [comment]
>Do you mean that styles on pages other than the settings console are broken?

Nah, just the console. Making it off limits to user scripts/styles is no small detail though.

As for it being more responsive, I thought you meant in terms of CSS. At least there's some benefit to them, but quarantining the console will have a negative impact on anyone who has customized it in any way.

Any type of workaround would be a bonus.  Didn't even expect that much tbh, I just needed to complain to somebody. Appreciate you taking the time.

**Comment by larsjohnsen** [comment]
Added in #5040

**Comment by larsjohnsen** [comment]
Yeah, as far as I can see, the only way to add custom styles now is by using RES' stylesheets module. I'll try find some way to transmit certain styles to the embedded page.
