### ISSUE TITLE
SubReddit Link Auto Complete Displayes Behind Big Editor

### ISSUE THREAD

**Issue by Tensounder54** [honestbleeps/Reddit-Enhancement-Suite#5059]
- My browser: https://whatismybrowser.com/w/PQZZHTQ
- My RES version: v5.14.3
- Am I in reddit beta: No

*What's the problem?*
When using the big editor the SubReddit auto complete is displayed behind the big editor, blocking its visibility. I have attached an image to show this in action:
https://i.imgur.com/Tedo0Gk.png

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
Nope

*What other browser extensions are installed?*
None that would effect the operation of RES in anyway related to this issue.

**Comment by Tensounder54** [comment]
If you really need a complete list of my extensions then let me know. 

Also if your willing to give me some pointer as to where you think I should start I can look into fixing this myself.

**Comment by larsjohnsen** [comment]
Fixed in 10277a5c6875dbf3e2f882b22521300c655f8f2d
