### ISSUE TITLE
pauseAfterEvery and Autoload

### ISSUE THREAD

**Issue by xenius** [honestbleeps/Reddit-Enhancement-Suite#5067]
- My browser 72.0.3626.81
- My RES version: v5.14.4
- Am I in reddit beta (yes/no): No
- Nightmode ON

*What's the problem?*

I've set my pauseAfterEvery on 3. And autoload on. They way it worked before is that i get 3 page with NER, it would pause, and when i click next page it goes to the next page and it starts from page 4 and it would unpause. Now it doesn't unpause anymore .... NER works fine when i just put pauseAfterEvery on 0. But i really want this feature to work again like it used to, if its possible.

I really appreciate all the work you've done on this extension, but this is the feature i use to most :)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2367

*What other browser extensions are installed?*

even in incognito without every other extension disabled except RES it doesn't work anymore.

**Comment by larsjohnsen** [comment]
Is the issue fixed?

**Comment by xenius** [comment]
It is fixed yes. Thanks alot!
