### ISSUE TITLE
User tagger appears multiple times for postAuthor in lightbox when N/P

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#5068]
1. https://new.reddit.com
2. Click the "comments" button on a post.
3. Observe a usertag button to the right of the author link, above the post.
4. Press `N` on your keyboard to open the next post, keeping the lightbox open.

Expected: only one user tag button (user tag is updated or replaced)
Actual: tags accumulate

This is probably because React is reusing the postAuthor JSAPI container and not wiping the contents. RES should be aware that a container may get reused and update it accordingly. RES should probably remove any existing user tags in the JSAPI container before adding a new user tag.

**Comment by andytuba** [comment]
@prakhar1912, would you like to take on this bug?

**Comment by prakhar1912** [comment]
> @prakhar1912, would you like to take on this bug?

@andytuba Sure, on it.
