### ISSUE TITLE
hide the three icons in the site

### ISSUE THREAD

**Issue by gabri25ele** [honestbleeps/Reddit-Enhancement-Suite#5095]
Is possible to Hide the three icons (to-top, add-account, RES-settings) in the site toolbar?
![sshot-1](https://user-images.githubusercontent.com/33927879/55415121-c4e9db00-556c-11e9-9847-911ef714e452.png)

I saw in the appearance section, but found anything

![sshot-2](https://user-images.githubusercontent.com/33927879/55415165-dcc15f00-556c-11e9-80d2-24d26aec6635.png)

**Comment by andytuba** [comment]
Could you ask this question in r/enhancement please?

**Comment by gabri25ele** [comment]
where is r/enhancement?
😧

**Comment by andytuba** [comment]
@gabri25ele https://www.reddit.com/r/enhancement
