### ISSUE TITLE
Hidden posts not shown in hidden section

### ISSUE THREAD

**Issue by josephlee93** [honestbleeps/Reddit-Enhancement-Suite#5097]
- My browser (copy from https://www.whatismybrowser.com): whatismybrowser.com/w/CXHWR73
- My RES version: v5.14.5
- Am I in reddit beta: No

*What's the problem?*

All my hidden posts aren't shown under https://old.reddit.com/user/<user>/hidden

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

None directly to those, but a r/Enhancement thread was created a couple days ago regarding this issue.

https://www.reddit.com/r/Enhancement/comments/b8ar9n/all_the_posts_i_have_hidden_are_no_longer/

*What other browser extensions are installed?*

ublock, darkreader, duckduckgo, and chrome ua spoofer

**Comment by larsjohnsen** [comment]
Fixed by Reddit
