### ISSUE TITLE
conserveMemory hiding images onscreen in Chromium based browsers

### ISSUE THREAD

**Issue by simshaun** [honestbleeps/Reddit-Enhancement-Suite#5104]
- My browser:
Microsoft Edge 75.0.139.1 (Official build) dev (64-bit)

- My RES version:
v5.14.5

- Am I in reddit beta (yes/no): 
No

*What's the problem?*
Inline image viewer images randomly dissappear without any interaction. (Not scrolling. Not hovering on/off the image. Just moving mouse around.)

In RES settings, I turned off Conserve Memory and that seems to have stopped the problem.

I was running the RES Chrome extension in Edge, but just to be sure I tried uninstalling it and installing the MS Store version of RES. The issue still occurred.

Note, it was running fine before today's Edge update. So, I'm guessing Edge did something that messed it up. I just don't know what.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
No

*What other browser extensions are installed?*
uBlock Origins, LastPass

**Comment by BenMcGarry** [comment]
We saw this issue in Chromium Canary but it looks like its creeping down into Dev channels. For the moment disabling "Conserve Memory" will be the official fix until we can see if its an issue that gets resolved in upstream browser fixes or it becomes a patch for us.

**Comment by BenMcGarry** [comment]
Fixed in https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/7a3ab68eff2b9d743e406eacd2dcab311d0c34f3 @ 5.15.0
