### ISSUE TITLE
Occasionally both 'Static Image' & 'Video' icons displayed at once

### ISSUE THREAD

**Issue by NginUS** [honestbleeps/Reddit-Enhancement-Suite#5118]
- My browser (copy from https://www.whatismybrowser.com):
- My RES version:
- Am I in reddit beta (yes/no): 

Firefox 66.0.5
RES 5.16.7
Linux Mint 18.3
No beta

*What's the problem?*

Sometimes I see this like the attached screenshot, only 1 works & only 1 is displayed when viewing the link on its own page.

![Reddit_DoubleIcon](https://user-images.githubusercontent.com/8769067/58083935-ed16b300-7b87-11e9-9703-e9b2fea660d8.png)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

*What other browser extensions are installed?*
Auto Reload Tab
Disable HTML5 Autoplay
Disable Tab Detach 2
Evernote Web Clipper
Facebook Container
Firefox DevTools ADB Extension
Firefox Pioneer
htofix-update-xpi-intermediate
HTTPS Everywhere
iGive Button
In-Page Pop-Up Reporter
Joplin Web Clipper
MTurk Suite
No Coin
NoScript Security Suite
Old Reddit Redirect
Pretty New Tab Image
Privacy Badger
Reddit Enhancement Suite
Save Page WE
Tabloc
Tampermonkey (TurkerviewJS)
uBlock Origin
Undo Closed Tabs Button
Dark Reader
One-click Screenshot
RedditNotifier-WE
Redirector
Video Background Play Fix

**Comment by simeon4110** [comment]
I am unable to reproduce this issue. Has anyone else had any luck?

**Comment by NginUS** [comment]
Again tonight:
![Clipboard01](https://user-images.githubusercontent.com/8769067/58389183-0ee3c000-7ff6-11e9-80d0-5bdbf2025a7f.png)
![Clipboard010](https://user-images.githubusercontent.com/8769067/58389184-1014ed00-7ff6-11e9-853c-c3b00cc85fc0.png)

**Comment by larsjohnsen** [comment]
Have you noticed this anytime lately?

**Comment by NginUS** [comment]
Now that you mention it, no. Probably the last time I saw it was a day or so after the last I posted here.
