### ISSUE TITLE
Pictures disappear after a while

### ISSUE THREAD

**Issue by courrier1** [honestbleeps/Reddit-Enhancement-Suite#5130]
Opera 62.0.3331.43
RES 5.12.8
Other extensions: uBlock Origin, Twitch Now, Enhancer for Youtube, Translate Google, LastPass (they shouldn't matter since turning off RES seems to fix the problem)

It's happening since at least June, I've tried the same combination of extensions on Chrome and it's working normally

Video proof: [https://youtu.be/qcTglWp2XqE](https://youtu.be/qcTglWp2XqE)

**Comment by larsjohnsen** [comment]
See https://www.reddit.com/r/RESAnnouncements/comments/aqbc4t/opera_releases_are_moving_to_a_new_home/
