### ISSUE TITLE
Endless scrolling not working

### ISSUE THREAD

**Issue by DanielValahul** [honestbleeps/Reddit-Enhancement-Suite#5136]
As the title says, i have endless scrolling enabled but i get this error

> Could not load the next page: Page loaded was not for current user

Is there a way to enable it? Im on old reddit and not really enthusiastic about the redesign

**Comment by andytuba** [comment]
@DanielValahul Have you posted to r/RESissues?

**Comment by DanielValahul** [comment]
No, but in the end I switched back to new reddit
