### ISSUE TITLE
Auto Nightmode: Access to your current location was denied

### ISSUE THREAD

**Issue by jeffreymcclain** [honestbleeps/Reddit-Enhancement-Suite#5151]
- My browser (copy from https://www.whatismybrowser.com): Chrome 77, 64-bit on Windows 10, v1903
- My RES version: 5.18.0
- Am I in reddit beta (yes/no): No

*What's the problem?*

I can't enable auto-nightmode, it reverts back after refreshing. I have already granted location permission within the browser.

*Where does it happen?*

It occurs when I enable auto-nightmode and then refresh the page and click the RES settings icon.

*Screenshots or mock-ups*

https://i.imgur.com/2eLI3ap.png

https://i.imgur.com/9Vre5Cf.png

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Yes, [my first post](https://www.reddit.com/r/Enhancement/comments/c8xjzl/auto_nightmode_access_to_your_current_location/) and [my second post.](https://www.reddit.com/r/RESissues/comments/cm45z1/auto_nightmode_access_to_your_current_location/)

*What other browser extensions are installed?*

I disabled all other browser extensions to ensure there were no conflicts.

**Comment by Raptime** [comment]
I'm having the same issue using Firefox on Linux:

- Firefox 75 (was already an issue with 74)
- RES v5.18.12

I gave location access to www.reddit.com, old.reddit.com and the extension itself, I still get the same popup about location access denied :(

**Comment by azumukupoe** [comment]
Same issue on

Firefox 77.0.1
Reddit Enhancement Suite v5.20.0

**Comment by BenMcGarry** [comment]
This looks to be a permission issue with the manifest. Doing testing.

**Comment by BenMcGarry** [comment]
Resolved in next release

**Comment by jeffreymcclain** [comment]
@BenMcGarry Thanks for submitting a fix for this! No rush, but it's been two months without a stable release that would contain this fix, do you know if a stable release is planned for the near future?
