### ISSUE TITLE
"unhidehide" after a post is hidden

### ISSUE THREAD

**Issue by scharmach** [honestbleeps/Reddit-Enhancement-Suite#5152]
- My browser: https://www.whatismybrowser.com/w/LDLNB28
- My RES version: 5.18.2
- Am I in reddit beta (yes/no): No

*What's the problem?*

RES shows "unhidehide" after a post is hidden. I would expect it to say "unhide". Maybe has to do with the new autohide-function?

![grafik](https://user-images.githubusercontent.com/9080980/66201873-a9d75f80-e6a4-11e9-969d-82921755b955.png)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Haven't found any.

EDIT: Stumbled upon it being mentioned in /r/Enhancement just now: https://old.reddit.com/r/Enhancement/comments/dd1ufx/when_i_press_hide_it_turns_into_unhidehide/

*What other browser extensions are installed?*

Don't think this is relevant here.

**Comment by larsjohnsen** [comment]
Does enabling the option fixHideLinks fix it? https://old.reddit.com/r/Enhancement/comments/dd1ufx/when_i_press_hide_it_turns_into_unhidehide/#res:settings/betteReddit/fixHideLinks

**Comment by scharmach** [comment]
The option was already enabled on my system. Turning it off and on again (saved in between of course) made no difference.

**Comment by larsjohnsen** [comment]
Fixed in v5.18.3.
