### ISSUE TITLE
addons.mozilla.org: "add-on requieres at least FF 69. You are using 68." Actually using 70.

### ISSUE THREAD

**Issue by jtagcat** [honestbleeps/Reddit-Enhancement-Suite#5158]
![image](https://user-images.githubusercontent.com/38327267/67434243-41abd780-f5d9-11e9-8e4b-34cf5aae0c56.png)
/tableflip First impression.

*What other browser extensions are installed?*
Disabled anything relevant (useragent, other blockers).

**Comment by AB1908** [comment]
Am facing the same. Extensions currently installed are:
- Vimium
- HTTPS Everywhere
- Terms of Service; Didn’t Read
- Decentraleyes
- Privacy Settings
- Google search link fix
- KeePassXC-Browser
- Privacy Badger
- uBlock Origin
- TreeStyle Tab (disabled)

**Comment by jtagcat** [comment]
Do you have anything messing with the user agent? IIRC, I had an older version's user agent and AMO only realized that I have a newer agent, once the browser was restarted.

I think you can 'install anyway' with right clicking the install button, save as (and you get an xpi). Note, that way you won't receive updates.

You can always get RES from https://github.com/honestbleeps/Reddit-Enhancement-Suite/releases (also click watch->releases only)

**Comment by BenMcGarry** [comment]
Please see here: https://www.reddit.com/r/RESissues/comments/gekv12/res_common_issues_read_me_first/
