### ISSUE TITLE
No more pages [Chrome]

### ISSUE THREAD

**Issue by atmogenic** [honestbleeps/Reddit-Enhancement-Suite#5175]
Hello, I've been having this issue with RES for quite sometime now and its getting to my limit of this bug i've been having. Whenever reddit tries to load a page, it will load no more than 3 to 4 pages before saying "no more pages" when the subreddits have way more content then what its showing

![chrome_O0EPIKlfSL](https://user-images.githubusercontent.com/56037304/71380061-c9a46280-25c5-11ea-9c51-7ea27d963660.png)

This is on the Livestreamfail subreddit, its been around for 4 years and gets content daily. but as u can see the page loading is messed up and only gets to page 3 before giving up loading anything else. I've got filters on but disabling the filters doesn't solve the issue because it can only still load content from only 12 days ago, past that it says "no more pages" again, this doesn't just happen on this subreddit, this happens on my home page as well it only loads up to around 230 posts before giving up.

Browser - Google Chrome 
Res v5.18.8 

These are the things i've tried that i've seen people talk about a similar issue
- Cleaned up my cache and cookies = failure
- Disabled all extensions except RES = failure
- Disabled Never ending reddit = failure
- Disabled filtereddit = failure
- Disabled RES which brought back the original reddit and there was no more loading pages issue but also means no filtereddit which i need

I did do a post on r/Enhancement but it didn't get any help whatsoever and only downvoted.

This is the only place I can think of that someone might be able to help me out with and finally resolve this annoying issue.

thanks for reading

**Comment by BenMcGarry** [comment]
What version of chrome are you using? And do you have any filters enabled?

**Comment by atmogenic** [comment]
Chrome 79

and yes i've got a lot of filiters with RES but as I said it doesn't change when i disable the filtreddit nor when i disable all my other extensions except RES

**Comment by atmogenic** [comment]
still no fix

**Comment by atmogenic** [comment]
ok i've fixed it but it seems some kind of bug on reddit where it doesn't show anything in the past if you set posts with a certain number of upvotes or higher, I just removed that so its blank and now no more "no more pages" issues.

**Comment by atmogenic** [comment]
nevermind it still having the paging issue as seen here
![chrome_u3ic84QsxU](https://user-images.githubusercontent.com/56037304/71642757-427f7a80-2ca8-11ea-8652-3d7a9dc37125.png)

**Comment by BenMcGarry** [comment]
What are your filters set to? You are filtering a lot of posts based on the left counter.

________________________________

**Comment by atmogenic** [comment]
the filters are to the big twitch streamers, but this doesn't just happen with livestreamfails. The other thing I saw today was that the apollo is also doing the same thing and since that doesn't have RES then i figured its reddit itself causing the issue so i looked at my settings and the only thing that came to mind that might be the issue is that i had the "hide posts lower than 50" so i removed that so its blank and i thought i fixed the issue, but that seems it wasn't the case.

here is my media and link settings 

![chrome_QTa4RAyr5s](https://user-images.githubusercontent.com/56037304/71642786-f08b2480-2ca8-11ea-89a6-924a89995bde.png)

**Comment by BenMcGarry** [comment]
@andytuba What’s Reddit’s API limits?

________________________________

**Comment by atmogenic** [comment]
sorry idk what u mean and where i find that?

**Comment by BenMcGarry** [comment]
That ones not for you, but want to check what our limits to Reddit’s api is.

________________________________

**Comment by atmogenic** [comment]
oh ok sorry

**Comment by atmogenic** [comment]
did u get a reply back?

**Comment by hemlok89** [comment]
The Reddit API access rules state that you may make up to 60 requests per minute, but the response headers given are on a 10 minute time scale.

**Comment by atmogenic** [comment]
I'm sorry but I have no idea what you're on about, I just want to know whats causing this issue for me that i've had for a long time.

**Comment by atmogenic** [comment]
![chrome_c4kVYu2JUn](https://user-images.githubusercontent.com/56037304/72062270-5ee66d00-32cf-11ea-9518-c9e14c110f57.png)
This what I got today on my home tab

**Comment by hemlok89** [comment]
What ad blocker are you using?

**Comment by andytuba** [comment]
Hiya, what happens if turn off Never Ending Reddit in RES settings and just scroll down and click "next" at the bottom of the post list? What's the highest numbered post (the number on the left) you can get to?

**Comment by gavin19** [comment]
Closing as this was due to reddit prefs (hide after downvote/only show posts with more than) and not RES (although it was filtering as instructed, the large number of missing posts was due to the aforementioned reddit options).
