### ISSUE TITLE
Google Drive Backup fails on Restore

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#5180]
Google Drive Backup appears to be failing on restore. **Backups appear to be unaffected and fine.**

> 405: The request method OPTIONS is inappropriate for the URL

> Access to fetch at 'REMOVED' (redirected from 'https://content.googleapis.com/drive/v3/files/REMOVED?alt=media') from origin 'chrome-extension://kbmfpngjjgdllneeigpgjifpgocmfgmb' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by BenMcGarry** [comment]
Looks like this may be a platform issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=966223
https://docs.google.com/document/d/1gJnF1jp7AFHAJBhwgC8cdSDBN5iOEzf4tdNsOTfJC2Y

**Comment by BenMcGarry** [comment]
Chromium have ruled out a platform issue and appears to be an issue directly related to GDrive. Firefox, Chrome and Edge are all affected. I think we need to look at how we are interfacing with the API.

**Comment by erikdesjardins** [comment]
I think this is a bug on the Google Drive side, [other](https://issuetracker.google.com/issues/150193301) people [are](https://support.google.com/chrome/thread/29767271) seeing the same thing. (We do need to request permissions for googleusercontent.com in Chrome like we do in Firefox, but then we just get a 403.)

It's funny, it doesn't seem possible to access the url it redirects us to in any way. I thought it might require cookie auth instead, but that doesn't work either (even if it worked, it would be inconsistent for people logged into multiple google accounts).

**Comment by creesch** [comment]
On irc we found a few things the other day: 

- A published change [here](https://cloud.google.com/blog/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api) 
- A difference in the endpoints RES uses [and those documented here](https://developers.google.com/drive/api/v3/reference/files/get)

**Comment by BenMcGarry** [comment]
Looking at that bug raised with Google, are they even treating this as an issue or intended feature?

**Comment by erikdesjardins** [comment]
omg

it does work on www.googleapis.com

w h a t

why is there a slightly different api hosted on content.googleapis.com?

**Comment by creesch** [comment]
Did anyone try altering the endpoints to the documented ones yet? 

I mean [this](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/backupAndRestore/providers/GoogleDrive.js#L36) is clearly a different url from the [documented here](https://developers.google.com/drive/api/v3/reference/files/get)
