### ISSUE TITLE
OAuth redirection URI must be updated for Firefox

### ISSUE THREAD

**Issue by larsjohnsen** [honestbleeps/Reddit-Enhancement-Suite#5184]
Breaking change in Firefox 75. All OAuth providers must allow `https://f6be6623b0b4ed4e84464ff8b07afff3c421e497.extensions.allizom.org` as redirect URIs.

https://bugzilla.mozilla.org/show_bug.cgi?id=1617885

Updated docs https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity#Getting_the_redirect_URL:
> Starting with Firefox 75, you must use the redirect URL returned by identity.getRedirectURL().  Earlier versions allowed you to supply any redirect url.

**Comment by thaurane** [comment]
The issue is still present.
