### ISSUE TITLE
Error "Could not load the next page: Page loaded was not for current user" while using Never Ending Reddit

### ISSUE THREAD

**Issue by rdivanji** [honestbleeps/Reddit-Enhancement-Suite#5217]
- My browser: [My main Firefox Nightly build.](https://whatismybrowser.com/w/F9A36EN) It also does not work on Firefox stable, with [this](https://whatismybrowser.com/w/Q8JCB32) browser profile.
- My RES version: v5.18.14
- Am I in reddit beta (yes/no): Yes

*What's the problem?*
When enabling Never Ending Reddit and visiting any subreddit (including /r/all and my frontpage), this error is displayed: `Could not load the next page: Page loaded was not for current user`

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
Not from within the last month. From what I can find, those posts say it was fixed magically somehow, maybe from a server-side Reddit change? 

*What other browser extensions are installed?*
Facebook Container, GNOME Shell Integration, Google Images Restored, HTTPS Everywhere, MaterialFox Helper, and uBlock Origin. The error still appears even after disabling the extensions, restarting the browser, then refreshing the page. 

I do not think this was caused by a recent update to Firefox. It started happening within the past 24 hours, if that helps. I have tried the solutions on the FAQ to no avail.  

Ninja edit: fixed links

**Comment by BenMcGarry** [comment]
Please try this: https://www.reddit.com/r/Enhancement/wiki/faq/never_ending_reddit

**Comment by rdivanji** [comment]
I tried the solution again on the firefox nightly build and it doesn't work. Here's the thing though, I opened Stable and now it works. Within the past 12 hours I have done nothing to that version's settings, yet it didn't work last night and now it somehow does. I matched the reddit cookie permission settings and FireFox privacy preferences on each build and still the nightly doesn't work. I messed around with third party cookie settings and whatismybrowser always shows that third party cookies are disabled on the nightly, so maybe it is in fact a nightly bug? How can I further debug this?

**Comment by BenMcGarry** [comment]
As it looks to be a nightly issue there’s not much point debugging it. We only really support RES when releases hit beta as the codebase is stable(?). In nightly something can break and be fixed 48 hours later and the time taken to figure it out isn’t worth it at that point. The risk of running nightly is things will break.

**Comment by honestbleeps** [comment]
Just to add on to what Ben said:

You really shouldn't be running nightly unless you have a strong reason to.
It's made for folks who are in need of testing bleeding edge features
before they're readily available and the whole purpose of not releasing
whatever is in nightly yet is that it's likely rife with bugs.

Aside from specific subset of web developers, nobody should really have a
need for nightly versions as a daily driver.

**Comment by evilpie** [comment]
Thanks for using Nightly and helping to find bugs. :smiling_imp: In fact the likely regressor is already in Beta now. https://bugzilla.mozilla.org/show_bug.cgi?id=1635490

Do you have cookies for multiple different users?

**Comment by BenMcGarry** [comment]
What do you mean by cookies for multiple different users?

**Comment by BenMcGarry** [comment]
It looks like this is a bigger issue that may impact RES significantly due to a Firefox platform change. Tracking at bugzilla posted by evilpie.

1. Requests will need shifting from context > background page.

With the above done, we may have to drop RES support for private browsing as Mozilla hasnt implemented https://bugzilla.mozilla.org/show_bug.cgi?id=1380812.

**Comment by BenMcGarry** [comment]
Issues now fixed within Firefox, with the patch pushed to FF 77 Beta 6 (Sometime around 15th May).

**Comment by BenMcGarry** [comment]
Closing as this should now be fixed.
