### ISSUE TITLE
Redgifs expandos do not expand when clicking "Show Images"

### ISSUE THREAD

**Issue by joshieecs** [honestbleeps/Reddit-Enhancement-Suite#5233]
- My browser: Firefox 78 on Windows 10
- My RES version: 5.18.14 and 5.19.1beta
- Am I in reddit beta (yes/no): no

Redgifs expandos do not expand when clicking "Show Images" when opted out of the new Reddit (old.reddit.com). They work when expanded individually. 

autoExpandTypes set to "All muted Expandos (including iframes)"
autoplayVideo enabled or disabled has no effect. 

Changes in #5221 are present in 5.19.1beta but do not resolve this issue.

**Comment by BenMcGarry** [comment]
This is intended at this time. Redgifs do not have a API we can use that is stable to we are relying on a iFrame that they provided which we do not expand.

https://www.reddit.com/r/RESissues/comments/gxpubm/redgifs_not_expanding_show_all_images/ftafbqu/

**Comment by BenMcGarry** [comment]
Actually re-opening this for curiosity, @larsjohnsen do we know if iFrames are meant to expand on show all? Wording in console looks so but cant find history of it.

**Comment by xenius** [comment]
Would be nice if this would work again like it did with gfycat.

**Comment by jingofett** [comment]
Your issue could be Privacy Badger blocking RedGIFs from loading. Found here:
https://old.reddit.com/r/Enhancement/comments/hdu1qe/psa_privacybadger_breaks_the_redgifs_popups_not/

Changing the Privacy Badger slider for redgifs.com to block the cookie instead of the domain worked for me.

**Comment by joshieecs** [comment]
@jingofett Thanks for the suggestion. I think there are several different Redgifs issues right now.

The one I a reporting is that muted Redgifs expandos don't expand when I click "show images". They play fine when I manually expand them. I can reproduce this behavior even in a clean environment with no extensions running other than RES.

**Comment by TrentSterling** [comment]
Just noticed this is an issue today. Seems a shame when gfycat pages would **Show Images** so well!

**Comment by decaff** [comment]
> From @jingofett:
> Your issue could be Privacy Badger blocking RedGIFs from loading. 
> Changing the Privacy Badger slider for redgifs.com to block the cookie instead of the domain worked for me.

Yes!  Thanks so very much.  **Works for me**.

**Comment by thorman123** [comment]
any updates on this yet? Has the api been updated? Are we currently waiting on redgifs?

**Comment by Luke-L** [comment]
necro but its still an issue so ¯\_(ツ)_/¯
