### ISSUE TITLE
"Use subreddit style" is not working on old.reddit.com

### ISSUE THREAD

**Issue by Runiko** [honestbleeps/Reddit-Enhancement-Suite#5237]
- My browser (copy from https://www.whatismybrowser.com): Firefox 77.0.1 on Debian 10
- My RES version: 5.20.0
- Am I in reddit beta (yes/no): no

*What's the problem?*
When I'm trying to toggle subreddit style, whether on address bar or navbar, it does nothing. Box is still checked; alternatively page refreshes without change.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?* No

*What other browser extensions are installed?*
- uBlock Origin
- Privacy Badger
- Cookie AutoDelete
- uMatrix
- HTTPS Everywhere

I tried to disable all the extensions but the issue still persists.

**Comment by larsjohnsen** [comment]
Fixed in d2291a7d3e76ad1cee6a7913da8b22388e704b2e
