### ISSUE TITLE
Dark mode setted on automatic causes frequent system-wide disconnects

### ISSUE THREAD

**Issue by madiele** [honestbleeps/Reddit-Enhancement-Suite#5242]
- My browser: Firefox 78 on Windows 10
- My RES version: v5.20.1
- Am I in reddit beta (yes/no): no

*What's the problem?*
After enabling dark mode based on location the extension causes disconnects in the whole computer of 1-2 seconds multiple times every minute (the wifi doesn't drop but all everything is unable to load in that time)

the location access is enabled (firefox actually says RES asked for it recently), but for some reason, when opening the settings RES is telling me that firefox didn't give the permission and asks to disable automatic dark mode, once disabled the bug goes away only after a full restart of firefox, the disconnects once started keep happening even when no Reddit tabs are open

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
didn't find any

*What other browser extensions are installed?*
tested with all other extensions disabled, the bug is still present

**Comment by BenMcGarry** [comment]
RES uses the browsers implementation so this would be a browser bug rather than a RES bug as we cannot interact with the system. Please file this with Mozilla.

**Comment by madiele** [comment]
I tried calling the API usend in the RES source code on my website and I confirm that the bug is in the firefox API, I sent a bug report to Mozilla, thank you for your time and the great extension!
