### ISSUE TITLE
RES allocates 16 MB of asm.js memory (for snudown.js) in every Firefox content process

### ISSUE THREAD

**Issue by cpeterso** [honestbleeps/Reddit-Enhancement-Suite#5253]
- My browser (copy from https://www.whatismybrowser.com): Firefox 82
- My RES version: 5.25.0
- Am I in reddit beta (yes/no): no

*What's the problem?*

A Firefox user reported that Firefox was using a lot of memory here: https://bugzilla.mozilla.org/show_bug.cgi?id=1663074

Firefox engineers examined the bug reporter's memory dump and saw that RES appears to be allocating 16 MB of asm.js memory (for snudown.js) in every Firefox content process.

Does RES need to be loaded in every Firefox content process? Can RES initialize snudown.js lazily to avoid allocating that 16 MB of asm.js memory?

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

*What other browser extensions are installed?*

Name: Always Right
Type: extension
Version: 2.0.7
Enabled: true
ID: jid0-SzimoL45Ib8OddgoUBG0buQmjec@jetpack

Name: Amazon Container
Type: extension
Version: 2.0.0
Enabled: true
ID: @contain-amzn

Name: Firefox DevTools ADB Extension
Type: extension
Version: 0.0.5
Enabled: true
ID: adb@mozilla.org

Name: Google Container
Type: extension
Version: 1.5.0
Enabled: true
ID: @contain-google

Name: LinkedIn Container
Type: extension
Version: 1.2.5
Enabled: true
ID: @contain-linked-in

Name: Reddit Enhancement Suite
Type: extension
Version: 5.20.5
Enabled: true
ID: jid1-xUfzOsOFlzSOXg@jetpack

Name: Twitter Container
Type: extension
Version: 1.3.1
Enabled: true
ID: @contain-twitter

Name: Duplicate Tabs Closer
Type: extension
Version: 3.5.3
Enabled: false
ID: jid0-RvYT2rGWfM8q5yWxIxAHYAeo5Qg@jetpack

Name: GNOME Shell integration
Type: extension
Version: 10.1
Enabled: false
ID: chrome-gnome-shell@gnome.org

**Comment by creesch** [comment]
Are there any reproduction steps to verify this claim? I have been trying to look into this and can't seem to get to the same reported memory usage for RES. I have been taking memory snapshots from the developer console and for reddit I see higher memory usage on new reddit for just the reddit scripting itself. 

I am basically wondering if there is a difference between various reddit pages and the two variants of reddit? For context https://old.reddit.com acts very different from https://new.reddit.com which is a react rewrite of reddit. RES interacts differently with both versions of reddit.

**Comment by cpeterso** [comment]
Thanks, @erikdesjardins! 👍
