### ISSUE TITLE
Edge 87: Attempting to backup/restore RES settings with Google Drive/OneDrive/Dropbox fails

### ISSUE THREAD

**Issue by kirazy** [honestbleeps/Reddit-Enhancement-Suite#5274]
- My browser: https://www.whatismybrowser.com/w/GF6ZK9N
- My RES version: v5.20.12
- Am I in reddit beta (yes/no): No

*What's the problem?*
Attempting to create or restore backups using any of Google Drive, Dropbox or One Drive results in an error: "Cannot read property 'getRedirectURL' of undefined".

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
https://www.reddit.com/r/RESissues/comments/krzcut/unable_to_restore_saved_settings/

*What other browser extensions are installed?*
uBlock Origin, NoScript, LastPass, Picture-in-Picture

**Comment by alysson-silva** [comment]
This only happens for me if I use the extension from the Microsoft Store. The one from Chrome works fine.

**Comment by BenMcGarry** [comment]
Fixes in #5279
