### ISSUE TITLE
Redgifs suddenly very small

### ISSUE THREAD

**Issue by Primeey** [honestbleeps/Reddit-Enhancement-Suite#5280]
- My browser (copy from https://www.whatismybrowser.com): Chrome 89 on Windows 10
- My RES version: 5.20.12
- Am I in reddit beta (yes/no):  No

*What's the problem?*

Every redgif I open is very small.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

https://www.reddit.com/r/RESissues/comments/l8tzav/redgifs_suddenly_very_small/

*What other browser extensions are installed?*

None.

**Comment by larsjohnsen** [comment]
Redgifs' API has been fixed. https://www.reddit.com/r/redgifs/comments/lb05x3/site_currently_down_we_are_currently/glr9hrh/
