### ISSUE TITLE
Twitch clips start muted 

### ISSUE THREAD

**Issue by arye321** [honestbleeps/Reddit-Enhancement-Suite#5282]
Night mode: true
    RES Version: 5.20.12
    Browser: Firefox (happens with Chrome also)
    Browser Version: 85
    Cookies Enabled: true
    Reddit beta: false

I've disabled auto mute on all settings, Firefox, RES console. nothing helps. 

Heres how it looks: https://streamable.com/5608q3
If I load the link directly its not muted: https://streamable.com/tg3p3v

Other websites work and load with sound, only twitch clips load muted.

**Comment by larsjohnsen** [comment]
Fixed by #5281.
