### ISSUE TITLE
TwitchClip edge case not fixed

### ISSUE THREAD

**Issue by Saxayone** [honestbleeps/Reddit-Enhancement-Suite#5284]
There is still an edge case that was missed with this fix.
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/5281

When it has a double hyphen, example:
https://clips.twitch.tv/ResourcefulCrazyNarwhalMau5--lX7NFdp8DZQTyMV

**Comment by kcyk01** [comment]
Hey @Saxayone , thanks for providing an example of the edge case. I'm just aggregating a bit more data to see what other formats the twitch clip names are like before attempting another fix for a more generic RegEx.

Using this thread to track a few more formats:
https://clips.twitch.tv/HyperCarefulFennelCorgiDerp-QBN2K-63wIY7ULy-
