### ISSUE TITLE
Night Mode Display Issues

### ISSUE THREAD

**Issue by juststur** [honestbleeps/Reddit-Enhancement-Suite#5285]
- My browser (copy from https://www.whatismybrowser.com): Edge 90 on Windows 10
- My RES version: v5.20.12 
- Am I in reddit beta (yes/no): no

*What's the problem?*
Night mode does not display correctly, large blocks of white/light blue content shows.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Yes, https://www.reddit.com/r/RESissues/comments/llpacl/night_mode_doesnt_work_properly_in_current_beta/

*What other browser extensions are installed?*
LastPass, OneNote Web Clipper, uBlock Origin

**Comment by BenMcGarry** [comment]
This looks to be an upstream issue with Edge 790, its been fixed in latest chromium so should come through to Edge dev soon.
