### ISSUE TITLE
[REQUEST] Warning to dismiss all unread messages

### ISSUE THREAD

**Issue by mirh** [honestbleeps/Reddit-Enhancement-Suite#5293]
- My browser: Firefox 88 on Windows 10
- My RES version: 5.22.3
- Am I in reddit beta (yes/no): no

*What's the problem?*
I don't really know what happened in that minute my connection was slow as sin and dropping packets like they were candies... Anyway long story short I tried to open my inbox, only to find all my 60 unread messages gone. 
Perhaps in my goddamn-please-just-open fury I clicked somewhere I didn't have (to be honest, I don't even know if such a "dimiss all" button exists on desktop), but it happened. 

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
Doesn't seem so.

**Comment by mirh** [comment]
Seriously, what the fuck?
I didn't even do anything particular this time, and I got all my unread messaged purged again.

**Comment by honestbleeps** [comment]
if you think that coming back to your feature request with profanity is going to help get it prioritized, you're mistaken.

losing your unread messages is a bummer, but that's nothing to do with RES. RES doesn't have a "dismiss all unread messages" button - so you are swearing at us about something you dislike about reddit, not reddit enhancement suite.

going to go ahead and close this issue.
