### ISSUE TITLE
Account switching not working

### ISSUE THREAD

**Issue by mrstoffer** [honestbleeps/Reddit-Enhancement-Suite#5302]
- My browser (copy from https://www.whatismybrowser.com): Firefox 89 https://whatismybrowser.com/w/FFQHQ5G
- My RES version: 5.22.5
- Am I in reddit beta (yes/no): no

*What's the problem?*
Accounts don't switch. When I click on my alt, it loads but nothing happens. The console outputs the following:
Error: https://www.reddit.com/logout?app=res failed with status 503
    FetchError moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:4421
    ajax moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:4467
    switchTo moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:21211
    mutex moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:906
    createAccountMenu moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:21189
    createAccountMenu moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:21185
    open moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:8360
    open moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:8365
    begin moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:8328
    contentStart moz-extension://56d92d40-21c9-46cf-801c-066293f20acd/foreground.entry.js:21121
foreground.entry.js:21192:17

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
I have found some with the same issue but none with the same console output. But I didn't look for long

*What other browser extensions are installed?*
Dark reader
Ublock Origin
Bitdefender Anti-tracker and Wallet
SponsorBlock
Side view
Firefox Notes
Bitwarden
Vue Devtools
User-agent Switcher
Opt-out for Google Analytics
Disable Youtube Comments
Privacy Badger
Bypass Paywalls Clean

**Comment by BenMcGarry** [comment]
This is reddit side related to a current service issue. The site is currently returning lots of 503s.

https://www.redditstatus.com/incidents/7k8ktx4rdj5c
