### ISSUE TITLE
subreddit bar: "Home" and other links not available (RES is loading before these are loaded)

### ISSUE THREAD

**Issue by kennypu** [honestbleeps/Reddit-Enhancement-Suite#5360]
**- My browser (copy from https://www.whatismybrowser.com):**
Chrome 96 on Windows 10

**- My RES version:** 5.22.5 
**- Am I in reddit beta (yes/no):** no

**What's the problem?**
"Home", "Popular" and some other links that are pulled from the original site is not available in the top subreddit bar.

Issue seems to be due to RES loading before these are loaded on Reddit. Breakpoint on `createSubredditBar()`:
![image](https://user-images.githubusercontent.com/1253814/145275933-97d7d32d-7d7a-4682-bd4e-3708e9217334.png)

you can see `originalShortcuts` where RES seems to pull these links from is empty.

**Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?**
https://www.reddit.com/r/RESissues/comments/qvbzv7/home_link_in_subreddit_manager_has_gone_missing/
https://www.reddit.com/r/RESissues/comments/p8ndx5/sometimes_the_home_link_disappears/

**What other browser extensions are installed?**
None

**Comment by SirRahikkala** [comment]
I have the issue as well and there is a Reddit thread about it too. https://www.reddit.com/r/Enhancement/comments/r96mbq/ive_lost_my_home_button/

**Comment by BenMcGarry** [comment]
Are you able to provide any console logs? I am unable to reproduce this on Chrome Stable/Dev/Canary.

**Comment by kennypu** [comment]
@BenMcGarry only thing in the console (at the time of the breakpoint) are the following: 

**main tab**
![image](https://user-images.githubusercontent.com/1253814/145707615-8d4047ef-72ad-4a17-a0e8-173cf3517269.png)

**background.entry.js**
![image](https://user-images.githubusercontent.com/1253814/145707912-0cf3725c-dee6-4b9c-9e13-b5af08ff386a.png)

the structure of `_subredditBar` is:
![image](https://user-images.githubusercontent.com/1253814/145708216-6d983868-dec7-4928-9f7d-143237dc6ec3.png)



and yeah it seems to only affect some people, and sometimes randomly. Let me know if there is anything I can do to try to debug/replicate.

**Comment by hlovdal** [comment]
Regarding

> Issue seems to be due to RES loading before these are loaded on Reddit. 

this is potentially very simple to fix (given that the dependencies are known).

We faced a similar problem with a leaflet map which fires `onMapReady` when the base library is ready, but before additional leaflet controls are added, one of which we wanted to modify. This turned out to be easy to do using a `waitForElement` function:

```typescript
onMapReady(leafletMap: L.Map) {
    ...
    // While this function is called when the map is ready, that is only an
    // indication that the base leaflet map component is present. Additional
    // controls are put into place with the "onAdd" method, which happens
    // *after* onMapReady returns.
    // https://leafletjs.com/examples/extending/extending-2-layers.html
    // https://leafletjs.com/examples/extending/extending-3-controls.html
    // Therefore we need to wait for the relevant control to be added before
    // trying to modify it. This is fortunately easy to do using waitForElement.
    waitForElement(this.nativeElement, '.leaflet-control-layers').then(element => {
      element.addEventListener('mouseenter', (e) => element.classList.remove('leaflet-control-layers-expanded'));
    });
  }

...

// Based on https://stackoverflow.com/a/61511955/23118
// Usage:
//    waitForElement(this.nativeElement, 'button .click-me')
//      .then(element => element.click())
export function waitForElement(rootElement: HTMLElement, selector: string) {
  return new Promise<ReturnType<typeof rootElement.querySelector>>(resolve => {
    if (rootElement.querySelector(selector)) {
      return resolve(rootElement.querySelector(selector));
    }

    const observer = new MutationObserver(mutations => {
      if (rootElement.querySelector(selector)) {
        resolve(rootElement.querySelector(selector));
        observer.disconnect();
      }
    });

    observer.observe(rootElement, {
      childList: true,
      subtree: true
    });
  });
}
```

**Comment by SirRahikkala** [comment]
This issue is back again.

**Comment by BenMcGarry** [comment]
This has not yet been released to stable
