### ISSUE TITLE
v.redd.it expandos not working consistently.

### ISSUE THREAD

**Issue by crespire** [honestbleeps/Reddit-Enhancement-Suite#5366]
- My browser (copy from https://www.whatismybrowser.com): https://whatismybrowser.com/w/YFWQW7F
- My RES version: 5.22.5
- Am I in reddit beta (yes/no): no, on old.reddit.com

*What's the problem?*
Certain video expandos from v.redd.it were not working. I resolved the issue by turning RES off, expanding the v.redd.it content expando using vanilla Reddit, closing the expando, and re-enabling RES. The previous v.reddit.com expando that was not working is now working with RES enabled. Maybe there's an issue with caching the content initially? There were no console errors when the expando was not working.

This particular video was not loading for me before I did the off/on steps above: https://www.reddit.com/r/ontario/comments/rs6rcu/were_back_to_where_we_were_youd_think_by_the/?ref=share&ref_source=link

I tried to find other expandos that were previously not working but it seems after off/on, they also work as expected. This was another v.redd.it expando that was not working previously: https://www.reddit.com/r/IdiotsInCars/comments/rs2jjj/battle_of_the_karens_be_careful_who_you_cutoff/?ref=share&ref_source=link

*What other browser extensions are installed?*
Pocket, Notion Webclipper, Lastpass and uBlock Origin. No other addons were modified during this time.

**Comment by hlovdal** [comment]
@crespire It would be great if you added a comment about why you closed this issue (even if it is just "Turned out to be problem X instead").

**Comment by crespire** [comment]
> @crespire It would be great if you added a comment about why you closed this issue (even if it is just "Turned out to be problem X instead").

Thanks for the prompt. I closed as I am not sure what the original problem was and I don't seem to be encountering it any longer. Because I wasn't able to provide any more insight nor reproduce it, I figure it was probably a one off interaction between all the elements.

Thanks for all the work you put into this!
