### ISSUE TITLE
Banned Users lose access to Reddit-based reporting functions.

### ISSUE THREAD

**Issue by Mayakovsky** [honestbleeps/Reddit-Enhancement-Suite#5409]
I've been permanently banned from Reddit.  Which is fine, the censorship there is absolute.  But by extension - Github is the only place I can actually connect to RES coders/community.

What I wanted to do was make a suggestion.  I'd like have a toggle that flags every comment that an OP has interacted with, and move them to the top of the comment section.  For instance - r/amitheasshole is a subreddit where a narrative is developed, so additions to that narrative are often requested and responded to.  Edits are usually added to the original post text, but this is at the discretion and abilities of the OP.

Flagging all OP responses and bringing them to the top of comments would save an enormous amount of scrolling time.

r/AMA is anther obvious candidate for this functionality.

Sorry for jumping into bug world - if there is an alternative comm better suited to this issue - please let me know and I'll redirect.

**Comment by creesch** [comment]
Already is a thing, not exactly in the way you describe but close enough

At the top of a comment section you have this menu. 
![image](https://user-images.githubusercontent.com/2502190/177056241-e811a7c4-a487-4436-8ddf-b4c4923100bc.png)

Once clicked, you get navigation on the right of the window
![image](https://user-images.githubusercontent.com/2502190/177056266-157dc6d9-625b-4057-90ae-b214f746869b.png)
