### ISSUE TITLE
Onion site support?

### ISSUE THREAD

**Issue by hasandiwan** [honestbleeps/Reddit-Enhancement-Suite#5423]
https://www.reddit.com/r/Enhancement/comments/ycq5ja/can_res_be_used_on_the_reddit_onion_site/ 

This seems like a trivial thing to do, but I don't know enough about the RES codebase to do it myself. Fundamentally, I use the tor browser to access reddit and reddit.com stopped working on tor this evening.

While I've reported this, I am able to access the hidden service, albeit without res. 

I would like some pointers on where to look to allow RES on the onion site. Many thanks, in advance.

**Comment by BenMcGarry** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/5422
