### ISSUE TITLE
Disabled by MS Edge because the extension now requires access to all sites

### ISSUE THREAD

**Issue by DarthJahus** [honestbleeps/Reddit-Enhancement-Suite#5437]
It seems like RES has got an update (5.22.11), and Edge has disabled it because it now requires access to all sites.

**Comment by BenMcGarry** [comment]
RES does not require access to all sites and does not ask for it, its disabled due to a prompt to add support for Reddits Tor site. If the user does not interact it will remain disabled.

https://www.reddit.com/r/Enhancement/comments/zqi9v8/the_new_release_of_res_is_safe_the_weird_looking/

**Comment by DarthJahus** [comment]
Thank you for clarifying the matter, @BenMcGarry.
