### ISSUE TITLE
[bug] Hiding posts fails with error

### ISSUE THREAD

**Issue by jfessard** [honestbleeps/Reddit-Enhancement-Suite#5471]
- My browser : Chrome 114 on Windows 11 (114.0.5735.199 (Official Build) (64-bit))
  - Also happens on Firefox 114.0.2 (64-bit)
- My RES version: 5.22.17
- Am I in reddit beta (yes/no): yes, bug happens in both

*What's the problem?*
Pressing the "hide" button below any submission (next to "share/save/give award" shows the popup message: 
> "Sorry, there was an error trying to hide your submission. Try clicking again."

Disabling RES, I can hide a post without any issues. (on `old.reddit.com`)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
I did not find any.

*What other browser extensions are installed?*
- ublock Origin (disabling has no effect)
- video speed controller

**Comment by aayio** [comment]
I think this is a change on Reddit's end, see [Need help cannot hide posts (self.help)](https://old.reddit.com/r/help/comments/14rkm19/need_help_cannot_hide_posts/)
