### ISSUE TITLE
NSFW-style filter with custom subreddits

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#548]
http://www.reddit.com/r/Enhancement/comments/1lbtat/a_nsfwlike_personal_filter_for_res/

http://www.reddit.com/r/Enhancement/comments/1ptlpc/feature_request_add_quick_toggle_for_toggling/

**Comment by erikdesjardins** [comment]
filters in #2077, and toggles in another PR
