### ISSUE TITLE
Causing Rate Limit Cap?

### ISSUE THREAD

**Issue by chryton** [honestbleeps/Reddit-Enhancement-Suite#5485]
- My browser (copy from https://www.whatismybrowser.com): https://whatismybrowser.com/w/WLBLDNJ
- My RES version: 5.22.17
- Am I in reddit beta (yes/no): no

*What's the problem?*
Whenever I visit reddit (main page, subreddit, thread, etc.) I am served with a blocked screen due to rate limiting despite no other actions taken on Reddit during the day. RES is the only reddit extension used and I am the only person in my household using reddit. No scraping or other scripts are running in the background.

I have already reached out to Reddit about this but I have a sneaking suspicion that RES could be triggering a false positive on Reddit's end and triggering a rate limit cap despite normal usage.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
No

*What other browser extensions are installed?*
uBlock Origin
WAppalyzer
(not an extension but possibly relevant) pi.hole

**Comment by BenMcGarry** [comment]
Please see https://www.reddit.com/r/Enhancement/comments/17vbmwe/reddit_blocking_my_user_agent/

**Comment by chryton** [comment]
Good to know. Thanks!
