### ISSUE TITLE
MV3 CSP Blocking Reddit media player

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#5511]
`Refused to load the script 'https://www.redditstatic.com/videoplayer.XCrwE8Bi5A4.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/utils/pageContextScript.js

Stack trace points here: https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/580e8eafa9bdd1d4bd2ff9db1cd2f6e53c783a51/lib/modules/showImages.js#L460-L476

**Comment by BenMcGarry** [comment]
Appears https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/hosts/vreddit.js is pulling in a external script and MV3 doesnt allow that anymore.

**Comment by larsjohnsen** [comment]
No, but it it is added directly via `build.js`.

The `onInit` in showImages block had, as far as I can remember, no side effects other than some performance improvements, so I think we might as well remove it.

**Comment by BenMcGarry** [comment]
Removing that `onInit `block may have fixed it... Not able to repro it anymore and no CSP error. It looks like Reddits advert block might have been messing with it.

**Comment by BenMcGarry** [comment]
Looking at https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/507c0b2e89a839a9c08fff90c28f3dcf826b2a03

I think its because theyve started to run ads through the same domain with a different player.
