### ISSUE TITLE
Search does not work with old layout on Firefox

### ISSUE THREAD

**Issue by manumaan** [honestbleeps/Reddit-Enhancement-Suite#5533]
<img width="958" alt="Screenshot 2024-08-25 at 10 52 17 AM" src="https://github.com/user-attachments/assets/39a76402-e661-4946-82f5-37cbdf02b646">

- My browser (copy from https://www.whatismybrowser.com):Firefox 129 on macOS (Catalina) 
- My RES version: 5.24.6
- Am I in reddit beta (yes/no): no

*What's the problem?*

Searching anything in reddit brings empty list of pages. See the screenshot

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

*What other browser extensions are installed?*
Even with only this extension this happens

**Comment by benmcgarry** [comment]
You have turned on the expando filter, in /r/RESIssues there are no posts for this so its empty. Turn the filter off.

![image](https://github.com/user-attachments/assets/79e88840-54d4-40e3-ba2e-f6285cef2383)

**Comment by manumaan** [comment]
It is not empty, there are results. But yes, after turning off expando I can see results. Thanks.
![Uploading Screenshot 2024-08-25 at 6.53.14 PM.png…]()
