### ISSUE TITLE
Feature: Enable RES Support For Reddit TOR Domain

### ISSUE THREAD

**Issue by disinfectantinjector** [honestbleeps/Reddit-Enhancement-Suite#5541]
Patch to add RES support for Reddit TOR domain:

```
diff --git a/firefox/manifest.json b/firefox/manifest.json
index 3e5b278d..af1d8475 100644
--- a/firefox/manifest.json
+++ b/firefox/manifest.json
@@ -35,7 +35,8 @@
        },
        "content_scripts": [{
                "matches": [
-                       "https://*.reddit.com/*"
+                       "https://*.reddit.com/*",
+                       "https://*.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion/*"
                ],
                "all_frames": true,
                "exclude_matches": [
@@ -71,6 +72,7 @@
        "content_security_policy": "default-src 'self'; img-src 'self' data:; connect-src https:; font-src 'self' data:; frame-ancestors https://*.reddit.com",
        "permissions": [
                "https://*.reddit.com/*",
+               "https://*.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion/*",
                "cookies",
                "identity",
                "tabs",
```

**Comment by benmcgarry** [comment]
https://www.reddit.com/r/Enhancement/comments/zqi9v8/the_new_release_of_res_is_safe_the_weird_looking/

**Comment by disinfectantinjector** [comment]
commit 85992c30da6f98e100d7b46b3bd2b31749c937e7 Remove tor support (https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/5434) reverts commit ab10588d367183bffddab87914fd81ca8762ec70 Add Reddit Tor Support (https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/5422)

Are there any plans to re-enable this in mainline so I don't have to maintain my own fork? I need this feature because Reddit recently started blocking all Tor exit nodes in the last ~2 weeks.

**Comment by benmcgarry** [comment]
No, adding this disables the extension and causes a permissions prompt that scared a substantial amount of users and also lost us tens of thousands of users. We do not plan on re-adding this.
