### ISSUE TITLE
<!doctype html>
<html>
        <head>
                <title>Angular 2 - Poor Man's Reddit</title>
                <script src= "https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
                <script src="https://jspm.io/system@0.16.js"></script>
                <script src="bundle/angular2.dev.js"></script>
                <link rel="stylesheet" type="text/css" href="styles.css">
        </head>
        <body>
                <script>
                        System.import('app');
                </script>

                <reddit></reddit>
        </body>
</html>

### ISSUE THREAD

**Issue by Playaset** [honestbleeps/Reddit-Enhancement-Suite#5548]
https://github.com/samjulien/ng2-ts-reddit/blob/master/index.html#L1-L17

**Comment by Playaset** [comment]
> https://github.com/samjulien/ng2-ts-reddit/blob/master/index.html#L1-L17

<!doctype html>
<html>
        <head>
                <title>Angular 2 - Poor Man's Reddit</title>
                <script src= "https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
                <script src="https://jspm.io/system@0.16.js"></script>
                <script src="bundle/angular2.dev.js"></script>
                <link rel="stylesheet" type="text/css" href="styles.css">
        </head>
        <body>
                <script>
                        System.import('app');
                </script>

                <reddit></reddit>
        </body>
</html>

**Comment by benmcgarry** [comment]
Spam
