### ISSUE TITLE
NER on wiki history page resets revision selections (and possibly other bugs)

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#562]
http://www.reddit.com/r/Enhancement/comments/1lp8vd/can_someone_explain_the_never_ending_reddit/cc1laj2?context=3

of course you'll need to test on a wiki page with lots of revisions

**Comment by erikdesjardins** [comment]
NER doesn't run on the wiki anymore, so this is no longer an issue.

**Comment by andytuba** [comment]
i think
