### ISSUE TITLE
NeverEndingReddit should not run on "saved comments" page

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#655]
I'll post a bit more detailed bug report a bit later, but here's how to reproduce the issue:

1. Assuming you have a few long comments saved, visit your "saved comments" page.
2. Scroll down to the end of your saved comments section.
3. Scroll back to the very top.
4. Scroll back down again to the end. Now, `#page=N` (`N` being the page number) gets appended to the URL instead of `#comments`. The issue is made clear when you visit your "saved links" page: as you scrolled down your "saved comments" page, you have also scrolled down your "saved links" page.

**Comment by andytuba** [comment]
This appears to be fixed, please reopen if not.
