### ISSUE TITLE
Merge MediaCrush requests into one request per page

### ISSUE THREAD

**Issue by SirCmpwn** [honestbleeps/Reddit-Enhancement-Suite#663]
Instead of making a new HTTP request for every MediaCrush link parsed.

I'll take care of this, I'm just making an issue to remind myself to.

**Comment by allthefoxes** [comment]
Close

:(

**Comment by andytuba** [comment]
Eh, we could close this on account of it's stale. However, we're still supporting pulling content from mediacrush and forks.
