### ISSUE TITLE
[Req] Hide/move comment box

### ISSUE THREAD

**Issue by quaz3** [honestbleeps/Reddit-Enhancement-Suite#67]
Most users don't comment right away when opening the comments. It would be nice to have the option to collapse/hide the 
user comment text box (usertext.cloneable) and/or to move it to the bottom.

**Comment by dhensche** [comment]
I know this is a pretty stale issue, but do people still want the ability to have a collapsible comment box (configurable)? We now have a 'back to top' button in the comment navigator, so maybe this can be closed?

**Comment by andytuba** [comment]
Spin-off idea: adding a "add comment" button to the page info popup next to the (back-to-top) button which scrolls you to the textarea and puts focus in.

**Comment by dhensche** [comment]
Oooh, I like that idea @andytuba. I could probably whip something up
