### ISSUE TITLE
Add link to RES subreddit styling wiki on subreddit stylesheet editor

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#676]
Add a link to http://www.reddit.com/r/Enhancement/wiki/subredditstyling on /r/{{subreddit}}/about/stylesheet if user is moderator

**Comment by erikdesjardins** [comment]
1134a490c7ca0386092ceb376214952d7d4a1ffd and 639250d3bbfc859c3b0603937d10bfe7f87193a6
