### ISSUE TITLE
"Use subreddit style" vs reddit preference "show custom subreddit styles = false"

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#677]
If the user has unchecked the "allow subreddits to show me custom styles" reddit preference, then uncheck the "use subreddit style" checkbox. If the user has whitelisted (checked) the "use subreddit style" checkbox then add the subreddit's stylesheet.

**Comment by larsjohnsen** [comment]
Cannot be implemented due to the stylesheet not being accessible when `allow subreddits to show me custom themes` is disabled.
