### ISSUE TITLE
Using account switcher in Firefox Private browsing switches accounts in NORMAL browsing

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#681]
Steps to reproduce:
1. Make sure that more than one account is listed under account switcher.
2. Open both a normal and a private browsing window with Reddit open. You should not be logged in on the private window.
3. On the private window, log in to any account using the normal login form.
4. Now, use the account switcher on the private window.

EXPECTED: Account should switch on the private window.
ACTUAL: Account remains the same, but on the _normal_ window, the user has been switched (refresh the page to see).

I have not checked this bug on any of the other browsers, so if this issue does exist elsewhere, please comment.

**Comment by andytuba** [comment]
Fixed yet?
