### ISSUE TITLE
iFrame history hack doesn't persist through browser restart in Safari 7

### ISSUE THREAD

**Issue by meastes** [honestbleeps/Reddit-Enhancement-Suite#716]
In Safari 7: When an image is viewed using the inline image viewer, the image history only seems to be saved for the current session. Upon restarting the browser, the history is forgotten.

More information: http://www.reddit.com/r/RESissues/comments/1sb5i7/bug_in_line_image_viewer_not_keeping_the_links/

**Comment by erikdesjardins** [comment]
stale, the iframe history hack will be ditched in 4.7 (doesn't seem to work at all anymore)
