### ISSUE TITLE
Double check that video expandos have a limited width

### ISSUE THREAD

**Issue by SirCmpwn** [honestbleeps/Reddit-Enhancement-Suite#735]
I'll do this myself, but I wanted to get it written down before I forgot about it.

**Comment by larsjohnsen** [comment]
Videos are width-limited.

**Comment by erikdesjardins** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/7c96315e9f6fb1e2f30b229d4aa8034671e7fb3a/lib/modules/showImages.js#L1595
