### ISSUE TITLE
templates/{{templategroup}}.html containing a few templates instead of templates.html containing all templates?

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#742]
How about splitting groups of templates into separate files, following the pattern of each module in its own file?  

e.g. templates/commandLine.html would contain just its one template, templates/settingsConsole.html would contain a "console frame" template, "module frame" template, "option frame", "boolean option", "table option", etc.

**Comment by mc10** [comment]
Fixed by #2916.
