### ISSUE TITLE
Scripted task to add new files (.css, .js, .html) to manifests/loaders

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#761]
We could use a bash/grunt script to simplify adding new modules and their assets (modules/*.js, *.css, *.html)

**Comment by erikdesjardins** [comment]
Fixed by #2014

I guess it's only modules and hosts, not other assets, though.

**Comment by mc10** [comment]
Should be superseded by #2916.
