### ISSUE TITLE
[documentation] Requirements for new video sites? 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#762]
http://www.reddit.com/r/Enhancement/comments/1x2tj8/how_hard_is_it_to_make_built_in_video_players_for/

Sounds like there might be a need to support more video hosts.  What can we do to make it easier? I'm thinking it'd be good to document (in the form of a nice boilerplate message to send to video hosts which might want to integrate with RES) what that video host would need to provide.

**Comment by erikdesjardins** [comment]
Pretty much fixed in #2005
