### ISSUE TITLE
Show progress bar under element while waiting to show hover popup

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#784]
When hovering over an element, show a subtle progress bar under/behind the element to inform the user that 1) this element has a hover popup attached to it and 2) how long until you show the popup.

Of course, modules.hover.options.showProgressBar = type: boolean, value: true

This is a blue-sky idea to help discovery: some people don't realize that many elements have hover-actions attached to them.

**Comment by larsjohnsen** [comment]
I believe this has been resolved, the popup appears instantly and has a load indicator. #3273
