### ISSUE TITLE
commentPreview.options.enabledOnPAGE

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#823]
http://www.reddit.com/r/Enhancement/comments/1zz51u/feature_request_option_to_disable_snoodown_live/

OP specifically wants a toggle for disabling commentPreview on wiki pages, but we may as well throw in onCommentsPage, maybe onInbox

**Comment by erikdesjardins** [comment]
Fixed by #1629
