### ISSUE TITLE
imageViewer GUI controls

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#834]
The image viewer's controls are difficult to discover.  The single discoverability item, "click and drag to resize" tooltip, is a little annoying.

In the interest of discoverability and mouse control, I'd like to see a floating toolbar that appears when hovering on a draggable image/video, with +/- and < ^ v > controls and ? to educate the user on click-drag functionality.

**Comment by larsjohnsen** [comment]
Resolved by #3316, #2755
