### ISSUE TITLE
make file requirements

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#853]
These tasks are sorted by importance descending, not order of operations.

* copy files into browser-specific folders  (1)
* list files in extension manifests (1)
* concatenate templates into one file
* compile extensions for development (firefox)
* reload dev extension in browser (chrome, safari, operablink, opera?) / launch browser with dev extension (firefox, chrome?, opera?)
* compile scss (2)
* compile coffeescript (2)
* package extensions for distribution?

1: One job per task per browser, one task to call all of the tasks's jobs at once, one task to call those tasks
2: I would like to limit the number of dependencies *required* to build RES in the interest of onboarding new developers, I would like to enable developers to use compiled-to-JS/CSS languages. So, there should be tasks to compile *.coffee,*.scss, etc.; then build the extensions normally.  
If we can make it trivially easy to set up the dependencies (e.g. a task to fetch and configure compilers), great!  If not, there should be a task to compile and commit to git.  (Can we set up a hook on github to automatically compile and commit after merging a PR?)

**Comment by mc10** [comment]
I think this is pretty much done, but feel free to reopen if it isn't.
