### ISSUE TITLE
Replace bitcointip with ChangeTip

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#868]
Per [the official bitcointip post](http://www.reddit.com/r/bitcointip/comments/220zzh/bitcointip_will_be_shutting_down_soon/), bitcointip is officially shutting down, as they are being superseded by ChangeTip. As such, we need to update our bitcointip module.

**Comment by BenMcGarry** [comment]
Closed as ChangeTip has shut down.
