### ISSUE TITLE
Uncollapsing a collapsed comment containing an expando kills the expando

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#893]
http://www.reddit.com/r/RESissues/comments/22b8ob/bug_after_collapsing_then_reopening_a_comment/

http://www.reddit.com/r/RESissues/comments/22nhgq/bug_inline_images_in_precollapsed_comments_dont/

**Comment by erikdesjardins** [comment]
I can't reproduce this, I think it's fixed.

**Comment by erikdesjardins** [comment]
Definitely fixed.
