### ISSUE TITLE
Show "drag to resize" educational notification instead of tooltip

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#902]
Instead of showing a tooltip on images which gets in the way, instead occasionally (every tenth time?) show a notification describing drag-to-resize after hovering over an image for several seconds.

**Comment by andytuba** [comment]
how about the cursor change(s), plus add a [?] block to @thybag's hover tools with the tooltip?

**Comment by larsjohnsen** [comment]
Resolved in #3316
