### ISSUE TITLE
modules['example']

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#907]
addModule("newModuleId", function(module, moduleID) {
        module.moduleName = "New Module"; 
        module.description = "This is such a new module!";
        module.category = "General";

        module.options['newOption'] = { ... }
        module.options['newOption2'] = { ... }

         /* UNCOMMENT AND EDIT TO CUSTOMIZE FOR YOUR MODULE 
		 // What pagetypes / URL patterns this module runs on  (see RESUtils.pageTypes)
		 module.includes = [ 'all' ]; 
		*/

		/* UNCOMMENT AND EDIT TO CUSTOMIZE FOR YOUR MODULE 
		 // What pagetypes / URL patterns this module should not run on   (see RESUtils.pageTypes)
		 module.excludes = [ ]; 
		*/

        module.go = function() {
            if (module.isEnabled() && module.isMatchURL()) {
                go();
            }
        };

        function beforeLoadSetup() {
           // add CSS, load in data from settings, etc. Can use RESUtils, RESTemplates, etc.
        }

       function go() {
           // change the DOM. can use other modules
        }
    });

**Comment by mc10** [comment]
I think our current example is okay.
