### ISSUE TITLE
Expanding Twitter Images

### ISSUE THREAD

**Issue by myblindy** [honestbleeps/Reddit-Enhancement-Suite#913]
Twitter images aren't recognized by the expander (probably because of the ending, like http://pbs.twimg.com/media/BheNWJSCQAA8Q18.jpg:large).

**Comment by erikdesjardins** [comment]
More info:
https://www.reddit.com/r/RESissues/comments/2u4yc6/bug_res_doesnt_recognise_jpgorig_files_on_twitter/
