### ISSUE TITLE
"filtered all" subreddit manager shortcut

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#919]
If the user has filtered any subreddits from all, then automatically add a link to **ALL-** to the subreddit manager's left-hand block of shortcuts (next to friends, modqueue, etc.)  This would link to /r/all-sub1-sub2-sub3-etc. populated from filteReddit.options.subreddits.

**Comment by erikdesjardins** [comment]
filteReddit useRedditFilters should cover this, and does it more seamlessly
