### ISSUE TITLE
Add "search reddit" submit button to sidebar search form

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#970]
http://www.reddit.com/r/Enhancement/comments/23i2za/is_there_a_search_button_option/

**Comment by erikdesjardins** [comment]
This has been implemented by both us and reddit at this point.

**Comment by andytuba** [comment]
us first, then reddit added theirs (and maybe bmaybe ours visually?) then we removed ours
