### ISSUE TITLE
YouTube time skipping expando support doesn't work with new default YouTube format

### ISSUE THREAD

**Issue by isstabb** [honestbleeps/Reddit-Enhancement-Suite#984]
http://www.reddit.com/r/videos/comments/246v5d/harry_potter_vs_star_wars/ch4d4c6?context=1

I confirmed the latest format created by youtube on right-click is just seconds with no unit markup, although it supports the previous format as well.  I would think it should be possible to relax the regex to recognize both forms.

**Comment by erikdesjardins** [comment]
Fixed in https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/83cb8accc0f9a606f3d3d75ee6c886767f19e65f
