### ISSUE TITLE
advise user to click through to links that don't load inside reddit.com/tb/X 

### ISSUE THREAD

**Issue by andytuba** [honestbleeps/Reddit-Enhancement-Suite#996]
Some websites don't load inside iframes, which is how the "reddit toolbar frame" is implemented.  [Example -- make sure to load in incognito](http://www.reddit.com/tb/24m1m6).  If RES can detect this, it should advise the user that "nothing's wrong, just click through to the link".  maybe pulsing the link button on the right

**Comment by erikdesjardins** [comment]
toolbar is now dead
https://www.reddit.com/wiki/toolbar
